### ISSUE TITLE
Frcmod from chamberparm 

### ISSUE THREAD

**Issue by akshay-sridhar** [ParmEd/ParmEd#1008]
Hello,

I have a system I need to load into leap for modification. It is a DNA double-helix that I want link to lipid head groups using leap. However, the parmed recognizes the Slipid parameters as Chamerparm objects. So, when I try writeFrcmod xx.frcmod, I get 'ChamberParm objects are not supported by this action'. 

Is there a way to dump the frcmod file so, I can couple it to the .mol2 files of the lipids? Or even a hack to read in prmtop/inpcrd files into leap would do. 

Thanks,
Akshay

**Comment by akshay-sridhar** [comment]
Hello,

Thanks for the reply. So, the only 'painful' workaround I can think of is to modify the lipid using arbitrary parameters within tleap. Then, write prmtop/inpcrd. Convert these to human modifiable gromacs .itp files using acpype. Then, manual re-edit them to get the parameters correctly back again?

Akshay

**Comment by swails** [comment]
Parmed can convert to GROMACS as well. 

I’m not exactly sure what it is that you’re trying to do.

**Comment by akshay-sridhar** [comment]
Sorry. I think I should have been more specific about my system. I want to model a membrane where a Cholesterol within it has a PEG attached to its headgroup. 

I want to use the Slipid parameters at http://www.fos.su.se/~sasha/SLipids/Downloads.html. However, they are only in Gromacs format. I want to use Parmed to dump a frcmod from the itp files so that I can load the Cholesterol into xleap for manual modification. But, the Slipid parameters have Urey-bradley terms within them that cause Parmed to load them as ChamberParm format. 

So, am I correct in understanding that writing these frcmod files is due to the inherent inability of leap to understand them?

**Comment by swails** [comment]
> So, am I correct in understanding that writing these frcmod files is due to the inherent inability of leap to understand them?

Yes.
