### ISSUE TITLE
add xyz array to AmberParm constructor?

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#101]
@swails 

I am not sure how often people need this. What do you think?

parm = AmberParm(top_fn, rst7.xyz)
(You have this in pysander but `AmberParm` only check `coordinates` attribute. 

    >>> from chemistry.amber.readparm import AmberParm
    >>> parm = AmberParm(top_fn, traj[100].xyz)

Hai

**Comment by swails** [comment]
Good idea.

**Comment by swails** [comment]
Done in #218.
