### ISSUE TITLE
Version 3.0.3 fails to read CHARMM top_all36_cgenff.rtf

### ISSUE THREAD

**Issue by rabdano** [ParmEd/ParmEd#1014]
Version 3.0.3 reported "CharmmError: LONEPAIR type COLINEAR not supported; only BISEctor and RELEtive supported." The problem is reproduced on two machines. After downgrading to 2.7.3 .rtf file loaded without problems.

**Comment by swails** [comment]
I like your last idea. I could parse the residue but just not put it in the lookup dictionary so any attempt to use it will result in an error.
