### ISSUE TITLE
Time to cut a new release?

### ISSUE THREAD

**Issue by jchodera** [ParmEd/ParmEd#1016]
Looks like there have been [98 commits since 3.0.3](https://github.com/ParmEd/ParmEd/compare/3.0.3...master), and it would be great to get all the final openmm forcefield conversion changes into a release version so we can easily describe the provenance of the converted OpenMM ffxml files it is distributed with.

**Comment by mattwthompson** [comment]
Selfishly I would like a new release as well, I have an open [PR](https://github.com/mosdef-hub/mbuild/pull/456) in mbuild that relies on some of these commits.

**Comment by jchodera** [comment]
@swails : Any thoughts on whether it would be possible to cut a release soon?

**Comment by swails** [comment]
I'll do it this weekend.

**Comment by jchodera** [comment]
OpenMM 7.3.0 is out! Can we get this release cut so I can put out an openmm-forcefields release?

**Comment by jchodera** [comment]
Any ETA on this @swails ?

**Comment by swails** [comment]
[Done](https://github.com/ParmEd/ParmEd/releases/tag/3.1.0).

I've also pushed 3.1.0 to PyPI, so it's pip-installable.  I'll leave it to you to add it to the omnia conda if you want to.

**Comment by jchodera** [comment]
Woohoo! Thanks!

> I've also pushed 3.1.0 to PyPI, so it's pip-installable. I'll leave it to you to add it to the omnia conda if you want to.

Have you been thinking of migrating to conda-forge, or just happy with PyPI for now?

**Comment by mattwthompson** [comment]
@jchodera are you planning on uploading this to the omnia channel? I would second a recommendation of conda-forge, but otherwise I believe omnia is the [only](https://anaconda.org/search?q=parmed) channel that has recent builds.

**Comment by hainm** [comment]
The good thing about conda-forge is that the build is automatically triggered when the package is pushed to pypi.

**Comment by jchodera** [comment]
@swails @hainm : What do you think of setting up a conda-forge feedstock for ParmEd starting with this release? @hainm points out that this would simplify maintaining packages going forward.

**Comment by hainm** [comment]
The only thing I worry is there won't be any stable channel for ParmEd. Since it's already in omnia for a while, can you add the mechanism to update it automatically? :D Otherwise, adding it to conda-forge is a good idea too (but I don't know how long conda-forge exists).

**Comment by jchodera** [comment]
@swails: I'll create an omnia release for now, and you can go to `conda-forge` for the next release if you'd like.
