### ISSUE TITLE
parmed should respect AmberTools' config?

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#1023]
Hi,

GNU compiler is used but parmed's using clang for macos . This prevent compiling its C/C++ extension in the latest MacOS Mojave.

```
AmberTools/src/parmed/src/readparm.h:5:10: fatal error: 'locale' file not found
#include <locale>
         ^~~~~~~~
1 warning and 1 error generated.
error: command 'clang' failed with exit status 1
make[2]: *** [parmed] Error 1
make[1]: *** [serial] Error 2
make: *** [install] Error 2
```

**Comment by swails** [comment]
This was done intentionally to fix other issues (but I forget what at the moment).

**Comment by swails** [comment]
This is not the problem, I'm going to close this issue (in lieu of #1024, which is the real problem).
