### ISSUE TITLE
fatal error: 'locale' file not found (MacOS Mojave)

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#1024]
Hi,

any idea how to fix that issue with MacOS Mojave. The install is quite simple.

```
pip install parmed
```

```
    /private/var/folders/q9/y2dwpbb13ydclj2mr6btq3xw0000gn/T/pip-install-u47ydriv/parmed/src/readparm.h:5:10: fatal error: 'locale' file not found
    #include <locale>
             ^~~~~~~~
    1 warning and 1 error generated.
    error: command 'clang' failed with exit status 1
```

**Comment by hainm** [comment]
Related to #1023

**Comment by mattwthompson** [comment]
Also getting this on an older Mac running High Sierra

**Comment by dacase** [comment]
Does it help to export MACOSX_DEPLOYMENT_TARGET=10.14  ?

If that alone doesn't help, check out this post, which is how we compile parmed inside AmberTools:

https://www.ovetande.se/software/amber/installation/

See especially the part about installing XCode.

[Above suggestions don't appear to be relevant to the High Sierra problems, however....]

**Comment by swails** [comment]
I can't reproduce this on a mid-2014 MBP running OS X Mojave.

**Comment by swails** [comment]
I haven't been able to reproduce this on either a MBP or Mac Mini running macOS 10.14.3.  Without being able to reproduce the issue, I have no way of debugging it.

This is what I get:

```
[swails@Robin ~ ]$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.14.3
BuildVersion:	18D109
[swails@Robin ~ ]$ pip install --no-cache-dir parmed
Collecting parmed
  Downloading https://files.pythonhosted.org/packages/8b/3e/4f54833855ca64ad5d9667285125c7ce9ae026cb5cc6b7c3f0a643178354/ParmEd-3.1.0.tar.gz (1.6MB)
    100% |████████████████████████████████| 1.6MB 31.1MB/s 
Installing collected packages: parmed
  Running setup.py install for parmed ... done
Successfully installed parmed-3.1.0
```

**Comment by hainm** [comment]
> Does it help to export MACOSX_DEPLOYMENT_TARGET=10.14 ?

@dacase : Oh yeah, that helps.

@swails My versions are the same too. Not sure why you can't reproduce it. May be I need to update xcode.

**Comment by YoshitakaMo** [comment]
Hello. Today I encountered the same problem on my macOS Mojave 10.14.3 when installing AmberTools 18. I finally solved by adding the environment variable `export MACOSX_DEPLOYMENT_TARGET='10.14'`. I appreciate this forum.

I used gcc-8 installed by `brew install gcc`. But without the variable, `parmed` could not be built because the machine used clang instead of gcc-8 like http://archive.ambermd.org/201810/0115.html  . I could find out the reason.

**Comment by swails** [comment]
Also note that even if I remove the lines setting `CC` and `CXX` to clang and clang++, respectively, I get the same errors.  So "letting AmberTools set the compilers" wouldn't necessarily work, either (nor do I think it's the way to fix these issues).

**Comment by mattwthompson** [comment]
I can reproduce the above comment (`python setup.py build` vs `/usr/bin/python setup.py build`) on a 2017 MBP

> OS X 10.7

Wow! That is ancient.

**Comment by swails** [comment]
I've confirmed that #1033 fixes this issue.

**Comment by hainm** [comment]
> Does pytraj build on macOS 10.14?

likely not. I had lots of troubles in building pytraj on mac recently and am just switch to GNU compiler to quickly test pytraj. :D

**Comment by dacase** [comment]
Hai asked: Does pytraj build on macOS 10.14?

I think all that is required is the libstdc++ -> libc++ substitution in setup.py.  With that change, it seems to work OK for me.  [I've asked people on the amber-developers list to see if this change is deleterious in previous version of OSX.]

Apologies for posting to a closed issue.....

**Comment by hainm** [comment]
> With that change, it seems to work OK for me.

In term of compiling or using pytraj? Can you run the pytraj test on AT?

**Comment by dacase** [comment]
Hai wrote:  Can you run the pytraj test on AT?

Yes: cd $AMBERHOME/AmberTools/test; make test.pytraj

Everything passes; OSX 10.14.3

**Comment by hainm** [comment]
yeah, I confirm that. I've tried with python 3.7 and it seems Miniconda is more friendly to MacOS now.
Both pytraj and libcpptraj.dylib are both linked to `@rpath/libc++.1.dylib`.
