### ISSUE TITLE
suggested update to wiki "OpenMM Tricks and Recipes"

### ISSUE THREAD

**Issue by thempel** [ParmEd/ParmEd#1026]
Hi everyone, let me first thank you for providing this wiki page ("OpenMM Tricks and Recipes")! It helped a lot to get me started with openMM some years ago. Since I share the link with basically everybody who wants to start with openMM, I suggest a small update to the very last section. (Sorry for doing it here, but as far as I know it's not possible to do a PR on the wiki page).

**now online:**
To use a restart file, just use the restart file name you generated in the AmberParm declaration at the top of the script and make sure you add the line
```python
sim.context.setVelocities(parm.velocities)
```
at the same time you set the positions as well.

**proposed new version:**
To use a restart file, just use the restart file name you generated in the AmberParm declaration at the top of the script and make sure you add the line
```python
sim.context.setVelocities(parm.velocities[0] * u.angstrom / u.picosecond)
```
at the same time you set the positions as well. Further, if using periodic boundary conditions, it is necessary to set the box vectors to the ones saved to the restart file. For rectangular boxes, this is achieved with the following line.
```python
sim.context.setPeriodicBoxVectors(*(parm.cell_lengths * np.eye(3)).tolist() * u.angstrom)
```

**some comments:**
Instead of `parm.velocities[0]` one could do a parm.velocities.squeeze() if that's clearer, but apparently `parm.velocities` has shape (1, n_atoms, 3). Further, setting the periodic box looks pretty ugly and requires numpy import. One could do it without, but the formats (cell vectors vs cell length and angle vectors) need to be matched somehow.

Further, a couple of lines above, it is stated that `RestartReporter` has a `uses_pbc=True` flag, which isn't actually the case (any more?). If that's taken care of automatically, it could be deleted here.

**Comment by swails** [comment]
You can find the internal set of units that OpenMM uses [here](http://docs.openmm.org/latest/userguide/theory.html#units).  So if you pass in anything unitless to OpenMM, it assumes the units are derived from those.  For example, a length is nm.  A velocity is nm/ps.  etc.

If you use units, OpenMM will always perform the conversions for you.  It'll also throw up if the dimensions are wrong (which is a good thing!)

The main reason *not* to use units is if the performance hit of doing so is unacceptable.  That's not usually the case (or you'd not be doing it in Python in the first place.

I'm going to go ahead and close this.  Thanks!
