### ISSUE TITLE
harmonic/periodic CHARMM impropers

### ISSUE THREAD

**Issue by wiederm** [ParmEd/ParmEd#1027]
I just recently updated to parmed version 3.0.1 and when I tried to repeat some simulations using the openMM API with CHARMM parameter files I realized that improper torsions are handled differently than in parmed 2. 

Looking at a system (toluene in vacuum) that has 6 improper torsions defined in the parameter and psf file these improper torsions are now (with parmed 3) added to the `PeriodicTorsionForce` class, but not to the `CustomTorsionForce` (as I would have expected with parmed 2). In fact no `CustomTorsionForce` is created in the openMM system at all. 

After having read this:
https://github.com/ParmEd/ParmEd/blob/f0fd15267d92346ca948f6bc740962e25071b03b/parmed/charmm/psf.py#L619
am I save to assume that for every harmonic improper there will be an entry in the `CustomTorsionForce` and for every periodic improper there will be an entry in the `PeriodicTorsionForce` class?

**Comment by swails** [comment]
Sorry for the delay -- I only just saw this question.

CHARMM _can_ specify that improper torsions be modeled with a periodic (Fourier) functional form.  That's necessary, for instance, to implement the Amber force field which uses the same functional forms for improper torsions as it does for proper ones.

Maybe the CHARMM parm file specifies periodic impropers, and version 3.0.1 is doing things correctly?  I believe I fixed CHARMM treating _all_ impropers as harmonic impropers even when the prm files specified not to awhile ago.  This may be why you're seeing what you're seeing.
