### ISSUE TITLE
question about ParmEd license

### ISSUE THREAD

**Issue by dacase** [ParmEd/ParmEd#1046]
The setup.py file says this:
```
license='LPGL (or GPL if released with AmberTools)'
```
But I think this is incorrect.  The intent is for ParmEd to be LGPL, independent of the distribution channel.

**Comment by swails** [comment]
That’s fine :). 

There was a time when AmberTools was mostly GPL, so I just added that text to make things easier.  

I don’t care between GPL or LGPL, although I’d prefer to stay away from the licenses that are way less restrictive like MIT or BSD.
