### ISSUE TITLE
simulation box in PDB files

### ISSUE THREAD

**Issue by stephanmohr85** [ParmEd/ParmEd#1050]
Dear developers, 

With parmed it is possible to read in several PDB files at once, for instance from a MD trajectory. The command get_coordinates() then gives the coordinates of all the snapshots that are contained in the PDB file. However, the command get_box() gives the simulation box of only the last snapshot, and not of all snapshots in the file. This is problematic for simulations where the box size changes.

The following code snippet illustrates the problem, using the file test.pdb:

In [1]: import parmed

In [2]: pdb = parmed.load_file('test.pdb')

In [3]: pdb.get_coordinates()
Out[3]: 
array([[[  31.548,   18.66 ,  104.544],
        [  32.218,   18.816,  105.209],
        [  31.109,   19.504,  104.442]],

       [[  27.511,   18.566,  103.113],
        [  27.958,   19.072,  102.435],
        [  27.97 ,   17.727,  103.129]],

       [[  21.719,   10.476,  107.767],
        [  21.332,    9.805,  107.205],
        [  22.011,   11.158,  107.161]]])

In [4]: pdb.get_box()
Out[4]: array([[ 120.898,  130.535,  119.825,   90.   ,   90.   ,   90.   ]])

[test.pdb.tar.gz](https://github.com/ParmEd/ParmEd/files/3084462/test.pdb.tar.gz)

**Comment by swails** [comment]
The PDB standard permits only a single set of box dimensions to be present. 

It is one of several severe limitations of the PDB file when it comes to representing trajectories of MD simulations.

**Comment by stephanmohr85** [comment]
Thanks a lot for your reply @swails! I was not aware of this.

Which format (parsable by parmed) would you recommend instead of PDB? The MD code I use is Gromacs.

**Comment by swails** [comment]
ParmEd only understands trajectories of Amber formats (NetCDF and the mdcrd ascii trajectory file). 

But ParmEd is not a trajectory analysis program, and doesn’t try to duplicate this functionality. There are several libraries that will read almost any trajectory format you would use, including those generated by gromacs. 

Examples are pytraj and mdtraj — both play nicely with ParmEd. MDAnalysis is another option, but I have a lot less experience with that library.
