### ISSUE TITLE
non-integer residue ID in CHARMM PSF and CRD files

### ISSUE THREAD

**Issue by charmm-gui** [ParmEd/ParmEd#1058]
It seems like that current ParmEd is not able to handle non-integer residue ID in CHARMM PSF and CRD(? not sure).
It would be great if it can support non-integer residue ID for the PDB file containing insertion code.
The example CHARMM PSF and CRD files are attached.

[non_int_resid.zip](https://github.com/ParmEd/ParmEd/files/3411414/non_int_resid.zip)

**Comment by swails** [comment]
[According to the CRD specification](https://www.charmm.org/charmm/documentation/by-version/c40b1/params/doc/io/#Coordinate) that field is supposed to be an arbitrary 4-character string.

I agree ParmEd's behavior should be updated.

**Comment by swails** [comment]
Turns out this was incredibly easy to fix.  See #1059
