### ISSUE TITLE
add universal `save` for Parm object

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#106]
I am playing with ParmEd in pytraj namespace

    >>> from pytraj import io
    >>> p_top = io.load_ParmEd("./Tc5b.top")
    >>> p_top
        <AmberParm 304 atoms; 20 residues; 310 bonds; parametrized>

     >>> # it's really nice if ParmEd has this
     >>> p_top.save("Tc5b.cif")
     >>> p_top.save("Tc5b.psf")
     >>> p_top.save("Tc5b.crazy_ext", fmt='psf') 
     >>> # if fmt is not None, ParmEd will set filetype of fmt

(I know there are methods like `write_cif` in ParmEd)

**Comment by swails** [comment]
+1

**Comment by hainm** [comment]
@swails: so `pytraj` code has just broken when trying to load ParmEd object.

https://github.com/pytraj/pytraj/blob/master/pytraj/io.py#L305

I guess 'write_parm' is only for Amber, right? I look at `CharmmPsfFile` and it has `write_psf`.  So I think it's reasonable to have the same method's name, like `write_parm` for all Topology from Amber, Charmm, ...

Hai

**Comment by swails** [comment]
How about I just add a `save` method that works for all types like this enhancement asks for?

I don't want to change `write_psf` to `write_parm` (`write_psf` is actually an attribute of `Structure`, not `CharmmPsfFile`).

**Comment by hainm** [comment]
@swails: yes, if you just need add `save` (or any other names). I can just make `pytraj` to adjust to your change.

Hai
