### ISSUE TITLE
Convert xml with custom atom types to GROMACS topology

### ISSUE THREAD

**Issue by wpm216** [ParmEd/ParmEd#1069]
Hi,

I'm trying to convert an xml force field file with custom atom types to a GROMACS topology file. It seems this functionality isn't yet supported in parmed:
```
>>> import parmed
>>> parmed.__version__
'3.2.0'
>>> parmed.openmm.OpenMMParameterSet("ff.xml")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wpm216/psi4conda/envs/fb2/lib/python3.6/site-packages/parmed/openmm/parameters.py", line 97, in __init__
    raise NotImplementedError('Cannot yet read OpenMM Parameter sets')
NotImplementedError: Cannot yet read OpenMM Parameter sets
```

I couldn't find any other direct conversion methods, so I've taken a (seemingly) obtuse route. I've tried to create an OpenMM System object from a parmed structure and an OpenMM forcefield, and in turn convert that back to parmed to write the GROMACS topology.
```
from simtk.openmm.app.forcefield import ForceField
import parmed

mol2file = parmed.load_file("molecule.mol2") # contains an @TRIPOS<MOLECULE> with custom atomtypes
pmd_struct_no_ff = mol2file.to_structure() 


forcefield = ForceField("ff.xml") # contains a Residue matching the molecule in the mol2 file, plus all parameters. generated by ForceBalance.
omm_system = forcefield.createSystem(pmd_struct_no_ff.topology)

pmd_struct_with_ff = parmed.openmm.load_topology(pmd_struct_no_ff.topology, omm_system, pmd_struct_no_ff.positions) #

pmd_struct_with_ff.save('molecule.top', overwrite = True, parameters = "ff.itp")
```

My question is essentially that pmd_struct_no_ff and pmd_struct_with_ff have different atom types assigned to each atom:
```
>>> pmd_struct_no_ff.atoms[0].type
'cc'
>>> pmd_struct_with_ff.atoms[0].type
'C1'
```

Naturally, this change results in errors writing the GROMACS topology file. Comparing e.g. the atom type definitions in "ff.xml",
```
  <AtomTypes>
    <Type class="cc" element="C" mass="12.01" name="cc"/>
    <Type class="cf" element="C" mass="12.01" name="cf"/>
    <Type class="cd" element="C" mass="12.01" name="cd"/>
    <Type class="ce" element="C" mass="12.01" name="ce"/>
    <Type class="h4" element="H" mass="1.008" name="h4"/>
    <Type class="ss" element="S" mass="32.06" name="ss"/>
    <Type class="os" element="O" mass="16.0" name="os"/>
    <Type class="c3" element="C" mass="12.01" name="c3"/>
    <Type class="h1" element="H" mass="1.008" name="h1"/>
  </AtomTypes>

```

with those in "ff.itp":
```
[ atomtypes ]
; name    at.num    mass    charge ptype  sigma      epsilon
C1             6  12.010780  0.00000000  A     0.33996695       0.359824
H1             1   1.007947  0.00000000  A     0.25105526        0.06276
S1            16  32.065500  0.00000000  A     0.35635949          1.046
O1             8  15.999430  0.00000000  A     0.30012343        0.71128
C2             6  12.010780  0.00000000  A     0.33996695      0.4577296
H2             1   1.007947  0.00000000  A      0.2471353      0.0656888
```
(note: LJ parameters are defined in "ff.xml" in a NonbondedForce tag section.)

Analogous behavior is seen for bond, angle, and dihedral parameters. I think it's clear that the system's topology is getting reassessed at some point, but I'm not sure why it's happening, or even where (i.e. in the OpenMM System creation or the conversion back to parmed). Was hoping y'all could help identify what I'm doing wrong, or suggest an alternative route to accomplish what I'm trying to do. 

Thanks so much! Happy to provide more information, as needed.

-Wes

**Comment by ahy3nz** [comment]
```
pmd_struct_with_ff = parmed.openmm.load_topology(struct.topology, omm_system, struct.positions) #
```
Is this a typo? `struct.topology` doesn't seem to exist in the code you've provided

In [this module](https://github.com/ParmEd/ParmEd/blob/master/parmed/openmm/topsystem.py#L98) that gets called when you load your openmm system to a parmed structure, the atomtypes and atom names are parsed via the openmm topology you provide, so it might help to inspect the openmm topology you're passing, particularly the `openmm.atom.id` and `openmm.atom.name` attributes 
Do you have example files to help reproduce this error?

A package that might help, [foyer](https://github.com/mosdef-hub/foyer/tree/master/foyer) allows combining modified-OpenMM XMLs with ParmEd structures. There would be some work to utilize foyer here, but what you've provided seems like a very reasonable approach in my opinion.

**Comment by wpm216** [comment]
Yes, thanks for the catch (and the quick reply 😄)! I edited the command. It now reads:
```
pmd_struct_with_ff = parmed.openmm.load_topology(pmd_struct_no_ff.topology, omm_system, pmd_struct_no_ff.positions) 
```
In other words, I use the `openforcefield.topology.Topology` attached to the `parmed.structure.Structure` with the correct atom type definitions.

In generating an MWE, I stumbled upon a workaround that solves my issue. I'm describing it here for posterity. 

First, here's how to replicate the error. Using the code I posted above with [dms.mol2](https://github.com/ParmEd/ParmEd/files/3853782/dms.mol2.txt) and [dms.xml](https://github.com/ParmEd/ParmEd/files/3853783/dms.xml.txt) produces [error.itp](https://github.com/ParmEd/ParmEd/files/3853785/error.itp.txt). Atomtypes that are chemically identical are grouped together, as seen by the `h1` and `h2` atomtypes in [dms.xml](https://github.com/ParmEd/ParmEd/files/3853783/dms.xml.txt) being grouped together in [error.itp](https://github.com/ParmEd/ParmEd/files/3853785/error.itp.txt). This happens despite differences in the values of `k` and `length` in their HarmonicBondForces with `c3`.

Second, here's how to avoid it. At least in this case, Parmed/OpenMM decide to group atomtypes together based on their nonbonded parameters. I tweaked the LJ sigma values of `type=dms-c3-2` and `type=dms-h1-{7..9}` by 10^-12 to create [dms_lj_tweaked.xml](https://github.com/ParmEd/ParmEd/files/3853787/dms_lj_tweaked.xml.txt). Using that file along with [dms.mol2](https://github.com/ParmEd/ParmEd/files/3853782/dms.mol2.txt) generates [correct.itp](https://github.com/ParmEd/ParmEd/files/3853797/correct.itp.txt). `h1` and `h2` are correctly regarded as distinct throughout the file. In contrast, `c1` and `c2` are still grouped together because their LJ parameters are identical. All atomtypes are still given new names, but that's a trivial concern.

I haven't looked into exactly where the "grouping together" happens during the conversion process, but hopefully this example can provide some insight. Let me know if I made any other mistakes or if I should provide additional information. Thanks for the support!
