### ISSUE TITLE
Trailing spaces missed for all % flagged lines

### ISSUE THREAD

**Issue by Ruibin-Liu** [ParmEd/ParmEd#1081]
As in the title, if we load a `.parm7` file generated by `leap` and save it using `outparm` (I also tried the corresponding python API), we will notice that all trailing spaces in those flagged lines are deleted. I don't know whether it will cause any problems, but it might be better to keep those spaces.

**Comment by swails** [comment]
It does not cause problems.  ParmEd has been writing files this way for over 10 years at this point, and nary a problem has occurred yet :smiley:

**Comment by swails** [comment]
I'm going to go ahead and close this, since this doesn't cause problems for any Amber prmtop parser I've ever seen (and I've seen many).
