### ISSUE TITLE
Reinstallation of python distribution through miniconda for Ambertools19

### ISSUE THREAD

**Issue by calgator1317** [ParmEd/ParmEd#1088]
This issue should be published on Amber category in general. My apology!

Hi Amber users,

I've been trying to follow the Amber Tutorials using Python (written by Hai Nguyen THANK YOU!). At some point nglview couldn't be loaded (Fig 1&2) so I tried (`jupyter-nbextension enable nglview --py --sys-prefix`) and still couldn't open nglview. Then I tried (`amber.conda upgrade nglview --force`) to see if upgrade would solve. It turned out it did so many changes that I feel like it ruined miniconda or something (Fig3) and now it can't even open jupyter notebook Fig 4 (`amber.jupyter notebook`) Anyone who knows how to fix this issue? or is there a way to reinstall the python part designated for amber?

1
![image](https://user-images.githubusercontent.com/44783102/82139118-b6539700-97f3-11ea-9207-d50fbeaaa4e6.png)
2
![image](https://user-images.githubusercontent.com/44783102/82139122-bc497800-97f3-11ea-94d3-04fd3a7b1d9e.png)
3
![Screen Shot 2020-05-17 at 4 09 46 AM](https://user-images.githubusercontent.com/44783102/82139300-c5871480-97f4-11ea-8712-09c5c3c93df2.png)
4
![Screen Shot 2020-05-17 at 4 12 45 AM](https://user-images.githubusercontent.com/44783102/82139305-ca4bc880-97f4-11ea-9d23-a07a06be15bd.png)

**Comment by calgator1317** [comment]
output detail info about after running `amber.conda upgrade nglview --force` is
WARNING: The --force flag will be removed in a future conda release.
         See 'conda update --help' for details about the --force-reinstall
         and --clobber flags.


Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Applications/amber18/miniconda

  added / updated specs:
    - nglview


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    asn1crypto-1.3.0           |           py27_0         164 KB
    atomicwrites-1.4.0         |             py_0          11 KB
    ca-certificates-2020.1.1   |                0         125 KB
    certifi-2019.11.28         |           py27_0         153 KB
    chardet-3.0.4              |        py27_1003         169 KB
    conda-4.8.3                |           py27_0         2.8 MB
    cryptography-2.8           |   py27ha12b0ac_0         518 KB
    futures-3.3.0              |           py27_0          28 KB
    ipaddress-1.0.23           |             py_0          22 KB
    ipywidgets-7.5.1           |             py_0         104 KB
    jinja2-2.11.2              |             py_0         103 KB
    jsonschema-2.6.0           |   py27hd9b497e_0          64 KB
    libcxx-10.0.0              |                1         760 KB
    libffi-3.3                 |       h0a44026_1          45 KB
    ncurses-6.2                |       h0a44026_1         749 KB
    pycparser-2.20             |             py_0          92 KB
    pyopenssl-19.1.0           |           py27_0          86 KB
    pyparsing-2.4.7            |             py_0          65 KB
    pysocks-1.7.1              |           py27_0          30 KB
    requests-2.22.0            |           py27_1          92 KB
    ruamel_yaml-0.15.87        |   py27h1de35cc_0         238 KB
    sqlite-3.31.1              |       h5c1f38d_1         1.3 MB
    tqdm-4.46.0                |             py_0          60 KB
    widgetsnbextension-3.5.1   |           py27_0         867 KB
    ------------------------------------------------------------
                                           Total:         8.5 MB

**The following packages will be REMOVED:

  libcxxabi-4.0.1-hcfea43d_1
  pip-19.0.3-py27_0
  pyrsistent-0.15.6-py27h1de35cc_0
  python_abi-2.7-1_cp27m
  wheel-0.33.1-py27_0**

The following packages will be UPDATED:

  asn1crypto                                  0.24.0-py27_0 --> 1.3.0-py27_0
  atomicwrites       pkgs/main/osx-64::atomicwrites-1.3.0-~ --> pkgs/main/noarch::atomicwrites-1.4.0-py_0
  chardet                                      3.0.4-py27_1 --> 3.0.4-py27_1003
  cryptography                         2.6.1-py27ha12b0ac_0 --> 2.8-py27ha12b0ac_0
  futures                                      3.2.0-py27_0 --> 3.3.0-py27_0
  ipaddress          pkgs/main/osx-64::ipaddress-1.0.22-py~ --> pkgs/main/noarch::ipaddress-1.0.23-py_0
  jinja2                                        2.11.1-py_0 --> 2.11.2-py_0
  libcxx                                   4.0.1-hcfea43d_1 --> 10.0.0-1
  libffi                                   3.2.1-h475c297_4 --> 3.3-h0a44026_1
  ncurses                                    6.1-h0a44026_1 --> 6.2-h0a44026_1
  pycparser          pkgs/main/osx-64::pycparser-2.19-py27~ --> pkgs/main/noarch::pycparser-2.20-py_0
  pyopenssl                                   19.0.0-py27_0 --> 19.1.0-py27_0
  pyparsing                                      2.4.6-py_0 --> 2.4.7-py_0
  pysocks                                      1.6.8-py27_0 --> 1.7.1-py27_0
  requests                                    2.21.0-py27_0 --> 2.22.0-py27_1
  ruamel_yaml                        0.15.46-py27h1de35cc_0 --> 0.15.87-py27h1de35cc_0
  sqlite                                  3.27.2-ha441bb4_0 --> 3.31.1-h5c1f38d_1
  tqdm                                          4.44.1-py_0 --> 4.46.0-py_0

The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates    conda-forge::ca-certificates-2020.4.5~ --> pkgs/main::ca-certificates-2020.1.1-0
  certifi            conda-forge::certifi-2019.11.28-py27h~ --> pkgs/main::certifi-2019.11.28-py27_0
  conda              conda-forge::conda-4.8.3-py27h8c360ce~ --> pkgs/main::conda-4.8.3-py27_0
  ipywidgets                                    conda-forge --> pkgs/main
  openssl            conda-forge::openssl-1.1.1g-h0b31af3_0 --> pkgs/main::openssl-1.1.1g-h1de35cc_0
  widgetsnbextension                            conda-forge --> pkgs/main

The following packages will be DOWNGRADED:

  jsonschema                                   3.2.0-py27_0 --> 2.6.0-py27hd9b497e_0

Proceed ([y]/n)? y

Downloading and Extracting Packages
tqdm-4.46.0          | 60 KB     | ######################################################################## | 100%
ca-certificates-2020 | 125 KB    | ######################################################################## | 100%
jinja2-2.11.2        | 103 KB    | ######################################################################## | 100%
pycparser-2.20       | 92 KB     | ######################################################################## | 100%
ipywidgets-7.5.1     | 104 KB    | ######################################################################## | 100%
ncurses-6.2          | 749 KB    | ######################################################################## | 100%
ipaddress-1.0.23     | 22 KB     | ######################################################################## | 100%
pyopenssl-19.1.0     | 86 KB     | ######################################################################## | 100%
pysocks-1.7.1        | 30 KB     | ######################################################################## | 100%
libffi-3.3           | 45 KB     | ######################################################################## | 100%
sqlite-3.31.1        | 1.3 MB    | ######################################################################## | 100%
ruamel_yaml-0.15.87  | 238 KB    | ######################################################################## | 100%
widgetsnbextension-3 | 867 KB    | ######################################################################## | 100%
certifi-2019.11.28   | 153 KB    | ######################################################################## | 100%
libcxx-10.0.0        | 760 KB    | ######################################################################## | 100%
asn1crypto-1.3.0     | 164 KB    | ######################################################################## | 100%
chardet-3.0.4        | 169 KB    | ######################################################################## | 100%
requests-2.22.0      | 92 KB     | ######################################################################## | 100%
pyparsing-2.4.7      | 65 KB     | ######################################################################## | 100%
atomicwrites-1.4.0   | 11 KB     | ######################################################################## | 100%
conda-4.8.3          | 2.8 MB    | ######################################################################## | 100%
cryptography-2.8     | 518 KB    | ######################################################################## | 100%
jsonschema-2.6.0     | 64 KB     | ######################################################################## | 100%
futures-3.3.0        | 28 KB     | ######################################################################## | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: \ Uninstalling jupyter-js-widgets jupyter-js-widgets/extension
Removing: /Applications/amber18/miniconda/share/jupyter/nbextensions/jupyter-js-widgets

done

After that I tried to open `amber.jupyter notebook` and this error appears

Traceback (most recent call last):
  File "/Applications/amber18/miniconda/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/Applications/amber18/miniconda/lib/python2.7/site-packages/notebook/notebookapp.py", line 47, in <module>
    from zmq.eventloop import ioloop
  File "/Applications/amber18/miniconda/lib/python2.7/site-packages/zmq/__init__.py", line 42, in <module>
    _load_libzmq()
  File "/Applications/amber18/miniconda/lib/python2.7/site-packages/zmq/__init__.py", line 9, in _load_libzmq
    import sys, ctypes, platform, os
  File "/Applications/amber18/miniconda/lib/python2.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: dlopen(/Applications/amber18/miniconda/lib/python2.7/lib-dynload/_ctypes.so, 2): Library not loaded: @rpath/libffi.6.dylib
  Referenced from: /Applications/amber18/miniconda/lib/python2.7/lib-dynload/_ctypes.so
  Reason: image not found

**I think _ctypes.so is missed here.**

**Comment by hainm** [comment]
hi @calgator1317, this is `parmed` repo and your issue does not relate to that.

But please follow below steps:
- rebuild your ambertools with python 3
    - You can install the binary here: https://ambermd.org/GetAmber.php#ambertools (Option 2)
- delete the old distribution: https://github.com/arose/nglview/blob/master/docs/FAQ.md#widget-not-shown

- reinstall `nglview`:
https://github.com/arose/nglview#released-version

(if you have amber.conda, replace `conda` by `amber.conda` and so on).

PS: Sorry for the outdated tutorial.

**Comment by calgator1317** [comment]
@hainm Thank you very much for your help (again). I was immediately went back to add "This issue should be published on Amber category in general. My apology!" at the beginning when I realized I was in the wrong place. Sorry again!

> * You can install the binary here: https://ambermd.org/GetAmber.php#ambertools (Option 2)
 
→ Yesterday I decided to move to Ambertools20 which came with Python 3.7. Yet the problem still persists even though I followed your suggests here.

`amber.python -m ipykernel install ` (DONE)
→ Output: Installed kernelspec python3 in /usr/local/share/jupyter/kernels/python3

`jupyter-nbextension enable nglview --py --sys-prefix`
(I actually had to run `amber.jupyter nbextension enable nglview --py --sys-prefix`)
→ Validating OK

NGLview was installed via miniconda so I don't have nglview-js-widgets folder the following path
`$HOME/.local/share/jupyter/nbextensions/nglview-js-widgets/`
Instead, I have it here `/$AMBERHOME/miniconda/share/jupyter/nbextensions/nglview-js-widgets`. However if I deleted this folder, I would not be able to enable nglview above (→ validating: problem found, require? X nglview-js-widgets/extension)

![Screen Shot 2020-05-18 at 12 29 05 PM](https://user-images.githubusercontent.com/44783102/82241491-41bf4c00-990a-11ea-8d36-ee3aa6dd963b.png)

![Screen Shot 2020-05-18 at 12 29 15 PM](https://user-images.githubusercontent.com/44783102/82241504-45eb6980-990a-11ea-91b0-5482c0fd85f8.png)

Although I've got started on python very recently, I'd love to debug problem. It's kind of late for to learn and it's frustrating yet fascinating! Thanks Hai!

**Comment by calgator1317** [comment]
In case it's important for you to know, I have
jupyter folder after installing
` amber.python -m ipykernel install`
 /usr/local/share/jupyter/kernels/python3

However, I do not have `/usr/local/share/jupyter/nbextensions/`

**Comment by hainm** [comment]
@calgator1317 Please move our discussion to `nglview` repo.

**Comment by hainm** [comment]
https://github.com/arose/nglview/issues/899
