### ISSUE TITLE
[FR] Interface with PyRosetta API

### ISSUE THREAD

**Issue by cxhernandez** [ParmEd/ParmEd#109]
I posted this on the [MDTraj page earlier](https://github.com/mdtraj/mdtraj/issues/806), but @kyleabeauchamp thought it might be more appropriate here.

It might be nice to have a class that could extract information from a PyRosetta pose object:

``` python
from rosetta import *
from chemistry.rosetta import RosettaPose

init()
pose = pose_from_seq('AAAAAAAA')
ala = RosettaPose(pose)

sys = ala.createSystem(...)
# Continue on to simulate system in OpenMM
```

Let me know if you think this might be worth a PR. Thanks!

**Comment by swails** [comment]
> Let me know if you think this might be worth a PR.

Yea, definitely.  I don't know anything about Rosetta, myself, so it would take me a little while to get to the point where I could add this myself.

If you wanted to have a go at the implementation, I'd be more than happy to field any questions if the (docs)[http://parmed.github.io/ParmEd] are either inadequate or too poorly organized (and of course, doc improvements are *always* welcome).

**Comment by swails** [comment]
This is mostly done in #111.  Let's keep this open with a checklist of what to do next:

- [ ] Update Sphinx docs for this new functionality
- [ ] Add a test case for the "round-trip" Rosetta->ParmEd->OpenMM/mdtraj

**Comment by cxhernandez** [comment]
I'll get started with the Sphinx today.

p.s. I just seeded a simulation of a mutated peptide from WT using this and OpenMM. Seems to work just fine!

**Comment by swails** [comment]
Awesome.  Just out of curiosity, where did you get the parameters?  Did they come from OpenMM (via `ForceField`), or did you get them out of Rosetta somehow?

**Comment by cxhernandez** [comment]
I just used `ForceField`. Rosetta seems to have [ways of extracting CHARMM-like parameters](https://www.rosettacommons.org/node/3725), but I don't know if it's the full set.

**Comment by cxhernandez** [comment]
Should the "round trip" test actually assert anything or just make sure we can start a simulation and load the results into MDTraj?

@kyleabeauchamp

**Comment by kyleabeauchamp** [comment]
Maybe a nan check?  I don't think there's a right answer here, we just want to make sure the molecule is not royally screwed up.

**Comment by kyleabeauchamp** [comment]
E.g. Make sure we can do a single step of MD with a short timestep and a Langevin integrator?
