### ISSUE TITLE
Wrong output for gromacs nonbond_params 

### ISSUE THREAD

**Issue by bisdan** [ParmEd/ParmEd#1094]
Hello ParmEd Team,

in "parmed/gromacs/gromacstop.py" there seems to be a mistake while writing gromacs topologies in "nonbond_params" sections. See lines 1484-1485. 

`sig = val[0];
eps = val[1]`

shoulde be

`sig = val[1];
eps = val[0]`

when compared to how they are assigned in lines 387-388. With this change I get similar values when reading a topology and then writing it.

Cheers,

Daniel

**Comment by mattwthompson** [comment]
Not sure which is right but see https://github.com/ParmEd/ParmEd/pull/923 and https://github.com/ParmEd/ParmEd/pull/1021 for context.

Probably worth writing up a round-trip test before patching anything in the source code - here is probably the starting point: verify that the data is valid, not just that it exists. (I'm responsible for that shortcoming, as you can see.)

https://github.com/ParmEd/ParmEd/blob/0f3dae24583409e9dc14546430384a2bc21f6cb7/test/test_parmed_gromacs.py#L761-L767

**Comment by mattwthompson** [comment]
Yeah, that's definitely wrong

```python3
(Pdb) top.atoms[0].atom_type.nbfix
{'opls_135': (6.299605249474366, 0.11950286806883365, 6.299605249474366, 0.11950286806883365)}
(Pdb) top_test.atoms[0].atom_type.nbfix
{'opls_135': (0.11950286806883363, 6.299605249474366, 0.11950286806883363, 6.299605249474366)}
