### ISSUE TITLE
Documentation broken link https://parmed.github.io/ParmEd 😥

### ISSUE THREAD

**Issue by diallobakary4** [ParmEd/ParmEd#1106]
Hello 

The link to the documentation page seems to be broken 😥

**Comment by orbeckst** [comment]
In the interim, see https://orbeckst.github.io/ParmEd/

**Comment by swails** [comment]
Much nicer!

**Comment by orbeckst** [comment]
Thank you for accepting my PR. However, the issue remains as https://parmed.github.io/ParmEd still shows a 404. Could you please re-open it until the official URL is back?

(Also, if we can help in any way please say so.)

**Comment by orbeckst** [comment]
I tried building on RTD but it fails because it's not finding stk https://readthedocs.org/projects/parmed/builds/12060221/

I'll happily hand over the RTD to anyone, I don't want to squat on it, just see if there's an easy way to keep the docs going.

**Comment by swails** [comment]
> I tried building on RTD but it fails because it's not finding stk

Actually `simtk` is an optional dependency.  The real exception is that it can't find `numpy` (which is a hard requirement).

**Comment by swails** [comment]
Website seems to work for me now: https://parmed.github.io/ParmEd/html/index.html

**Comment by orbeckst** [comment]
Awesome! Thank you @swails – issue can be closed for good from my perspective.

I removed the interim pages on my fork again so that there's no confusion about where to go.

**Comment by orbeckst** [comment]
For RTD: adding a `requirements.txt` file with minimal dependencies anywhere in the repo would probably allow it to build as one can point RTD there. Or add the requirements to `setup.py`. 

@swails – let me know a username on RTD and I add you as a maintainer to the project so that you have full admin access. Alternatively, if I don't hear from you over the next few days I'll delete the RTD again.

**Comment by swails** [comment]
I just created an account "swails" on rtd.org. 

Thanks!

**Comment by orbeckst** [comment]
I added you, you should have all privileges. Feel free to remove me as a maintainer – I don't think I can do this myself.
