### ISSUE TITLE
Converting from OpenMM topology to ParmEd 

### ISSUE THREAD

**Issue by asgharrazavi** [ParmEd/ParmEd#1109]
I have a three residue system that I can build topology for it using Charmm force field and simulate it in OpenMM. However, when I try to convert back and forth between OpenMM and ParmEd topologies, I get error. Here is the full description:

PDB:

<pre>
CRYST1   41.604  116.842   91.486  90.00  90.00  90.00 C 2 2 21      8
MODEL        1
ATOM      1  CY3 MET A   1      35.416   9.009 -18.663  1.00  0.00           C  
ATOM      2  CY  MET A   1      34.218   9.958 -18.693  1.00  0.00           C  
ATOM      3  OY  MET A   1      33.432   9.978 -17.748  1.00  0.00           O  
ATOM      4 1HY  MET A   1      35.403   8.426 -17.715  1.00  0.00           H  
ATOM      5 2HY  MET A   1      35.362   8.313 -19.530  1.00  0.00           H  
ATOM      6 3HY  MET A   1      36.359   9.596 -18.727  1.00  0.00           H  
ATOM      7  N   MET A   1      34.018  10.791 -19.775  1.00 20.33           N  
ATOM      8  CA  MET A   1      32.868  11.699 -19.798  1.00 18.20           C  
ATOM      9  C   MET A   1      31.568  10.891 -19.713  1.00 15.92           C  
ATOM     10  O   MET A   1      31.352   9.991 -20.514  1.00 14.01           O  
ATOM     11  CB  MET A   1      32.903  12.559 -21.061  1.00 21.42           C  
ATOM     12  CG  MET A   1      31.963  13.738 -21.031  1.00 25.49           C  
ATOM     13  SD  MET A   1      32.638  15.208 -21.861  1.00 31.29           S  
ATOM     14  CE  MET A   1      32.598  14.706 -23.443  1.00 28.17           C  
ATOM     15  HN  MET A   1      34.664  10.775 -20.551  1.00  0.00           H  
ATOM     16  HA  MET A   1      32.926  12.355 -18.930  1.00  0.00           H  
ATOM     17  HB3 MET A   1      32.676  11.938 -21.927  1.00  0.00           H  
ATOM     18  HB2 MET A   1      33.920  12.912 -21.229  1.00  0.00           H  
ATOM     19  HG3 MET A   1      31.724  13.984 -19.996  1.00  0.00           H  
ATOM     20  HG2 MET A   1      31.018  13.460 -21.499  1.00  0.00           H  
ATOM     21  HE1 MET A   1      32.982  15.498 -24.086  1.00  0.00           H  
ATOM     22  HE2 MET A   1      33.215  13.815 -23.558  1.00  0.00           H  
ATOM     23  HE3 MET A   1      31.571  14.475 -23.726  1.00  0.00           H  
ATOM     24  N   THR A   2      30.712  11.223 -18.741  1.00  9.98           N  
ATOM     25  CA  THR A   2      29.469  10.501 -18.503  1.00  8.85           C  
ATOM     26  C   THR A   2      28.342  11.463 -18.217  1.00 11.00           C  
ATOM     27  O   THR A   2      28.506  12.405 -17.424  1.00  9.24           O  
ATOM     28  CB  THR A   2      29.651   9.536 -17.306  1.00 15.81           C  
ATOM     29  OG1 THR A   2      30.789   8.703 -17.531  1.00 13.83           O  
ATOM     30  CG2 THR A   2      28.415   8.664 -17.034  1.00 15.49           C  
ATOM     31  H   THR A   2      30.915  12.004 -18.134  1.00  0.00           H  
ATOM     32  HA  THR A   2      29.222   9.920 -19.391  1.00  0.00           H  
ATOM     33  HB  THR A   2      29.843  10.135 -16.416  1.00  0.00           H  
ATOM     34  HG1 THR A   2      30.901   8.105 -16.788  1.00  0.00           H  
ATOM     35 HG21 THR A   2      28.610   8.012 -16.183  1.00  0.00           H  
ATOM     36 HG22 THR A   2      27.560   9.303 -16.813  1.00  0.00           H  
ATOM     37 HG23 THR A   2      28.197   8.058 -17.913  1.00  0.00           H  
ATOM     38  N   GLU A   3      27.186  11.203 -18.842  1.00  8.87           N  
ATOM     39  CA  GLU A   3      25.982  11.973 -18.580  1.00  7.86           C  
ATOM     40  C   GLU A   3      25.238  11.354 -17.409  1.00 11.09           C  
ATOM     41  O   GLU A   3      25.183  10.124 -17.284  1.00 10.54           O  
ATOM     42  CB  GLU A   3      25.055  11.978 -19.791  1.00  9.04           C  
ATOM     43  CG  GLU A   3      25.462  12.978 -20.839  1.00 12.16           C  
ATOM     44  CD  GLU A   3      24.509  13.090 -22.010  1.00 19.31           C  
ATOM     45  OE1 GLU A   3      24.886  13.774 -22.981  1.00 11.19           O  
ATOM     46  OE2 GLU A   3      23.403  12.500 -21.976  1.00 12.96           O1-
ATOM     47  H   GLU A   3      27.134  10.454 -19.517  1.00  0.00           H  
ATOM     48  HA  GLU A   3      26.256  12.998 -18.332  1.00  0.00           H  
ATOM     49  HB3 GLU A   3      24.036  12.188 -19.466  1.00  0.00           H  
ATOM     50  HB2 GLU A   3      25.030  10.981 -20.232  1.00  0.00           H  
ATOM     51  HG3 GLU A   3      26.458  12.730 -21.207  1.00  0.00           H  
ATOM     52  HG2 GLU A   3      25.581  13.958 -20.376  1.00  0.00           H  
ATOM     53  NT  GLU A   3      24.622  12.170 -16.482  1.00  0.00           N  
ATOM     54  CAT GLU A   3      23.907  11.584 -15.358  1.00  0.00           C  
ATOM     55  HT  GLU A   3      24.667  13.173 -16.584  1.00  0.00           H  
ATOM     56 1HA  GLU A   3      23.976  10.475 -15.428  1.00  0.00           H  
ATOM     57 2HA  GLU A   3      24.361  11.929 -14.402  1.00  0.00           H  
ATOM     58 3HA  GLU A   3      22.839  11.897 -15.386  1.00  0.00           H  
ENDMDL
END 
</pre>

Code:
```python
from simtk.openmm.app import PDBFile
from simtk.openmm import app
from simtk import unit
from simtk.openmm import Platform
from simtk.openmm import LangevinIntegrator

print('building protein and solvating...')
# Load the force field parameters through OpenMM.
omm_forcefield = app.ForceField('charmm36.xml','charmm36/water.xml')

# Load the PDB file.
prot_pdb_file = PDBFile('final_pdb_git_edit.pdb') 
modeller = app.Modeller(prot_pdb_file.topology, prot_pdb_file.positions)
top = prot_pdb_file.topology

## ADDING EXTRA BONDS ##
# Adding extra bonds to the first residue
res = [res for res in top.residues()][0]
atoms = [atom for atom in res.atoms()]
bonds = [bond for bond in res.bonds()]
top.addBond(atoms[0],atoms[3])  
top.addBond(atoms[0],atoms[4])  
top.addBond(atoms[0],atoms[5])  
top.addBond(atoms[0],atoms[1])  
top.addBond(atoms[1],atoms[2])  
top.addBond(atoms[1],atoms[6])   

res = [res for res in top.residues()][0]
bonds = [bond for bond in res.bonds()]

# Adding extra bonds to the last residue
res = [res for res in top.residues()][-1]
atoms = [atom for atom in top.atoms()]
bonds = [bond for bond in res.bonds()]
top.addBond(atoms[39],atoms[52])
top.addBond(atoms[52],atoms[53])
top.addBond(atoms[52],atoms[54])
top.addBond(atoms[53],atoms[55])
top.addBond(atoms[53],atoms[56])
top.addBond(atoms[53],atoms[57])
res = [res for res in top.residues()][-1]
bonds = [bond for bond in res.bonds()]
## FINISHED ADDING EXTRA BONDS ##

print('Adding hydrogens...')
modeller.addHydrogens(omm_forcefield)

# Deleting exra hydrogens
h2 = [atom for atom in modeller.topology.atoms() if atom.name == 'H2' and atom.residue.name == 'MET']
print('atom to be deleted:', h2)
modeller.delete(h2)
h3 = [atom for atom in modeller.topology.atoms() if atom.name == 'H3' and atom.residue.name == 'MET']
print('atom to be deleted:', h3)
modeller.delete(h3)

print('Adding solvent...')
# here we can also add ionic concentration (read addSolvent?)
modeller.addSolvent(omm_forcefield, model='tip3p', padding=1*unit.nanometer, ionicStrength=0.1*unit.molar, positiveIon='Na+', negativeIon='Cl-')

with open('output.pdb', 'w') as f:
    PDBFile.writeFile(modeller.topology, modeller.positions, f)

prot_system = omm_forcefield.createSystem(modeller.topology, nonbondedMethod=app.PME, rigidWater=True)


import parmed
print('creating protein structure')
prot_structure = parmed.openmm.load_topology(modeller.topology, prot_system, xyz=modeller.getPositions())
prot_system2 = prot_structure.createSystem(nonbondedMethod=app.PME, rigidWater=True)
```

Output:

<pre>
building protein and solvating...
Adding hydrogens...
atom to be deleted: [Atom 7 (H2) of chain 0 residue 0 (MET)]
atom to be deleted: [Atom 7 (H3) of chain 0 residue 0 (MET)]
Adding solvent...
creating protein structure
/home/asgharrazavi/miniconda3/lib/python3.7/site-packages/parmed/openmm/topsystem.py:451: OpenMMWarning: Detected incomplete exceptions. Not supported.
  warnings.warn('Detected incomplete exceptions. Not supported.', OpenMMWarning)
/home/asgharrazavi/miniconda3/lib/python3.7/site-packages/parmed/openmm/topsystem.py:187: OpenMMWarning: Unsupported Force type CustomNonbondedForce
  warnings.warn('Unsupported Force type %s' % type(force).__name__, OpenMMWarning)
/home/asgharrazavi/miniconda3/lib/python3.7/site-packages/parmed/openmm/topsystem.py:187: OpenMMWarning: Unsupported Force type CustomBondForce
  warnings.warn('Unsupported Force type %s' % type(force).__name__, OpenMMWarning)
Traceback (most recent call last):
  File "__code.py", line 74, in <module>
    prot_system2 = prot_structure.createSystem(nonbondedMethod=app.PME, rigidWater=True)
  File "/home/asgharrazavi/miniconda3/lib/python3.7/site-packages/parmed/utils/decorators.py", line 31, in new_fcn
    return fcn(*args, **kwargs)
  File "/home/asgharrazavi/miniconda3/lib/python3.7/site-packages/parmed/structure.py", line 1995, in createSystem
    raise ParameterError('Cannot createSystem: unknown functional')
parmed.exceptions.ParameterError: Cannot createSystem: unknown functional
</pre>

OpenMM accepts and simulated the system created by  `prot_system = omm_forcefield.createSystem(modeller.topology, nonbondedMethod=app.PME, rigidWater=True)`.  I suspect that the step using ` parmed.openmm.load_topology` is the actual issue.

**Comment by ahy3nz** [comment]
https://github.com/ParmEd/ParmEd/blob/master/parmed/openmm/topsystem.py#L190 You might be right. Parmed tries its best to translate the various openmm forces into respective parmed objects and parameters, but there are various XML tags (LennardJonesForce and NBFixPair I think) that create openmm Force objects (CustomNonbondedForce and CustomBondForce) that parmed cannot correctly parse, and this causes the program to error out only when your incomplete-parmed structure tries to create an openmm system... which is interesting because [parmed's xml writer](https://github.com/ParmEd/ParmEd/blob/109486be7177adc7c2f792884a68165f27db0062/parmed/openmm/parameters.py#L1032) appears responsible for writing out some of these tags to the XML

**Comment by asgharrazavi** [comment]
Is it possible to write the parameters in the `prot_structure` object in above code as OpenMM `xml` parameter file?  so that I can load the parameter file directly to OpenMM?

**Comment by ahy3nz** [comment]
I haven't done this in a rigorous simulation procedure for accuracy. With some prototype code and some roundabout methods, it seems possible and here's maybe some starter code

You can convert your parmed structure into a parmed amber parameter set, parmed amber parameter set into parmed openmm parameter set, parmed openmm parameterset into xml

```
amber_pset = pmd.amber.parameters.ParameterSet.from_structure(struc)
omm_pset = pmd.openmm.parameters.OpenMMParameterSet.from_parameterset(amber_pset)
omm_pset.write("test.xml")
```

And some [additional write arguments](https://github.com/ParmEd/ParmEd/blob/109486be7177adc7c2f792884a68165f27db0062/parmed/openmm/parameters.py#L305)

**Comment by asgharrazavi** [comment]
Thanks @ahy3nz ! Your procedure works and I can write an xml file. However, the names given for atomtypes are very general and they overlap with other atom types in charmm force filed. Is there a way to ask the program to write unique names for atom types?

**Comment by asgharrazavi** [comment]
Also, I noticed that the written `xml` file doesn't have the `Residues` section. Is there a way to add the residue information (i.e. residue name and bonds) to the xml writer?

**Comment by swails** [comment]
> Also, I noticed that the written `xml` file doesn't have the `Residues` section. Is there a way to add the residue information (i.e. residue name and bonds) to the xml writer?

[This is already done in the code](https://github.com/ParmEd/ParmEd/blob/109486be7177adc7c2f792884a68165f27db0062/parmed/openmm/parameters.py#L405-L406) as long as the parameter set has residue information.  The problem here is that `ParameterSet.from_structure` doesn't populate a library of residue templates from the residues defined therein.

You can use the following code to add templates (and then they will be written out):

```python
import parmed as pmd

amber_pset = pmd.amber.parameters.ParameterSet.from_structure(struc)
omm_pset = pmd.openmm.parameters.OpenMMParameterSet.from_parameterset(amber_pset)
omm_pset.residues.update(pmd.modeller.ResidueTemplateContainer.from_structure(struc).to_library())
omm_pset.write("test.xml")
```

See if that works for you.

**Comment by asgharrazavi** [comment]
Thanks @swails ! Your code is working and an xml is written.  The only thing that I had to modify was to add a `LennardJonesForce` section at the end of xml. Without this, OpenMM complains that can't find LennardJones values. To created `LennardJonesForce` section, I simply copied data from `NonbondedForce` section.

```xml
<NonbondedForce coulomb14scale="1.0" lj14scale="1.0">
    <UseAttributeFromResidue name="charge"/>
    <Atom type="LIGC1" sigma="0.3399669508423535" epsilon="0.359824"/>
    <Atom type="LIGO1" sigma="0.3066473387839048" epsilon="0.8803136"/>
    <Atom type="LIGO2" sigma="0.2959921901149463" epsilon="0.87864"/>
  </NonbondedForce>
  <LennardJonesForce  lj14scale="1.0">
    <Atom type="LIGC1" sigma="0.3399669508423535" epsilon="0.359824"/>
    <Atom type="LIGO1" sigma="0.3066473387839048" epsilon="0.8803136"/>
    <Atom type="LIGO2" sigma="0.2959921901149463" epsilon="0.87864"/>
  </LennardJonesForce>
</ForceField>
```
