### ISSUE TITLE
Stripping only a subset of atoms

### ISSUE THREAD

**Issue by chrisjonesBSU** [ParmEd/ParmEd#1114]
I'm a little confused about the strip method in a Structure object.  

Per the doc strings, strip `Deletes a subset of the atoms corresponding to an atom-based selection.`

However, if using an iterable it requires that the selection is the same length as all of the atoms in the system.  How can I pass an iterable that contains (and removes) only the subset of atoms I want to delete?

For example, if I have a Structure that was a benzene molecule and I want to remove only the hydrogen atoms while leaving carbon.

```
>>>len(benzene.atoms)
12
>>>hydrogens = [a for a in benzene.atoms if a.name == 'H']
>>>benzene.strip(selection=hydrogens)
>>>len(benzene.atoms)
6
```

**Comment by swails** [comment]
`Structure.split` takes either an Amber-style mask selection (as an `AmberMask` or `str` instance), or it takes a mask array.

A mask array is an array of the same length as the collection it is selecting from, with each element treated as a boolean.  If you want to strip out all hydrogen atoms, you can do this:

```python
benzene.strip([a.atomic_number == 1 for a in benzene.atoms])
```
