### ISSUE TITLE
AttributeError in gromacstopfile with 2 site extra point

### ISSUE THREAD

**Issue by tverho** [ParmEd/ParmEd#1121]
Writing a structure with a two point virtual site as a gromacs topology results in an error due to a typo in the code:

https://github.com/ParmEd/ParmEd/blob/8adcb002f24eb4d898f11329392cca4df3bdb084/parmed/gromacs/gromacstop.py#L2030

It should be `EP.frame_type.get_weights()` instead of `EP.get_weights()`.

**Comment by swails** [comment]
Sorry I didn't see this before.  I'll incorporate this fix into my next PR.

**Comment by tverho** [comment]
Thanks!
