### ISSUE TITLE
Generation of 1,4 pairs for a molecule using ParmEd?

### ISSUE THREAD

**Issue by sathishclri** [ParmEd/ParmEd#1124]
Hi
Can we generate 1, 4 pairs for a given molecule using ParmEd?

Please provide details how to generate 1,4 pairs using ParmEd.

Thanks
Sathish

**Comment by swails** [comment]
You just want atoms that are separated by only 3 bonds within a molecule?

You could loop through each atom and scan through the `dihedral_partners`:

```python
# Assumes you have a Structure named "struct"
pairs_14 = set()
for atom in struct[:1]: # Assumes the first residue is a "molecule"
    for atom2 in atom.dihedral_partners:
        # Avoid duplicates by sorting
        pairs_14.add((atom, atom2) if atom.idx < atom2.idx else (atom2, atom))
```

The `ResidueTemplate` class has a `to_networkx()` method that builds a graph based on bond connectivity.  I should add this to `Structure` as well so you can use that library for doing these kinds of graph-based analyses.

**Comment by swails** [comment]
Closing this as it's been answered.
