### ISSUE TITLE
Dependencies?

### ISSUE THREAD

**Issue by emleddin** [ParmEd/ParmEd#1126]
Hi!

I'm thinking of tinkering with the Tinker submodule, and I was wondering if `numpy` is still the only dependency for ParmEd (#574 from 2016). Despite `numpy` clearly being imported in several parts of the code, there are no [dependencies declared](https://setuptools.readthedocs.io/en/latest/userguide/dependency_management.html#declaring-dependencies) in `setup.py` (which also means none are listed in the [dependency graph](https://github.com/ParmEd/ParmEd/network/dependencies) from GitHub's insights). 

I've seen `pandas` mentioned a few times throughout issues and the docs, but I couldn't tell if it was just a formatting compatibility thing. A lot of the scripts that I've written for dealing with Tinker use `pandas`, so that'd be my go-to strategy for addressing certain things.

**Comment by hainm** [comment]
I guess there is a assumption that `numpy` is everywhere.

**Comment by mattwthompson** [comment]
Python packaging is a bit of a mess; unfortunately there tends to be no single source of truth for what a package depends on and in many cases it depends on how it's packaged and/or how the user accesses it. For example, one of the conda builds (but not the only one) has a really light set of dependencies: https://github.com/conda-forge/parmed-feedstock/blob/ceb46412899a930e3746beb32dc56faa0f3f6bf3/recipe/meta.yaml#L20-L29. I don't know how it's packaged within other Amber infrastructure, but it probably doesn't bring in other Python dependencies.

**Comment by swails** [comment]
The philosophy that ParmEd uses is that having certain packages will "unlock" certain functionality that depends on it, but is not required to use the functionality that doesn't depend on that package.

I made the decision awhile ago that numpy is ubiquitous enough, powerful enough, and needed in enough places that continuing to make it optional was a crappy tradeoff.  The other dependencies were easy enough to isolate that I felt the benefits of making them optional outweighed the added complexity (which is minimal).

**Comment by swails** [comment]
> I've seen `pandas` mentioned a few times throughout issues and the docs, but I couldn't tell if it was just a formatting compatibility thing.

Some parts of ParmEd support, effectively, serializing to (and deserializing from) a pandas DataFrame.  It's a convenience for people that like using pandas for everything, but I expect it's far from common use.

**Comment by salotz-sitx** [comment]
This should really be addressed. There are ways to specify the different optional dependencies. For me I have to go through and figure this out based on imports.

**Comment by swails** [comment]
> There are ways to specify the different optional dependencies.

Do you have a reference to these ways you speak of?  I'd be happy to do something here to make life easier.

**Comment by salotz-sitx** [comment]
https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies

**Comment by salotz-sitx** [comment]
At minimum specifying the necessary dependencies in either `setup.py`/`setup.cfg`/`pyproject.toml` is typically a given in any project.
