### ISSUE TITLE
12-6-4 parameters of ions (conversion from amber to gromacs topology)

### ISSUE THREAD

**Issue by eveliz147** [ParmEd/ParmEd#1129]
Hello!
I would like to know how parmed convert 12-6-4 parameters of ions during the conversion of amber topology to gromacs?
I converted files like : amber = pmd.load_file('prmtop', 'inpcrd')
amber.save('gromacs.top')
amber.save('gromacs.gro') and had some parameters for ions, but I am not sure that they are correct. Probably, somebody could help me? How these parameters were made or maybe I need to do something else?

**Comment by radakb** [comment]
The 12-6-4 parameters in the AMBER format are a bit of a hack. The ParmEd action just adds a new LENNARD_JONES_CCEOF section to the prmtop which in turn flags an alternate code path in sander/pmemd. The only other special function in ParmEd is the combining rules for the CCOEF values, which were specially derived (I believe) for things like cations and metal centers. I would read the papers by Li and Merz on the subject.

I don't know if _any_ of this is compatible with any other formats (for example, it's definitely not supported in CHARMM/XPLOR). Does Gromacs say that it supports 12-6-4 potentials? You may need to manually test the potential in your program of choice by doing a scan with a simple reference system.

**Comment by swails** [comment]
As @radakb pointed out, GROMACS does not support the 12-6-4 potential that Amber uses for certain ions.

To my knowledge, the only two simulation packages that actually support this potential is Amber and OpenMM (through its ParmEd support).
