### ISSUE TITLE
Cut a new release?

### ISSUE THREAD

**Issue by jchodera** [ParmEd/ParmEd#1134]
@swails: The latest release of ParmEd was 2019, and it turns out we need the a release with #1082 and #1091 in it for completing our omnia ecosystem migration to conda-forge.

Would it be possible to cut a new release and update the version on conda-forge?

cc https://github.com/openmm/openmmforcefields/pull/149#issuecomment-766715783
cc @SimonBoothroyd @jaimergp

**Comment by jchodera** [comment]
@swails : Just wondering what you thought the timescale for cutting a new release and updating the version on conda-forge might be.

**Comment by swails** [comment]
I'm actually doing a little ParmEd revival work at the moment.  I'm currently working through a substantial code simplification that's basically a jettison of the Python 2.7 legacy support and leveraging Python 3.6+ features.  While I was at it, I was going to remove options and behavior that has been deprecated (and raising DeprecationWarnings) for years.

My plan was to cut a 4.0 release after I was done with this work (should be within a week or so).

That doesn't prevent me from cutting 3.3.0 now, but everything else equal I'd rather just do 4.0.

**Comment by jaimergp** [comment]
I'd prefer a 3.3.0 of the current `master` if possible. I have some ideas for the `ambertools` vendoring situation that would benefit from a release now :)

**Comment by swails** [comment]
I cut 3.3.0 and 3.4.0 as requested -- I'll leave it up to you to update the conda-forge feedstocks.

**Comment by jchodera** [comment]
Thanks!
