### ISSUE TITLE
Cite ParmEd??

### ISSUE THREAD

**Issue by Clownshift** [ParmEd/ParmEd#1142]
Hello Devs,

I wanted to refer to ParmEd in a paper and I wondered whether there is a specific publication to cite?

I am aware that ParmEd may be associated with Amber, but also OpenMM. Therefore, I asked myself whether there is a stand-alone publication of the tool, which I overlooked, or whether I may cite some publication of these engines. Of course, I might also simply give the github-link.

In any case, I would be happy to do as the developers prefer...?

Thanks in advance!
Patrick

**Comment by swails** [comment]
This is the third time this issue has popped up - see #1108 for my response there.

I think what this means is I need to update the README to add the citation there 😃

**Comment by Clownshift** [comment]
Great thank you for the reply. Also, I like the idea of putting it in the README. 

For future reference:
https://www.biorxiv.org/content/10.1101/077248v1
or
http://dx.doi.org/10.1007/s10822-016-9977-1
