### ISSUE TITLE
Newer versions of ParmEd errantly converting to CHAMBER-style prmtop

### ISSUE THREAD

**Issue by tuckerburgin** [ParmEd/ParmEd#1151]
I have been using ParmEd in Python to make some minor changes to Amber prmtop files:

```
parmed_top = parmed.load_file(path_to_prmtop)
<do some actions on parmed_top>
parmed_top.save(path_to_prmtop, overwrite=True)
```

I originally began development on version 3.2.0+27, and had no trouble. Since updating to version 3.4.0, however, the same code causes ParmEd to output a CHAMBER-style file. To illustrate, the portion of my prmtop file before the `%FLAG ATOM_NAME` line goes from

```
%VERSION  VERSION_STAMP = V0001.000  DATE = 02/26/21  10:37:27
%FLAG TITLE
%FORMAT(20a4)
default_name
%FLAG POINTERS
%FORMAT(10I8)
   68801      23   49734   19187    8064    5150   16509   15763       0       0
  147758   15841   19187    5150   15763      97     213     214      57       1
       0       0       0       0       0       0       0       1      56       0
   15398
```

... to:

```
%VERSION  VERSION_STAMP = V0001.000  DATE = 02/27/21  15:21:13
%FLAG CTITLE
%FORMAT(20a4)

%FLAG POINTERS
%FORMAT(10I8)
   68801      57   49734   19187    8064    5150   16509   15763       0       0
  147758   15841   19187    5150   15763      97     213     214       1       0
       0       0       0       0       0       0       0       1      56       0
   15398
%FLAG FORCE_FIELD_TYPE
%FORMAT(i2,a78)
 1                               CHARMM force field: No FF information parsed...
```

... (along with extensive changes to the rest of the file, of course) whereas, on version 3.2.0+27, the prmtop file produced by ParmEd is identical to the input file (except for the date and timestamp, of course). On both versions, the `chamber` AmberParm attribute is `False`, as expected.

This bug is causing problems for my workflow (namely, passing the topology to OpenMM, which cannot read CHAMBER-style files). For now, I'll just revert to an earlier version without the bug.

Thanks!

**Comment by tuckerburgin** [comment]
Sorry -- have to amend this. Downgrading to 3.2.0+27 did NOT fix the issue for me as I had expected, nor did downgrading AmberTools to the version I had previously been working with (from 20.15 to 20.9). Can the ParmEd devs help me identify what other factors might be responsible for this unexpected behavior?

**Comment by swails** [comment]
Can you send me a file with a script that exposes the issue?

**Comment by tuckerburgin** [comment]
Sorry, are you asking for a prmtop file which I'm getting this issue with, or a Python script?

As for the Python script, this'll do it:

```
import parmed
parmed_top = parmed.load_file('top.prmtop')
parmed_top.save('test.prmtop')
```

I've attached the `top.prmtop` I've been using, if that's what you mean. GitHub won't let me upload it as a .prmtop file so it's zipped.

[test.prmtop.zip](https://github.com/ParmEd/ParmEd/files/6056124/test.prmtop.zip)

**Comment by tuckerburgin** [comment]
It looks like the issue isn't actually to do with the ParmEd or Ambertools version but with the specific prmtop file (sorry about the confusion on that point). Just tested the above `test.prmtop` with the above three lines of code and got the CHAMBER issue, but this other .prmtop goes through the same code just fine on the same system.

These two topology files are of very similar systems (a protein in explicit water), but involve different force fields and water molecules. Both were built with Amber's tleap and use native Amber force fields. I didn't use CHARMM for anything. The working one (workingfine.prmtop, attached here) is ff14SB in TIP3P built in Amber 16 or 18 (don't recall which) and the not-working one (test.prmtop above) is ff19SB in OPC built in Amber 20.

[workingfine.prmtop.zip](https://github.com/ParmEd/ParmEd/files/6056127/workingfine.prmtop.zip)

**Comment by swails** [comment]
The problem is that CMAP terms were introduced in Amber force fields far after they were introduced into the Amber source code base via the CHARMM extensions.

While in most places I added support for reading and writing CMAP terms in regular Amber-style topologies, `Structure.save` (which is pretty complicated as it does automatic structure conversions) was still being told to think that any structure it found with CMAPs must be converted to Chamber-style topologies.

I've raised #1152 to fix this problem.

A workaround is to use `write_parm()` instead of `save()`.  The former only works on `AmberParm` or `ChamberParm` objects and will always write a file of the same type.  But this happens to be exactly what you want.

**Comment by tuckerburgin** [comment]
Workaround works for me like a charm (heh). Thanks for your very quick help!

**Comment by swails** [comment]
I converted your topology file (stripped down to a minimal example that reproduced this bug) into a unit test which failed under the old code (expectedly) and now passes.

This should be fixed in the latest version on git, and the workaround I described above should help.
