### ISSUE TITLE
"Cl" in prmtop recognized as "C" when loaded

### ISSUE THREAD

**Issue by ggdhzdx** [ParmEd/ParmEd#1158]
I have a Cl atom in my prmtop 
When it loaded as a structure in Parmed 
the Cl atom become a carbon
the atom.atomic_num and atom.element are 6

**Comment by swails** [comment]
prmtop files have element information stored in them.  Are you sure it's supposed to be a chlorine?

**Comment by ggdhzdx** [comment]
I found the problem. It's in the prmtop
I generate this prmtop by antechamber and tleap from a gaussian log file.
The chlorine has correct atom_name,  Mass,  and atom type. But its atomic_number became 6.
