### ISSUE TITLE
doctrees update

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#116]
@swails 

hey man,
is there any better/cleaner way to update 'doctrees' in your github? I saw endless black files.
https://github.com/ParmEd/ParmEd/commit/a0bfae0949ca85f28ee16dbb9ea5cc53d0049544

Or may be using different approach/account to upload doc?

Hai

**Comment by swails** [comment]
This is done in the `gh-pages` branch, which is the branch controlling the website (http://parmed.github.io/ParmEd).  This branch shares no history with any of the code branches (like `master`).  It works a bit like `amber_web` in that the Git repo hosts all of the code, and a simple "push" to `gh-pages` updates the website... very convenient.

And I use [sphinx](http://sphinx-doc.org/install.html) to generate documentation, so those doctrees are automatically generated.  There is no way to change that without either switching where I host the docs or not using Sphinx anymore.  The simple solution is to just not look at any commits that only live in the `gh-pages` branch :).
