### ISSUE TITLE
add bond, angle, dihedral indices

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#117]
What do you think about adding "indices" as 2D array of integers for bonds, angles, dihederal

    import chemistry as chem
    parm = chem.load_file(parm_name)

    print (parm.bonds.indices)

This is my motivation:
https://github.com/pytraj/pytraj/commit/2d49d6c5a06d0307249fe013b56c990eb7f01d96#diff-92f64d23082b0f9b6e46fcf1146703c3R544

(or may be no one except me wants them :D)

**Comment by swails** [comment]
This should be easy enough to do with a listcomp.  For example:

```Python
bond_indices = [[b.atom1.idx, b.atom2.idx] for b in parm.bonds]
angle_indices = [[a.atom1.idx, a.atom2.idx, a.atom3.idx] for a in parm.angles]
dihed_indices = [[d.atom1.idx, d.atom2.idx, d.atom3.idx, d.atom4.idx] for d in parm.dihedrals]
```

and so on.  Getting these indices are simple, fairly efficient 1-liners, so I don't think it's worth the added complexity (on top of an already-too-complex bookkeeping scheme) to add.  Also, this `indices` descriptor wouldn't really fit naturally on any of the classes ParmEd uses (`parm.bonds`, for instance, is a `TrackedList`, along with a lot of other lists, like the atom and residue lists).

But if you wanted to be opaque and convoluted, you can monkey-patch this into ParmEd using something like the following:

```Python
import chemistry as chem

def indices(self):
    index_array = []
    for term in self:
        index_array.append([])
        for attr in dir(term):
            if attr.startswith('atom'):
                index_array[-1].append(getattr(term, attr).idx)
    return index_array # You can cast to numpy array first if you want

# Turn it into a descriptor on the TrackedList type
chem.TrackedList.indices = property(indices)
del indices
```

:)

**Comment by hainm** [comment]
I see. 

H
