### ISSUE TITLE
Inconsistent SHAKEH hydrogen clusters

### ISSUE THREAD

**Issue by aminsagar** [ParmEd/ParmEd#1181]
Dear ParmEd Users/Developers,
I am trying to run some simulations with Amber using a modified force field that is only available for gromacs. I tried preparing the system with gromacs and then convert it to amber format files using gromber. My input script is 

gromber topol.top conf1-ions.gro topdir forcefield.ff radii mbondi2
outparm conf1-ions.parm7 conf1-ions.rst7

With the resulting files, I can run minimization, but when I try to start an equilibration, I get an error i.e.
4: 7 - 8 and 6: 7 - 10
Hydrogen atom 7 appears to have multiple bonds to atoms 8 and 10 which is illegal for SHAKEH.
Exiting due to the presence of inconsistent SHAKEH hydrogen clusters.

I searched the Amber forum and it seemed like this could be due to atom naming problems.  
To make sure that this was really the reason, I tried using AMBER99SB-ILDN and CHARMM27 but I got the same error with both. So, it seems that force-field is not the problem here. Also, I tried another structure with CHARMM27 and I didn't get any errors. 

The structure I am using works well with gromacs. What could be wrong with my structure that is leading to this?
I would be grateful for any suggestions.

Best,
Amin.

**Comment by aminsagar** [comment]
I think I have made some progress. Initially, I was using -heavyh in pdb2gmx step for hydrogen mass repartitioning. I tried removing it and using hmassrepartition in the parmed input. Now, I don't get the error with CHARMM27 and am able to run the simulations.

With the modified force field, the error moves to a later atom as 
552: 1139 - 1140 and 554: 1140 - 1141
Hydrogen atom 1140 appears to have multiple bonds to atoms 1139 and 1141 which is illegal for SHAKEH.
Exiting due to the presence of inconsistent SHAKEH hydrogen clusters. These atoms actually belong to waters as seen in my input gro file.

   68PRO    OC1 1137   7.898   4.517   6.731
   68PRO    OC2 1138   8.053   4.607   6.659
   69SOL     OW 1139   1.736   0.839   0.257
   69SOL    HW1 1140   1.777   0.781   0.322
   69SOL    HW2 1141   1.643   0.831   0.274
   69SOL     MW 1142   1.730   0.831   0.267

**Comment by swails** [comment]
Sorry, I just noticed this.  I think this problem is actually getting fixed in #1157 -- can you try the code in that branch to see if it fixes your issues?

**Comment by swails** [comment]
> 2\. If I change ifbox to 3, I can run the simulation. Is this way correct? or should I change the angles?

Yes, that's fine.  If the box configuration is wrong, one of two things will happen:

1. The simulation will blow up due to overlaps
2. The simulation density will be way too low because the box is too big and there's way too much empty space

If neither of those are the case, then the PBC are being handled correctly.  It's really hard to handle those "wrong" without noticing.

**Comment by aminsagar** [comment]
Thanks Jason. 
I checked the box and everything seemed correct so I continued these simulations. They have been running for many days now without a problem so I think it works.
I will check with the new version of ParmEd early next week and report back. 
Thanks again.
Amin.
