### ISSUE TITLE
catch OpenMMWarning

### ISSUE THREAD

**Issue by qvv5013** [ParmEd/ParmEd#1192]
Hi all,
How can I catch the OpenMMWarning? As I load the OpenMM system which contains CustomNonbondedForce, I know this is safe for my problem then want to get rid of the warnings.
I try with `except OpenMMWarning` but doesn't work

```
/home/qvuvan/anaconda3/lib/python3.8/site-packages/parmed/openmm/topsystem.py:191: OpenMMWarning: Unsupported Force type CustomNonbondedForce
  warnings.warn('Unsupported Force type %s' % type(force).__name__, OpenMMWarning)
/home/qvuvan/anaconda3/lib/python3.8/site-packages/parmed/openmm/topsystem.py:191: OpenMMWarning: Unsupported Force type CustomNonbondedForce
  warnings.warn('Unsupported Force type %s' % type(force).__name__, OpenMMWarning)
```

**Comment by swails** [comment]
These are issued by the Python `warnings` module.  You can silence them with [`warnings.filterwarnings`](https://docs.python.org/3/library/warnings.html#warnings.filterwarnings):

```python
import warnings
from parmed.exceptions import OpenMMWarning

warnings.filterwarnings("ignore", category=OpenMMWarning)
```

**Comment by qvv5013** [comment]
thanks
