### ISSUE TITLE
darwin_major table in setup.py is outdated

### ISSUE THREAD

**Issue by dacase** [ParmEd/ParmEd#1193]
In setup.py, the MACOS_DEPLOYMENT_TARGET is determined by the following code in `setup.py`:
```def prepare_env_for_osx():
    """ Prepares the environment for OS X building """
    darwin_major_to_osx_map = {
        '11': '10.7',
        '12': '10.8',
        '13': '10.9',
        '14': '10.10',
        '15': '10.11',
        '16': '10.12',
        '17': '10.13',
        '18': '10.14',
        '19': '10.15',
    }
```
This table is outdated, (and this will be a recurring problem).  My darwin major for OSX 11.5 is "20".  I'm not really sure
what deployment target I should set: `11.5`?

Not setting the deployment target leads to the dreaded "locale not found" error.  Adding a 20 to the table (pointing to 11.5) eliminates that problem.

p.s. for @hainm:  similar problems arise for `pytraj`:  I haven't yet investigated those....

**Comment by hainm** [comment]
> p.s. for @hainm: similar problems arise for pytraj: I haven't yet investigated those....

Noted. I've opened a new issue to keep track. Thanks
https://github.com/Amber-MD/pytraj/issues/1581

**Comment by swails** [comment]
I think #1200 offers a more permanent fix.  I don't have old versions of macOS/OSX to try it on so I left the current (known-to-work) solution in place, but set the deployment target based on the output of the `sw_vers` program that seems to be properly functional on big sur.

We can probably roll this solution out to other python packages that encounter this error (like pytraj and anything else with compiled extensions).
