### ISSUE TITLE
What are differences between ParmEd and Acpype? 

### ISSUE THREAD

**Issue by physicshinzui** [ParmEd/ParmEd#1194]
I know the two ways to convert amber force field parameters to Gromacs: ParmEd and acpype. Could you please tell me what are differences between the two programs? What are pros and cons?

**Comment by swails** [comment]
acpype is a Amber -> GROMACS conversion utility.  ParmEd is a macromolecular MD modeling library with I/O support for a wide array of "standard" file formats.  It represents systems as a generalized data model (class) that allows you to interact with the system (remove atoms, cut bonds, slice, view, evaluate energies and forces, and much more).

By its nature, it can interconvert between many different file formats:

* PDB
* PDBx/mmCIF
* Amber prmtop/inpcrd
* GROMACS top/gro
* CHARMM prm/rtf/psf/crd
* OpenMM System, topology, etc.

So ParmEd can do what acpype can do and much more.  But you have to write a (2-3 line) Python script to do what acpype allows you to do via the command-line.

**Comment by physicshinzui** [comment]
I understand. Thanks!
