### ISSUE TITLE
GB parameters not written to prmtop from OpenMM system

### ISSUE THREAD

**Issue by rosemary-cresset** [ParmEd/ParmEd#1195]
I have the following script: 

`from simtk.openmm import app`
`import parmed as chem`

`pdb_file = app.PDBFile('1UHL.prep.protein.pdb')`
`forcefield = app.ForceField('amber/protein.ff14SB.xml')`
`system = forcefield.createSystem(pdb_file.topology, nonbondedMethod=app.CutoffNonPeriodic, implicitSolvent=app.OBC2)`

`struct = chem.openmm.load_topology(pdb_file.topology, system)`
`struct.save('1UHL.prmtop', overwrite=True)`

The prmtop file generated from the above does not contain the GB parameters under %FLAG RADII and %FLAG SCREEN (they are all zero). I can easily add them, but was just wondering if this was intentional or if there is something I am doing wrong that is causing them not to appear? 

Thanks

**Comment by rosemary-cresset** [comment]
Just read the OpenMM documentation a bit more closely and realised that implicitSolvent is not a supported argument for Forcefield.createSystem, but is for AmberPrmtopFile.createSystem. I get no error because arbitrary arguments are allowed in this call, so didn't notice. Posted this issue a bit prematurely, sorry!

**Comment by swails** [comment]
Glad you figured it out!
