### ISSUE TITLE
Wrong TIP3P water parameters saved out by ParmEd

### ISSUE THREAD

**Issue by yunhuige** [ParmEd/ParmEd#1197]
Hi,

I tried to parametrize my ligand (69G.sdf) using OpenFF 1.2.1 and the protein (protein.pdb) using AMBER14SB and built the simulation box (and added TIP3P water + ions). I used ParmEd to save *gro and *top files out. However, I found in the *top file (complex.top), the water hydrogen LJ parameters were not correct:

```
[ atomtypes ]
; name    at.num    mass    charge ptype  sigma      epsilon
H4             1   1.007947  0.00000000  A     0.26495328      0.0656888
``` 
After checking the topology file, I found these hydrogen parameters were the same as some hydrogens on the ligand.  
For a TIP3P water, the H atoms should have following parameters:
```
[ atomtypes ]
; name    at.num    mass    charge ptype  sigma      epsilon
H6             1   1.007947  0.00000000  A              1              0
```

I also tried to build the system without the ligand and I did not have this issue. So I think ParmEd got confused by some hydrogen atoms on the ligand and mistakenly assigned these ligand hydrogen atom type to the water hydrogens when saving the gromacs topology out. Do you have any insights?

I attached my input files and scripts as well. 

Here is a list of package versions I used. 

```
openeye-toolkits          2020.1.0                 py37_0    openeye
openforcefield            0.7.1              pyh39e3cac_0    omnia
openforcefields           1.3.0                      py_0    omnia
parmed                    3.4.1            py37hcd2ae1e_0    conda-forge
openmm                    7.5.1            py37h96c4ddf_0    conda-forge
```

Thanks!

[input_scripts.zip](https://github.com/ParmEd/ParmEd/files/7188223/input_scripts.zip)

**Comment by davidlmobley** [comment]
Following

**Comment by yunhuige** [comment]
A quick update: 

I just found this issue also messed up protein atoms parameters. Below is an example:

The HE2/HE3 atoms in LYS have the same atomtype but different LJ parameters: 

Just use protein-only:
```
[ atomtypes ]
; name    at.num    mass    charge ptype  sigma      epsilon
H2             1   1.007947  0.00000000  A     0.19599772      0.0656888
```

Use both protein and ligand (as in my scripts):
```
; name    at.num    mass    charge ptype  sigma      epsilon
H2             1   1.007947  0.00000000  A     0.25105526        0.06276
```

I also find this issue in other systems not just on H atoms but also C atoms.

**Comment by yunhuige** [comment]
With @mattwthompson's help, we now have a better understanding of the origin of this issue.
So the problem is that ParmEd assigns an atom type (as a simple string) to different atom types in each component, and when components are adding, they clash.  For example, if we follow my scripts attached earlier, and print out some LJ parameters (e.g., sigma) for different components (protein: `pmd_receptor_struct` and ligand: `pmd_ligand_struct`)
```
In [27]: {a.sigma for a in pmd_ligand_struct.atoms if a.type == 'H3'}
Out[27]: {2.5996424595335106}

In [28]: {a.sigma for a in pmd_receptor_struct.atoms if a.type == 'H3'}
Out[28]: {2.471353044121301}
```

We can see they have the same atom type ('H3' in this case) for different types of hydrogen atoms (since the parameters are different). Then let's take a look what is the sigma value for this atom type after we combine the two components (`pmd_complex_struct`):

```
pmd_complex_struct = pmd_receptor_struct + pmd_ligand_struct
```

```
In [29]: {a.sigma for a in pmd_complex_struct.atoms if a.type == 'H3'}
Out[29]: {2.471353044121301, 2.5996424595335106}
```

So the ligand’s H3 is assigned a sigma of 2.5996, the protein’s H3 is assigned 2.47, the complex manages to get both of them. If we save it out to a GROMACS topology file:

```
pmd_complex_struct.save('complex.top', overwrite=True)
``` 

Then take a look at the output file:

```
In [30]: !grep H3 complex.top | head -n 1
H3             1   1.007947  0.00000000  A     0.25996425        0.06276
```

Now we can see the sigma that’s associated with H3 in the top file is just whichever one is combined the last; in this case,  that’s the ligand value. In other worlds, this atom type for the protein is overwritten by the one for the ligand. Following this logic, we believe that is why those LJ parameters of water hydrogen, ions (CL) were replaced by those from the ligand as we've seen in this system and many other ones (not shown here).

So the problem seems to be the common protein and ligand atom names. One way to work around (without digging into ParmEd source code) is to give unique atom name for the ligand to avoid this issue. 
The following scripts were developed by Gaetano Calabro' (@nividic) (many thanks!) and we believe this could solve the issue for now. We can still use my original scripts but we need to create a new function:

```
    def unique_atom_types(pmd_structure):


        omm_system = pmd_structure.createSystem(nonbondedMethod=app.NoCutoff,
                                                constraints=None,
                                                removeCMMotion=False,
                                                rigidWater=False)


        # # Copy the topology and positions
        topology = pmd_structure.topology
        positions = pmd_structure.positions



        def check_water(res):
            two_bonds = list(res.bonds())

            if len(two_bonds) == 2:

                waters = []

                for bond in two_bonds:

                    elem0 = bond[0].element
                    elem1 = bond[1].element

                    if (elem0.atomic_number == 1 and elem1.atomic_number == 8) \
                            or (elem0.atomic_number == 8 and elem1.atomic_number == 1):
                        waters.append(True)

                if all(waters):
                    return True

            else:
                return False

        atom_types_dic = {}
        count_id = 0

        for c in topology.chains():
            for r in c.residues():
                for a in r.atoms():
                    if r.name + a.name in atom_types_dic:
                        a.id = atom_types_dic[r.name + a.name]
                        print('a.id',a.id)
                    else:
                        if check_water(r):
                            if a.element.atomic_number == 1:
                                a.id = 'HW'
                            else:
                                a.id = 'OW'
                            atom_types_dic[r.name + a.name] = a.id
                        elif r.name == 'LIG':
                            a.id = 'L' + str(count_id)


                        count_id += 1




        # Define a new parmed structure with the new unique atom types
        new_system_structure = pmd.openmm.load_topology(topology,
                                                           system=omm_system,
                                                           xyz=positions)
        # Re-set positions, velocities and box
        new_system_structure.positions = pmd_structure.positions
        new_system_structure.velocities = pmd_structure.velocities
        new_system_structure.box = pmd_structure.box

        return new_system_structure

```

Then we need to run this function before we save out GROMACS files:

```
new_pmd = unique_atom_types(pmd_complex_struct)

# Export the Structure to Gromacs files
new_pmd.save('new_complex.gro', overwrite=True)
new_pmd.save('new_complex.top', overwrite=True)
```

Here is an example of what we had before:

```
[ atomtypes ]
; name    at.num    mass    charge ptype  sigma      epsilon
N1             7  14.006720  0.00000000  A     0.32499985        0.71128
C1             6  12.010780  0.00000000  A     0.33996695      0.4577296
C2             6  12.010780  0.00000000  A     0.33996695       0.359824
O1             8  15.999430  0.00000000  A     0.29599219        0.87864
O2             8  15.999430  0.00000000  A     0.30664734      0.8803136
H1             1   1.007947  0.00000000  A      0.2471353      0.0656888
H2             1   1.007947  0.00000000  A     0.25105526        0.06276
H3             1   1.007947  0.00000000  A     0.25996425        0.06276
H4             1   1.007947  0.00000000  A     0.26495328      0.0656888
H5             1   1.007947  0.00000000  A     0.10690785      0.0656888
H6             1   1.007947  0.00000000  A     0.25996425        0.06276
H7             1   1.007947  0.00000000  A     0.25105526        0.06276
H8             1   1.007947  0.00000000  A     0.24214627        0.06276
S1            16  32.065500  0.00000000  A     0.35635949          1.046
O3             8  15.999430  0.00000000  A     0.31507524       0.635968
Na1           11  22.989769  0.00000000  A     0.24392807     0.36584603
Cl1           17  35.453200  0.00000000  A      0.4477657     0.14891274

```

And this is what we got after using this new function:
```
[ atomtypes ]
; name    at.num    mass    charge ptype  sigma      epsilon
N1             7  14.006720  0.00000000  A     0.32499985        0.71128
C1             6  12.010780  0.00000000  A     0.33996695      0.4577296
C2             6  12.010780  0.00000000  A     0.33996695       0.359824
O1             8  15.999430  0.00000000  A     0.29599219        0.87864
O2             8  15.999430  0.00000000  A     0.30664734      0.8803136
H1             1   1.007947  0.00000000  A     0.10690785      0.0656888
H2             1   1.007947  0.00000000  A     0.19599772      0.0656888
H3             1   1.007947  0.00000000  A      0.2471353      0.0656888
H4             1   1.007947  0.00000000  A              1              0
H5             1   1.007947  0.00000000  A     0.26495328      0.0656888
H6             1   1.007947  0.00000000  A     0.25996425        0.06276
H7             1   1.007947  0.00000000  A     0.25105526        0.06276
H8             1   1.007947  0.00000000  A     0.24214627        0.06276
S1            16  32.065500  0.00000000  A     0.35635949          1.046
OW             8  15.999430  0.00000000  A     0.31507524       0.635968
HW             1   1.007947  0.00000000  A              1              0
Na1           11  22.989769  0.00000000  A     0.24392807     0.36584603
Cl1           17  35.453200  0.00000000  A      0.4477657     0.14891274
L2140          6  12.010780  0.00000000  A     0.33996695      0.4577296
L2141          6  12.010780  0.00000000  A     0.33996695       0.359824
L2142          6  12.010780  0.00000000  A     0.33996695       0.359824
L2143          6  12.010780  0.00000000  A     0.33996695       0.359824
L2144          6  12.010780  0.00000000  A     0.33996695       0.359824
L2145          6  12.010780  0.00000000  A     0.33996695       0.359824
L2146          6  12.010780  0.00000000  A     0.33996695       0.359824
L2147          6  12.010780  0.00000000  A     0.33996695       0.359824
L2148          6  12.010780  0.00000000  A     0.33996695       0.359824
L2149          6  12.010780  0.00000000  A     0.33996695      0.4577296
L2150          6  12.010780  0.00000000  A     0.33996695       0.359824
L2151          7  14.006720  0.00000000  A     0.32499985        0.71128
L2152          7  14.006720  0.00000000  A     0.32499985        0.71128
L2153          8  15.999430  0.00000000  A     0.29599219        0.87864
L2154          6  12.010780  0.00000000  A     0.33996695       0.359824
L2155          6  12.010780  0.00000000  A     0.33996695       0.359824
L2156          6  12.010780  0.00000000  A     0.33996695       0.359824
L2157          6  12.010780  0.00000000  A     0.33996695       0.359824
L2158          6  12.010780  0.00000000  A     0.33996695       0.359824
L2159          6  12.010780  0.00000000  A     0.33996695       0.359824
L2160          6  12.010780  0.00000000  A     0.33996695       0.359824
L2161          8  15.999430  0.00000000  A     0.29599219        0.87864
L2162          7  14.006720  0.00000000  A     0.32499985        0.71128
L2163          6  12.010780  0.00000000  A     0.33996695      0.4577296
L2164          6  12.010780  0.00000000  A     0.33996695      0.4577296
L2165          1   1.007947  0.00000000  A      0.2471353      0.0656888
L2166          1   1.007947  0.00000000  A      0.2471353      0.0656888
L2167          1   1.007947  0.00000000  A     0.25105526        0.06276
L2168          1   1.007947  0.00000000  A     0.25996425        0.06276
L2169          1   1.007947  0.00000000  A     0.25105526        0.06276
L2170          1   1.007947  0.00000000  A     0.25996425        0.06276
L2171          1   1.007947  0.00000000  A     0.26495328      0.0656888
L2172          1   1.007947  0.00000000  A     0.26495328      0.0656888
L2173          1   1.007947  0.00000000  A     0.26495328      0.0656888
L2174          1   1.007947  0.00000000  A     0.25996425        0.06276
L2175          1   1.007947  0.00000000  A     0.10690785      0.0656888
L2176          1   1.007947  0.00000000  A     0.25996425        0.06276
L2177          1   1.007947  0.00000000  A     0.25996425        0.06276
L2178          1   1.007947  0.00000000  A     0.25996425        0.06276
L2179          1   1.007947  0.00000000  A     0.25996425        0.06276
L2180          1   1.007947  0.00000000  A      0.2471353      0.0656888
L2181          1   1.007947  0.00000000  A      0.2471353      0.0656888
L2182          1   1.007947  0.00000000  A      0.2471353      0.0656888
L2183          1   1.007947  0.00000000  A      0.2471353      0.0656888
L2184          1   1.007947  0.00000000  A      0.2471353      0.0656888
L2185          1   1.007947  0.00000000  A      0.2471353      0.0656888
```
We can see now the ligand/water/protein all have separate sets of atom names so that their parameters won't be jumbled by ParmEd. This is not the ultimate way to fix this issue. But it is working for now. 

@davidlmobley @mattwthompson @j-wags Please comment here if I missed anything from our discussion. Thanks!

**Comment by mattwthompson** [comment]
Great write-up @yunhuige!


We can kinda safeguard against this when ligands are parametrized with OpenFF by making funky atom names (https://github.com/openforcefield/openff-toolkit/pull/1096, likely in the next toolkit release) to avoid clashes with the "element plus small integer" naming logic.  But this does seem to be squarely a ParmEd problem, likely affecting users past, present, and future.

Some logic like the function Gaetano wrote might be a useful safeguarding, though I might consider operating on the atom names on the structure directly and not in the middle of a roundtrip with OpenMM. In any case, it looks like `Structure.__iadd__` would be a place to add it; I don't think these clashes occur except for adding structures together. Sorry I don't really have the time to commit to fixing this; hopefully somebody else can carry the torch.

**Comment by swails** [comment]
I’ll take a look at this.

**Comment by swails** [comment]
I think this is related to #1045 - in particular the `+` operator seems to miss clashes which should be better detected.

**Comment by mattwthompson** [comment]
Here is a somewhat minimal reproduction, although I think you already have enough to work off of.

In:
```python3
import os

from openff.toolkit.topology import Molecule
from openff.toolkit.typing.engines.smirnoff import ForceField
from parmed import Structure
from parmed.openmm import load_topology

thf = Molecule.from_smiles("C1CCOC1")
ace = Molecule.from_smiles("CC(=O)O")

thf.generate_conformers(n_conformers=1)
ace.generate_conformers(n_conformers=1)


def make_structure(molecule: Molecule) -> Structure:

    sage = ForceField("openff_unconstrained-2.0.0.offxml")

    molecule.generate_conformers(n_conformers=1)
    topology = molecule.to_topology()
    system = sage.create_openmm_system(topology)
    return load_topology(topology.to_openmm(), system, molecule.conformers[0])


thf_structure = make_structure(thf)
ace_structure = make_structure(ace)

complex_structure = thf_structure + ace_structure

thf_structure.save("thf_parmed.top", overwrite=True)
ace_structure.save("ace_parmed.top", overwrite=True)
complex_structure.save("add_parmed.top", overwrite=True)

os.system("grep -r '^O1' thf_parmed.top")
os.system("grep -r '^O1' ace_parmed.top")
os.system("grep -r '^O1' add_parmed.top")
```

Out:
```shell
$ python ligand_combination2.py
Warning: Unable to load toolkit 'OpenEye Toolkit'. The Open Force Field Toolkit does not require the OpenEye Toolkits, and can use RDKit/AmberTools instead. However, if you have a valid license for the OpenEye Toolkits, consider installing them for faster performance and additional file format support: https://docs.eyesopen.com/toolkits/python/quickstart-python/linuxosx.html OpenEye offers free Toolkit licenses for academics: https://www.eyesopen.com/academic-licensing
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
thf_parmed.top:O1             8  15.999430  0.00000000  A     0.30251065     0.70485815
ace_parmed.top:O1             8  15.999430  0.00000000  A     0.30398122     0.87950233
add_parmed.top:O1             8  15.999430  0.00000000  A     0.30398122     0.87950233
```

The OpenFF bits could be replaced with other things, but the important detail is that `load_topology` since ParmEd has to assign atom type strings on the fly; it's probably easy to reproduce with input files but not as easy to do accidentally.

**Comment by swails** [comment]
Fix posted in #1199 with unit test (I verified that the test actually failed with the expected bug without the fix).

**Comment by swails** [comment]
@mattwthompson with the latest version of `master`, this is what I get:

```
$ python test.py 
Warning: Unable to load toolkit 'OpenEye Toolkit'. The Open Force Field Toolkit does not require the OpenEye Toolkits, and can use RDKit/AmberTools instead. However, if you have a valid license for the OpenEye Toolkits, consider installing them for faster performance and additional file format support: https://docs.eyesopen.com/toolkits/python/quickstart-python/linuxosx.html OpenEye offers free Toolkit licenses for academics: https://www.eyesopen.com/academic-licensing
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
O1             8  15.999430  0.00000000  A     0.30251065     0.70485815
O1             8  15.999430  0.00000000  A     0.30398122     0.87950233
O1             8  15.999430  0.00000000  A     0.30251065     0.70485815
O1D            8  15.999430  0.00000000  A     0.30398122     0.87950233
```

As you can see, `O1` from the second molecule is renamed to `O1D`, after which the parameters remain the same.  I turned this exact example into a test case in #1199.

**Comment by mattwthompson** [comment]
The patch looks good - no surprising in reproducing your results:


```python3
In [1]: run ligand_combination2.py
Warning: Unable to load toolkit 'OpenEye Toolkit'. The Open Force Field Toolkit does not require the OpenEye Toolkits, and can use RDKit/AmberTools instead. However, if you have a valid license for the OpenEye Toolkits, consider installing them for faster performance and additional file format support: https://docs.eyesopen.com/toolkits/python/quickstart-python/linuxosx.html OpenEye offers free Toolkit licenses for academics: https://www.eyesopen.com/academic-licensing
thf_parmed.top:O1             8  15.999430  0.00000000  A     0.30251065     0.70485815
ace_parmed.top:O1             8  15.999430  0.00000000  A     0.30398122     0.87950233
add_parmed.top:O1             8  15.999430  0.00000000  A     0.30251065     0.70485815
add_parmed.top:O1D            8  15.999430  0.00000000  A     0.30398122     0.87950233

```

`ligand_combination2.py` is probably what I copy-pasted three comments earlier.

I notice the solution is implemented at writing the GROMACS files, whereas the structure is not fixed per se before hand:

```python3
In [2]: [a.epsilon for a in complex_structure.atoms if a.name.startswith("O1")]
Out[2]: [0.1684651402602, 0.2102061007896]

In [3]: [a.epsilon for a in complex_structure.atoms if a.name == "O1"]
Out[3]: [0.1684651402602, 0.2102061007896]

In [4]: [a.epsilon for a in complex_structure.atoms if a.name == "O1D"]
Out[4]: []
```

Wouldn't this cause issues with other formats? I would think that this fix needs to be applied to each writer that could encounter this clash?

**Comment by swails** [comment]
The solution is put in the `__iadd__` implementation of `Structure`.  On second thought a better place to put it might be in the `from_structure()` methods of the file classes that require distinct atom type names (like GROMACS topology files).

Only the GROMACS and CHARMM writers require distinct atom types, but CHARMM is much more strict (requiring distinct atom types for all parameters, not just atomic parameters).  That said, I don't think the CHARMM writers are used much if at all, so until someone complains about that functionality not working I'm going to leave it as is (note that it'll throw an exception rather than silently write incorrect parameters).

**Comment by mattwthompson** [comment]
I was more worried about Amber, since the atom types are stored at the top in a way that looks similar to GROMACS -  but now I see/recall that the actual parameters are expanded out (one per particle, not one per atom type).

Could you point me to where the relevant `+=` happens? I can definitely see that it works, but I can't quite grok how everything flows through the different classes - probably somewhere in `.write()`?

This confuses me - since it works on write but the object does not look right:

```
In [22]: top = pmd.gromacs.GromacsTopologyFile.from_structure(complex_structure)

In [23]: {a.sigma for a in top.atoms if a.name == "O1"}  # bad!
Out[23]: {3.0251064904353124, 3.039812205065809}

In [25]: top.save('blah.top')

In [26]: os.system("grep -r '^O1' blah.top")  # not bad?
blah.top:O1             8  15.999430  0.00000000  A     0.30251065     0.70485815
blah.top:O1D            8  15.999430  0.00000000  A     0.30398122     0.87950233
Out[26]: 0

**Comment by swails** [comment]
Here is where the deduplication happens currently: https://github.com/ParmEd/ParmEd/blob/master/parmed/structure.py#L3338

Also note that I never changed the atom *name*, just the type.  So `In [23]` should check for `a.type == "O1"`, which should only hit 1 line.  There are probably two atoms named `O1`, but one has atom type `O1` and the other `O1D`.

**Comment by mattwthompson** [comment]
Ah, that all makes sense. I was assumed that `.name` was some unique reference to the type, but if it's only used as a shorthand (and the writers follow the actual atom types) then I'm no longer confused. Thanks!

**Comment by swails** [comment]
It's not related to types at all, actually.  The type is a utility used during parametrization, while the name has more of an informatics origin (the alpha-carbon of every amino acid is given the conventional name "CA").

What caused the original problem here is that OpenMM forces just have parameters, so I have to "make up" atom types (and names if they're not provided by the topology).  Amber doesn't care about the actual atom type strings except in tleap (when it assigns parameters to a system) -- in the topology file the types are for all practical purposes ignored (atom mask selections can be done based on type, but few people do that).

GROMACS does care, but only about atom types (because other parameters can be overridden in-line), and OpenMM obviously doesn't care so long as you define the parameters correctly.
