### ISSUE TITLE
The attribute of the name of the molecule

### ISSUE THREAD

**Issue by xiki-tempula** [ParmEd/ParmEd#1198]
Say If I read a Gromacs topology with

```
[ moleculetype ]
; Name            nrexcl
UNL 3
```

I wonder how can I find the name of the molecule `UNL`? `top.name` will not yield this information.

**Comment by xiki-tempula** [comment]
It is `top.parm_data['TITLE']`

**Comment by swails** [comment]
`parm_data` is only for Amber topology files.

What is the script you're trying to run?

**Comment by xiki-tempula** [comment]
@swails 
I'm trying to read in amber or gromacs topology file
then change the name of the molecule
and write out amber or gromacs topology file.

In the case of the Gromacs,
I would expect that I read in a molecule

```
[ moleculetype ]
; Name            nrexcl
UNL 3
```
change the name to Lig
and it will write out 
```
[ moleculetype ]
; Name            nrexcl
Lig 3
```
I wonder how should I do it? Thank you.

**Comment by swails** [comment]
If it is a single residue molecule, change the name of the residue:

```python
top.residues[0].name = "Lig"
```

This of course assumes that the 1st residue is the one you want named `Lig`.  If it is a multi-residue molecule, then ParmEd will always name it `systemX`, where X is a simple counter.

**Comment by swails** [comment]
I'm going to close.  Feel free to open a new issue if there are unresolved questions.

**Comment by xiki-tempula** [comment]
Thanks for the explanation this fixes my issue but might be helpful if one could rename the molecule via a simple command like `top.molecules[0].name = "Lig"`
