### ISSUE TITLE
OpenMM -> `Structure`

### ISSUE THREAD

**Issue by swails** [ParmEd/ParmEd#120]
The idea is to be able to load a ParmEd `Structure` from an OpenMM `Topology` object and optionally a `System` instance or XML file.  The `Topology` is enough to set up the atoms, residues, and bonds; the latter will also permit establishing adding parameters.

**Comment by cxhernandez** [comment]
+1 

It would be great to have a way to bypass a StateReporter and just save the topology to a `prmtop` file.

**Comment by swails** [comment]
Added by #170.  Turned out to not be quite as tricky as I anticipated (although a lot of the additions in the Gromacs support helped here)

**Comment by swails** [comment]
Done in #170
