### ISSUE TITLE
Selecting part of the system from the OpenMM and recreating its part later on

### ISSUE THREAD

**Issue by DanielWicz** [ParmEd/ParmEd#1218]
I want from an already created system in OpenMM (e.g. a protein in a water box with ions) extract single selection (e.g. protein) and then recreate the system to the OpenMM object.

So far I did fallowing: 

```
from simtk.openmm.app import *
from simtk.openmm import *
from simtk.unit import *
from openmmtools.testsystems import SrcExplicit
from sys import stdout
import mdtraj as md
import numpy as np
import parmed as prm

testsystem = SrcExplicit()
positions = testsystem.positions
topology = testsystem.topology
system = testsystem.system

# here I  convert from OpenMM to the Parmed Struct's object
struct = prm.openmm.load_topology(topology, system)
# At the moment I don't know how to make a selection at the moment, so I make a split
splitted = struct.split()
protein = splitted[0][0] # the 0 is a protein
print(protein)
>>> <Structure 4427 atoms; 276 residues; 4481 bonds; PBC (orthogonal); parametrized>
# here I create a new system from struct
psystem = prot.createSystem(nonbondedMethod=CutoffPeriodic, nonbondedCutoff=1.2*prm.unit.nanometers)

>>>---------------------------------------------------------------------------
ParameterError                            Traceback (most recent call last)
<ipython-input-53-4fae6142dedc> in <module>()
----> 1 psystem = prot.createSystem(nonbondedMethod=CutoffPeriodic, nonbondedCutoff=1.2*chem.unit.nanometers)

/home/daniel/miniconda3/envs/openmmenv/lib/python3.7/site-packages/parmed/utils/decorators.py in new_fcn(*args, **kwargs)
     20         if not HAS_OPENMM:
     21             raise ImportError('Could not find or import OpenMM')
---> 22         return fcn(*args, **kwargs)
     23 
     24     return new_fcn

~/miniconda3/envs/openmmenv/lib/python3.7/site-packages/parmed/structure.py in createSystem(self, nonbondedMethod, nonbondedCutoff, switchDistance, constraints, rigidWater, implicitSolvent, implicitSolventKappa, implicitSolventSaltConc, temperature, soluteDielectric, solventDielectric, useSASA, removeCMMotion, hydrogenMass, ewaldErrorTolerance, flexibleConstraints, verbose, splitDihedrals)
   2029         LOGGER.info('Adding bonds...')
   2030         self._add_force_to_system(system,
-> 2031                 self.omm_bond_force(constraints, rigidWater, flexibleConstraints)
   2032         )
   2033         LOGGER.info('Adding angles...')

~/miniconda3/envs/openmmenv/lib/python3.7/site-packages/parmed/utils/decorators.py in new_fcn(*args, **kwargs)
     20         if not HAS_OPENMM:
     21             raise ImportError('Could not find or import OpenMM')
---> 22         return fcn(*args, **kwargs)
     23 
     24     return new_fcn

~/miniconda3/envs/openmmenv/lib/python3.7/site-packages/parmed/structure.py in omm_bond_force(self, constraints, rigidWater, flexibleConstraints)
   2259                 continue
   2260             if bond.type is None:
-> 2261                 raise ParameterError('Cannot find necessary parameters')
   2262             force.addBond(bond.atom1.idx, bond.atom2.idx, bond.type.req*length_conv,
   2263                           2*bond.type.k*frc_conv)

ParameterError: Cannot find necessary parameters

```

The problem is fallowing, I get the fallowing error: `ParameterError: Cannot find necessary parameters`, and I can't solve it further. 

Software version:
OpenMM: 7.7
Parmed: 3.4.3
Python: 3.7.12

**Comment by swails** [comment]
Systems are subscriptable, and subscripts can be indices (which return atoms), slices (which returns structures), or strings that are interpreted as the Amber mask syntax, so you can do something like this:

```python
structure[:100, :]  # selects the first 100 residues and all atoms in each of those residues
structure[":1-100"]  # selects the Amber mask selection (residues 1 to 100)
structure[":ALA"]  # selects all alanine residues
structure[:1000]  # Selects the first 1000 atoms
```

I suspect what's happening here is that the original OpenMM system was created with constraints, so there are no bond parameters between the constrained atoms in the generated system.  As a result, when it tries to create the bond force it fails to find some parameters and fails like this.

If you plan to use the same constraints, you can add a dummy bond type to each of the bonds whose type is `None`:

```python
new_structure = structure[...]  # specify your selection criteria

new_bond_type = BondType(k=400, req=1.0)
constrained_bond_type = new_structure.bond_types.append(new_bond_type)
new_structure.bond_types.claim()

for bond in new_structure.bonds:
    if bond.type is None:
        bond.type = new_bond_type
```

This should allow the system constructor to finish.

**Comment by DanielWicz** [comment]
@swails 
Thanks a lot ! Indeed the system is with some constraints !
>If you plan to use the same constraints, you can add a dummy bond type to each of the bonds whose type is None:

If I define them as you provided, the new system also is going to be constrained ? If so, how do I know which values of k and req do I use in `BondType(k=400, req=1.0)` ?

**Comment by swails** [comment]
When you created the system in the first place, you must have passed `constraints=[app.HBonds | app.HAngles | app.AllBonds]` to create the system with some constrained degrees of freedom.  As long as you pass the same value for the constraints argument to create the *new* system, then any bonds that were constrained in the original system will also be constrained in the new one.

This is the key assumption here.  As long as that bond is constrained, *the actual bond parameters don't matter*.  k=400 and req=1.0 were chosen to be somewhat typical of bonds-including-hydrogen, but they're really arbitrary choices.

Alternatively, if you go back and create the *original* system by passing `constraints=None` into the `createSystem` call, then no parameters will be missing and you won't run into this issue in the first place.  That's what I would actually recommend doing, I just didn't want to assume you could remake the original system when suggesting a solution.

**Comment by DanielWicz** [comment]
@swails 
Thanks for a quick answer, works perfectly well!

One last question: Can I pass indices (e.g. obtained from MDtraj) to make a selection ? Because Amber mask is quite difficult to use in comparison to MDTraj/VMD selection syntax.

**Comment by swails** [comment]
Yes, that works.  Here is the docstring for `Structure.__getitem__`:

```
    def __getitem__(self, selection):
        """
        Allows extracting a single atom from the structure or a slice of atoms
        as a new Structure instance. The following syntaxes are allowed:
            - struct[str] : str is interpreted as an Amber selection mask
            - struct[[sel,[sel,]],sel] : sel can be a list of indices (or
                            strings for chain selection) an integer, or a slice
        Parameters
        ----------
        selection : str, or slice|iter|str, slice|iter|int, slice|iter|int
            Which atoms to select for the new structure
```
