### ISSUE TITLE
parm slicing is very slow

### ISSUE THREAD

**Issue by swails** [ParmEd/ParmEd#122]
See timings that @hainm put in PR #121 

This is clearly unacceptable (although it would probably be 3-5x faster just running it in PyPy instead).

**Comment by swails** [comment]
Addressed as much as I plan to in 8ff15de85312665622eb4da97cf51a22c9af66fd. Note that this 

Using the `dhfr_cmap_pbc.parm7` chamber topology as a test (56K atoms) as well as a 12264-atom system (to compare with @hainm's timings):

Before:
```Python
In [7]: ll
Out[7]: <AmberParm 12264 atoms; 3385 residues; 12275 bonds; PBC; parametrized>

In [8]: %time ll['@CA']
CPU times: user 2.83 s, sys: 190 ms, total: 3.02 s
Wall time: 2.82 s
Out[8]: <AmberParm 162 atoms; 162 residues; 0 bonds; NOT parametrized>

In [9]: l
Out[9]: <ChamberParm 56057 atoms; 18015 residues; 56091 bonds; PBC; parametrized>

In [10]: %time l['@CA']
CPU times: user 11.2 s, sys: 190 ms, total: 11.4 s
Wall time: 11.2 s
Out[10]: <ChamberParm 159 atoms; 159 residues; 0 bonds; NOT parametrized>
```

After:
```Python
In [15]: ll
Out[15]: <AmberParm 12264 atoms; 3385 residues; 12275 bonds; PBC; parametrized>

In [16]: %timeit ll['@CA']
1 loops, best of 3: 309 ms per loop

In [20]: l
Out[20]: <ChamberParm 56057 atoms; 18015 residues; 56091 bonds; PBC; parametrized>

In [21]: %time l['@CA']
CPU times: user 1.17 s, sys: 80 ms, total: 1.25 s
Wall time: 1.15 s
Out[21]: <ChamberParm 159 atoms; 159 residues; 0 bonds; NOT parametrized>
```

**Comment by swails** [comment]
The old algorithm was O(N^2), by virtue of having to do a full copy of the structure, followed by a strip of the atoms we didn't want in the resulting structure.  The new algorithm is O(N), since it loops through the atoms and valence terms each once, adding the ones we want to keep into a new container.

**Comment by hainm** [comment]
nice job. ~10 times faster.

ever wanna try 2 millions atoms in $AMBERHOME/test/2_million_atom/prmtop.gz :D 

It took 40 seconds for `cpptraj` (through `pytraj`) to read.

**Comment by swails** [comment]
Actually I think both implementations are O(N), but the old one has a much larger prefactor.

Anyway, this is as good as slicing is going to get in pure Python, I suspect.  If/when certain performance bottlenecks become a problem and the algorithm can't be easily changed to achieve necessary speedup, I may turn to Cython.
