### ISSUE TITLE
Add new PBRadii sets

### ISSUE THREAD

**Issue by Valdes-Tresanco-MS** [ParmEd/ParmEd#1223]
Hi Jason. In our project, we have reviewed some recent studies where they propose a new set of PBRadii for GAFF and CHARMM. The new PBRadii sets would not overlap with the existing ones, but we would add them as new and with a different name. The purpose of this is that ParmEd has these options in the official repository and that we can use them with [gmx_MMPBSA](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA). 
We have seen that for CHARMM ff the same values are used as for Amber, which as mentioned in some mailing list threads, has not been extensively tested. We are implementing these features to do some further studies. So far, the results we get are consistent.

I can do a PR if you agree.

Papers:
- https://pubs.acs.org/doi/10.1021/jp970736r
- https://pubs.acs.org/doi/abs/10.1021/jp025852v
- https://pubs.acs.org/doi/10.1021/acs.jcim.1c00177
- https://pubs.acs.org/doi/full/10.1021/acs.jctc.9b00106

Sincerely
Mario S.

**Comment by swails** [comment]
Sure, I'd be happy to accept a PR with new PB radii!
