### ISSUE TITLE
Post talk slides

### ISSUE THREAD

**Issue by kyleabeauchamp** [ParmEd/ParmEd#123]
John and were talking about how your talk slides had a lot of good "big picture" commentary that was unavailable in the online documentation.  It might be useful to post those slides online and link to them in the README or the docs

**Comment by swails** [comment]
Sure.  Something like what you did for MSMBuilder? (e.g., http://rawgit.com/kyleabeauchamp/MSMBuilderTalk/master/index.html)

I'm also all for doc improvements, if anyone wants to make suggestions (or PRs) related to that

**Comment by kyleabeauchamp** [comment]
I'd be happy with even just dumping the keynote slides somewhere and adding a link--no need for you to go through reformatting.  Then we can clean up the actual docs in the future

**Comment by swails** [comment]
I can do that.  I liked your slide deck in MSMBuilder, so if I find it easy to do that I will. Otherwise I'll just dump a PDF version of the Keynote slides to the website and add a link.
