### ISSUE TITLE
differences between tleap and parmed when assigning ATOM_TYPE_INDEX

### ISSUE THREAD

**Issue by marioernestovaldes** [ParmEd/ParmEd#1231]
Hello there! 

we (@Valdes-Tresanco-MS and myself) have been working lately with _parmed_ and _tleap_ and we have noticed an unexpected difference between **ATOM_TYPE_INDEX** asignation between the two. This difference ultimately conducts to dramatic differences in single-point calculations (mostly because of huge differences in VDWAALS energies). We set up a simple test system to try this out. It is a simple peptide with the following sequence (Gly-Cys-Gly-Cys-Gly) with a disulfide bridge between the two cysteines. 

According to this [file](https://ambermd.org/prmtop.pdf), the **ATOM TYPE INDEX** section contains the Lennard-Jones atom type index. To minimize the memory requirements, all atoms with the same σ and ε parameters are assigned to the same type (regardless of whether they have the same AMBER ATOM TYPE). This significantly reduces the number of LJ coefficients that must be stored. Turns out that _tleap_ follows these rules, but it seems _ParmEd_ assigns **ATOM TYPE INDEX** for all different AMBER ATOM TYPE, regarding they have the same σ and ε parameters or not. For this system, we should expect 8 different **ATOM TYPE INDEX**, however, with parmed we get 11 different types (1 for every AMBER ATOM TYPE in the topology):

```
[ atomtypes ]
; name	at.num	mass	charge	ptype	sigma	epsilon	;	sigma_14	epsilon_14
       H     1     1.0080      0.164     A    1.06907846177e-01    6.568880e-02 
      H1     1     1.0080      0.077     A    2.47135304412e-01    6.568880e-02 
      HP     1     1.0080      0.089     A    1.95997717991e-01    6.568880e-02 
      2C     6    12.0100     -0.079     A    3.39966950842e-01    4.577296e-01 # same σ and ε as CX
       C     6    12.0100      0.616     A    3.39966950842e-01    3.598240e-01 
      CX     6    12.0100     -0.010     A    3.39966950842e-01    4.577296e-01 # same σ and ε as 2C
       N     7    14.0100     -0.416     A    3.24999852378e-01    7.112800e-01 # same σ and ε as N3
      N3     7    14.0100      0.294     A    3.24999852378e-01    7.112800e-01 # same σ and ε as N
       O     8    16.0000     -0.572     A    2.95992190115e-01    8.786400e-01 # same σ and ε as O2
      O2     8    16.0000     -0.785     A    2.95992190115e-01    8.786400e-01 # same σ and ε as O
       S    16    32.0600     -0.108     A    3.56359487256e-01    1.046000e+00 


N3, N:	1
H:	2
CX, 2C:	3
HP:	4
C:	5
O, O2:	6
H1:	7
S:	8
```

I'll walk through what we did for testing...

**Parmed**
Firstly, we prepared the GROMACS topology for this peptide with Amber ff14SB in CHARMM-GUI. Next, we used parmed to convert the GROMACS topology to AMBER's. 

```
from parmed import gromacs, amber, unit as u
from parmed.tools.changeradii import ChRad

gmx_top = gromacs.GromacsTopologyFile('/home/mario/Documents/test_1.5.0/gmx_MMPBSA_test/docs/examples/test/charmm-gui_SS/gromacs/parmed/topol.top')
gmx_gro = gromacs.GromacsGroFile.parse('/home/mario/Documents/test_1.5.0/gmx_MMPBSA_test/docs/examples/test/charmm-gui_SS/gromacs/parmed/step3_input.gro')
gmx_top.box = gmx_gro.box # Needed because .prmtop contains box info
gmx_top.positions = gmx_gro.positions
amb_prm = amber.AmberParm.from_structure(gmx_top)
ChRad(amb_prm, 'mbondi')
amb_prm.box = None
amb_prm.write_parm("/home/mario/Documents/test_1.5.0/gmx_MMPBSA_test/docs/examples/test/charmm-gui_SS/gromacs/parmed/parmed_SS.prmtop")
amb_inpcrd = amber.AmberAsciiRestart("/home/mario/Documents/test_1.5.0/gmx_MMPBSA_test/docs/examples/test/charmm-gui_SS/gromacs/parmed/parmed_SS.inpcrd", mode="w")
amb_inpcrd.coordinates = gmx_top.coordinates
# amb_inpcrd.box = gmx_top.box
amb_inpcrd.close()
```

Once we got the _parmed_SS.prmtop_ and _parmed_SS.inpcrd_ we conducted a single-point energy calculation with _pbsa_ in amber:

```
pbsa -O -i pbsa.mdin -p parmed_SS.prmtop -c parmed_SS.inpcrd -o out.mdout

#pbsa.mdin

Sample single point PB calculation
&cntrl
/
&pb
npbverb=1, istrng=150, fillratio=1.5, radiopt=0,
/
```

This is the mdout:
```
 NSTEP =        1   TIME(PS) =       0.000  TEMP(K) =     0.00  PRESS =     0.0
 Etot   =      -520.9855  EKtot   =         0.0000  EPtot      =         0.0000
 BOND   =         0.0000  ANGLE   =         0.0000  DIHED      =         0.0000
 1-4 NB =         0.0000  1-4 EEL =         0.0000  VDWAALS    =        -5.4725
 EELEC  =      -355.1433  EPB     =      -157.8180  RESTRAINT  =         0.0000
 ECAVITY=        37.8970  EDISPER =       -40.4487
```

**tleap**
We also prepared the AMBER's topology with _tleap_ using the same input structure we used with parmed: 

```
# tleap.in

source leaprc.protein.ff14SB
p = loadpdb step3_input.pdb
saveamberparm p tleap_SS.prmtop tleap_SS.inpcrd
quit
```

Once we got the _tleap_SS.prmtop_ and _tleap_SS.inpcrd_ we conducted a single-point energy calculation with _pbsa_ in amber:

```
pbsa -O -i pbsa.mdin -p tleap_SS.prmtop -c tleap_SS.inpcrd -o out.mdout

#pbsa.mdin

Sample single point PB calculation
&cntrl
/
&pb
npbverb=1, istrng=150, fillratio=1.5, radiopt=0,
/
```

This is the mdout:
```
 NSTEP =        1   TIME(PS) =       0.000  TEMP(K) =     0.00  PRESS =     0.0
 Etot   =      -117.7055  EKtot   =         0.0000  EPtot      =         0.0000
 BOND   =         0.0000  ANGLE   =         0.0000  DIHED      =         0.0000
 1-4 NB =         0.0000  1-4 EEL =         0.0000  VDWAALS    =       398.4173
 EELEC  =      -355.7395  EPB     =      -157.7674  RESTRAINT  =         0.0000
 ECAVITY=        37.8687  EDISPER =       -40.4846
```

As you can see the VDWAALS energies are quite different...

All files are attached in two different folders, i.e. _parmed_ and _tleap_

[test_system.zip](https://github.com/ParmEd/ParmEd/files/8091523/test_system.zip)

**Comment by swails** [comment]
You're expecting too much of tleap 😃 .  Note that without an explicit bond command _or_ `CONECT` records in the PDB dictating that the CYX residues be bonded at the sulfurs, tleap will _not_ actually put a bond there.

You can see that the tleap prmtop is missing a bond relative to the version from GROMACS:

```python
In [1]: import parmed as pmd

In [2]: from_gmx = pmd.load_file("parmed/parmed_SS.prmtop", xyz="parmed/parmed_SS.inpcrd")

In [3]: from_tleap = pmd.load_file("tleap/tleap_SS.prmtop", xyz="tleap/tleap_SS.inpcrd")

In [4]: len(from_tleap.bonds)
Out[4]: 43

In [5]: len(from_gmx.bonds)
Out[5]: 44
```

This alone is enough to explain the Lennard-Jones energy discrepancy, since the absence of the S-S bond in the tleap-generated system means that many interactions that are excluded in the GROMACS calculation.

What doesn't make sense to me are the other energy terms - most notably the bonded terms being 0 and the electrostatic energy not changing (since those should be impacted the same way that the Lennard-Jones terms are).  I'd recommend using `sander` instead of `pbsa` to compare energies.  You can do this with ParmEd easily:

```python
In [1]: import parmed as pmd

In [2]: from_gmx = pmd.load_file("parmed/parmed_SS.prmtop", xyz="parmed/parmed_SS.inpcrd")

In [3]: from_tleap = pmd.load_file("tleap/tleap_SS.prmtop", xyz="tleap/tleap_SS.inpcrd")

In [4]: pmd.tools.energy(from_gmx, igb=6).execute()
Bond     =            5.6648595     Angle    =            7.6394632
Dihedral =           46.4013363     1-4 vdW  =            8.9703939
1-4 Elec =          295.8134003     vdWaals  =           -5.4725154
Elec.    =         -355.1433177     Egb      =            0.0000000
TOTAL    =            3.8736200

In [5]: pmd.tools.energy(from_tleap, igb=6).execute()
Bond     =            3.1515814     Angle    =            5.5589504
Dihedral =           34.1167244     1-4 vdW  =            8.6902534
1-4 Elec =          299.4513686     vdWaals  =          398.4172653
Elec.    =         -355.7394722     Egb      =            0.0000000
TOTAL    =          393.6466713
```

Here you can see the bond, angle, torsion, and 1-4 terms are all quite different, even for electrostatics (and the values don't match what's coming out of PBSA, since those terms are likely ignored).  Note `igb=6` is a keyword for doing a gas-phase simulation.  While the eletrostatics are still unexpectedly similar between the two systems, the *actual* electrostatic difference (sum of Elec and 1-4 Elec) is larger.

To evaluate the effect of adding the bond, I changed your tleap.in file by adding a bond command:

```
source leaprc.protein.ff14SB
p = loadpdb step3_input.pdb
bond p.2.SG p.4.SG
saveamberparm p tleap_SS_bnd.prmtop tleap_SS_bnd.inpcrd
quit
```

You can see the difference:

```python
In [1]: import parmed as pmd

In [2]: from_gmx = pmd.load_file("parmed/parmed_SS.prmtop", xyz="parmed/parmed_SS.inpcrd")

In [3]: from_tleap = pmd.load_file("tleap/tleap_SS.prmtop", xyz="tleap/tleap_SS.inpcrd")

In [4]: from_tleap_bnd = pmd.load_file("tleap/tleap_SS_bnd.prmtop", xyz="tleap/tleap_SS_bnd.inpcrd")

In [5]: len(from_gmx.bonds)
Out[5]: 44

In [6]: len(from_tleap.bonds)
Out[6]: 43

In [7]: len(from_tleap_bnd.bonds)
Out[7]: 44

In [8]: pmd.tools.energy(from_gmx, igb=6).execute()
Bond     =            5.6648595     Angle    =            7.6394632
Dihedral =           46.4013363     1-4 vdW  =            8.9703939
1-4 Elec =          295.8134003     vdWaals  =           -5.4725154
Elec.    =         -355.1433177     Egb      =            0.0000000
TOTAL    =            3.8736200

In [9]: pmd.tools.energy(from_tleap_bnd, igb=6).execute()
Bond     =            5.4040251     Angle    =            7.6176378
Dihedral =           46.3922566     1-4 vdW  =            9.0392002
1-4 Elec =          295.8843956     vdWaals  =           -5.4515651
Elec.    =         -355.1279822     Egb      =            0.0000000
TOTAL    =            3.7579680
```

As you can see, once we add the S-S bond in tleap the energies are *much* closer (3.75 vs 3.87 kcal/mol).  The rest of this discrepancy can be explained by the difference in precision in the input coordinates.  Indeed, if you set the coordinates to be identical, the energy agreement is <0.0002 kcal/mol:

```python
In [1]: import parmed as pmd

In [2]: from_gmx = pmd.load_file("parmed/parmed_SS.prmtop", xyz="parmed/parmed_SS.inpcrd")

In [3]: from_tleap_bnd = pmd.load_file("tleap/tleap_SS_bnd.prmtop", xyz="parmed/parmed_SS.inpcrd")  # notice the incprd file is the same as above

In [4]: pmd.tools.energy(from_gmx, igb=6).execute()
Bond     =            5.6648595     Angle    =            7.6394632
Dihedral =           46.4013363     1-4 vdW  =            8.9703939
1-4 Elec =          295.8134003     vdWaals  =           -5.4725154
Elec.    =         -355.1433177     Egb      =            0.0000000
TOTAL    =            3.8736200

In [5]: pmd.tools.energy(from_tleap_bnd, igb=6).execute()
Bond     =            5.6648595     Angle    =            7.6395248
Dihedral =           46.4013459     1-4 vdW  =            8.9703939
1-4 Elec =          295.8135186     vdWaals  =           -5.4725154
Elec.    =         -355.1433177     Egb      =            0.0000000
TOTAL    =            3.8738096
```

This is within an acceptable range for me to be confident these are, in fact, equivalent representations (you'll be hard-pressed to do much better given the precision with which temporary files are written during these conversion processes).
