### ISSUE TITLE
Alpha angle is written to prmtop BOX_DIMENSIONS instead of beta

### ISSUE THREAD

**Issue by rosemary-cresset** [ParmEd/ParmEd#1238]
When converting from an OpenMM system to an AMBER prmtop file, I have found that the alpha angle of the periodic box is being written to the BOX_DIMENSIONS field instead of beta. This website specifies that the written angle will be beta: https://ambermd.org/FileFormats.php I used this field to set the box vectors for a simulation (though I now realise that using the box dimensions from the inpcrd is a better thing to do), and when using an octahedral box this caused an air gap to appear between the periodic copies. 

The octahedral box vectors I used in OpenMM were:
openmm.Vec3(1,0,0), openmm.Vec3(1/3,2*math.sqrt(2)/3,0), openmm.Vec3(-1/3,math.sqrt(2)/3,math.sqrt(6)/3)

**Comment by swails** [comment]
The way that Amber represents a truncated octahedron is different than how OpenMM does it (OpenMM requires so-called "reduced" vectors, while Amber has alpha/beta/gamma identical at ~109 degrees for a truncated octahedron).  So even if this was "corrected", I think you'd still have to use the inpcrd measurements to get the box vectors.

After all, you can't construct the box vectors correctly with 3 vector lengths and only one angle -- you need all 3 angles.  Amber has only supported orthorhombic and octahedral boxes where all 3 angles are identical (90 or ~109 degrees), so listing only a single angle is sufficient.

While I know that this is technically incorrect behavior relative to published format documentation, I don't think fixing it will actually resolve this issue, and the format spec explicitly says these values are ignored (indeed, Amber's MD engines return a fatal error if box information is not in the inpcrd, even if it's in the prmtop).

**Comment by rosemary-cresset** [comment]
Thanks for the explanation - I had misunderstood how this all worked. I will close this ticket.
