### ISSUE TITLE
Convert the openff small molecule topology to gromacs topology

### ISSUE THREAD

**Issue by xiki-tempula** [ParmEd/ParmEd#1246]
I wonder what is the current recommanded way of loading the openMM topology file?
I'm trying to convert the openMM topology to gromacs topplogy and it doesn't seems to work.
The system is a single ligand

```
top = pmd.load_file('lig.offxml')
top.save('lig.top')
```
[lig.offxml.zip](https://github.com/ParmEd/ParmEd/files/8444310/lig.offxml.zip)

**Comment by swails** [comment]
ParmEd doesn't support these files, so you'll need to convert this file to something that ParmEd *does* support (like an OpenMM `System` with OpenMM `Topology`).  I don't know the OpenFF toolkit well enough to know how to go from this file to an OpenMM System/Topology, but if you do that you can use `parmed.openmm.load_topology` to go the rest of the way.

HTH
