### ISSUE TITLE
Structure.copy() does not carry bond orders

### ISSUE THREAD

**Issue by sebastianmdick** [ParmEd/ParmEd#1255]
Copying a Structure causes all bond orders to be reset to 1.0.
This can be easily trace back to the lack of bond order specified in 
https://github.com/ParmEd/ParmEd/blob/b9f2955f792c03394686824519cabe030d5342b4/parmed/structure.py#L474-L479
so should be a straightforward fix.

**Comment by swails** [comment]
Thanks for the report.  The problem also exists in structure slicing, so I've fixed it in both places in #1256
