### ISSUE TITLE
ff19SB CMAP not supported when using tiMerge command. 

### ISSUE THREAD

**Issue by u5459577** [ParmEd/ParmEd#1264]
Reporting an issue where ff19SB's CMAP terms are not seeming to be read by parmed when applying the tiMerge command to remove redundant atoms from the system. Currently I have to resort to ff14SB to use tiMerge and run TI sims.

**Comment by swails** [comment]
Was the issue using an older ParmEd version?

As far as I knew the latest version of ParmEd does support cmaps in timerge.

**Comment by josiahbones** [comment]
I was using Parmed 3.4.3. I utilised the code modified here: https://github.com/ParmEd/ParmEd/issues/1169

This resolved my issue, but this code wasn't seemingly a part of my version.
