### ISSUE TITLE
update more examples

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#127]
hey man,

I've looked at example folder https://github.com/ParmEd/ParmEd/tree/master/examples and found only few. (and they are quite similar) 

It's great if you can update more various types of examples (may be from basic to advance?). Not just focus on how to use ParmEd to run things on `openmm` (which is great) but I think `ParmEd` can do much more than this (for me, I can use it for FF development; reading code is fun but examples are better to have overall view). thanks.

Hai

**Comment by swails** [comment]
Consider this an open invitation to anybody watching this repo to contribute examples.  No example will be better than one derived from real-world application.

**Comment by swails** [comment]
Same as #458

**Comment by swails** [comment]
Or close enough.
