### ISSUE TITLE
problem with nbfix and charmm

### ISSUE THREAD

**Issue by dacase** [ParmEd/ParmEd#1280]
Here is a communication from Alexander Sodt at NIH: alexander.sodt@nih.gov

>
> In _chamberparm.py (your line numbers won’t quite be mine):
>
> 578         if nbfixes is not None:
> 579             for i, fix in enumerate(nbfixes):
> 580                 for terms in fix:
> 581                     j, rmin, eps, rmin14, eps14 = terms
> 582                     i, j = min(i, j-1), max(i, j-1)
> 583                     eps = abs(eps)
> 584                     eps14 = abs(eps14)
> 585                     idx = data['NONBONDED_PARM_INDEX'][ntypes*i+j] - 1
>
> Line 582 in my version of the file appears to have incorrect code.
>
> Only when I make temp variables k and l:
>
> 586         if nbfixes is not None:
> 587             for i, fix in enumerate(nbfixes):
> 588                 for terms in fix:
> 589                     j, rmin, eps, rmin14, eps14 = terms
> 590                     #i, j = min(i, j-1), max(i, j-1)
> 591                     k, l = min(i, j-1), max(i, j-1)
> 592                     eps = abs(eps)
> 593                     eps14 = abs(eps14)
> 594                     idx = data['NONBONDED_PARM_INDEX'][ntypes*k+l] - 1
>
> do I get correct van der waals parameters with the CHARMM forcefield (related to nbfix).
>
> When i is swapped with j it doesn’t get swapped back for the next pass through the “for terms in fix” for loop --- and i might be set to the previous iteration’s j.
>
> In the unfixed code some values are off … and some of our simulations were subtly but (scientifically speaking) catastrophically incorrect. The effect of the bug will depend on the order of residues in the structure.

**Comment by swails** [comment]
Fixed in #1281 -- the bug report was very helpful.
