### ISSUE TITLE
should `parm` has `load_coords`  too? and load from coords from file too

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#129]
```python
parm = chem.load_file("./data/Tc5b.top")
parm.load_coordinates("myfile.rst7")

# what's about
parm.load_coords("myfile.rst7") #  more consistent with "parm.coords"
```

**Comment by swails** [comment]
There hasn't been much focus placed on coordinate access in ParmEd (pytraj and mdtraj are more appropriate for extracting coordinates).

In some cases I've tried establishing a standard across all of ParmEd.  For instance, the `positions` attribute in all cases returns a list of 3-element tuples with units attached.

I'd personally vote for `coordinates` as opposed to `coords` (or `xyz`, perhaps).  Does anybody else have a preference?

**Comment by mojyt** [comment]
On Sat, May 2, 2015 at 4:16 PM, Jason Swails <notifications@github.com>
wrote:

>
> I'd personally vote for coordinates as opposed to coords (or xyz,
> perhaps). Does anybody else have a preference?
>

All things considered, more descriptive names are usually better (in my
opinion at least).


> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ParmEd/ParmEd/issues/129#issuecomment-98408705>.
>



-- 
-------------------------
Daniel R. Roe, PhD
Department of Medicinal Chemistry
University of Utah
30 South 2000 East, Room 307
Salt Lake City, UT 84112-5820
http://home.chpc.utah.edu/~cheatham/
(801) 587-9652
(801) 585-6208 (Fax)

**Comment by hainm** [comment]
I agree with Dan about descriptive name. I am trying to make pytraj's method name similar to other packages too. It's easier to have common iterface. 

I get used to think about coors or coordinates as 1d array while xyz as 3d.

Anyway, methods and names are consistent is good too.

Hai

**Comment by hainm** [comment]
It's minor. I am closing it.

**Comment by swails** [comment]
Let's reopen this.  It's a useful enhancement and I don't want to forget about it.

**Comment by swails** [comment]
Assigning to `parm.coordinates` has this same effect.  And the `AmberParm` constructor takes `xyz` and `box` as potential arguments, where `xyz` can be any filename of any format that contains coordinates and/or unit cell info or a coordinate array. (It doesn't *just* have to be a restart file).  So this convenience is now added.
