### ISSUE TITLE
Splitting prmtop file yields 1 good file and 1 bad file - resulting NTYPES ptr don't match

### ISSUE THREAD

**Issue by pguillem** [ParmEd/ParmEd#1295]
Hello all,
I'm trying to split a complex PRMTOP generated from TLEAP, into **receptor.prmtop** and **ligand.prmtop**

According to the docs, this should do the trick:

```
import parmed as prm

file = prm.load_file("receptor-complex.prmtop")
a = file[":1-76"]
b = file[":77-323"]

a.write_parm("receptor.prmtop")
b.write_parm("ligand.prmtop")

```
When I try to load receptor.prmtop back into parmed it works perfectly. 
But when I try to load ligand.prmtop, the following message pops up: 

**parmed.exceptions.AmberError: FLAG LENNARD_JONES_ACOEF has 171 elements; expected 136**

Is the writer copying all existing NTYPES in the ligand file?, or just the ones present in the selection?. The complex and receptor files have 18 NTYPES and they pass the check, but according to parmed the resulting ligand file should have 16 and keeps having the original 18 NTYPES.

What is the proper way to split a prmtop file?

Thanks in advance for any hints!
Pedro

**Comment by pguillem** [comment]
I tried getting only the ligand part of the molecule.

Parmed is correctly calculating the new total NTYPES for the new file (16), but if any operation is called from the new object, its internal pointer still counts 18?. The strange thing is the ptr is counting 16. See below.

```
import parmed as pm

file = pm.load_file("receptor_ligand.prmtop")
b = file[":77-323"]

b.ptr("NTYPES")
16

b.load_structure()
Traceback (most recent call last):
    raise AmberError('FLAG %s has %d elements; expected %d' %
parmed.exceptions.AmberError: FLAG LENNARD_JONES_ACOEF has 171 elements; expected 136

```

**Comment by swails** [comment]
This is a known issue that is the result of trying to preserve NBFIXes when splitting Amber topologies.  I need to find a better way to record the off-diagonal modifications so they can be re-introduced.

I'll raise a PR with code you can use to fix the issue, just note that it'll also wipe out any off-diagonal pair interaction modifications that may have been made (this is an issue with CHARMM-converted force fields and some less commonly used Amber force fields like those in the ipolq family, I think).

**Comment by pguillem** [comment]
Dear Jason,

Thank you. We very much appreciate your support and insights on the the problem. I wish I understood the problem in more depth to help out with the coding.

The system involves a metalloproteinase with Zn atoms using ZAFF. Such atoms are in positions 74, 75 and 76. I noticed that when splitting, only fragments containing at least two Zincs are being generated properly. No residues are interacting with Zinc from residue 77 onwards (this is our ligand).

If it helps the assessment, I attempted splitting some arbitrary chunks (including or excluding all or some zincs), and here is the summary:

file[':1-73'] - > fails check
file[':1-74'] - > fails check
file[':1-75'] - > works
file[':1-76'] - > works
file[':74-323'] - > works
file[':75-323'] - > works
file[':76-323'] - > fails check
file[':77-323'] - > fails check

No modifications are being introduced with Parmed, we only use it for splitting. 

The goal is only to isolate the receptor and ligand (from the source prmtop) and generate inputs for MMPBSA. Would the code you mention preserve the original interactions? or they must be forcefully recreated by parmed to perform splitting?

Best!
Pedro

**Comment by pguillem** [comment]
Sorry, I accidentally closed the thread.

**Comment by pguillem** [comment]
Ok this approach seems to be working, using strip().

```
file = pm.load_file("receptor_ligand.prmtop", xyz="receptor_ligand.inpcrd")
file.strip(":77-323")
file.write_parm('receptor.prmtop')

file = pm.load_file("receptor_ligand.prmtop", xyz="receptor_ligand.inpcrd")
file.strip(":1-76")
file.write_parm('ligand.prmtop')

ligand = pm.load_file('ligand.prmtop')
receptor = pm.load_file('receptor.prmtop')

ligand.ptr("NTYPES")
18
receptor.ptr("NTYPES")
18

<AmberParm 4051 atoms; 247 residues; 4081 bonds; parametrized>
<AmberParm 1147 atoms; 76 residues; 1173 bonds; parametrized>

```
