### ISSUE TITLE
Can ParmEd convert a customized amoeba18 force field parameter file to OpenMM xml format?

### ISSUE THREAD

**Issue by taoliu032** [ParmEd/ParmEd#1300]
Hello ParmEd developers!

Can ParmEd convert an amoeba force field containing custom parameters, from TINKER .prm format to OpenMM .xml format?

For example, I parameterized a small molecule, caffeine, via the parameterization tool "Poltype". The custom parameters are to be used together with amoeba18 force field to simulate a system of nucleic acids, water and this small molecule. The output of Poltype has a format that is compatible with TINKER, but not with OpenMM.

I was told by OpenMM developers that ParmEd can do the conversion. But I didn't seem to find such function(s) in the documentation. Could anyone point them out, in case I missed them? Thanks a lot!

Best,
Tao

**Comment by swails** [comment]
ParmEd has very limited amoeba force field support and cannot do this.
