### ISSUE TITLE
Error when using restraints with OpenMM within ParmEd

### ISSUE THREAD

**Issue by nabilfarukqtx** [ParmEd/ParmEd#1301]
Hello, v4.0.0 of ParmEd, getting
> AttributeError: 'Rst7' object has no attribute 'reshape'

when trying to run OpenMM with restraints. The pmemd/sander input file contains (just showing the restraint specific options)
```
ntr=1,
restraintmask='@CA,C,N,O',
restraint_wt=1.0,
```
And I'm passing reference coords with the `-ref` argument, e.g.
`OpenMM -i md_openmm.in -o md.mdout -r md.rst7 -x md.nc -ref min.rst7 -O script openmm_run.py`

**Comment by swails** [comment]
@nffaruk just pushed a fix for this.  Thanks!
