### ISSUE TITLE
load_file method does not populate angles

### ISSUE THREAD

**Issue by mmfarrugia** [ParmEd/ParmEd#1322]
Hello,

I notice that while bonds are indeed populated upon using parmed.load_file(mol2_or_pdb_file, structure=True), the angles TrackedList is empty. Is there a particular method which will trigger population of the angles property or is this a bug?  I have tested this for both mol2 and pdb files on large and small test cases.

Happy to provide files as needed, thank you!

Mikaela

**Comment by swails** [comment]
angles are only populated by file types that define force fields.  Same with dihedrals and every other valence term that ParmEd supports.

**Comment by mmfarrugia** [comment]
Ah ok I see now, thank you.

**Comment by swails** [comment]
If it helps, ParmEd can export a networkx graph that you may find useful.

**Comment by mmfarrugia** [comment]
I've worked around it in a different way to reduce dependencies, but this is actually very cool, will be seeing if I can use it to set features within my analysis pipeline for MD, thank you!
