### ISSUE TITLE
LJ repulsion

### ISSUE THREAD

**Issue by JaimeRubioMartinez** [ParmEd/ParmEd#1339]
Dear all,
I am doing calculations introducing a new LJ repulsion point ( atom C99) . 

To introuce the new repulsion term I used  this input file :  
  addLJType @C99
  printLJTypes  @C99
  changeLJPair @C99 @C99 23.0 0.01
  printLJMatrix @C99
  outparm bak_p2_vdWRep.top

However in the new version : ParmEd-4.2.2 ( from gihub ) I obtain a matrix with zero for all the interactions between c99Type    and  otherTypes.

                  Atom Type 1                   Atom Type 2   A coefficient   B coefficient      R i,j    Eps i,j
------------------------------------------------------------------------------------------------------------------
            N,N2,N3,NA,NB [1]                       ca [27]        0.000000        0.000000   0.000000   0.000000
                     H,HS [2]                       ca [27]        0.000000        0.000000   0.000000   0.000000
           2C,3C,C8,CT,CX [3]                       ca [27]        0.000000        0.000000   0.000000   0.000000
                       HP [4]                       ca [27]        0.000000        0.000000   0.000000   0.000000
                       H1 [5]                       ca [27]        0.000000        0.000000   0.000000   0.000000
                       OH [6]                       ca [27]        0.000000        0.000000   0.000000   0.000000
                       HO [7]                       ca [27]        0.000000        0.000000   0.000000   0.000000
C,C*,CA,CB,CC,CN,CO,CR,CW [8]                       ca [27]        0.000000        0.000000   0.000000   0.000000
                     O,O2 [9]                       ca [27]        0.000000        0.000000   0.000000   0.000000
                      HC [10]                       ca [27]        0.000000        0.000000   0.000000   0.000000
                      HA [11]                       ca [27]        0.000000        0.000000   0.000000   0.000000
                      H4 [12]                       ca [27]        0.000000        0.000000   0.000000   0.000000
                      H5 [13]                       ca [27]        0.000000        0.000000   0.000000   0.000000
                    S,SH [14]                       ca [27]        0.000000        0.000000   0.000000   0.000000
                     Na+ [15]                       ca [27]        0.000000        0.000000   0.000000   0.000000
             ca,cc,cd,cp [16]                       ca [27]        0.000000        0.000000   0.000000   0.000000
                      ha [17]                       ca [27]        0.000000        0.000000   0.000000   0.000000
                      na [18]                       ca [27]        0.000000        0.000000   0.000000   0.000000
                      hn [19]                       ca [27]        0.000000        0.000000   0.000000   0.000000
                      c3 [20]                       ca [27]        0.000000        0.000000   0.000000   0.000000
                      hc [21]                       ca [27]        0.000000        0.000000   0.000000   0.000000
                      nb [22]                       ca [27]        0.000000        0.000000   0.000000   0.000000
                      nh [23]                       ca [27]        0.000000        0.000000   0.000000   0.000000
                      OW [24]                       ca [27]        0.000000        0.000000   0.000000   0.000000
                      HW [25]                       ca [27]        0.000000        0.000000   0.000000   0.000000
                             [26]                       ca [27]        0.000000        0.000000   0.000000   0.000000       ??????????
                      ca [27]                       ca [27] 219146244320203.218750  2960717.780000  23.000000   0.010000
In the previous version these values where not modified and have those corresponding to the ca Type.

Also, in amber18 we modified de parmed sotware to change  the Bvdw parameter to have  Bc99-c99 = 0  without problems.

Thank in advance for your help.

Jaime Rubio 

~

**Comment by JaimeRubioMartinez** [comment]
Sorry, I solved the problem !!
was my error in the .top file.
Jaime

**Comment by swails** [comment]
Glad to hear that (I was having a hard time coming up with ideas of what may have gone wrong).

I'll go ahead and close this, then.
