### ISSUE TITLE
Converting a non-standard amino from Amber (off/frcmod) to CHARMM (rtf/pst)

### ISSUE THREAD

**Issue by pguillem** [ParmEd/ParmEd#1365]
Hello all.

I have a non-standard residue in Amber format (off/frcmod) and I need it in CHARMM format. 
Loading the .off / .frcmod works well. But I have no idea where to go from here to export in RTF.

This is what my object has so far.
OrderedDict([('XXX', <ResidueTemplate XXX: 26 atoms; 27 bonds; head=N; tail=C>)])

Is parmed the right tool to do this?

Thanks in advance for any guidance.
Pedro

**Comment by swails** [comment]
I don't think ParmEd can currently write out CHARMM RTF files with residue templates.  Doing so would require writing code to convert cartesian coordinates to CHARMM's internal coordinate table, which I never bothered to work out.

**Comment by pguillem** [comment]
Most appreciated, Jason!
Thanks for your answer.

Have a great weekend!
Pedro
