### ISSUE TITLE
Velocity off by factor of 10 (nm/ps vs Å/ps) when continuing a simulation with OpenMM from an Amber restart file

### ISSUE THREAD

**Issue by nffaruk** [ParmEd/ParmEd#1366]
Hi, I've been experiencing consecutive simulations (e.g. NVT equil -> NPT equil) blowing up when running them through OpenMM with ParmEd. I've narrowed it down to ParmEd not converting the velocities that it gets from the amber restart file (Å/ps) to OpenMM's units (nm/ps).

**Comment by swails** [comment]
Can you show me the code you're using to run the simulations?

**Comment by nffaruk** [comment]
I'll try to give an example, but these are the [relevant lines in ParmEd](https://github.com/ParmEd/ParmEd/blob/cd0f8789134e123d7127bc04560412ab740ccfe2/parmed/tools/simulations/openmm.py#L501-L506):
```
# Velocities
if runmd and mdin.cntrl_nml['irest'] == 1 and position_container.hasvels:
    if scriptfile is not None:
        scriptfile.write('# Set velocities\n')
        scriptfile.write('simulation.context.setVelocities(parm.velocities)\n')
    simulation.context.setVelocities(position_container.velocities)
``` 
I'm guessing `position_container.velocities` and `parm.velocities` returns the raw float in internal units? In my version I've just added /10 to them, but it is more appropriate to use the method that returns it in OpenMM units

**Comment by swails** [comment]
The `velocities` docstring indicates the units [as seen here](https://github.com/ParmEd/ParmEd/blob/master/parmed/structure.py#L1920-L1930).

I'd mostly forgotten about that bit of functionality (it predates when I learned about templating languages like Jinja). I can submit a fix for it. Thanks for the report.

The two fixes for the script that get generated are either

```python
simulation.context.setVelocities(parm.velocities / 10)
```

or

```python
simulation.context.setVelocities(parm.velocities * u.angstroms / u.picoseconds)
```
