### ISSUE TITLE
Bond order lost after serializing Structure

### ISSUE THREAD

**Issue by SHZ66** [ParmEd/ParmEd#1375]
Hi,

It seems that Structure.__getstate__ does not include bond order in its output dictionary, as seen here:
https://github.com/ParmEd/ParmEd/blob/master/parmed/structure.py#L3836

As a result, bond order information is lost during serialization and deserialization. Could you please consider implementing a fix for this issue?

Thank you!

**Comment by swails** [comment]
Thanks for the report! Fix (with test) is in #1376.
