### ISSUE TITLE
Plans for a new release?

### ISSUE THREAD

**Issue by chrisjonesBSU** [ParmEd/ParmEd#1380]
Hello!

I'm curious if the maintainers have plans for a new release as 4.2.2 was released 1 year ago. I feel like a release sooner rather than later is especially important with so many packages updating to numpy 2.0. You all [merged](https://github.com/ParmEd/ParmEd/pull/1374) numpy 2.0 compatibility about 6 weeks ago; having a packaged version of Parmed on conda-forge with numpy 2.0 support would be very helpful.

Thanks!

**Comment by CalCraven** [comment]
Yes I also ran into this issue with the `.pdb` file loading using numpy=2.0 and the current release of parmed on conda.

**Comment by njzjz** [comment]
I see v4.3.0 has been released, but I don't see this version on the PyPI: https://pypi.org/project/ParmEd/#history

**Comment by chrisjonesBSU** [comment]
@njzjz  It looks like @swails is working through the packaged releases, [the conda-forge release PR is open on the feedstock](https://github.com/conda-forge/parmed-feedstock/pull/40), so I'm guessing PyPI is next.

Thank you for the fast response @swails !

**Comment by swails** [comment]
The conda-forge release PR has been merged and the source distribution published to PyPI.org.

This should be all set. Feel free to reopen if I'm mistaken for any reason.
