### ISSUE TITLE
Omnia conda package?

### ISSUE THREAD

**Issue by jchodera** [ParmEd/ParmEd#146]
Just wondering what the status of creating an omnia conda package was...

**Comment by swails** [comment]
I cloned the omnia recipes repo and made the skeleton, but haven't done anything else with regards to it yet. I was going to wait for OpenMM to release so I can get rid of hacks to support OpenMM 6.2. 

At this point we are pretty deep in the gromacs support, and there are a couple bug fixes in that branch right now. So we also have to wait for that work to complete before an official release.

**Comment by jchodera** [comment]
> I cloned the omnia recipes repo and made the skeleton, but haven't done anything else with regards to it yet. I was going to wait for OpenMM to release so I can get rid of hacks to support OpenMM 6.2.

Given the very long OpenMM release cycles and the enormous amount of useful stuff in ParmEd right now, it would be really useful to put out a ParmEd conda package---even development ones---that might use `openmm-dev` instead of the openmm stable version.

**Comment by swails** [comment]
I was holding out hope that OpenMM would be released soon :).  But that's more NVidia's fault than ours.

I could do the dev package, but the only @kyleabeauchamp expressed an opinion about doing that in our email thread, and he was -1 IIRC.  I could change course though and create one once we're done with the Gromacs stuff.

(Well, not done, but at a stage where it's more complete and more validated, anyway).

**Comment by jchodera** [comment]
@ChayaSt is forging ahead to use it in a Charmm torsion refitting scheme
(thr one we discussed), so we now have at least one other project where
this would be useful.

I still wonder if there is a workaround for that CUDA7 FFT issue via
padding with zeros...

**Comment by hainm** [comment]
@swails I think you could just build ParmEd in ParmEd channel. 

`conda install -c ParmEd ParmEd`

(although building ParmEd by `pip` from git is very easy and fast)

**Comment by swails** [comment]
I'd rather stay away from proliferation of conda channels.  I wanted to consider adding an Amber conda channel and convincing you to put pytraj there.  My idea is to make ParmEd available in the Amber channel (alongside the sander API and hopefully pytraj) and the omnia channel if that's possible.

**Comment by hainm** [comment]
yeah, great idea.

`conda install -c amber pytraj parmed sanderapi libcpptraj`

I already have all files for building `pytraj`, so just need to upload to `amber` channel (if ever exist).

Hai

**Comment by swails** [comment]
Why would `libcpptraj` be necessary?  Is that not part of `pytraj`?  Or at the very least, it should be pulled in by `pytraj`...

**Comment by hainm** [comment]
@swails it's just for demonstration.

Ideally we just need '`conda install -c amber ambertools-dev`

this is a real `meta.yaml` file for building `pytraj` (pull `libcpptraj` too)

```python
package:
  name: pytraj-dev
  version: !!str 0.1.2.dev3

source:
  git_url: https://github.com/pytraj/pytraj.git
  git_tag: master

requirements:
  build:
    - python
    - cython
    - libcpptraj
  run:
    - python
    - libcpptraj
    - matplotlib
    - numpy

about:
  home: http://github.com/pytraj/pytraj
  license: BSD
  summary: Python wrapper for cpptraj - a package for data analysis of MD simulations
```

**Comment by jchodera** [comment]
Just wondering what the status of the conda package is here!

**Comment by swails** [comment]
Waiting on #152, which I finally got working yesterday.  I need to add a couple of tests before merging, but the conda package is on the docket after that.

**Comment by jchodera** [comment]
Awesome!

**Comment by swails** [comment]
OK.  I made a beta release to check out the conda packaging.  I submitted a PR for this in conda-recipes.  Am I doing this right?  What else do I need to do to get things uploaded to binstar correctly?

**Comment by swails** [comment]
This should be done.  See https://binstar.org/omnia/parmed/files.

I cut a beta release from the master branch specifically for the conda packaging.  I want to add Gromacs->Amber conversion to `parmed.py` before I cut the official release, as well as solicit input from anyone else that has an opinion.

**Comment by davidlmobley** [comment]
@swails - could you update with 2.0 beta 1? I'd like to be able to conda install the version where `import parmed` works, as opposed to `import chemistry` - at least if you're OK with that. (Or maybe a conda-installable development version? i.e. I can `conda install openmm-dev` to get a version which works with ParmEd but the ParmEd I can conda install doesn't work with my current code, which uses the new organization.

**Comment by swails** [comment]
Sorry!  I meant to do this a long time ago.  Done now, just waiting on @jchodera (or someone else with merge permissions in conda-recipes).

**Comment by jchodera** [comment]
Merged, and @swails has been added to the list of people able to merge.

Jenkins should be rebuilding now.

**Comment by jchodera** [comment]
Jenkins has finished building `osx` and `linux` packages.

**Comment by jchodera** [comment]
Thanks again!
