### ISSUE TITLE
Document Structure / AmberParm addition operations

### ISSUE THREAD

**Issue by kyleabeauchamp** [ParmEd/ParmEd#149]
The structure addition syntax from #145 looks excellent, but probably could use some examples / documentation on the main docs page when things are ready.  

```

#Test a simple merge of A and B (phenol and biphenyl)
phenol = chemistry.amber.AmberParm( 'phenol.prmtop', 'phenol.crd')
biphenyl = chemistry.amber.AmberParm( 'biphenyl.prmtop', 'biphenyl.crd')
phenol_biphenyl = phenol * 3 + biphenyl * 2
gromacs_topology = chemistry.gromacs.GromacsTopologyFile.from_structure( phenol_biphenyl )
chemistry.gromacs.GromacsTopologyFile.write( gromacs_topology, 'test_merged.top')

#Let's try that after conversion to GROMACS
gromacs_topology_phenol = chemistry.gromacs.GromacsTopologyFile.from_structure( phenol )
gromacs_topology_biphenyl = chemistry.gromacs.GromacsTopologyFile.from_structure( biphenyl )
phenol_biphenyl = gromacs_topology_phenol  + gromacs_topology_biphenyl
chemistry.gromacs.GromacsTopologyFile.write( phenol_biphenyl, 'test_merged_2.top' )
```

**Comment by swails** [comment]
I'll definitely add a page about Structure slicing and addition/multiplication.  For now this is not in the master branch, so it's not really part of the "official" dev version yet.

**Comment by swails** [comment]
Docs should have been added in the gromacs_support branch.

See [here](https://github.com/swails/ParmEd/blob/gromacs_support/doc/structure.rst#structure-manipulation-slicing-combining-replicating-and-splitting)

It looks better when processed by Sphinx into HTML, but the material is all there.

**Comment by hainm** [comment]
@swails 

the link in this line does not work
https://github.com/swails/ParmEd/blob/gromacs_support/doc/structure.rst#structure-manipulation-slicing-combining-replicating-and-splitting
"Now let's look at the slightly more complex Amber mask selection. See Amber mask syntax for more details."

**Comment by hainm** [comment]
```
phenol_biphenyl = phenol * 3 + biphenyl * 2
```
Does this vstack coords too?

**Comment by swails** [comment]
> the link in this line does not work

It does when processed to HTML.

> Does this vstack coords too?

Effectively, yes.

**Comment by hainm** [comment]
anyway, nice job on splitting. I will read and try to steal some of ideas to `pytraj` (although It might not very obvious what `traj += traj` mean (could be traj.xyz += traj.xyz, or just equal to [traj, traj.copy()]

Hai

**Comment by swails** [comment]
> (although It might not very obvious what traj += traj mean

Then my advice is don't do it until it becomes obvious to you.  Once you implement addition, you're SOL if you find a better definition for it.

**Comment by hainm** [comment]
just try to have internal talk between `pytraj` and `parmed`. nice

```python
In [27]: t  = chem.load_file("biphenyl.prmtop")

In [28]: top = io.load_pseudo_parm(t)

In [29]: t
Out[29]: <AmberParm 22 atoms; 1 residues; 23 bonds; parametrized>

In [30]: top
Out[30]: <Topology with 1 mols, 1 residues, 22 atoms, 23 bonds, non-PBC>
```

**Comment by hainm** [comment]
by the way, I just implemented very simple merging two traj this after (just like you did with chem) but I think I will let pytraj convert its Topology to ParmEd and let ParmEd to Topology manipulation and then load back again.

back and forth: https://github.com/hainm/pytraj/commit/7e0dae0949768896ccf68a8387a98f02d6b76c2d

merging trajs: https://github.com/hainm/pytraj/commit/54a8187bcfa54131c88dc6d00f560a00c77671f2#diff-5d4a5b70792fe5de510b982f3e19c545R40

**Comment by swails** [comment]
> @swails : is there any chain or mol in ParmEd?

I didn't see this earlier.  Each `Residue` instance has a `chain` attribute, but there is no `Chain` class (I've chosen instead to focus on atoms and residues).  So you can get all the same information as you do from MDTraj, pytraj, and MDAnalysis, it's just not as efficient.

As for molecules, there is some work going on in the gromacs_support branch working on this kind of thing (I'll probably bring in NetworkX to help with this kind of thing).

**Comment by swails** [comment]
Done in #152.
