### ISSUE TITLE
re-order README.md

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#154]
I myself prefer to read what is ParmEd and what it can do rather than reading License right away (especially when using phone)

(switch `License` and `Description`)

or just 
```LESSER GPL LICENSE INFO

Copyright (C) 2010 - 2014 Jason Swails```

and point to the link of full license. 

Hai

**Comment by hainm** [comment]
ah, FYI: i've found this program and keep laughing when reading the README

https://github.com/nvbn/thefuck

**Comment by swails** [comment]
I agree.

**Comment by swails** [comment]
Done inside #152

**Comment by hainm** [comment]
:+1:
