### ISSUE TITLE
conda amber

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#161]
I create issue here so we can list of programs we can include in amber channel in future

* `pytraj`
* `ParmEd`
* `sanderapi`
* `saxs_md` (will work with Hung to finish this)
* `amberlite` (?)
* ...

May be we have `amber` (`AMBER`?) channel with `ambertools-dev` (and `ambertools15`) as subdir...

Hai

**Comment by jchodera** [comment]
That would be awesome!

**Comment by hainm** [comment]
close since we already made https://github.com/Amber-MD/. Will move there for this kind of discussion.
