### ISSUE TITLE
Using the output of a gromacs simulation as input to amber

### ISSUE THREAD

**Issue by mpharrigan** [ParmEd/ParmEd#175]
Forgive my possible ignorance. I'm trying to extract a frame from a gromacs xtc file, save as an inpcrd, and run amber dynamics. The resulting bond energy is *******. If I use a 0.2 fs timestep, I can observe atoms (primarily lipids in my membrane) near the periodic boundary moving rapidly towards the center of the box. 

The amber manual (section describing `ntb`) says that amber does not support bonds spanning periodic boundaries. My hypothesis is that gromacs *does* support bonds spanning periodic boundaries, the lipids are split across the boundaries, and end up being harmonically pulled together *through* the box.

I know parmed has support for converting from gromacs. I was wondering if you had any insight into this problem, and whether parmed would be a good tool to fix it

**Comment by davidlmobley** [comment]
I think this probably can also be dealt with using the pbc options in the GROMACS tools such as trjconv.

**Comment by swails** [comment]
I've heard that Gromacs does support bonds spanning periodic boundaries (for things like surfaces), but Amber doesn't.  If you have them in your system, there is no way to map a Gromacs topology to an Amber topology.  If Gromacs doesn't do anything special to identify these bonds, then ParmEd will happily convert it to Amber's format, but it obviously won't work.

The only way you can model lipid layers in Amber is to model entire molecules.

**Comment by mpharrigan** [comment]
`trjconv -pbc mol` fixed the problem

**Comment by swails** [comment]
So what was the issue?  And it fixed the problem in terms of going from Gromacs -> Amber?

**Comment by mpharrigan** [comment]
the problem was that the molecules were split over a periodic boundary in gromacs' raw output. Amber can't deal with bonds across a periodic boundary. Making molecules whole with the above command fixed it.

**Comment by swails** [comment]
This is good to know.  I'll make a note to add it to the docs.

Thanks!
