### ISSUE TITLE
repo organization: again

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#184]
Why do you think about
* move `GmxTests` to `test` folder. (it's just a test)
* move `src` to `parmed` main package. May be rename it to something more descriptive?

**Comment by swails** [comment]
I'm going to delete GmxTests at some point. They don't fit Parmed's testing scheme, and the ones I wanted to run I already moved into the tests directory. 

As for the src folder, I rather prefer where it is. All extensions go there for now. If this becomes unwieldy in the future it can be revisited.
