### ISSUE TITLE
socket warning with download_PDB

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#188]
FYI: I got this warning (not in interactive mode)

`.<module 'parmed' from '/home/haichit/anaconda3/lib/python3.4/site-packages/parmed/__init__.py'>
/home/haichit/anaconda3/lib/python3.4/socket.py:447: ResourceWarning: unclosed <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('129.49.94.135', 50893), raddr=('128.6.70.11', 21)>
  self._sock = None
`

it's great if there is no warning (distracting)

**Comment by swails** [comment]
I hadn't seen this.  If I had to guess, it's because I didn't close the FTP object.  I'll look into it and fix it.
