### ISSUE TITLE
should Structure's pdbxyz return 2D list?

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#190]
what do you think? currently 
```python
In [64]: len(t.pdbxyz)
Out[64]: 1
```

**Comment by hainm** [comment]
2D to 1D (to compat with `pysander` as example)

```python
    import itertools
    return list(itertools.chain.from_iterable(arr0))
```

**Comment by swails** [comment]
`pdbxyz` is a hack that I plan to replace.  It holds the data for now, but I plan to replace it with "coordinates" as a 3-D numpy array with shape (frames, natom, 3) that will be common to all coordinate-bearing objects.

At least that's the plan.

**Comment by swails** [comment]
Done in #211.
