### ISSUE TITLE
suggestion for ParmEd's doc and website

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#195]
This is a placeholder for my future suggestion about its doc and website. Please don't close it. :D

**Comment by hainm** [comment]
#### gromacs: example usage

@swails: what do you mean about `amb_inpcrd.close()` in this case here:
http://parmed.github.io/ParmEd/html/gromacs.html

Naturally I will think about pair `open ... close`, not `write ... close` :D

**Comment by swails** [comment]
> Naturally I will think about pair open ... close, not write ... close :D

Actually, it's `open ... write ... close` -- simply `open ... close` is a fairly useless workflow ;).

The trajectory/restart file classes are intended to be file-like objects.  Calling the constructor (or one of the constructors) is akin to "opening" the file.  In the same way that `file('filename', <mode>)` opens the file using the default `file` constructor (in Python 2 -- Python 3 adds layers of indirection for standard I/O).  So this *is* a `open ... write ... close` type of workflow, but the `open` here behaves like the `bz2.BZ2File` class behaves.

**Comment by hainm** [comment]
>> Naturally I will think about pair open ... close, not write ... close :D
> Actually, it's open ... write ... close -- simply open ... close is a fairly useless workflow ;).

sure. this is what I meant. But with `open` we can do other things without `write` too. :P 

> So this is a open ... write ... close type of workflow, but the open here behaves like the bz2.BZ2File class behaves.

I see.

**Comment by hainm** [comment]
any way, nice job on writing doc.

To me, writing a good doc is much harder than writing python code. :(

**Comment by swails** [comment]
I'm going to go ahead and close this -- you've been opening up separate issues relating to the website, so I don't think this is really seeing much/any use anymore.

**Comment by hainm** [comment]
Yeah, it is easier to open separate issue
