### ISSUE TITLE
write_pdb?

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#196]
motivation: 

```python
import parmed as pmd
pdb = pmd.download_PDB("4PY3")
pdb.write_pdb("4PY3.pdb", mode='original') # just like download pdb file to disk.
```

I thought about this when using ParmEd to get b-factor. But I can't not find the method, so I wish to open the original pdb file and look inside.

Why not downloading myself or using other's program? I am too lazy. :D (open chrome, download pdb, browse to pdb file, use vim to open, ...). 

btw, did I miss that `parmed` read b-factor too?

**Comment by hainm** [comment]
or just 
```python
pdb = pmd.download_PDB("4PY3", mode='to_disk')
```

**Comment by swails** [comment]
I typically use `getPDB.sh` (https://github.com/swails/JmsScripts).  I might add a `saveto` argument, but `download_PDB` should always instantiate a Structure.  (And there *is* a `write_pdb`, it just doesn't write *everything* that was in the original PDB file.)

**Comment by hainm** [comment]
can you please copy code from `getPDB` to something like 'parmed.misc'? it's more convenient to use a single package.

It would be great to you can bundle other useful and related scripts (from yours) to `parmed` too. Just easier to remember, like 'I need this method, oh, it's in `ParmEd`'.

(yes, I knew there is `write_pdb` method in parmed and I did open saved pdb file).

**Comment by swails** [comment]
It doesn't really fit in ParmEd (and it's bash, not Python).

> It would be great to you can bundle other useful and related scripts (from yours) to parmed too. Just easier to remember, like 'I need this method, oh, it's in ParmEd'.

IMO it dilutes what ParmEd is.  The more code and stuff it does, the more there is to maintain.  There is good reason not to bloat a code base.  I can add a saveto argument, but I don't plan on treating ParmEd as a dumping ground for all my scripts.

**Comment by hainm** [comment]
I just meant "related", not all of your scripts :P . My bad English.
