### ISSUE TITLE
coverage?

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#203]
is there any intention to test coverage in `ParmEd`? I am thinking about use it for `pytraj` too.

http://coverage.readthedocs.org/en/coverage-4.0a5/

**Comment by swails** [comment]
I tried once a long time ago, but it took way too long to process so I gave up.  It's something I'd revisit, though, if I learned more about how to use it efficiently.

**Comment by hainm** [comment]
close to move to https://github.com/ParmEd/ParmEd/issues/434
