### ISSUE TITLE
Amber prmtop to gromacs topology

### ISSUE THREAD

**Issue by sarahwitzke** [ParmEd/ParmEd#204]
Hi all,

Does any of you know how I use ParmEd to convert an Amber .prmtop to a gromacs topology?

All the best,
Sarah

**Comment by davidlmobley** [comment]
Yes. For an example function, see
https://github.com/MobleyLab/openmoltools/blob/master/openmoltools/utils.py#L488



On Mon, Jun 15, 2015 at 8:22 AM, sarahwitzke <notifications@github.com>
wrote:

> Hi all,
>
> Does any of you know how I use ParmEd to convert an Amber .prmtop to a
> gromacs topology?
>
> All the best,
> Sarah
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ParmEd/ParmEd/issues/204>.
>



-- 
David Mobley
Associate Professor
Department of Pharmaceutical Sciences
Department of Chemistry
3134B Natural Sciences I
University of California, Irvine
Irvine, CA 92697
dmobley@uci.edu
work (949) 824-6383
cell (949) 385-2436

**Comment by sarahwitzke** [comment]
Dear David,

Thank you very much for your response.

The argument parsing makes sense now. 
How do I call the functionality in ParmEd? 
When I type “amber_to_gromacs” I get “amber_to_gromacs command not recognized”.

All the best,
Sarah

**Comment by davidlmobley** [comment]
This is a different package, openmoltools. You can get it (though the code
I showed you isn't in the main release yet so you'd have to get that branch
from github) or just use the code in that function as a model for your own.

On Mon, Jun 15, 2015 at 8:44 AM, sarahwitzke <notifications@github.com>
wrote:

> Dear David,
>
> Thank you very much for your response.
>
> The argument parsing makes sense now.
> How do I call the functionality in ParmEd?
> When I type “amber_to_gromacs” I get “amber_to_gromacs command not
> recognized”.
>
> All the best,
> Sarah
>
> > On 15 Jun 2015, at 16:35, David L. Mobley <notifications@github.com>
> wrote:
> >
> > Yes. For an example function, see
> >
> https://github.com/MobleyLab/openmoltools/blob/master/openmoltools/utils.py#L488
> >
> >
> >
> > On Mon, Jun 15, 2015 at 8:22 AM, sarahwitzke <notifications@github.com>
> > wrote:
> >
> > > Hi all,
> > >
> > > Does any of you know how I use ParmEd to convert an Amber .prmtop to a
> > > gromacs topology?
> > >
> > > All the best,
> > > Sarah
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/ParmEd/ParmEd/issues/204>.
> > >
> >
> >
> >
> > --
> > David Mobley
> > Associate Professor
> > Department of Pharmaceutical Sciences
> > Department of Chemistry
> > 3134B Natural Sciences I
> > University of California, Irvine
> > Irvine, CA 92697
> > dmobley@uci.edu
> > work (949) 824-6383
> > cell (949) 385-2436
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/ParmEd/ParmEd/issues/204#issuecomment-112112505>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ParmEd/ParmEd/issues/204#issuecomment-112114810>.
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by sarahwitzke** [comment]
Ahh I see :-)

Thank you David!

All the best,
Sarah

**Comment by swails** [comment]
Thanks @davidlmobley for helping out here! I assume that the problem was solved. If not feel free to reopen the issue or start a new one.
