### ISSUE TITLE
2.0 beta2 release making `parmed.py`->`parmed` change?

### ISSUE THREAD

**Issue by davidlmobley** [ParmEd/ParmEd#205]
@swails - could you go ahead and make the 2.0 beta 2 release you mentioned (#181) to adjust the `parmed.py` issue, and update the omnia package? Travis-CI is unhappy for `openmoltools` because of the same issue in #181 - specifically, it gets confused about importing the `parmed` module versus `parmed.py`, like nose and IPython. 

If you want to see the output, it's here: https://github.com/choderalab/openmoltools/pull/124

**Comment by swails** [comment]
Doing this in #206 (I think we can both agree that it's important to make sure the version number is correct :)).

Once that's done, I will cut the prerelease and update the conda recipe.

**Comment by davidlmobley** [comment]
Thanks. Sorry to be so picky here but it makes testing a lot easier. Plus I have a lot of rookies and undergrads in my group and it's easier if I can just tell them "conda install openmoltools" instead of "download ParmEd from GitHub and install via setup.py, then install openmoltools"... :) Especially because there are enough other "special" steps already (i.e. they need the development version of OpenMM, etc.).

**Comment by swails** [comment]
I understand that.  These are good reasons IMO.
