### ISSUE TITLE
Add GROMACS parsers

### ISSUE THREAD

**Issue by swails** [ParmEd/ParmEd#21]
It would be nice to add support for reading in GROMACS topology and parameter files and instantiate a `Structure` object from them.

That would allow users to convert GROMACS files into Amber topology files.

**Comment by kyleabeauchamp** [comment]
I presume you've seen the Shirts lab tool InterMol (https://github.com/shirtsgroup/InterMol/tree/develop)?  Could also be useful.  Pmx is OK too, but I've found it to be a bit incomplete.

**Comment by swails** [comment]
> I presume you've seen the Shirts lab tool InterMol (https://github.com/shirtsgroup/InterMol/tree/develop)?

I hadn't, actually.  I'll poke around it to see if there's anything I can use.  Thanks for the pointer!

> Pmx is OK too, but I've found it to be a bit incomplete.

This one I'd seen.  What drew me to their approach was actually their hijacking of `cpp.py` from SCons, which I feel will make my life easier in the long run.

Thanks!

**Comment by swails** [comment]
Done (finally) in #152

**Comment by swails** [comment]
Lot of work just to close one issue :).
