### ISSUE TITLE
GROMACS .gro file format is apparently allowed to violate format specifications

### ISSUE THREAD

**Issue by davidlmobley** [ParmEd/ParmEd#220]
Apparently, ParmEd is currently allowing .gro files to be written which violate .gro file format specifications (see http://manual.gromacs.org/current/online/gro.html). Specifically, I can currently get output which looks like this:

```
GROningen MAchine for Chemical Simulation
 1836
    1solute   C1    1   0.777   2.671   2.404
    1solute   C2    2   0.693   2.671   2.515
    1solute   C3    3   0.555   2.671   2.498
    1solute   C4    4   0.501   2.671   2.369
    1solute   C5    5   0.585   2.671   2.258
    1solute   C6    6   0.723   2.671   2.275
    1solute   H1    7   0.885   2.671   2.417
    1solute   H2    8   0.736   2.671   2.615
    1solute   H3    9   0.490   2.671   2.584
    1solute   H4   10   0.393   2.671   2.356
    1solute   H5   11   0.543   2.671   2.158
    1solute   H6   12   0.789   2.671   2.189
    2benzene   C1   13   0.038   2.434   2.246
    2benzene   C2   14   0.059   2.540   2.334
    2benzene   C3   15   0.081   2.515   2.469
```

This is incorrect, because the residue name (in the .gro file) must be (at max) a five character string - i.e. it is a fixed width format. 

Possibly this is partly my fault, in that I did read in a set of AMBER-format files which had shorter residue names and then modify the residue names to be longer. Still, this is allowed (as far as I am aware) in topology files. I *think* (though I am not 100% certain) that no incorrect behavior will result if you simply truncate the residue names at 5 characters for the purpose of writing .gro files, as these are normally simply matched to topology files when generating input. As far as I can tell from the GROMACS manual the residue name in the topology file is just a string.

This issue originates because I have single-molecule GROMACS topology files wherein I want the molecule names to be 'solute', 'benzene', etc., and currently the only way to achieve this is to make the RESIDUE names be 'solute', 'benzene', etc. (even though I'd be OK with a shorter residue name). 

So, there are two fixes which immediately present themselves and I'm not sure which is preferable:
* Modify the .gro writer to use short residue names even if the residues have longer names
* Allow GROMACS Structure objects to separately modify molecule and residue names (or maybe this is there and I'm missing it) so I can use short residue names but long molecule names.

@nividic - this is the issue you mentioned.

**Comment by swails** [comment]
Yea, this was an oversight.  There is already protection in the PDB file writing that just truncates string fields that might overflow in order to prevent this kind of thing.

All I did was truncate the residue name (and atom name as well).  It's easy to implement and seems as good a convention as any.  Let me know if this works for you.

**Comment by swails** [comment]
BTW, this is implemented in #221

**Comment by nividic** [comment]
YES, it seems ok now. Thanks

**Comment by davidlmobley** [comment]
@swails - this looks good to us.
