### ISSUE TITLE
gro.coordinates = None --> no 'xx' for atom

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#224]
```python
In [15]: p = pmd.load_file("1aki.ff99sbildn.gro")

In [16]: p.atoms[0].xx
Out[16]: 44.6

In [17]: p.coordinates = None

In [18]: p.atoms[0].xx
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-18-a12f522e88b7> in <module>()
----> 1 p.atoms[0].xx

AttributeError: 'Atom' object has no attribute 'xx'
```

should 'xx' is None rather `AttributeError`?

**Comment by swails** [comment]
> should 'xx' is None rather AttributeError?

No, it does clearly say this in the `Atom` docstring (unfortunately numpydoc doesn't like the "Possible Attributes" section, so it isn't translated to the sphinx docs on the website... not sure how to convince numpydoc/sphinx to actually *print* that section).

There are already quite a few places in parmed where `xx` is assumed to be a float or non-existent.

**Comment by hainm** [comment]
what's your motivation of using `AttributeError`? 

to me, `atom.xx is None` is easier to type. :D (vs if hasattr(atom, 'xx')(

**Comment by swails** [comment]
> what's your motivation of using AttributeError?
> 
> to me, atom.xx is None is easier to type. :D (vs if hasattr(atom, 'xx'))

Easier to use in listcomps:

```Python
try:
    positions = [[a.xx, a.xy, a.xz] for a in struct.atoms]
except AttributeError:
    positions = None
```

**Comment by hainm** [comment]
I see.

**Comment by swails** [comment]
It also gives you a consistent exception type that you always get if positions are not set.

```Python
# Reflect all atoms in the yz-plane
for a in struct.atoms:
    a.xx *= -1

# Create ndarray of Heavy-atom positions
np.array([[a.xx, a.xy, a.xz] for a in struct.atoms if a.atomic_number > 1])

# Print out all of the coordinates
for atom in struct.atoms:
    print('Coordinates of atom %d = (%10.3f, %10.3f, %10.3f)' % (atom.idx, atom.xx, atom.xy, atom.xz))
```

If you have `xx` be `None`, you get `TypeError` for the first and third, and no error at all for the middle (just an ndarray of dtype `object` full of `None`).  This way if you have no coordinates set, and you try to access coordinates, you get an `AttributeError` every time.  Easy to catch, and fails as early as possible if they aren't present in a script that needs them.

**Comment by swails** [comment]
To clarify, I don't think my approach here is better than just using `None` -- there are advantages and disadvantages to both (and `None` I think is more typical).  But my approach has some advantages that I routinely make use of, which I think is a good motive to keep it.

**Comment by hainm** [comment]
yeah, I agree with you rationale.

**Comment by swails** [comment]
I'm going to go ahead and close this.
