### ISSUE TITLE
New beta release since gromacs file format fix?

### ISSUE THREAD

**Issue by davidlmobley** [ParmEd/ParmEd#229]
Any chance of a new beta release/conda package now that #221 was fixed? The people I have using the conda install can't safely use some ParmEd features I have in openmoltools until this happens.

**Comment by swails** [comment]
Done.  Release made and PR to omnia-md/conda-recipes#241 submitted.  Just waiting on someone (maybe @jchodera?) to merge that and it should be good.

**Comment by swails** [comment]
This should be done.  @davidlmobley -- feel free to reopen if the conda package isn't uploaded.
