### ISSUE TITLE
load mol2 to Structure

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#242]
Jason,

I try to load a mol2 file and got this
```python

In [11]: t = pmd.load_file("LA.mol2")

In [12]: t
Out[12]: <ResidueTemplate LA: 34 atoms; 37 bonds; head=None; tail=None>

In [13]: pmd.write_PDB(t, '/home/haichit/test.pdb')
```
I got error "AttributeError: 'ResidueTemplate' object has no attribute 'box'".

My question is
Is there any option I can load this mol2 file as a Structure?
pmd.load_file('LA.mol2', format='Structure')

thanks

Hai

**Comment by hainm** [comment]
I got this error with iteractive parme.

```parmed La_bcc.mol2```

```

  ____    .---.  ,-----.  _____
.'    `,.':   :'' :    :.'     `.
| :   :    ' '     '  '   :   :  \
|  ' '                     ' '    \
|       v                          \
|       |       v                   \
|       |       |       v            \
|   P   |   A   |   R   |   M   |     \
|       |       |       |       |      \
|       |       |       |       |       \
|       |       |       |       |        \
| ===== |       |       |       |         )
 \ --- /| ===== |       |       |        /
  `---'  \ --- /| ===== | ===== |       /
          `---'  \ ---- A ----- /      /
                  `----'.`-----'      /
                       /             /
                       '-._    ED   /
                           '.      /
                             `----'

ParmEd: a Parameter file Editor


Traceback (most recent call last):
  File "/home/haichit/anaconda3/bin/parmed", line 6, in <module>
    clapp()
  File "/home/haichit/anaconda3/lib/python3.4/site-packages/parmed/scripts.py", line 128, in clapp
    amber_prmtop.add_parm(parm)
  File "/home/haichit/anaconda3/lib/python3.4/site-packages/parmed/tools/parmlist.py", line 41, in add_parm
    raise ParmError('Added parm must be Structure or a subclass')
parmed.tools.exceptions.ParmError: Added parm must be Structure or a subclass
```

it likely that this only work with `prmtop` file?

**Comment by swails** [comment]
> Is there any option I can load this mol2 file as a Structure?

Yes.

```Python
import parmed as pmd
pmd.load_file('something.mol2', structure=True)
```

**Comment by swails** [comment]
> it likely that this only work with prmtop file?

It will work with any kind of parm file.  The default mol2 return object is a `ResidueTemplate` -- I just have to add support for detecting mol2 files and getting a `Structure` from it in the `parm` action.

**Comment by hainm** [comment]
thanks.

I think you should update doc for load_file.

```python
Signature: pmd.load_file(filename, *args, **kwargs)
Docstring:
Identifies the file format of the specified file and returns its parsed
contents.

Parameters
----------
filename : str
    The name of the file to try to parse
*args : other positional arguments
    Some formats accept positional arguments. These will be passed along
**kwargs : other options
    Some formats can only be instantiated with other options besides just a
    file name.
```

Hai

On Mon, Jul 6, 2015 at 8:40 AM, Jason Swails <notifications@github.com>
wrote:

> Is there any option I can load this mol2 file as a Structure?
>
> Yes.
>
> import parmed as pmd
> pmd.load_file('something.mol2', structure=True)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ParmEd/ParmEd/issues/242#issuecomment-118841952>.
>



-- 
Hai Nguyen

**Comment by swails** [comment]
> I think you should update doc for load_file.

In what way?  `*args` and `**kwargs` are passed along to the parsing functions for each of the various file types.  It would be a bit much to keep a list of all keywords for all supported filetypes in the docstring of `load_file`.

The docstring of `Mol2File.parse` details this option.  I should probably add a statement to the docs about this, though.

**Comment by hainm** [comment]
may be just add few examples. i don't know how to load mol2 to structure
without asking you and the doc does not say anything.


On Mon, Jul 6, 2015 at 10:49 AM, Jason Swails <notifications@github.com>
wrote:

> I think you should update doc for load_file.
>
> In what way? *args and **kwargs are passed along to the parsing functions
> for each of the various file types. It would be a bit much to keep a list
> of all keywords for all supported filetypes in the docstring of load_file.
>
> The docstring of Mol2File.parse details this option. I should probably
> add a statement to the docs about this, though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ParmEd/ParmEd/issues/242#issuecomment-118877971>.
>



-- 
Hai Nguyen
