### ISSUE TITLE
what does `parametrized` mean?

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#244]
I can understand what `parametrized` mean if I load a regular parm7 file. But when slicing a `Structure`, I still get `parametrized`. So what does it mean?

```python
In [9]: t
Out[9]: <AmberParm 1086 atoms; 34 residues; 1170 bonds; parametrized>

In [21]: t[:33]
Out[21]: <AmberParm 33 atoms; 2 residues; 35 bonds; parametrized>

In [22]: t[:37]
Out[22]: <AmberParm 37 atoms; 2 residues; 39 bonds; parametrized>

```

**Comment by swails** [comment]
It means that the `Structure` contains valence parameters and defines a potential energy function for the system.

Basically, you can pass it to OpenMM (or sander, if Amber supports the functional form) and get energies and forces back.

Slices of a parametrized structure return another parametrized structure.  All of the nonbonded parameters are retained as are the valence parameters that exist between the atoms that are in both the original structure *and* the slice.

**Comment by davidlmobley** [comment]
Tangentially, I think `parametrized` would properly be spelled
`parameterized` since I don't see a reason to drop the "e" in "parameter"
when adding the "-ized" suffix. But perhaps I'm mistaken.

On Mon, Jul 6, 2015 at 8:52 AM, Jason Swails <notifications@github.com>
wrote:

> It means that the Structure contains valence parameters and defines a
> potential energy function for the system.
>
> Basically, you can pass it to OpenMM (or sander, if Amber supports the
> functional form) and get energies and forces back.
>
> Slices of a parametrized structure return another parametrized structure.
> All of the nonbonded parameters are retained as are the valence parameters
> that exist between the atoms that are in both the original structure *and*
> the slice.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ParmEd/ParmEd/issues/244#issuecomment-118879119>.
>



-- 
David Mobley
Associate Professor
Department of Pharmaceutical Sciences
Department of Chemistry
3134B Natural Sciences I
University of California, Irvine
Irvine, CA 92697
dmobley@uci.edu
work (949) 824-6383
cell (949) 385-2436

**Comment by swails** [comment]
> Tangentially, I think `parametrized` would properly be spelled
> `parameterized` since I don't see a reason to drop the "e" in "parameter"
> when adding the "-ized" suffix. But perhaps I'm mistaken.

English is weird, and both are legal: http://www.merriam-webster.com/dictionary/parameterize.  I've seen it without the 'e' more than with it, so that's the way I usually spell it (although I *used* to keep that e in).

**Comment by swails** [comment]
For past-tense, that is.  If you google "Parameterize", you'll see that Google only lists "parametrized" as the past tense, I think (and not "parameterized").

**Comment by davidlmobley** [comment]
Hah, odd. Well, thanks for the clarification! I'm gonna have to try and
re-learn this.

On Mon, Jul 6, 2015 at 9:00 AM, Jason Swails <notifications@github.com>
wrote:

> Tangentially, I think parametrized would properly be spelled
> parameterized since I don't see a reason to drop the "e" in "parameter"
> when adding the "-ized" suffix. But perhaps I'm mistaken.
>
> English is weird, and both are legal:
> http://www.merriam-webster.com/dictionary/parameterize. I've seen it
> without the 'e' more than with it, so that's the way I usually spell it
> (although I *used* to keep that e in).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ParmEd/ParmEd/issues/244#issuecomment-118882101>.
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by hainm** [comment]
I asked google "Parameterized vs parametrized" and he ask

Did you mean: Parameterized vs *parameterized*
<https://www.google.com/search?rlz=1C1CHMO_enUS485US485&biw=1600&bih=815&q=Parameterized+vs+parameterized&spell=1&sa=X&ei=v5iaVcbEFMjk-AHl3YCgDw&ved=0CBoQBSgA>

On Mon, Jul 6, 2015 at 11:00 AM, Jason Swails <notifications@github.com>
wrote:

> Tangentially, I think parametrized would properly be spelled
> parameterized since I don't see a reason to drop the "e" in "parameter"
> when adding the "-ized" suffix. But perhaps I'm mistaken.
>
> English is weird, and both are legal:
> http://www.merriam-webster.com/dictionary/parameterize. I've seen it
> without the 'e' more than with it, so that's the way I usually spell it
> (although I *used* to keep that e in).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ParmEd/ParmEd/issues/244#issuecomment-118882101>.
>



-- 
Hai Nguyen

**Comment by swails** [comment]
https://www.google.com/search?rlz=1C1CHMO_enUS485US485&biw=1600&bih=815&q=Parameterized+vs+parameterized&spell=1&sa=X&ei=v5iaVcbEFMjk-AHl3YCgDw&ved=0CBoQBSgA#q=parametrized

**Comment by swails** [comment]
The z-s battle notwithstanding, both spellings appear valid.  I switched to "parametrized" back in grad school since that was the more common spelling I'd seen in stuff I read.

**Comment by hainm** [comment]
ha ha, I know they are both legit. "Parametrization (or parameterization;
also parameterisation, parametrisation)" from wiki page in your link.

Personally for non-English speaker like me, I prefer "parameterized"
because it's easier to pronounce.

On Mon, Jul 6, 2015 at 11:08 AM, Jason Swails <notifications@github.com>
wrote:

>
> https://www.google.com/search?rlz=1C1CHMO_enUS485US485&biw=1600&bih=815&q=Parameterized+vs+parameterized&spell=1&sa=X&ei=v5iaVcbEFMjk-AHl3YCgDw&ved=0CBoQBSgA#q=parametrized
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ParmEd/ParmEd/issues/244#issuecomment-118884968>.
>



-- 
Hai Nguyen

**Comment by swails** [comment]
> Personally for non-English speaker like me, I prefer "parameterized"
> because it's easier to pronounce.

Huh... I would not have expected that.  Par-a-met-rized is easier for me (over Par-a-me-ter-ized).  Maybe it depends on what language you are coming from...

**Comment by swails** [comment]
Closing this, since I think it's been answered?
