### ISSUE TITLE
importing time

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#248]
This is not an issue, just FYI.

I am reducing importing time for `pytraj`, so I use `mdtraj` and `parmed` for comparison. It turns out that it took 1.6 s to import parmed in casegroup.  For `pytraj` and `mdtraj`, about 1.2 s.

(of course, 1.6 s is fast enough but this surprised me, I thought parmed is very light).

```python
haichit@casegroup ~ $ for ((i=0; i<=20; i++)); do time python -c 'import parmed'; done

real    0m1.618s
user    0m1.455s
sys     0m0.163s

real    0m1.633s
user    0m1.455s
sys     0m0.179s

real    0m1.637s
user    0m1.465s
sys     0m0.173s

real    0m1.634s
user    0m1.461s
sys     0m0.177s

real    0m1.636s
user    0m1.467s
sys     0m0.169s

real    0m1.645s
user    0m1.483s
sys     0m0.162s

real    0m1.701s
user    0m1.469s
sys     0m0.170s

real    0m1.630s
user    0m1.466s
sys     0m0.164s
....
```

```python
haichit@casegroup ~ $ for ((i=0; i<=20; i++)); do time python -c 'import pytraj'; done

real    0m1.131s
user    0m1.032s
sys     0m0.099s

real    0m1.144s
user    0m1.023s
sys     0m0.121s

real    0m1.131s
user    0m1.037s
sys     0m0.095s

real    0m1.120s
user    0m1.005s
sys     0m0.115s

real    0m1.148s
user    0m1.046s
sys     0m0.102s
```

**Comment by swails** [comment]
This would probably take longer if OpenMM was importable.  My dependencies are still small enough (even including all optional dependencies) that I'm not worried about delayed importing yet.

ParmEd also imports most of its own modules, of which there is a fair amount.  And file I/O on casegroup is *slow*.  On my desktop, ParmEd imports take 0.5s.  On casegroup, it takes 10 s.  All optional deps are installed in both places.  The filesystem layout/organization here is absolutely terrible.

**Comment by hainm** [comment]
it only take 10 ns in the first time I guess. it will be much faster that thanks to __pycache__
