### ISSUE TITLE
Wrap tleap

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#265]
I just implemented wraping tleap for pytraj. I think it is good to have some methods in parmed too. Sometimes it's very convenient to have some structure template without explicitly writting leap.in file and call tleap. Check out my recent commit and https://github.com/pytraj/pytraj/issues/523

Hai

**Comment by swails** [comment]
There's too much stuff that has to happen behind-the-scenes.  For instance, how do you handle disulfide bonds?  What about custom residues?  What about solvation?  What about protonation states and tautomers?

I think ParmEd can eventually get to the point where it can *replace* tleap, but wrapping it is not something I want to sit down and figure out how to do well.  `pdb4amber` does a lot of useful prep, and I think a useful first step would be to encapsulate that functionality into ParmEd.  I think openmoltools does a bit of this.

But at the end of the day, I know that if I added this functionality to ParmEd, I don't think I'd even use it since I speak tleap pretty well (and any wrapping I did would basically just be a translation layer between my own invented syntax and tleap, right?)

**Comment by mojyt** [comment]
As I've indicated to Jason before I'm all for moving towards getting rid of
tleap. In my opinion the leap code base is obfuscated enough at this point
that it's worth pushing towards something new. I approach fixes/additions
to leap with something akin to dread - I always have to spend at least 30
minutes reminding myself what all of those wrappers for manipulating arrays
etc in leap do.

I may be in the minority here, but I'm against anything that keeps leap
around for longer than it needs to be.

-Dan

On Mon, Jul 13, 2015 at 9:45 AM, Jason Swails <notifications@github.com>
wrote:

> There's too much stuff that has to happen behind-the-scenes. For instance,
> how do you handle disulfide bonds? What about custom residues? What about
> solvation? What about protonation states and tautomers?
>
> I think ParmEd can eventually get to the point where it can *replace*
> tleap, but wrapping it is not something I want to sit down and figure out
> how to do well. pdb4amber does a lot of useful prep, and I think a useful
> first step would be to encapsulate that functionality into ParmEd. I think
> openmoltools does a bit of this.
>
> But at the end of the day, I know that if I added this functionality to
> ParmEd, I don't think I'd even use it since I speak tleap pretty well (and
> any wrapping I did would basically just be a translation layer between my
> own invented syntax and tleap, right?)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ParmEd/ParmEd/issues/265#issuecomment-120974191>.
>



-- 
-------------------------
Daniel R. Roe, PhD
Department of Medicinal Chemistry
University of Utah
30 South 2000 East, Room 307
Salt Lake City, UT 84112-5820
http://home.chpc.utah.edu/~cheatham/
(801) 587-9652
(801) 585-6208 (Fax)

**Comment by hainm** [comment]
I agree with both of you.

**Comment by davidlmobley** [comment]
I agree with this as well. We use tleap a lot still and every time I'm
writing a Python function which writes a tleap input file I grimace. I'd
love to see it replaced by ParmEd or other modern tools which incorporate
the leap functionality but interface well with ParmEd and Python, etc.

Though there is also the issue of GUI functionality, i.e. xleap...

On Mon, Jul 13, 2015 at 9:08 AM, Daniel R. Roe <notifications@github.com>
wrote:

> As I've indicated to Jason before I'm all for moving towards getting rid of
> tleap. In my opinion the leap code base is obfuscated enough at this point
> that it's worth pushing towards something new. I approach fixes/additions
> to leap with something akin to dread - I always have to spend at least 30
> minutes reminding myself what all of those wrappers for manipulating arrays
> etc in leap do.
>
> I may be in the minority here, but I'm against anything that keeps leap
> around for longer than it needs to be.
>
> -Dan
>
> On Mon, Jul 13, 2015 at 9:45 AM, Jason Swails <notifications@github.com>
> wrote:
>
> > There's too much stuff that has to happen behind-the-scenes. For
> instance,
> > how do you handle disulfide bonds? What about custom residues? What about
> > solvation? What about protonation states and tautomers?
> >
> > I think ParmEd can eventually get to the point where it can *replace*
> > tleap, but wrapping it is not something I want to sit down and figure out
> > how to do well. pdb4amber does a lot of useful prep, and I think a useful
> > first step would be to encapsulate that functionality into ParmEd. I
> think
> > openmoltools does a bit of this.
> >
> > But at the end of the day, I know that if I added this functionality to
> > ParmEd, I don't think I'd even use it since I speak tleap pretty well
> (and
> > any wrapping I did would basically just be a translation layer between my
> > own invented syntax and tleap, right?)
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ParmEd/ParmEd/issues/265#issuecomment-120974191>.
> >
>
>
>
> --
> -------------------------
> Daniel R. Roe, PhD
> Department of Medicinal Chemistry
> University of Utah
> 30 South 2000 East, Room 307
> Salt Lake City, UT 84112-5820
> http://home.chpc.utah.edu/~cheatham/
> (801) 587-9652
> (801) 585-6208 (Fax)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ParmEd/ParmEd/issues/265#issuecomment-120982486>.
>



-- 
David Mobley
Associate Professor
Department of Pharmaceutical Sciences
Department of Chemistry
3134B Natural Sciences I
University of California, Irvine
Irvine, CA 92697
dmobley@uci.edu
work (949) 824-6383
cell (949) 385-2436

**Comment by swails** [comment]
> Though there is also the issue of GUI functionality, i.e. xleap...

Yep.  I'd thought about interfacing with chemlab for that, unless I somehow find the time to learn OpenGL well enough to write my own :).  One problem I think I'll have to address before that point is making ParmEd a bit faster, but these are concerns for another day.

**Comment by swails** [comment]
Closing this for now.  If someone needs this and submits a PR I would be receptive, but it's not something I would want added all things considered.
