### ISSUE TITLE
atom.type vs atom.atom_type?

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#266]
```python
In [19]: a.atom_type 
Out[19]: <parmed.topologyobjects.AtomType at 0x2aaacc5e2438>

In [20]: a.type
Out[20]: 'os'
```

it's kind of confusing.

**Comment by hainm** [comment]
and what's the different here?

```python
In [43]: a.element
Out[43]: 8

In [44]: a.atomic_number
Out[44]: 8
```

**Comment by swails** [comment]
`Atom.type` is the name of the atom type.  `Atom.atom_type` is an `AtomType` instance that contains a lot more information.  Different programs use different strategies for parameter assignment and such -- `atom_type` is an extension of `type` that is needed to support, for instance, how CHARMM does things.  When `Atom.type` suffices, that's all you need to worry about.  When it doesn't, that's what `atom_type` is there for.

**Comment by swails** [comment]
> and what's the different here?
> 
```Python
> In [43]: a.element
> Out[43]: 8
> 
> In [44]: a.atomic_number
> Out[44]: 8
```

Nothing.  They're aliases.

**Comment by hainm** [comment]
ack. I though "element" should be a string.

**Comment by swails** [comment]
The decision to make them aliases is one I made a long time ago when I got sick of using `atomic_number` everywhere but didn't want to change it everywhere I had already used it.

I'd personally rather replace the `periodic_table` module with something like what OpenMM and MDTraj does, and then turn `element` a reference to the corresponding `Element` instance.
