### ISSUE TITLE
load from url

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#269]
does parme support this? something like

```python
mol2 = pmd.dowload_mol2("http://q4md-forcefieldtools.org/REDDB/projects/W-73/tripos1.mol2")
```

**Comment by swails** [comment]
No, but it could be added to `genopen`.  Then it would work just as:

```Python
import parmed as pmd

mol2 = pmd.load_file('http://q4md-forcefieldtools.org/REDDB/projects/W-73/tripos1.mol2')
```

**Comment by hainm** [comment]
yeah, please add it. very convenient.

**Comment by swails** [comment]
Hm.  #279 was incomplete for this feature.

**Comment by swails** [comment]
Now this really *is* implemented.

**Comment by hainm** [comment]
@swails 

this is the reason why load from url is very convenient

```python
In [10]: t0 = pt.load_parmed(
pmd.load_file("http://ambermd.org/tutorials/advanced/tutorial1/files/polyAT.pdb"),
as_traj=True)

In [11]: t1 = pt.load_parmed(
pmd.load_file("http://ambermd.org/tutorials/advanced/tutorial1/files/fam5_leap.pdb"),
as_traj=True)

In [12]: pt.tools.merge_trajs(t0, t1)
Out[12]:
<pytraj.Trajectory with 1 frames: <Topology with 495 atoms, 1 residues, 6 mols, 542 bonds, 
non-PBC>>
```

**Comment by swails** [comment]
Wow I misread that at first.  I read "convenient" as "inconvenient". :)

Here's a suggestion, though: Why not change the signature of `pt.load_parmed` to take either a string or a `Structure`?  If it's a string, pass it to `pmd.load_file` internally.  This way people won't necessarily have to *know* ParmEd in order for them to be able to harness its capabilities in pytraj.

Or perhaps `pt.load_traj` can interpret a URL as an instruction to use ParmEd to download the file?  Just a couple thoughts.

**Comment by hainm** [comment]
yeah, you're right. I will do #1 first and think about #2 later.

**Comment by hainm** [comment]
umh, I did both

https://github.com/hainm/pytraj/commit/12f74875e6a5ac302230e84174579efec1cb92ae
