### ISSUE TITLE
better word alignment for print stuff

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#276]
I mentioned this in one of the issues but I think it's better to create a new one.

 `Atom 1               Atom 2               Atom 3               Atom 4 ` 

```python
In [9]: pmd.tools.printDihedrals(p, ':1@CA')
Out[9]:
Atom 1               Atom 2               Atom 3               Atom 4                Height     Periodic.  Phase      EEL Scale  VDW Scale
       10   OG (  OH)        7   CB (  CT)        5   CA (  CX)       12    C (   C)     0.1556     3.0000     0.0000     1.2000     2.0000
        7   CB (  CT)        5   CA (  CX)       12    C (   C)       13    O (   O)     0.0000     2.0000     0.0000     1.2000     2.0000
        7   CB (  CT)        5   CA (  CX)       12    C (   C)       14    N (   N)     0.2000     1.0000     0.0000     1.2000     2.0000
```

**Comment by swails** [comment]
Done in #279 (in particular, commits 0361ac7 and 3e6852c)

**Comment by hainm** [comment]
thx. I will try when merged.

**Comment by swails** [comment]
Fixed by #279.

**Comment by hainm** [comment]
@swails 

Look nice now. Can you tell me what are "M" and "I" in left-most column?

```python
In [3]: pmd.tools.printDihedrals(p, ':1@CA')
Out[3]:
               Atom 1               Atom 2               Atom 3               Atom 4     Height  Periodic.      Phase  EEL Scale  VDW Scale
       10   OG (  OH)        7   CB (  CT)        5   CA (  CX)       12    C (   C)     0.1556     3.0000     0.0000     1.2000     2.0000
        7   CB (  CT)        5   CA (  CX)       12    C (   C)       13    O (   O)     0.0000     2.0000     0.0000     1.2000     2.0000
        7   CB (  CT)        5   CA (  CX)       12    C (   C)       14    N (   N)     0.2000     1.0000     0.0000     1.2000     2.0000
M       7   CB (  CT)        5   CA (  CX)       12    C (   C)       14    N (   N)     0.2000     2.0000     0.0000     1.2000     2.0000
M       7   CB (  CT)        5   CA (  CX)       12    C (   C)       14    N (   N)     0.4000     3.0000     0.0000     1.2000     2.0000
M       7   CB (  CT)        5   CA (  CX)       12    C (   C)       14    N (   N)     0.0000     4.0000     0.0000     1.2000     2.0000
        5   CA (  CX)       12    C (   C)       14    N (   N)       16   CA (  CX)     2.5000     2.0000   180.0001     1.2000     2.0000
        1    N (  N3)        5   CA (  CX)        7   CB (  CT)       10   OG (  OH)     0.1556     3.0000     0.0000     1.2000     2.0000
        1    N (  N3)        5   CA (  CX)       12    C (   C)       13    O (   O)     0.0000     2.0000     0.0000     1.2000     2.0000
        1    N (  N3)        5   CA (  CX)       12    C (   C)       14    N (   N)     0.0000     2.0000     0.0000     1.2000     2.0000
I       5   CA (  CX)       14    N (   N)       12    C (   C)       13    O (   O)    10.5000     2.0000   180.0001     0.0000     0.0000
        9  HB3 (  H1)        7   CB (  CT)        5   CA (  CX)       12    C (   C)     0.1556     3.0000     0.0000     1.2000     2.0000
```

**Comment by swails** [comment]
`I` means Improper.  M means that the end-group interactions (i.e., the 1-4 interactions) are omitted.  This is usually [1] because that dihedral is one in a multi-term series (which is where the "M" comes from).  But this also occurs in 5- and 6-member ring systems for some dihedrals that have only 1 term.

Cpptraj uses the same notation, I believe, except that Dan chose "E" instead of "M".

[1] I say "usually", but that's only true in proteins where there are few rings.  In nucleic acids, every residue has many rings -- the ribose, and 1 or two on the base.  So there are probably just as many ring-omitted dihedrals as there are multi-term dihedrals.

**Comment by hainm** [comment]
thanks.

**Comment by mojyt** [comment]
On Tuesday, July 21, 2015, Jason Swails <notifications@github.com> wrote:
>
> Cpptraj uses the same notation, I believe, except that Dan chose "E"
> instead of "M".
>
Well I based it on rdparm, so blame Tom :)

> [1] I say "usually", but that's only true in proteins where there are few
> rings. In nucleic acids, every residue has many rings -- the ribose, and 1
> or two on the base. So there are probably just as many ring-omitted
> dihedrals as there are multi-term dihedrals.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ParmEd/ParmEd/issues/276#issuecomment-123504629>.
>


-- 
-------------------------
Daniel R. Roe, PhD
Department of Medicinal Chemistry
University of Utah
30 South 2000 East, Room 307
Salt Lake City, UT 84112-5820
http://home.chpc.utah.edu/~cheatham/
(801) 587-9652
(801) 585-6208 (Fax)

**Comment by swails** [comment]
"E" was a better choice in retrospect.  This was before I knew about (or at least before I really thought about/understood) the ring omissions.

Really the whole thing is a hack.  More modern MD engines (e.g., GROMACS and OpenMM -- *not* CHARMM) don't use the dihedral list as the list of nonbonded exceptions -- they are explicitly enumerated instead.  They do the equivalent of having tleap build the list of exceptions from the bond graph -- adding all atoms <= 2 bonds away into an exclusion list and all atoms at least 3 bonds away to a list of exceptions (or adjusts).  That way you don't have to play funny games like hijacking the sign bit as a flag to exclude a pair from a list and make sure that even torsions that don't need a dihedral term still have one that's zero just so the exception list is properly built...

But it's certainly too late to change that now unless someone is masochistic enough to spend their time "fixing" this :).
