### ISSUE TITLE
detect amber ff?

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#280]
Jason,

given a Amber parm file, can 'parmed' predict which forcefield(s) is(are) in that parm? :D

**Comment by swails** [comment]
Short answer: no.  However, you can dump an frcmod file that you can use to compare to the existing parameters if that helps.

Really we need tleap to print some provenance information to the prmtop file.

**Comment by hainm** [comment]
thanks. Do you want to close it or leave it open (so we can change tleap code later if ever wanted).

**Comment by swails** [comment]
Let's close it.  This isn't something that can realistically be implemented in ParmEd very easily.  One thing that makes it particularly challenging is that the standard FF definitions contain wild-card definitions for torsions and impropers that will be hard to match up with those in a particular Structure.  Add in all the processing that goes on (e.g., charge pre-scaling, L-J epsilon/sigma -> A/B-coefficients, etc.), the flexibility of LJEDIT (AKA NBFIX), and all that other crap, and *actually* doing this robustly is nearly impossible.

The most reliable way to actually do this is to compare by hand -- either dump a frcmod file and compare the terms to the various force fields to make sure that they match or parametrize the same system with known force fields until you get energies that match.

This is so hard to do, and the benefit so minimal, that it's simply only with doing by having each leaprc set the provenance information inside the prmtop file directly, and that has nothing to do with ParmEd (at least not until/if ParmEd replaces tleap, and then I can do that easily).

**Comment by hainm** [comment]
agree
