### ISSUE TITLE
A word of caution here – the multiplication operator for integers is not implemented for Structure

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#286]
Is there any reason not to implement it?

```python
>>> 20 * phenol
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for *: 'int' and 'AmberParm'
```

**Comment by davidlmobley** [comment]
You want:

phenol * 20

not

20 * phenol

This is documented.

On Wed, Jul 22, 2015 at 1:01 PM, Hai Nguyen <notifications@github.com>
wrote:

> Is there any reason not to implement it?
>
> >>> 20 * phenol
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>TypeError: unsupported operand type(s) for *: 'int' and 'AmberParm'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ParmEd/ParmEd/issues/286>.
>



-- 
David Mobley
Associate Professor
Department of Pharmaceutical Sciences
Department of Chemistry
3134B Natural Sciences I
University of California, Irvine
Irvine, CA 92697
dmobley@uci.edu
work (949) 824-6383
cell (949) 385-2436

**Comment by hainm** [comment]
@davidlmobley: Hi, I knew that. My question is *why don't implement `20 * phenol` too?*

**Comment by swails** [comment]
I don't know.  Since I didn't have a good reason to implement it, I didn't.

Speaking of which, I should probably go through and `return NotImplemented` in the existing operator overloads.
