### ISSUE TITLE
cpptraj can not recognize residue from mol2 file saved by parmed

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#287]
```python
In [1]: p = pmd.load_file("./data/tz2.pdb")

In [2]: p.residues
Out[2]:
ResidueList([
        <Residue SER[1]>
        <Residue TRP[2]>
        <Residue THR[3]>
        <Residue TRP[4]>
        <Residue GLU[5]>
        <Residue ASN[6]>
        <Residue GLY[7]>
        <Residue LYS[8]>
        <Residue TRP[9]>
        <Residue THR[10]>
        <Residue TRP[11]>
        <Residue LYS[12]>
        <Residue NME[13]>
])

In [3]: p.save("./tz2.mol2")

In [4]: top = pt.load("./tz2.mol2")

In [5]: top.residue_info()
#Res  Name First  Last Natom #Orig  #Mol
    1 ▒n▒     1   223   223     0     1
```

do @swails  and @mojyt have any comment about this?

'tz2.pdb' is here: https://github.com/pytraj/pytraj/blob/master/tests/data/tz2.pdb

**Comment by hainm** [comment]
this is saved file from parmed
https://github.com/hainm/amber_things/blob/master/tz2.mol2

**Comment by mojyt** [comment]
It seems to me that the mol2 format written out by parmed doesn't follow the TRIPOS mol2 standard (which is what cpptraj uses): http://www.tripos.com/data/support/mol2.pdf
In particular the atom_type field following the coordinates is missing:

PARMED:
       1 N           -1.8890     9.1590     7.5690               1 SER
CPPTRAJ:
      1 N          -1.8890    9.1590    7.5690 N          1 SER      0.000000

Not sure if there are some other standards out there where this field is optional. The way cpptraj handles atoms that do not have a type is to just use the atom name instead (to avoid breaking the format). Cpptraj should probably do some more error checking though.

**Comment by swails** [comment]
ParmEd *does* always write the atom type.  See [here](https://github.com/ParmEd/ParmEd/blob/master/parmed/formats/mol2.py#L446-L447).

But sometimes the atom type is the empty string.  Cpptraj needs to be fixed to recognize as a valid atom type.  See it there?  Between the "recognize" and "as"?

</joke> 

I'll fix this.  Thanks for the report.

**Comment by mojyt** [comment]
On Wednesday, July 22, 2015, Jason Swails <notifications@github.com> wrote:

> ParmEd *does* always write the atom type. See here
> <https://github.com/ParmEd/ParmEd/blob/master/parmed/formats/mol2.py#L446-L447>
> .
>
> But sometimes the atom type is the empty string.
>
> Ah, I see now. Just like how zero is a number - silly cpptraj :)

>  Cpptraj needs to be fixed to recognize as a valid atom type. See it
> there? Between the "recognize" and "as"?
>
>  I'll fix this. Thanks for the report.
>
—
> Reply to this email directly or view it on GitHub
> <https://github.com/ParmEd/ParmEd/issues/287#issuecomment-123892624>.
>


-- 
-------------------------
Daniel R. Roe, PhD
Department of Medicinal Chemistry
University of Utah
30 South 2000 East, Room 307
Salt Lake City, UT 84112-5820
http://home.chpc.utah.edu/~cheatham/
(801) 587-9652
(801) 585-6208 (Fax)
