### ISSUE TITLE
Gromacs to Amber issues

### ISSUE THREAD

**Issue by mpharrigan** [ParmEd/ParmEd#292]
I'm trying to convert an amber (prepared with leap, equilibrated in amber) system to gromacs:

```python
import parmed
from parmed.gromacs import GromacsGroFile, GromacsTopologyFile
parm = parmed.load_file("struct.prmtop", "struct.inpcrd")
GromacsGroFile.write(parm, "4bw5.gro")
top = GromacsTopologyFile.from_structure(parm)
top.write("4bw5.top")
```

It seems to work fine, but when I run `grompp` I get this warning:

```
Warning: atom name 8157 in ../4bw5.top and ../4bw5.gro does not match (K+ - C116)
Warning: atom name 8158 in ../4bw5.top and ../4bw5.gro does not match (K+ - H16R)
Warning: atom name 8159 in ../4bw5.top and ../4bw5.gro does not match (K+ - H16S)
Warning: atom name 8160 in ../4bw5.top and ../4bw5.gro does not match (K+ - H16T)
Warning: atom name 8161 in ../4bw5.top and ../4bw5.gro does not match (K+ - C115)
Warning: atom name 8162 in ../4bw5.top and ../4bw5.gro does not match (K+ - H15R)
Warning: atom name 8163 in ../4bw5.top and ../4bw5.gro does not match (K+ - H15S)
Warning: atom name 8164 in ../4bw5.top and ../4bw5.gro does not match (K+ - C114)
Warning: atom name 8165 in ../4bw5.top and ../4bw5.gro does not match (K+ - H14R)
Warning: atom name 8166 in ../4bw5.top and ../4bw5.gro does not match (K+ - H14S)
Warning: atom name 8167 in ../4bw5.top and ../4bw5.gro does not match (K+ - C113)
Warning: atom name 8168 in ../4bw5.top and ../4bw5.gro does not match (K+ - H13R)
Warning: atom name 8169 in ../4bw5.top and ../4bw5.gro does not match (K+ - H13S)
Warning: atom name 8170 in ../4bw5.top and ../4bw5.gro does not match (K+ - C112)
Warning: atom name 8171 in ../4bw5.top and ../4bw5.gro does not match (K+ - H12R)
Warning: atom name 8172 in ../4bw5.top and ../4bw5.gro does not match (K+ - H12S)
Warning: atom name 8173 in ../4bw5.top and ../4bw5.gro does not match (K+ - C111)
Warning: atom name 8174 in ../4bw5.top and ../4bw5.gro does not match (K+ - H11R)
Warning: atom name 8175 in ../4bw5.top and ../4bw5.gro does not match (K+ - H11S)
Warning: atom name 8176 in ../4bw5.top and ../4bw5.gro does not match (K+ - C110)
(more than 20 non-matching atom names)

WARNING 2 [file 4bw5.top, line 92939]:
  22055 non-matching atom names
  atom names from ../4bw5.top will be used
  atom names from ../4bw5.gro will be ignored
```

And the simulation blows up. Step 0:

![code1](https://cloud.githubusercontent.com/assets/4967059/8839201/15be931c-3088-11e5-9e5d-c3f1ad05ca6f.png)

Do you have any idea why this is happening?

**Comment by mpharrigan** [comment]
Files are here:

https://www.dropbox.com/sh/x6zkehs4k6kqvvd/AAC3l5SaetX2lI9Ixp9iyQmua?dl=0

**Comment by swails** [comment]
I think I know what's happening.  The workaround for now is to pass the `combine='all'` keyword to `top.write('4bw5.top', combine='all')`.

Basically what's happening is that Gromacs has a rather unique way of building a system -- define each molecule (complete with connectivity and parameters), and then at the end define a list of molecules with their corresponding counts representing how many of those molecules are in the system.

ParmEd runs the assumption that all molecules of the same type appear contiguously in the original `Structure`, which is not the case here.  For instance, you have like 4 or 5 `K+` residues near the beginning of the residue list and then a bunch more presumably after some lipids.  So when ParmEd splits the `Structure` into molecule definitions, it is implicitly (and incorrectly) reordering the atoms as Gromacs would understand it, but not properly reflecting this in the GRO file.  So the coordinates are no longer correctly corresponding to the correct atoms.  And chaos ensues.

The `combine='all'` keyword will combine all atoms into the same molecule definition, which will sidestep this problem, but will make things like TI and other alchemical FE methods difficult to impossible to accomplish.

I'll have to figure out how I want to fix this problem.  Thanks for the report, and let me know if the `combine='all'` keyword fixes your problems with the system blowing up.

**Comment by swails** [comment]
By the way, I've downloaded the files onto one of my computers, so if you need to take those files down from Dropbox, go ahead.

**Comment by mpharrigan** [comment]
Thanks for the prompt and informative response. I assumed the K+ ions in the middle of the protein were screwing things up.

I'll try it with `combine='all'` and report back.

**Comment by swails** [comment]
Yay! Fixed!
