### ISSUE TITLE
load_file for zip file?

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#293]
What do you think? 

it's in standard lib
https://docs.python.org/2/library/zipfile.html

**Comment by swails** [comment]
+1.  You want to submit the PR?  Or add this to my to-do list?  I may not get to it for awhile.

**Comment by hainm** [comment]
me neither (need to play with modified RNA force field stuff first). Let's put it in to-do-list.

**Comment by swails** [comment]
So there are two compression libraries here: `zlib` and `zipfile`.  The former is an old compression algorithm that I *think* is supposed to be implemented by the `compress` and `decompress` programs in Unix, and use the `.Z` suffix.  The latter is a `.zip` file that is more like a `.tar.gz` than an actual compressed file.

Quick tests with the .zip files tells me that even for a single file, the zip file will be a directory with a single file contained inside.  While I could always just assume such zip files have only a single file inside with the same name (less the `.zip` extension), this doesn't seem like a worthwhile change to make.

As for the `.Z` files, I was having a hard time getting `zlib.decompress` to recognize a file compressed with the `compress` program.  Not sure why it doesn't work, but I also don't think it's worth trying to figure out.  `gzip` and `bzip2` are *way* more common and probably a lot newer and better as well.  It's enough that ParmEd handles them -- I don't see a need for this.

**Comment by hainm** [comment]
Okie
