### ISSUE TITLE
save frcmod

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#295]
It's not clear to me how to save `frcmod` file from parm7 in API mode.

(I saw the doc here: [writeFrcmod <frcmod_name>] (http://parmed.github.io/ParmEd/html/parmed.html) and your post here http://archive.ambermd.org/201502/0462.html).

I blindly do 'p.save("test.frcmod")` but parmed raised format error.

**Comment by swails** [comment]
```Python
import parmed as pmd
p = pmd.load_file('your.prmtop')
pmd.tools.writeFrcmod(p, 'test.frcmod')
```

**Comment by hainm** [comment]
thanks. So from now, my rule of thumb will use 'pmd.tools.bla_bla' if I don't find the things I want. :D

**Comment by hainm** [comment]
@swails 
I got blank file

```python
In [21]: p
Out[21]: <AmberParm 33 atoms; 1 residues; 35 bonds; parametrized>

In [22]: pmd.tools.writeFrcmod(p, "test.frcmod")
Out[22]: <parmed.tools.actions.writeFrcmod at 0x2aaacce05860>

In [23]: cat ./test
./test.frcmod  ./test.mol2    ./test.pdb     

In [23]: cat ./test.frcmod
```

**Comment by swails** [comment]
`pmd.tools` contains all of the cpptraj-like actions in the parmed scripts.  `writeFrcmod` needs to be overhauled a little, but for the most part what it does under the hood is generate a `ParameterSet` from the `Structure`, then write that to Amber format.  The stuff in `parmed.tools` is a collection of classes that clump together a set of commands to do common tasks.

**Comment by swails** [comment]
Right, my mistake:

```Python
import parmed as pmd
p = pmd.load_file('your.prmtop')
pmd.tools.writeFrcmod(p, 'test.frcmod').execute()
```

**Comment by hainm** [comment]
thanks. Is there any reason to use extra 'execute'? (for batch job, right?)

**Comment by swails** [comment]
That's just how I designed `parmed.py` back in the day.  Modeled after cpptraj/ptraj -- you had an action setup, print (`__str__`), and `DoAction` routine.  It allows setup and execute steps to be run separately.  I probably wouldn't make the same decision again, but it will be overly painful to change, and there are a couple benefits.

**Comment by hainm** [comment]
I got the same problem (with pytraj) when designing a Python package with perspective from C++.

**Comment by swails** [comment]
Closing.  Feel free to reopen if there's unresolved issues still.

**Comment by hainm** [comment]
yes. closed.

**Comment by hainm** [comment]
have been using `pmd.tools.writeFrcmod`, really cool. Save my time a lot.
