### ISSUE TITLE
load frcmod

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#296]
I know parmed is able to parse frcmod file but the class is deeply hidden. (I tried before but could not recall).

I search `pmd.read_`, `pmd.load_`, `pmd.tools.load_`,  ... but found nothing. Is there any intention to expose the class?

**Comment by hainm** [comment]
technically, it makes sense if there is `pmd.tools.writeFrcmod` and `pmd.tools.readFrcmod`.

**Comment by swails** [comment]
> I know parmed is able to parse frcmod file but the class is deeply hidden. (I tried before but could not recall).

Actually it can't... yet.

> technically, it makes sense if there are pmd.tools.writeFrcmod and pmd.tools.readFrcmod

readFrcmod wouldn't *do* anything in the scripts, would it?

**Comment by hainm** [comment]
> Actually it can't... yet.

I remember I tried before and got a dictionary. But can not recall.

**Comment by swails** [comment]
This is implemented in #343.  frcmod files are actually autodetected, so it works with `parmed.load_file`.  Alternatively, instantiate it using `parmed.amber.AmberParameterSet('frcmod')`.  Same with regular parameter databases.  You can even load a leaprc file.

**Comment by hainm** [comment]
wow, this is quick. I though you would implement this in near future. lol. thanks. This is really cool.

**Comment by swails** [comment]
Well it's a necessary step toward replacing LEaP :)

**Comment by hainm** [comment]
it (leap) drove me crazy this two weeks.
