### ISSUE TITLE
[enhancement?] short and easy what to get/set some common values

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#298]
we did discuss here about getting bfactors (https://github.com/ParmEd/ParmEd/issues/233). And you did introduce 'to_dataframe()' to get the values.

However, I still think `parmed` should have an easy way to let user set property from an array rather than explicitly writing `for` loop. This is based on my experience. For example. atom mask output from R.E.D server is different from input PDB file. I simply just want to write a mol2 file with atom name from original PDB with new coordinates, charges ... from output from RED. 

Ideally, I just want to do this

```python
orig_pdb = pmd.load_file("orig_pdb.pdb")
red_pdb = pmd.load_file("red_pdb.pdb")
orig_pdb.coordinates = red_pdb.coordinates
org_pdb.charges = charges_from_another_gaussian_run
org_pdb.atom_names = atom_names_from_a_secret_program_output
...
org_pdb.save("my_lovely_mol.mol2")
```

(Again, everything could be solve if this is solved (ha ha). https://github.com/ParmEd/ParmEd/issues/270)

Of course, I could write my own wrapper to set those attributes, but it's for others' benefit too.

**Comment by swails** [comment]
I think this is just going to make the `Structure` object unwieldy.  This can still be done in a single line:

```Python
for atom1, atom2 in zip(orig_pdb, red_pdb): atom1.charge = atom2.charge
```

So I'm -1 on adding a new attribute on `Structure` for each attribute on `Atom`.  I'd much rather implement a `load_dataframe`, and make that capable of loading a `DataFrame` or an equivalent `dict`.  This is pretty low on my list of priorities right now, though, so if you want to give a crack at the implementation I'd be happy to help.

**Comment by swails** [comment]
Closing in favor of #270 (which I reopened)
