### ISSUE TITLE
[enhancement?] 3 to 1 letter?

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#300]
should parmed add this function to `parmed.tools`?

(below is how I get 1 letter code for RNA to feed to Curve+ program; of course this not a general solution).

```python
In [22]: "".join([res.name[0] for res in p.residues[:10]])
Out[22]: 'CCAACGUUGG'
```

**Comment by davidlmobley** [comment]
The syntax you have looks like it should give the first letter of every
residue name, which is not normally useful (i.e. ALA and ASP start with the
same letter). Am I missing something?

**Comment by hainm** [comment]
@davidlmobley yeah, I used that code for quickly get the RNA residues for my analysis, not a general code.

**Comment by davidlmobley** [comment]
I guess what I'm saying is that if you're proposing that it be included in
parmed, then it seems like it ought to be generally useful...

**Comment by hainm** [comment]
hi, sorry for my bad English. In my first sentence in 1st post, it should be `should parmed add a  function to convert 3 to 1 letter`. And the 2nd sentence should be `while waiting for that function, I need to write below code for my RNA system`. :D

**Comment by swails** [comment]
There's already some semblance of this functionality (or at least this information) in ParmEd.  See [here](https://github.com/ParmEd/ParmEd/blob/master/parmed/residue.py).  It's also not a trivial problem -- you have modified residues and each program gives slightly different names to various tautomers and protomers.  [MDTraj's mapping](https://github.com/mdtraj/mdtraj/blob/master/mdtraj/core/residue_names.py#L49-L175), for instance is... extensive.

My feeling is that this functionality would be useful for possibly interfacing with a few programs.  In that case, I think I'd rather see ParmEd interface with those programs or libraries directly.

**Comment by hainm** [comment]
yeah.

It's likely that I need to install `biopython` too.

**Comment by davidlmobley** [comment]
Also, you have the problem of ligands or cofactors for which there are no
single residue abbreviations. Or the fact that a 'C' means something
different depending on whether you are talking about a nucleic acid or a
protein, and some structures contain both. Plus, even three letter residue
names are not necessarily always unique/meaningful (i.e. I've sometimes set
up systems where I have two residues named 'MOL' which are different from
one another). There are not enough three letter combinations to cover all
possible ligands or cofactors (only 17.5k three letter combinations).

I suppose this isn't to say that it shouldn't be done, necessarily. But if
it's done it has to be done very carefully and it will be a lot of work. At
this point I'd argue it makes more sense for the end user (who knows what
their system contains) to take care of this if it needs to be done.

**Comment by hainm** [comment]
thanks.

so I guess there should be a function like this `3_to_1(residue_array, residue_dict)`

**Comment by swails** [comment]
> There are not enough three letter combinations to cover all
> possible ligands or cofactors (only 17.5k three letter combinations).

Since I love picking nits, the PDB uses numbers in addition to letters, so the number of 3-letter combos sits at just over 46.6k.

It's still not enough combos for everything, but components.cif *does* define a lot of 1-letter abbreviations (that's where the MDTraj list came from).

But I agree with you, this problem is not well-defined enough often enough to make implementing a solution in ParmEd worthwhile.  The data in `residues.py` adds some well-defined convenience functions, but often enough, people will need to implement their own 3-to-1 function, regardless of whatever implementation is chosen for ParmEd.
