### ISSUE TITLE
parsing pdb file is 5 times slower than parsing parm7

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#306]
FYI

```python
In [9]: p0 = pmd.load_file("./data/tz2.pdb")

In [10]: p0
Out[10]: <Structure 5293 atoms; 1704 residues; 0 bonds; PBC (orthogonal); NOT parametrized>

In [11]: p1 = pmd.load_file("./data/tz2.ortho.parm7")

In [12]: p1
Out[12]: <AmberParm 5293 atoms; 1704 residues; 5300 bonds; PBC (orthogonal); parametrized>

In [13]: %timeit p0 = pmd.load_file("./data/tz2.pdb")
1 loops, best of 3: 2.23 s per loop

In [14]: %timeit p1 = pmd.load_file("./data/tz2.ortho.parm7")
1 loops, best of 3: 447 ms per loop
```

this is (perhap) closely related to #219

**Comment by hainm** [comment]
the files are here: https://github.com/pytraj/pytraj/tree/master/tests/data

**Comment by swails** [comment]
I'm OK with this.  That PDB is a 10-frame trajectory, which is ~8x slower than parsing a single-frame PDB.

```Python
In [2]: %timeit pmd.load_file('tz2.pdb.1')
1 loops, best of 3: 844 ms per loop

In [3]: %timeit pmd.load_file('1frame.pdb')
10 loops, best of 3: 111 ms per loop

In [5]: %timeit pmd.load_file('tz2.truncoct.parm7')
1 loops, best of 3: 210 ms per loop
```

Trajectory processing is not a main goal for ParmEd (and PDB is a stupid format to use for trajectory storage ;)), so I'm OK with a pure-Python PDB parser only being twice as fast as a C++-optimized prmtop parser.

**Comment by hainm** [comment]
Uhm. I though parmed only read 1st frame coords?

Hai

**Comment by swails** [comment]
Nope

```Python
In [1]: import parmed as pmd

In [2]: p = pmd.load_file('tz2.pdb.1')

In [3]: p.get_coordinates('all').shape
Out[3]: (10, 5293, 3)
```

It does all of them.  I wanted a way of extracting different conformers in an NMR ensemble.

**Comment by hainm** [comment]
thanks. I always use 'coordinates' so I don't about this.

**Comment by hainm** [comment]
what's about `p.get_coordinates()` to return all coordinates? Too implicit?

**Comment by swails** [comment]
> what's about p.get_coordinates() to return all coordinates? Too implicit?

That's already how it works.

```Python
In [1]: import parmed as pmd

In [2]: p = pmd.load_file('tz2.pdb.1')

In [3]: p.get_coordinates().shape
Out[3]: (10, 5293, 3)
```

**Comment by hainm** [comment]
oh, I see.

**Comment by swails** [comment]
The PDB parser is also not optimized (there is a lot of branching in the parsing loop).  There's certainly room for improvement even in pure Python if it becomes important for something (or we can go to C/C++ for even more).  But not until then.

**Comment by hainm** [comment]
is there any quick way to only load only 1st frame? just for curiosity.

**Comment by swails** [comment]
No.
