### ISSUE TITLE
download Theoretical Model pdb: error

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#310]
```python
In [9]: pdb_parmed = pmd.download_PDB("1MMH")
```

there are bunch of errors but this is the key error
`OSError: Could not retrieve PDB ID 1mmh; 550 Can't open /pub/pdb/data/structures/divided/pdb/mm/pdb1mmh.ent.gz: No such file or directory
`

It's fine with pytraj (due to different implementation)
```python
In [10]: pdb = pt.load_pdb_rcsb("1MMH")

In [11]: pdb
Out[11]:
<pytraj.Trajectory with 1 frames: 
<Topology with 1623 atoms, 209 residues, 8 mols, 1664 bonds, non-PBC>>
```

1MMH: http://www.rcsb.org/pdb/files/1mmh.pdb

**Comment by swails** [comment]
Hmm...  It seems that the PDB isn't particularly fond of theoretical models: http://www.rcsb.org/pdb/static.do?p=download/theoretical_models/index.html

> As of October 15, 2006, PDB depositions have been restricted to atomic coordinates that are substantially determined by experimental measurements on specimens containing biological macromolecules. Thus, theoretical model depositions (such as models determined purely in silico using, for example, homology or ab initio methods) will no longer be accepted.

And they've all been moved off to "the shed out back" (along with a bunch of "obsolete" models, like 116L, which has been superseded by 216L).  I can add an option to search for obsolete models as well.

**Comment by hainm** [comment]
Oh really. So i think it is not worth to implement.

Hai
