### ISSUE TITLE
Validation of AmberTools15 --> OpenMM converted force field files

### ISSUE THREAD

**Issue by rafwiewiora** [ParmEd/ParmEd#312]
Moving the issue from pandegroup/openmm#1054 here and tagging @swails and @jchodera. 

So here's the plan: we start with the force field files that come with AmberTools15 - that's .lib, .off, .dat and frcmod. files and convert them with http://git.io/vYF7h to the .xml format compatible with OpenMM. 

Following that we want to validate the conversion with the ParmEd scripts by comparing the Amberff- and OpenMMff-generated energies - any luck digging those up @swails ?

**Comment by swails** [comment]
OK, so my validation script for the GB changes that you referenced in the last issue had to do with comparing Amber, OpenMM, and the OMM PR energies and forces all using the same topology file.

What you're trying to do here is a little different -- you're trying to get the energy and forces from `ForceField` and compare that with the energy and forces from a prmtop file.

The way you should set up for this is to go to tleap, load your PDB file, and save a new PDB file and topology file (to get all of the added atoms in the same place for both the Amber system and PDB file you feed to OpenMM).  Then you can do one of two things:

1. Compute the energy and forces using the prmtop file with OpenMM and compare to the energy and forces you get using `ForceField` on the PDB file
2. Compute the energy and forces using the prmtop file with sander and compare to the energy and forces you get using `ForceField` on the PDB file

(You can actually also use ParmEd to convert the `Topology` and `System` to an Amber topology file and use sander to compute that energy as well, if you wanted to go that route).

In any case, I don't have any scripts specifically doing any of those.

**Comment by swails** [comment]
If you want to do energy/force calculations with sander, I can give you a short example using the sander API directly in Python if you want.

**Comment by jchodera** [comment]
Yes please!

**Comment by rafwiewiora** [comment]
What John said, thanks a lot @swails!

**Comment by swails** [comment]
Assuming the "Yes please" was in response to an example using the sander API, here it is:

```Python
import sander

# Using gas-phase calculations
inp = sander.gas_input()
with sander.setup('prmtop', 'inpcrd', box=None, mm_options=inp):
    e, f = sander.energy_forces()
```

And that's it.  `e` is a struct of energy components.  The total energy is `e.tot`.  Other relevant quantities are `e.bond`, `e.angle`, `e.dihedral`, `e.elec`, `e.elec_14`, `e.vdw`, and `e.vdw_14`.  The force array is a natom*3-length list of forces in kcal/mol/A.

**Comment by swails** [comment]
This interacts well with ParmEd (i.e., you can use ParmEd AmberParm and coordinate file objects), but the version from AmberTools 15 only plays nicely with ParmEd from AmberTools 15.  The Github version has changed so much that only the developmental version of the sander API works. (I can give you the `__init__.py` file with the changes necessary to make the sander API work with ParmEd from Github if you want, but just passing filenames works as well).

**Comment by swails** [comment]
I think this has been largely superseded by #486
