### ISSUE TITLE
add overwrite=True/False

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#314]
to avoid accidentally overwrite existing data.

**Comment by swails** [comment]
Where?

**Comment by hainm** [comment]
save

On Wednesday, July 29, 2015, Jason Swails <notifications@github.com> wrote:

> Where?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ParmEd/ParmEd/issues/314#issuecomment-126014212>.
>


-- 
Hai Nguyen

**Comment by swails** [comment]
`Structure.save`?  That's a convenience function, so may make sense there.

**Comment by hainm** [comment]
Or any where you 'write' to disk.

On Wednesday, July 29, 2015, Hai Nguyen <hainm.comp@gmail.com> wrote:

> save
>
> On Wednesday, July 29, 2015, Jason Swails <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> Where?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ParmEd/ParmEd/issues/314#issuecomment-126014212>.
>>
>
>
> --
> Hai Nguyen
>
>

-- 
Hai Nguyen

**Comment by swails** [comment]
That's a lot of places.  I think doing it in the convenience functions is enough.

**Comment by hainm** [comment]
Agree. Just add to the methods that expose to end-user. We should be
critical about 'save' since it is easy to blow unbackup data.

On Wednesday, July 29, 2015, Jason Swails <notifications@github.com> wrote:

> That's a lot of places. I think doing it in the convenience functions is
> enough.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ParmEd/ParmEd/issues/314#issuecomment-126015549>.
>


-- 
Hai Nguyen
