### ISSUE TITLE
add bonds and bond related questions

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#315]
Jason,

I downloaded a pdb file
```python
p = pmd.download_PDB("2lho")
```
and tried to `p.split()` and got IndexError. I guess this is due to no bond info.

So is there any way to update bonds in one line? For example I can feed bond array from `pytraj` to parmed.
(cpptraj' guess)

```python
p.add_bonds(traj.top.bond_indices)
```
(lol, the question again comes back to `from_dataframe` issue).

Hai

**Comment by hainm** [comment]
uhm, I think should close this issue.

**Comment by swails** [comment]
This isn't actually a `from_dataframe` issue.  You're right, it's the lack of bonds (which means that there *are* no molecules).  I should probably add a check for the existence of bonds before allowing split to run.
