### ISSUE TITLE
author vs journal_authors

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#316]
I am not sure I understand the difference

```python
In [63]: p = pmd.download_PDB("3sv3")

In [64]: p.journal_authors
Out[64]: 'K.BETZ,D.A.MALYSHEV,T.LAVERGNE,W.WELTE,K.DIEDERICHS,T.J.DWYER,P.ORDOUKHANIAN,F.E.ROMESBERG,A.MARX'

In [65]: p.authors
Out[65]: 'K.BETZ,K.DIEDERICHS,A.MARX'
```

**Comment by swails** [comment]
`authors` is in the `AUTHOR` record ([example here](https://github.com/ParmEd/ParmEd/blob/master/test/files/4lzt.pdb#L17-L18)). `journal_authors` is the entry under the `JRNL` record, `AUTH` subsection ([example here](https://github.com/ParmEd/ParmEd/blob/master/test/files/4lzt.pdb#L22-L23)).

I don't remember the difference (I don't remember if the PDB spec actually says what it is, either).

**Comment by hainm** [comment]
thanks.

**Comment by swails** [comment]
So I think the consensus is "I don't know; I do it because the PDB does it" :)

**Comment by hainm** [comment]
fair enough.
