### ISSUE TITLE
Gromacs combine='all' doesn't write [ molecules ] section

### ISSUE THREAD

**Issue by mpharrigan** [ParmEd/ParmEd#324]
continuing #292 

The solution in #299 works wonderfully for modern gromacs, but folding@home is sadly on 4.5.3. This version of mdrun segfaults using the topologies generated from #299 when using gromacs "threads" or mpi. It works for single-core runs. It works on gromacs 5.0.5 under large mpi parallelization

So I tried to use the `combine='all'` suggestion as mentioned in #292. The topology files that are written out do not contain the `[ molecules ]` directive and `grompp` exits with a fatal error.

I added this to the bottom of my top file manually

```
[ system ]
my fun system name

[ molecules ]
system 1
```

and it grompped happily. It runs under 4.5.3 (gromacs threading)

**Comment by swails** [comment]
I see the problem.  Should be an easy fix.

Thanks for the report!

**Comment by swails** [comment]
Let me know if this is fixed.

**Comment by mpharrigan** [comment]
Thanks. looks good
