### ISSUE TITLE
AttributeError: 'Atom' object has no attribute 'connections'

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#329]
I got above error when loading mol2 file generated by R.E.D server

this file is here
https://github.com/hainm/pytraj/blob/master/tests/data/m2-c1_f3.mol2

(cpptraj can read this file without any problem)

**Comment by davidlmobley** [comment]
Have you checked that this is a valid mol2 file? Often people violate
format specifications which causes problems. i.e. the question is, is this
a problem with ParmEd, or with RED's mol2 files?

**Comment by hainm** [comment]
@davidlmobley I have not checked yet, but I am making assumption that this file is good (generated from RED + `cpptraj` (workhorse of amber for data analysis) can read it. (of course, `cpptraj` need less information from mol2 file than parmed does).

**Comment by davidlmobley** [comment]
Hah. You're more optimistic than I am. "Readable" and "consistent with
format specifications" are often not at all the same thing. :) That said, I
did just verify that OpenEye's OEChem can read it, and apparently print out
the bond tree. So I think it's good.

Thanks.

**Comment by hainm** [comment]
@davidlmobley hah, just because I am too lazy. :P

**Comment by swails** [comment]
So this is actually a "mol3" file -- it has extra information about the head/tail atoms for a residue template.  cpptraj ignores this information (as does OEChem, most likely).  The only programs that I know of that actually reads the extra Mol3 sections added by the R.E.D. authors is R.E.D., tleap, and ParmEd (well, if it didn't error, anyway).

I found the fix and it's pretty easy.  Thanks for the report.

**Comment by hainm** [comment]
ah yes. It's mol3.
