### ISSUE TITLE
amber atom types

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#339]
Jason,

does `parmed` have amber atom type info? I look at doc + inspect in ipython but can't not find anything.

The idea is to look at description of amber atom type without opening amber's website

http://www.quimica.urv.es/~bo/MOLMOD/General/Forcefields/AMBER.html#AAT

something likes

```python
hydrogen_types = {
'H' : 
'amide or imino hydrogen',
'HC':
'explicit hydrogen attached to carbon'
...
}
```

**Comment by swails** [comment]
No it doesn't.  It doesn't read Amber parameter files yet, either.  There's a lyx doc in the amber repository with this information if you wanted it.

**Comment by hainm** [comment]
thanks. Do you want to close or leave it open?

**Comment by swails** [comment]
Let's close it.  It's not really on my radar.  If I need it for something and see a good way of supporting it (in general, for all packages), I'll do that.  But until the need presents, I'm not going to think about it.
