### ISSUE TITLE
Automatic bond determination in PDB and mm/CIF parsing.

### ISSUE THREAD

**Issue by swails** [ParmEd/ParmEd#34]
It would be nice to have some kind of automatic bond determination.  This should come, ideally, from residue template libraries if available, and then basic bond-by-distance if the non-standard residue is unavailable.

It might be nice to add the 'components.cif' file from the PDB somewhere to significantly expand the number of residues for which we have a known bonding pattern.

**Comment by swails** [comment]
Also, the `CONECT` records should be read in PDBs

**Comment by davidlmobley** [comment]
While this is fine for proteins, it will need to get a lot more complicated for ligands/hetero atoms or you may just not want to deal with it at all in that case. It's not uncommon for these to get refined with somewhat strained bond distances so inferring bond types for ligands can be tricky. The best solutions I've seen also use local geometry (i.e. bond angles and configuration, i.e. tetrahedral/etc.), and even those sometimes go wrong. The challenge is in part that you don't always know what compound you're dealing with (in terms of protonation state/bond types) and so sometimes you have to guess this based on the geometry you're provided.

**Comment by swails** [comment]
My plan is to treat this the same way that LEaP does (and I presume Gromacs as well): bonds are determined from templates (the `ResidueTemplate` object defined in the `modeling` package).  I'll add templates for the standard residues (amino and nucleic acids) and assign bonds from those.

Ligand(/non-standard residue) bonds I can handle a number of ways:

- Assign from distances (with the caveats you mentioned)
- Do nothing (but respect `CONECT` records, which in RCSB-downloaded PDB files should specify all of the bonds)
- Optionally go to the wwPDB, download the chemical component CIF file, create a ResidueTemplate from that, and assign bonds that way.

I might also go ahead and survey the PDB to pull out the most common chemical components and create ResidueTemplates for those.

It won't work for everything, but it will work for a lot.

**Comment by hainm** [comment]
+1 for guess_bond. cpptraj does has it.

```python
In [5]: pdb = io.loadpdb_rcsb("1o15")

In [6]: pdb
Out[6]:
<pytraj.Trajectory with 1 frames: <Topology with 2 mols, 34 residues, 1086 atoms, 
1170 bonds, PBC with box type = ortho>>
```

`parmed`
```python
In [2]: t = pmd.download_PDB("1o15")

In [3]: t
Out[3]: <Structure 1086 atoms; 34 residues; 0 bonds; PBC; NOT parametrized>
```

**Comment by swails** [comment]
distance-based bonds are a last resort IMO (I'll probably have it as an option that can be turned on, but is off by default).  And residues that have pre-defined templates will *always* have those templates used first.

I could also download the component CIF file if available and build a custom residue template on-the-fly that way...

**Comment by swails** [comment]
This is finally done in #668
