### ISSUE TITLE
auto run doc

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#340]
I am thinking about getting output for pytraj's doc on-the-fly by using ipython. It might be good for parmed too.

for example

```
.. ipython::
struct = load_file('4LZT.cif')
struct
```

vs

```python
[place holder] by atom index::
    >>> struct = load_file('4LZT.cif') # use the 4LZT.cif file in test/files/
    >>> struct
    <Structure 1164 atoms; 274 residues; 0 bonds; PBC; NOT parametrized>
    >>> struct[0]
    <Atom N [0]; In LYS 0>
```

check the pandas guide:
http://pandas.pydata.org/pandas-docs/version/0.15.2/contributing.html#building-the-documentation
`This directive lets you put code in the documentation which will be run during the doc build.`

**Comment by swails** [comment]
neat.  I don't have importable tests, though, so I'm not sure how easy this will be to make it work...

**Comment by hainm** [comment]
I don't think you need to include all data for all examples in website (for example: running openmm simulation). Just add as much as you like (pdb file, cif, ...). You might want to change a tiny output in the future and it's pain to manually update your docs.

pandas does heavy lifting but it includes several files in its docs too. check `pandas/doc/data`

**Comment by hainm** [comment]
>I don't have importable tests

wait,  but you have all the files in test folder. When building the docs (locally), you just need 'make html', right?

**Comment by swails** [comment]
> wait, but you have all the files in test folder. When building the docs (locally), you just need 'make html', right?

But that doesn't go out and look for the test files.  It makes the HTML files, but it doesn't run any of the code in the documentation.

**Comment by hainm** [comment]
ha ha. you need to correctly set it up. (I don't know yet). pandas is a good start to look at.

**Comment by hainm** [comment]
I just tried and it's incredibly easy and really cool. You should check it out, man.

just copied `pandas/doc/sphinxext/` to our 'doc' folder

add (and modify) this (from pandas conf.py)
```
sys.path.extend([

    # numpy standard doc extensions
    os.path.join(os.path.dirname(__file__),
                 '..', '../..',
                 'sphinxext')

])
```

replace the old extension by below (might need to modify a bit)
```
# ones.
extensions = ['sphinx.ext.autodoc',
              'sphinx.ext.autosummary',
              'sphinx.ext.doctest',
              'sphinx.ext.extlinks',
              'sphinx.ext.todo',
              'numpydoc', # used to parse numpy-style docstrings for autodoc
              'ipython_sphinxext.ipython_directive',
              'ipython_sphinxext.ipython_console_highlighting',
              'sphinx.ext.intersphinx',
              'sphinx.ext.coverage',
              'sphinx.ext.pngmath',
              'sphinx.ext.ifconfig',
              ]
```

then in all doc, we just need to

```
.. ipython:: python
    import parmed as pmd
    p = pmd.load_file('test.pdb')
    print(p)
```

**Comment by hainm** [comment]
It's been for a year now. So close it.
