### ISSUE TITLE
add format='same' (or another word)

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#344]
this one does not work

```python
pmd.load_file(fname).save('test')
```
`ValueError: Could not determine file type of test`

This function (if exist) would be good for cpptraj/pytraj (and others) since they detect file by content.

```python
parm.save('test')
pt.load_topology('test')
```

The point here is: sometimes we don't want `parmed` to convert from one to another format and we (user) don't want to use 'if then else` or dict to map the format by our self.

**Comment by swails** [comment]
Won't work:

```Python
>>> import parmed as pmd
>>> pmd.download_PDB('4lzt')
<Structure 1164 atoms; 274 residues; 0 bonds; PBC (triclinic); NOT parametrized>
>>> pmd.download_CIF('4lzt')
<Structure 1164 atoms; 274 residues; 0 bonds; PBC (triclinic); NOT parametrized>
```

Same with GRO and Mol2 files as well.  Those are static parsing classes that return a `Structure` -- there's no way to know the file type of the original file.  The only ones that you *can* tell are `AmberParm`, `CharmmPsfFile`, and `GromacsTopologyFile`.  That's less than half of the formats ParmEd supports.

**Comment by hainm** [comment]
so if I only need to use parm as template for pytraj's Topology (don't need about coords), what's format you suggest (mol2?) I want to use `.pdb` but got atom attribute error if there is no coords (if I recall correctly).

```
parm.save('test.ext', format='from_Jason_suggestion')
pt.load_topology('test.ext')
```

**Comment by swails** [comment]
I would suggest PSF.

**Comment by hainm** [comment]
Thanks
