### ISSUE TITLE
[website] add index page

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#351]
Just like this

http://amber-md.github.io/pytraj/doc/build/html/genindex.html

**Comment by swails** [comment]
There is already https://parmed.github.io/ParmEd/html/genindex.html

**Comment by hainm** [comment]
But not shown up in main page yet

Hai

**Comment by swails** [comment]
> But not shown up in main page yet

Sure it is.  Top right:

<img width="1537" alt="screen shot 2015-08-14 at 9 10 07 pm" src="https://cloud.githubusercontent.com/assets/779022/9286782/b3d2b36e-42c9-11e5-9aef-5871389994fc.png">

**Comment by swails** [comment]
It's there in your pytraj site as well (although you also put a link to it at the bottom).  This is a common theme, so I'm happy just leaving it at its default.

**Comment by hainm** [comment]
Okie

**Comment by hainm** [comment]
I really should upgrade to iphone 6+ for bigger screen. :))
