### ISSUE TITLE
[wishlist] add 'TER' keyword with `save` to pdb

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#355]
In [3]: p = pmd.download_PDB('3gx5')

In [4]: p
Out[4]: <Structure 2193 atoms; 207 residues; 0 bonds; PBC (orthogonal); NOT parametrized>

In [7]: p0 = p['(!:K)&(!:MG)&(!:SAM)']

In [8]: set([res.name for res in p0.residues])
Out[8]: {'A', 'C', 'G', 'HOH', 'U'}

In [9]: p0.save('3gx5_only_nuc_and_hoh.pdb')

`cpptraj` has 'TER' keyword when saving pdb file (life below)
```
ATOM   2051  O   HOH A 115       3.578  -2.703   8.282  1.00 56.04           O
TER    2052      HOH A 115
ATOM   2052  O   HOH A 116      24.458 -10.733  23.188  1.00 51.39           O
TER    2053      HOH A 116
ATOM   2053  O   HOH A 117       0.118 -19.394   5.378  1.00 79.30           O
```

**Comment by hainm** [comment]
if not having 'TER': tleap will give wrong charge.

**Comment by swails** [comment]
I know.  I really want this to wait on #34, though to make sure it's as close as I can get it to the actual PDB standard (basically equivalent to cpptraj's `terbyres` keyword).

**Comment by hainm** [comment]
what do you think about adding option to add 'TER' keyword between specific residues?

**Comment by hainm** [comment]
ok, I found myself `res.ter = True`
