### ISSUE TITLE
triclinic vs truncoct

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#357]
cpptraj uses `truncoct` while parmed use `triclinic` word. What's your opinion?

@swails  @drroe

```python
In [7]: p = pmd.load_file('./C2Me_GC.prmtop')

In [8]: p
Out[8]: <AmberParm 27350 atoms; 8788 residues; 27402 bonds; PBC (triclinic); parametrized>

In [9]: top = pt.load_topology(p.__str__())

In [10]: top
Out[10]: <Topology: 27350 atoms, 8788 residues, 8756 mols, PBC with box type = truncoct>
```

**Comment by drroe** [comment]
Triclinic is a general case, 'truncoct' is a specific case. A general triclinic cell that is not truncated octahedron (angles 109.47 I think) or rhombic dodecahedron (a,b,g = 60,90,60 I think) is referred to simply as "non-orthogonal" by cpptraj.

**Comment by hainm** [comment]
so I think parmed should be more specific (at least for amber community). It's good to inspect topology generated from tleap by parmed.

**Comment by swails** [comment]
tleap supports two box types: a truncated octahedron and an orthorhombic cell.  Orthorhombic cells are, like truncated octahedrons (and any other periodic tessellating shape), a special-case of a triclinic cell.  But it is a special case that is *actually* special.  It is the only unit cell shape in which the most spherical imaging scheme is the same as the triclinic imaging scheme (in cpptraj language, `image familiar` is exactly equivalent to `image`) and the matrix that takes you to fractional coordinates is diagonal.  This allows you to simplify a lot of PBC code.  Unless I'm mistaken, all other shapes follow the same code path for minimum image distances and imaging.

And it's also the case that for many shapes, there are multiple, degenerate triclinic shapes that represent the same unit cell.  For example, OpenMM and Gromacs use a "reduced" form for unit cell vectors.  As Dan pointed out, a rhombic dodecahedron has angles 90, 60, and 90.  But OpenMM and Gromacs doesn't work with those angles -- you need to make the second angle 120 (which is an exactly equivalent representation of the unit cell).

The only time I've seen people care about the difference between the exact shape of the triclinic cell is for crystal simulations.  And I think the majority of those are neither trunc. octahedron *or* rhombic dodecahedron, so I didn't think distinctions beyond ortho/non-ortho mattered.

**Comment by hainm** [comment]
ok. I see. I spent too much time with implicit solvent. It's time to move on. :D
