### ISSUE TITLE
could not load pdb from `reduce` program

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#359]
Hi

I got this error with `parmed SAM_addH.pdb`

`parmed.tools.exceptions.ParmError: Could not determine file type of SAM_addH.pdb`

This is how I got original ligand file

```python
import parmed as pmd

p = pmd.download_PDB('3gx5')
p[':SAM'].save('SAM.pdb')
```

then using `reduce` to get `SAM_addH.pdb`
```bash
$AMBERHOME/bin/reduce $pdbname.pdb > ${pdbname}_addH.pdb
```

all files are here: https://github.com/hainm/fftools/tree/master/sam

**notes** both cpptraj and parmed don't recognize the pdb file but vmd can.

**Comment by swails** [comment]
Yea, because `reduce` adds `USER  ` records, which are *not* a valid PDB record.  `reduce` sucks that way.

**Comment by hainm** [comment]
@swails @drroe: so I just don't use `reduce`, right? alternatively, I just use `gaussview` since both parmed and cpptraj can read the H-added pdb file.

**Comment by swails** [comment]
`reduce` sucks in that one way :) (and in a couple others, really, but overall it's good at what it does).  I'll fix ParmEd and cpptraj to work for `reduce`-generated PDB files.

**Comment by hainm** [comment]
cool

**Comment by swails** [comment]
See #360.
