### ISSUE TITLE
[wishlist] add resmap, atom_map, ...?

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#365]
`parm.save('test.pdb', resmap='AF2:RA')`

(of course I can use if ... else to change residue name but it's nice to that in parmed)

from [amber mails] (https://www.google.com/search?q=OP1+does+not+have+a+type&oq=OP1+does+not+have+a+type&aqs=chrome..69i57.3632j0j7&sourceid=chrome&espv=2&es_sm=121&ie=UTF-8#q=does+not+have+a+type+amber)

and from my own experience. 

similar to tleap: 
http://ambermd.org/doc6/html/AMBER-sh-5.9.html 
(addPdbResMap, ...)

**Comment by swails** [comment]
-1

I could imagine an argument requesting name regularization to PDB standards (e.g., ASH -> ASP, C3 -> C, ... etc.), but this proposal adds unnecessary complexity IMO.

If someone wants to change all AF2 residues to RA, they can do something like this:

```Python
for residue in struct.residues:
    if residue.name == 'AF2': residue.name = 'RA'
    # Any other substitutions
```

It's not worth the additional API complexity IMO.

**Comment by hainm** [comment]
agree. May be I just make another package, like 'ptools' built on top of ParmEd to have some ready-to-use functions. 

In the future, if some methods are useful, we can merge back to parmed.
