### ISSUE TITLE
update how to make doc

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#371]
can you update some where (great if update in website) how to make parmed doc?

for pytraj, user just needs

```bash
git checkout gh-pages
cd doc 
make html
```

**Comment by hainm** [comment]
I again strongly encourage you to write 1 page about developer guide. 

For example, how to write a good test code in parmed (follow ParmEd's style). Just need few bullet points so both commiter and you don't need to spend time discuss about this.

The motivation is: encourage people to contribute small code (just bug fix, add more test case, ...)

(or just simply open an issue and wait for Jason to make it done :p).

**Comment by swails** [comment]
For the time being, I'm the only one who can update the docs online.  What I do is set a new working directory, `gh-pages/` in the ParmEd git repo, doing the following:

```bash
bash$ git clone git@github.com:/swails/ParmEd.git # Use your own fork
Cloning into 'ParmEd'...
remote: Counting objects: 8453, done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 8453 (delta 15), reused 0 (delta 0), pack-reused 8421
Receiving objects: 100% (8453/8453), 27.83 MiB | 2.97 MiB/s, done.
Resolving deltas: 100% (6106/6106), done.
Checking connectivity... done.

bash$ cd ParmEd

bash$ mkdir gh-pages

bash$ /opt/local/share/git/contrib/workdir/git-new-workdir . gh-pages # Might be somewhere else
Your branch is up-to-date with 'origin/master'.

bash$ cd gh-pages # This is now a new copy of the master branch

bash$ git checkout gh-pages # Change to the webpage branch

bash$ cd ../doc

bash$ make html # This updates the website in gh-pages
[snip lots of output]

bash$ cd ../gh-pages

bash$ git add .

bash$ git commit -m "update docs"

bash$ git push
```

By default, the docs install to `ParmEd/gh-pages`, so you can just create that directory and run `make html` to see how the pages render (but again, only I can push to ParmEd/ParmEd/gh-pages).

**Comment by swails** [comment]
BTW, here is where I got that recipe: http://raxcloud.blogspot.com/2013/02/documenting-python-code-using-sphinx.html

**Comment by hainm** [comment]
> (but again, only I can push to ParmEd/ParmEd/gh-pages).

uhm, but we can still PR to gh-pages, right?

**Comment by hainm** [comment]
oh, wait. the gh-pages is from your account 'swails', not from 'ParmEd/ParmEd'. nmv about above comment.

**Comment by hainm** [comment]
ideally, we can

```bash
git clone https://github.com/ParmEd/ParmEd
cd ParmEd
git checkout gh-pages
git chec
cd doc
# make change
```

**Comment by swails** [comment]
> uhm, but we can still PR to gh-pages, right?

Sure, but I'll probably close the PR and just push updates directly :).  The contents of that branch are auto-generated by `make html` in the doc directory, so I don't see the point of going through the whole PR thing.

> oh, wait. the gh-pages is from your account 'swails', not from 'ParmEd/ParmEd'.

Actually the gh-pages is only on ParmEd/ParmEd, and that's what I push directly to.  Updates to the docs should go in the `doc` folder as PRs into master.  I'll run `make html; ...; git push upstream/gh-pages` following doc updates.

**Comment by hainm** [comment]
> Sure, but I'll probably close the PR and just push updates directly :). The contents of that branch are auto-generated by make html in the doc directory, so I don't see the point of going through the whole PR thing.

I agree. So just PR for rst file and let Jason do the html.

**Comment by swails** [comment]
> I agree. So just PR for rst file and let Jason do the html.

That's what I do for now.

**Comment by hainm** [comment]
I've been trying to make doc for ParmEd from Parmed/Parmed. It turned out that I need to clone your personal repo. Is it right?
