### ISSUE TITLE
clean before cut release?

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#372]
since you're going to cut an official release soon. Should you spend a bit time to clean parmed a bit, such as 'coords', 'vels', ... or leave it to v3.0?

I mentioned this before

```python
In [41]: p.has
p.has_1012   p.has_NBFIX  p.has_cmap   p.hasbox     p.hasvels
```

want me to make a PR?

**Comment by swails** [comment]
Some of those are actually necessary -- `has_1012` is necessary, as is `has_NBFIX` and `has_cmap`.  `hasbox` and `hasvels` are equivalent to `s.box is None` and `s.vels is None`

**Comment by hainm** [comment]
oh no, I meant 'hasbox' --> 'has_box', 'hasvels' --> 'has_velocities' (vels is deprecated, right?)

**Comment by hainm** [comment]
I think it's better to make things consistent. I've had hard time with tleap, like 'saveOff' vs 'saveoff'.

**Comment by swails** [comment]
LEaP is case-insensitive.  `saveOFF` is the same as `saveoff`... etc.

**Comment by swails** [comment]
`hasbox` and `hasvels` is basically deprecated for ParmEd.  So either get rid of them altogether or leave them for the time being, IMO.

**Comment by hainm** [comment]
> hasbox and hasvels is basically deprecated for ParmEd. So either get rid of them altogether or leave them for the time being, IMO.

so just get rid of them.

> LEaP is case-insensitive. saveOFF is the same as saveoff... etc.

yeah, this is my confusion (although I've using it but just forget if not touch it for a while). Different people  have different ways to write leap.in

**Comment by swails** [comment]
I think case-insensitivity is the easiest to remember.  The ParmEd interpreter is actually case-insensitive (for commands only)

**Comment by hainm** [comment]
I should buy a Mac.

**Comment by swails** [comment]
This should wait for after the release.

**Comment by swails** [comment]
> I should buy a Mac.

I'm not sure if this comment was directly related to this conversation, but this is Mac-independent.  Mac filesystems are (by default) case-aware, but case-insensitive... but that refers to file names, only.  Case-insensitivity in an interpreter is unrelated to the case-sensitivity of the underlying filesystem.
