### ISSUE TITLE
parmed and cpptraj can not load cif file in xray folder

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#373]
$AMBERHOME/test/xray/

for Parmed, I got this error 

AttributeError: 'NoneType' object has no attribute 'getAttributeIndex'

**Comment by drroe** [comment]
To be fair, those files are structure factor files, which don't contain structure information the way that parmed or cpptraj think of 'structure', i.e. there are no atoms/residues/molecules. Fitting diffraction data is way outside the purview of parmed or cpptraj so it's not important to support reading these.

**Comment by swails** [comment]
I agree with Dan here.

To clarify the file format here, what cpptraj and ParmEd support isn't the CIF format in general -- it's the PDBx/mmCIF format.  CIF is a very general file format, like CSV or JSON.  PDBx is the specification of how PDB information is stored in CIF format.  This is not PDBx/mmCIF, it's just CIF :).
