### ISSUE TITLE
load lib and got warning

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#382]
file from parmed/test/files/
```python
p = pmd.load_file('solvents.lib')
```

```
/home/haichit/anaconda3/lib/python3.4/site-packages/parmed/amber/offlib.py:356: AmberWarning: residue 
table predicted -1700, not 5 atoms for residue TIP5PBOX
  name), AmberWarning)
```

given that `solvents.lib` is standard in amber, I am not sure what does the warning mean or is it necessary. 

**Note**: I just copy a part of error (full screen)

**Comment by swails** [comment]
Yes, this library file is a bit broken, but LEaP apparently does not care.  There are several library files like this.  ParmEd is a stricter parser than tleap, but I changed these from errors to warnings specifically so it *supports* all of the files that tleap reads.

I'd thought about using ParmEd to actually *fix* these files, but only LEaP actually reads them and they haven't proven particularly problematic yet so I decided against it.

**Comment by hainm** [comment]
is it a good idea to add 'warning=False' for 'load_file' (with default=True)? I am willing to take risk to trade for pretty.

**Comment by swails** [comment]
> is it a good idea to add 'warning=False' for 'load_file' (with default=True)? I am willing to take risk to trade for pretty.

You can turn off the warnings yourself via the `warnings` module:

```Python
import warnings
warnings.filterwarnings('ignore', category=pmd.exceptions.AmberWarning)
```

Personally I would *always* want to see warnings.

**Comment by hainm** [comment]
thanks.
