### ISSUE TITLE
res recognize for modified nuc

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#396]
what do you think to add more to this?

https://github.com/ParmEd/ParmEd/blob/d831c5a45053cd6298ec61ca7a8d1f7cfabbd768/parmed/residue.py#L266-L276

**Comment by hainm** [comment]
btw, there are 2 'MG' here. Is it your intention?

https://github.com/ParmEd/ParmEd/blob/d831c5a45053cd6298ec61ca7a8d1f7cfabbd768/parmed/residue.py#L266-L276

**Comment by swails** [comment]
> what do you think to add more to this?

Fine by me.

> btw, there are 2 'MG' here. Is it your intention?

:).  Thanks for the pointer.  Actually, I plan on changing those into `set`s.

**Comment by hainm** [comment]
What's your suggestion about naming new class?

for example, 2'-F Adenine is not either DNA or RNA nucleotide (O2' and HO2' are replaced by F)

``ModifiedNucleicResidue``?

**Comment by swails** [comment]
Just put it in `RNAResidue` or `DNAResidue`.  You should pull the residue names from the chemical component library on the PDB.

Where is 2'-F Adenine usually substituted?  DNA or RNA sequences?

**Comment by hainm** [comment]
Okie

2'- f appears mostly in rna

Hai

**Comment by swails** [comment]
Then let's put it in RNAResidue

**Comment by swails** [comment]
Done in #407
