### ISSUE TITLE
adding flag to prmtop to specify if a residue is aa or nuc residue

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#400]
Jason,

currently GB8 parameters for protein and nuc were hard coded. GB8 will check if a residue belongs to nuc or not to assign parameters correctly. I want to add flag to prmtop top (just an array of 1, 0 to check if a given residue is nuc or aa).

Do you have any comment about this? (since you are more familiar with editing prmtop file).

I will make a PR after getting  you feed back.

**Comment by hainm** [comment]
I guess this is what I should look into? really cool.

```python
p.add_flag(flag_name, flag_format, data=None, num_items=-1, comments=None, after=None)
```

**Comment by hainm** [comment]
uhm, not sure if I understand correctly. 

below did not work

```python
In [23]: p = pmd.load_file('4lzt.parm7')

In [24]: p.add_flag('RESTYPES', flag_format='1I8', data=[0 for _ in range(len(p.residues))])

In [25]: p.save('test.prmtop', overwrite=True)

In [26]: !grep RESTYPE test.prmtop

In [27]:
```

**Comment by swails** [comment]
> uhm, not sure if I understand correctly.

You understand correctly.

> below did not work

Because `save` is too cute right now.  I always use `write_parm` when saving a prmtop from a prmtop.  I should have fixed this behavior in #403.

**Comment by swails** [comment]
Try again.  A tip of advice, though: `1I8` is a bad format to use -- it will print out one 8-character wide integer every line.  I think what you wanted there was `10I8`, right?

**Comment by hainm** [comment]
ah yes, I have not looked at prmtop file format yet. Just randomly picked up an example.

thanks for the ``10I8``.

I will check the PR.

**Comment by hainm** [comment]
work great now. thanks.
