### ISSUE TITLE
parmed recognizes `T` as a amino acid.

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#415]
There are few things here

* ``T`` is recognized as amino acid, so what's about A (Alanine), ...
* should we consider 'NA+', 'CL-' legit?

```c++
$ pmd.summary model_2.pdb
Amino Acid Residues:   9 # wrong, should be 0
Nucleic Acid Residues: 18 # wrong, should be 18 + 9 = 27
Number of cations:     0 # wrong, should be 58 (NA+)
Number of anions:      0 # wrong, should be 31 (CL-)
Num. of solvent mols:  0
Num. of unknown res:   89
Total charge (e-):     0.0000
Total mass (amu):      9307.1682
Number of atoms:       735
Number of residues:    116
Residue set:           A, C, CL-, G, NA+, T
Residue count:         A: 11, C: 3, CL-: 31, G: 4, NA+: 58, T: 9
```

pdb file is here: https://github.com/hainm/amber_things/blob/master/things/nucleic/model_2.pdb
(from X3DNA package)

**Comment by swails** [comment]
> T is recognized as amino acid, so what's about A (Alanine), ...

T is not recognized as a RNA residue -- only deoxy-T is recognized as a DNA residue.  That can be changed, but ribothymine is pretty rare.

> should we consider 'NA+', 'CL-' legit?

No reason not to add those to the list of anions and cations.
