### ISSUE TITLE
website: new theme sphinx-bootstrap-theme

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#417]
I am testing new theme for pytraj's website. The layout + color scheme are pretty good, IMO.
https://github.com/ryan-roemer/sphinx-bootstrap-theme

What do you think to try with ParmEd?

http://amber-md.github.io/pytraj/

**Comment by hainm** [comment]
this theme is also good for mobile device.

screen shots from from my phone.

**pytraj**
![fullsizerender 1](https://cloud.githubusercontent.com/assets/4451957/9697633/2dc69660-5362-11e5-9c92-07a6e548cfcf.jpg)


**parmed**
![fullsizerender](https://cloud.githubusercontent.com/assets/4451957/9697634/3123e92a-5362-11e5-819a-e27b4fce88fd.jpg)

**Comment by swails** [comment]
The theme does look nice on the pytraj website.  For the moment I'm pretty happy with the one I'm using, so I think I'll stick with that one.

As an aside, you're obviously welcome to copy over the Amber mask documentation to your site if you want to (rather than just linking to it).

**Comment by hainm** [comment]
Okie
