### ISSUE TITLE
website: expand toc tree for Program and API Reference

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#422]
What to you think about adding depth=2 to "Program and API Reference" in the top-left of index page (Table Of Contents)?

currently it costs me 2 mouse clicks to go to this page: http://parmed.github.io/ParmEd/html/readwrite.html from http://parmed.github.io/ParmEd/html/index.html

**Comment by swails** [comment]
Did you try clicking on "Table of Contents" on the left pane?

**Comment by swails** [comment]
<img width="1291" alt="screen shot 2015-09-11 at 6 20 50 pm" src="https://cloud.githubusercontent.com/assets/779022/9827633/134283f8-58b2-11e5-97b0-48decbc7f74e.png">

Both of the links I point to take you back to the top-level ParmEd documentation page (the one at the very top is on every page to my knowledge).

**Comment by hainm** [comment]
> Did you try clicking on "Table of Contents" on the left pane?

yes, nothing is like your photo. so I guess this is browser problem or something else.

![picture1](https://cloud.githubusercontent.com/assets/4451957/9827757/a068cce6-58b3-11e5-86ff-fa63527fcd14.png)

My wish is to see ""Program and API Reference" has a list like the ones in "getting started"

**Comment by swails** [comment]
What are you browsing this with? I see those links even on my phone.

**Comment by hainm** [comment]
I am using my computer (window 7) with Chrome.

test with my Iphone 6 + safari: no different from my comp.

**Comment by swails** [comment]
I misinterpreted.  I thought you were going the other way.

I tried out tocdepth=2 and I didn't like it primarily because `Core classes used to represent...` had about 30 entries.  Do you know how to get rid of those?

**Comment by hainm** [comment]
I don't know how to get rid of them, just trying differently.

**Comment by hainm** [comment]
after trying, there is no solution yet. Just let it be. I am closing now.
