### ISSUE TITLE
Minor Spelling Error

### ISSUE THREAD

**Issue by bannanc** [ParmEd/ParmEd#423]
Line 1298 You have espilon instead of epsilon. I thought you might want to know. 

Thanks!

**Comment by swails** [comment]
Which file? I'm surprised this didn't get caught already... :(

**Comment by bannanc** [comment]
Jason,

Sorry I'm still getting used to GitHub, it's in gromacs/gromacstop.py line
1298 (link below just in case).

https://github.com/ParmEd/ParmEd/blob/1b6dfe7ce9e3a02c2d1f3f22571d16e7165f8d05/parmed/gromacs/gromacstop.py

Thank you,

Caitlin



*****************************************************
Caitlin C. Bannan
Graduate Student
Mobley Group
Chemistry Department at UC Irvine
bannanc@uci.edu

**Comment by hainm** [comment]
@bannanc 
FIY: you can click the line number and copy the url

https://github.com/ParmEd/ParmEd/blob/1b6dfe7ce9e3a02c2d1f3f22571d16e7165f8d05/parmed/gromacs/gromacstop.py#L1298
