### ISSUE TITLE
python3.5

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#424]
it's available now, so what do you think adding to travis?

I tried but openmp-dev did not catch up.

**Comment by hainm** [comment]
```
Hint: the following packages conflict with each other:
  - python 3.5*
  - openmm-dev
```

**Comment by swails** [comment]
I'll wait for `openmm-dev` to support Python 3.5.  There's no reason to think it will not work since Python 3.4 works fine.

**Comment by swails** [comment]
3.5 should not have introduced anything that would break backwards-compatibility with Python 3.4.  At some point, I'll upgrade the 3.4 target to 3.5 when OpenMM comes along, but that won't be for awhile.  I don't think it's really important.
