### ISSUE TITLE
can not find bla_bla/forcefield.itp

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#431]
in the process of adding `osx` to travis build, I encounter above error. Any idea why?

https://travis-ci.org/hainm/ParmEd/jobs/81404548

**Comment by swails** [comment]
Because GROMACS is not installed.

**Comment by hainm** [comment]
I see.

**Comment by swails** [comment]
It would probably make sense to wrap all of those in a `@skipIf(not has_gromacs())` or something.

**Comment by swails** [comment]
Fixed in #432
