### ISSUE TITLE
coverage (update)

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#434]
just played with coverage with parmed.

https://travis-ci.org/hainm/ParmEd/jobs/81646589

There are several modules (from parmed, does not count things from outside packages)

Name                                                                   Stmts   Miss  Cover
parmed/amber/amberformat.py                           465    156    66%
parmed/amber/netcdffiles.py                           522    121    77%
parmed/charmm/_charmmfile.py                           99     25    75%
parmed/formats/pdbx/PdbxContainers.py                 519    240    54%
parmed/formats/pdbx/PdbxReader.py                     209     70    67%
parmed/gromacs.py                                      27      9    67%
parmed/rosetta/pose.py                                 56     43    23%
armed/tools/actions.py                              2400    745    69%
parmed/utils.py                                        38     18    53%

PS: not sure if I interpret the data correctly or not. 

```python
nosetests --with-coverage --cover-package parmed --processes=2 --process-timeout=120 -vs .
```

or shorter
```python
nosetests --with-coverage --cover-package parmed -vs .
```

PS: `pytraj` has very poor coverage (feel shame to tell the number, ha ha).

**Comment by swails** [comment]
So I've been adding tests based on the coverage reports -- thanks for the pointer.

A few comments here:

> parmed/formats/pdbx/PdbxContainers.py 519 240 54%
> parmed/formats/pdbx/PdbxReader.py 209 70 67%

These are not my fault -- it's part of an external library, so these really should be omitted from the report.

> parmed/rosetta/pose.py 56 43 23%

This one is not as bad as it appears.  It's impossible to deploy pyrosetta on Travis (I think), so all the tests for this module are skipped.

The others I plan on addressing.  I've already found a couple small bugs improving the coverage of _amberparm.py (although I won't be achieving 100% coverage, I should be able to get into the high-80s to 90s).

**Comment by hainm** [comment]
probably you know, but just in case.

I now can understand the line in the coverage report

`parmed/amber/amberformat.py  465    156    66%`         `29-31, 130, 138, 158, 193-194, 209-210, 219-227, 263, 397, 429, 446-447, 460-463, 523, 538-539, 575-576, 581-590, 595-611, 620-791, 887, 891, 894, 905, 910, 949`

The numbers after `66%` are the line numbers in `amberformat.py`. Those lines have never been executed in test cases. So our jobs are to write more tests for those lines. :D

**Comment by hainm** [comment]
Is it possible to have a good code coverage (95-99% :D) for parmed in AT16? Many potential bugs will be easily eliminated (would save us time to debug in amber mail list).

**Comment by hainm** [comment]
btw, pytraj has ~99% code coverage (py3) now: https://coveralls.io/builds/4497162

**Comment by swails** [comment]
> Is it possible to have a good code coverage (95-99% :D) for parmed in AT16?

95-99% is probably not going to happen before Feb 15

**Comment by swails** [comment]
Also note that while code coverage is nice, it won't even come close to finding everything.  For instance, #521 is a bug that occurred in a module that has near-complete coverage.  It's just that the tests didn't include the right combination, and code coverage alone does not tell you that.

**Comment by hainm** [comment]
>  it won't even come close to finding everything

agree.

**Comment by swails** [comment]
This is done.  Coverage is now part of the standard test suite and it's reported in the README.md.  It's currently sitting at ~92%, and that's including all error messages.  There are still tests to add, but most of the key functionality is being tested now.
