### ISSUE TITLE
GROMACS writing: Any way to merge molecules?

### ISSUE THREAD

**Issue by davidlmobley** [ParmEd/ParmEd#435]
In some circumstances, I may want a GROMACS topology file containing multiple molecules to be written to a single [ molecule ] definition. Is there a way to get ParmEd to do this rather than splitting different molecules? For example, if I have a protein + ligand and I want to apply certain restraints between the protein and ligand, I might want to load the two into ParmEd separately but write them out as a single "molecule" (i.e. with the protein and ligand atoms appearing consecutively in the same [ atoms ] section). 

Thanks.

**Comment by hainm** [comment]
@swails  will reply to you about your question, I just want to give you a trick to combine and save two (or more) structures in case you don't know.

```python
(struct_0 + struct_1).save('combined.gro')
```

**Comment by swails** [comment]
Right now ParmEd supports two modes of operation.  Split all molecules into separate `[ moleculetype ]` sections, or combine every atom in the system into a single `[ moleculetype ]`.  Mixing and matching has a placeholder for right now, since I didn't know what the best way to do it would be (and I wanted to do it *right* when that functionality was needed rather than try and guess and pigeonhole myself into a substandard API).

Look at the `combine` keyword [here](https://github.com/ParmEd/ParmEd/blob/master/parmed/gromacs/gromacstop.py#L1191-L1215).  If what you want is what I said was currently unsupported, then let's start a conversation of what that API would look like :).

**Comment by davidlmobley** [comment]
Ah, that looks like it would work. We'll try that out.

On Wed, Sep 23, 2015 at 10:25 AM, Jason Swails <notifications@github.com>
wrote:

> Right now ParmEd supports two modes of operation. Split all molecules into
> separate [ moleculetype ] sections, or combine every atom in the system
> into a single [ moleculetype ]. Mixing and matching has a placeholder for
> right now, since I didn't know what the best way to do it would be (and I
> wanted to do it *right* when that functionality was needed rather than
> try and guess and pigeonhole myself into a substandard API).
>
> Look at the combine keyword here
> <https://github.com/ParmEd/ParmEd/blob/master/parmed/gromacs/gromacstop.py#L1191-L1215>.
> If what you want is what I said was currently unsupported, then let's start
> a conversation of what that API would look like :).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ParmEd/ParmEd/issues/435#issuecomment-142671417>.
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by davidlmobley** [comment]
@swails - looks like that's what we want, though we actually don't want 'all' since in our case we also have water present which we don't want merged. So we'd want to provide something to specify which molecules we want merged. 

So, what if this took a list of molecule names to be merged?

@nividic may also have comments, as he's the one working on this.

**Comment by davidlmobley** [comment]
(Molecule indices - as the documentation specifies - would probably also work fine).

**Comment by nividic** [comment]
Yes, apparently the code part that should merge the passed molecule indices is not implemented yet. I got the error:

NotImplementedError: Specialized molecule splitting is not yet supported

my current code looks like:

from parmed import gromacs
gmx_top = gromacs.GromacsTopologyFile('complex.top')
gmx_top.write('test.top',[1,2])

Thanks for your help

**Comment by swails** [comment]
> So, what if this took a list of molecule names to be merged?

There were two reasons I avoided this.  First is that in general, these molecule names are arbitrarily defined.  The rule that ParmEd uses right now is to use `system` for any system in which there is only *one* multiple-residue molecule, and `system#` where `#` goes from 1 to *n* for *n* multiple-residue molecules.  Single residue molecules are given the same name as the residue name (with adjustments made for residues with the same name but different molecules).

The second was that even if the user was OK with this, combining a protein with a handful of waters would require uncomfortable gymnastics to avoid combining it with *all* waters.  Molecule indices seemed much cleaner to me, since it avoids both the problem of ambiguity in molecule naming and the awkwardness of treating *some* of one kind of molecule differently than others.

**Comment by swails** [comment]
> Yes, apparently the code part that should merge the passed molecule indices is not implemented yet. I got the error:

Indeed -- as I said there is a holder for this functionality, but I haven't implemented it yet :).

My original idea was to have a list of lists (or tuple of tuples), in which each tuple selected the molecule numbers to be combined into a single molecule, and all molecules that were *not* specified in one of the groups were unaltered.

Any other ideas for how this could be improved?  Or a better implementation?

**Comment by davidlmobley** [comment]
Ah, yes, all those points sound great. Actually molecule numbers sounds
perfect. I don't see an immediate way to implement this more effectively,
honestly.

Thanks.

On Wed, Sep 23, 2015 at 1:43 PM, Jason Swails <notifications@github.com>
wrote:

> Yes, apparently the code part that should merge the passed molecule
> indices is not implemented yet. I got the error:
>
> Indeed -- as I said there is a holder for this functionality, but I
> haven't implemented it yet :).
>
> My original idea was to have a list of lists (or tuple of tuples), in
> which each tuple selected the molecule numbers to be combined into a single
> molecule, and all molecules that were *not* specified in one of the
> groups were unaltered.
>
> Any other ideas for how this could be improved? Or a better implementation?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ParmEd/ParmEd/issues/435#issuecomment-142722650>.
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by swails** [comment]
@davidlmobley and @nividic -- this is now implemented.  Try this test code:

```Python
from parmed import gromacs
gmx_top = gromacs.GromacsTopologyFile('complex.top')
gmx_top.write('test.top',[[1,2]])
```

It needs to be a list of lists -- see the documentation (https://parmed.github.io/ParmEd) for more information.  (The GROMACS link will take you to the GROMACS documentation).

**Comment by nividic** [comment]
Hi there, I made some tests and it seems to correctly work. However, I noted that if in the original topology file are present values for the atom masses in the [ atomtypes ] section, these are reported as zeros in the [ atomtypes ] section related to the output file i.e.

Input Topology:

[ atomtypes ]
; name    at.num    mass    charge ptype  sigma      espilon
HC             1    0.00000    1.008000  A      0.264953     0.0656888
CT             6    0.00000   12.010000  A      0.339967       0.45773
C              6    0.00000   12.010000  A      0.339967      0.359824
....

Output Toplogy:

[ atomtypes ]
; name    at.num    mass    charge ptype  sigma      epsilon
HC             1    0.00000    0.000000  A      0.264953     0.0656888
CT             6    0.00000    0.000000  A      0.339967       0.45773
C              6    0.00000    0.000000  A      0.339967      0.359824
.......

In my opinion it would be better to keep the original values as well.

Thanks a lot,

Gaetano

**Comment by swails** [comment]
Can you open this in a new issue?  And possibly post an example where I can reproduce it?

Thanks!

**Comment by nividic** [comment]
I did it...issue #445
