### ISSUE TITLE
distance based mask selection example

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#436]
from website: http://parmed.github.io/ParmEd/html/amber.html

`:8<@5.0`     All atoms that are LESS THAN 5 Angstroms away from any atom in residue 8

`:1>:10.0`    All atoms in any residue in which one atom is MORE THAN 10 angstroms away from residue 1

is it a good idea for you to add this case too. To me, it's clearer since changing only '@' to ':'.

`:8<:5.0 `
and does that mask mean
`All atoms in any residue in which one atom is LESS THAN 5 angstroms away from residue 8`?

**Comment by hainm** [comment]
Amber man:

`The syntax for selection by distance is a mask expression followed by a distance operator: ’<:’, ’>:’, (residue
based), and ’<@’, ’>@’, (atom based).`

**Comment by drroe** [comment]
The actual construction of a distance-based mask is this:
```
<mask><criterion><thing><distance>
```
So the final "plain english" description is "`<thing> <criterion> <distance> from <mask>`", where `<thing>` can be "atoms" or "residues" and `<criterion>` can be "greater than" or "less than". It's admittedly a bit obscure but it is very concise. So your example, `:8<:5.0` means "Residues less than 5.0 Angstroms away from residue 8".

**Comment by hainm** [comment]
>  "Residues less than 5.0 Angstroms away from residue 8".

you mean ANY atoms in selected residues must have distance smaller than 5.0 from ANY atom in residue 8?

**Comment by swails** [comment]
> you mean ANY atoms in selected residues must have distance smaller than 5.0 from ANY atom in residue 8?

That's how I interpreted (and implemented) it for the ParmEd mask parser.

> if so, how is that different from ':8 <@5.0'?

`:8<:5.0` selects all atoms in all residues in which at least one atom in a residue is within 5A of any atom in residue 8.  By contrast, `:8<@5.0` will only select the individual atoms in which that atom is within 5A of one of the atoms in residue 8.  It won't necessarily pick entire residues (as the first would).

**Comment by hainm** [comment]
man, I always confuse between 'ANY' and 'ALL'. :(

**Comment by hainm** [comment]
> :8<:5.0 selects all atoms in all residues in which at least one atom in a residue is within 5A of any atom in residue 8. By contrast, :8<@5.0 will only select the individual atoms in which that atom is within 5A of one of the atoms in residue 8. It won't necessarily pick entire residues (as the first would).

I see now.
