### ISSUE TITLE
load_file doc for in ipython mode

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#437]
since `load_file` is parmed's API, I think it should have examples in its doc for loading files with different options.

Motivation: don't need to open parmed website.

what's about copying from website?

```python
>>> import parmed as pmd
>>> # Load a Mol2 file
... pmd.load_file('tripos1.mol2')
<ResidueTemplate DAN: 31 atoms; 33 bonds; head=None; tail=None>
>>> # Load a Mol2 file as a Structure
... pmd.load_file('tripos1.mol2', structure=True)
<Structure 31 atoms; 1 residues; 33 bonds; NOT parametrized>
>>> # Load an Amber topology file
... parm = pmd.load_file('trx.prmtop', xyz='trx.inpcrd')
>>> parm
<AmberParm 1654 atoms; 108 residues; 1670 bonds; parametrized>
>>> # Load a CHARMM PSF file
... psf = pmd.load_file('ala_ala_ala.psf')
>>> psf
<CharmmPsfFile 33 atoms; 3 residues; 32 bonds; NOT parametrized>
>>> # Load a PDB and CIF file
... pdb = pmd.load_file('4lzt.pdb')
>>> cif = pmd.load_file('4LZT.cif')
>>> pdb
<Structure 1164 atoms; 274 residues; 0 bonds; PBC (triclinic); NOT parametrized>
>>> cif
<Structure 1164 atoms; 274 residues; 0 bonds; PBC (triclinic); NOT parametrized>
>>> # Load a Gromacs topology file -- only works with Gromacs installed
... top = pmd.load_file('1aki.ff99sbildn.top')
>>> top
<GromacsTopologyFile 40560 atoms [9650 EPs]; 9779 residues; 30934 bonds; parametrized>
```

**Comment by hainm** [comment]
another thing:

`parm = pmd.load_file('trx.prmtop', xyz='trx.inpcrd')`

You said something before about not using `struct.xyz` and prefer using `struct.coordinates`, what's about updating above code to '`coordinates='...'`?

**Comment by swails** [comment]
> another thing:
> 
> parm = pmd.load_file('trx.prmtop', xyz='trx.inpcrd')
> 
> You said something before about not using struct.xyz and prefer using struct.coordinates, what's about updating above code to 'coordinates='...'?

I'd be fine with changing it to `coordinates`, and then recognizing `xyz` as a synonymous keyword to preserve backwards-compatibility.  It needs to be changed in multiple places though -- at least for `AmberParm` and `GromacsTopologyFile` off the top of my head.

**Comment by swails** [comment]
> since load_file is parmed's API, I think it should have examples in its doc for loading files with different options.

A couple illustrative examples would be a nice addition.

Neither of these are high on my priority list (particularly the `xyz` -> `coordinates` change which will be more involved and error-prone), so I will probably not get to this for awhile.

**Comment by hainm** [comment]
What do you think about my 1st post? I can make PR. Goodto learn too.
