### ISSUE TITLE
.mol2 file load fails for molecule with zero partial charges

### ISSUE THREAD

**Issue by davidlmobley** [ParmEd/ParmEd#441]
I'm trying to load a .mol2 file for a molecule which happens to have zero partial charges, and I get this issue:

```
/Users/dmobley/anaconda/lib/python2.7/site-packages/parmed/formats/registry.pyc in load_file(filename, *args, **kwargs)
    121                             name, arg)
    122     if hasattr(cls, 'parse'):
--> 123         return cls.parse(filename, *args, **kwargs)
    124     elif hasattr(cls, 'open_old'):
    125         return cls.open_old(filename, *args, **kwargs)

/Users/dmobley/anaconda/lib/python2.7/site-packages/parmed/formats/mol2.pyc in parse(filename, structure)
    145                         last_residue = (resid, resname)
    146                         restemp.name = resname
--> 147                     atom = Atom(name=name, type=typ, number=id, charge=charge)
    148                     atom.xx, atom.xy, atom.xz = x, y, z
    149                     struct.add_atom(atom, resname, resid)

UnboundLocalError: local variable 'charge' referenced before assignment
```

**Comment by swails** [comment]
Ack.  This should be easy to fix.  Just have to assign charge to 0 if it's not present.

I'm neck-deep in implementing #435 right now, though, so this may take me a day to get to.

**Comment by davidlmobley** [comment]
Ah, it turns out that was NOT the problem. It's actually because my files specify "NO_CHARGES" in the header. So, your .mol2 parser is broken for the case where a file header specifies that there are no charges.

No rush.

**Comment by swails** [comment]
> Ah, it turns out that was NOT the problem. It's actually because my files specify "NO_CHARGES" in the header. So, your .mol2 parser is broken for the case where a file header specifies that there are no charges.

This is what I suspected the problem to be.  The solution is still to assign the local variable `charge` a value of 0 in this case to avoid the `NameError` or `UnboundLocalError`.  Should be a 1-line fix.

Do you have a small sample file I can use for a test?

**Comment by davidlmobley** [comment]
Sure, try this one (or any of the individual molecules within it).


On Tue, Sep 29, 2015 at 11:10 AM, Jason Swails <notifications@github.com>
wrote:

> Ah, it turns out that was NOT the problem. It's actually because my files
> specify "NO_CHARGES" in the header. So, your .mol2 parser is broken for the
> case where a file header specifies that there are no charges.
>
> This is what I suspected the problem to be. The solution is still to
> assign the local variable charge a value of 0 in this case to avoid the
> NameError or UnboundLocalError. Should be a 1-line fix.
>
> Do you have a small sample file I can use for a test?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ParmEd/ParmEd/issues/441#issuecomment-144139113>.
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by swails** [comment]
I just tried parsing the file you attached in your email and it worked fine.

I also checked the code and saw that `charge` is initialized to 0 already if `NO_CHARGES` is set -- [see here](https://github.com/ParmEd/ParmEd/blob/master/parmed/formats/mol2.py#L164-L170).

I suspect maybe you are using an out-of-date ParmEd?  Your traceback says that the parsing is failing on `atom = Atom(name=name, type=typ, number=id, charge=charge)`, which it says is line 147.  But that doesn't match up with line 147 from the file in master.

**Comment by davidlmobley** [comment]
Ah, yes. Haven't updated in a while. Terribly sorry.

Thanks.


On Wed, Sep 30, 2015 at 5:56 AM, Jason Swails <notifications@github.com>
wrote:

> I just tried parsing the file you attached in your email and it worked
> fine.
>
> I also checked the code and saw that charge is initialized to 0 already
> if NO_CHARGES is set -- see here
> <https://github.com/ParmEd/ParmEd/blob/master/parmed/formats/mol2.py#L164-L170>
> .
>
> I suspect maybe you are using an out-of-date ParmEd? Your traceback says
> that the parsing is failing on atom = Atom(name=name, type=typ,
> number=id, charge=charge), which it says is line 147. But that doesn't
> match up with line 147 from the file in master.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ParmEd/ParmEd/issues/441#issuecomment-144387960>.
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by swails** [comment]
Awesome. Easiest bug fix ever :)
