### ISSUE TITLE
fake http

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#444]
might be good to make fake ones.

https://www.youtube.com/watch?v=FxSsnHeWQBY

check 28:09

**Comment by swails** [comment]
I don't see a need at the moment.  It works fine as-is, and creating a fake `urlopen` will require a bit more work than *not* doing that :).

**Comment by hainm** [comment]
yeah, I suggest since I saw you got problem with pulling files from github before. Just give you alternative solution in case you see again.

**Comment by swails** [comment]
It was actually when downloading files from q4md that was failing.  When I switched to downloading from Github, it worked fine.

**Comment by hainm** [comment]
what's about this?
`OSError: Could not open https://github.com/ParmEd/ParmEd/raw/master/test/files/ala_ala_ala.psf: HTTP Error 429: Too Many Requests`

https://github.com/ParmEd/ParmEd/pull/407

**Comment by swails** [comment]
Oh -- I fixed that by not using `load_file` :).  `load_file` opens and closes the same file numerous times when trying to determine the file format, and since I tried to open *many* files, Github suspected a DoS attack and closed me out :).

**Comment by hainm** [comment]
> Github suspected a DoS attack and closed me out

lol.
