### ISSUE TITLE
upload to ambermd channel on travis

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#454]
are you interested in this? If yes, I can make a PR.

**Comment by swails** [comment]
I don't think I want Travis doing it.

**Comment by hainm** [comment]
okie.

**Comment by swails** [comment]
actually, a parmed-dev package would be fine.  But I want to get a parmed package uploaded to binstar/anaconda first (which should be done through the omnia-md/conda-recipes pretty soon).
