### ISSUE TITLE
parm.save('test.pdb') does not update new residue name.

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#465]
I am trying to rename 'FAM' to 'FAM5' in this tutorial but ``parmed`` seems to fail to save pdb file with correct name.

```python
#!/usr/bin/env python

import sys
import parmed as pmd

parm = pmd.load_file(sys.argv[1])
for res in parm.residues:
    if res.name == 'FAM':
        res.name = 'FAM5'

print('after renaming')
print(sorted({res.name for res in parm.residues}))

# save parm to 'test.pdb' file
parm.save('test.pdb', overwrite=True)

# reload 'test.pdb' file
print('after renaming and saving')
print(sorted({res.name for res in pmd.load_file('test.pdb').residues}))
```

output
```python
after renaming
['DA', 'DA3', 'DT', 'DT3', 'DT5', 'FAM5']
after renaming and saving
['DA', 'DA3', 'DT', 'DT3', 'DT5', 'FAM']
```

file: http://ambermd.org/tutorials/advanced/tutorial1/files/fam5_polyAT_edit.pdb

**Comment by swails** [comment]
http://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#ATOM

Residues can't be printed in PDB format with more than 3 letters.  [See here](https://github.com/ParmEd/ParmEd/blob/master/parmed/formats/pdb.py#L750) (you can see where the temp function standardize is defined above, and where `reslen` is set to 3).

If you want to permit the writer (which is designed to be strict to the format by default) to write 4-letter residue names, pass `charmm=True` to the PDB writer.  Just note that not all programs may respect the longer residue.

If you want residue names to be larger than 3 letters, use a format that permits that (mol2, PDBx/mmCIF, ... etc.) :)

**Comment by hainm** [comment]
> If you want residue names to be larger than 3 letters, use a format that permits that (mol2, PDBx/mmCIF, ... etc.) :)

thanks. Sound good for me.
