### ISSUE TITLE
add more tests/fix to make sure there is no 'weird potential things like 12-6-4 and NBFIXes.'

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#470]
from this issue https://github.com/ParmEd/ParmEd/issues/469

>> Do you imply that p[':DAP'] + p['!:DAP'] does not result correct energy?

> No, it should give the correct energy, but it's a lot slower and may not play quite as nicely with some weird potential things like 12-6-4 and NBFIXes.

Just want to make sure if users use the '+' stuff, he/she should not get weird things like you said.

**Comment by swails** [comment]
Tests and stuff have been added.  There is no reason I can think of that this would *not* work correctly.
