### ISSUE TITLE
Convert Tinker XYZ file class to use the core classes

### ISSUE THREAD

**Issue by swails** [ParmEd/ParmEd#471]
Also provide a way to map residues from a PDB file to the XYZ

**Comment by swails** [comment]
Pinging @peastman, per our email conversation.

**Comment by swails** [comment]
This is added by #480.

@peastman -- you should now be able to make a PDB file with atoms in the same order as in the Tinker XYZ file.  In fact -- you may not even need to write out a PDB file at all.  After installing ParmEd (at least version 2.0.8, which is the PR #480), the following should give you an OpenMM `Topology` object:

```Python
import parmed as pmd
t = pmd.load_file('tinker_file.xyz', 'pdb_file_with_seq.pdb')
t.topology
```

The `t.topology` is an OpenMM `Topology` built from the structure.  It should have the proper residue names, although the atom names come from the XYZ file (not the PDB), so they won't match.  But the bonds will be correct, so if `ForceField` assigns parameters from element/bond information rather than atom names it should still work fine.

Let me know if you have any issues (either email or open a new issue here or on openmm).

**Comment by peastman** [comment]
This doesn't work correctly.  All the atoms in the topology have their element set to None.

**Comment by swails** [comment]
I think I see why.  When #481 is merged that should fix it.

**Comment by swails** [comment]
I just tested it and the generated `Topology` now has the correct element information attached (as long as the element guess based on the first letter of the atom name is correct).

**Comment by peastman** [comment]
Guessing the element based on the first letter of the atom name isn't reliable.  I'm now getting the following error:

```
ValueError: No template found for residue 36 (NA).  This might mean your input topology is missing some atoms or bonds, or possibly that you are using the wrong force field.
```

Because of course it's guessing NA as nitrogen rather than sodium.  PDBFile has some *slightly* more sophisticated logic for guessing.  At any rate, it handles some common cases like this correctly.  But if the elements are actually specified in the PDB file, it would be much better to use those.

**Comment by swails** [comment]
> But if the elements are actually specified in the PDB file, it would be much better to use those.

Agreed, but the atom ordering comes from the XYZ file, where the atom order does not match up with the PDB file from which the sequence is determined.  And ParmEd does not (yet) assign bonds to PDB files, so there's no convenient way to map the PDB elements to the XYZ atoms yet (since I can't match bonding patterns and Tinker preserves neither atom order or atom name in its pdbxyz conversion).

The XYZ file format itself really does not make it easy *at all* to determine element information...

For this particular case, it's only a couple lines to change the element for these atoms "by hand":

```Python
import parmed as pmd
t = pmd.load_file('tinker_file.xyz', 'pdb_file_with_seq.pdb')
for atom in t.view['NA',:].atoms:
    atom.atomic_number = 11
for atom in t.view['CL',:].atoms:
    atom.atomic_number = 17
t.topology
```

If this is still incomplete, I can prep a quick script for you if you send me the pdb and xyz file (my hard drive that contained those files died awhile ago).

**Comment by peastman** [comment]
That's ok, I already did the same thing.  But making this function more robust would be a good thing, and even if you just copy the guessing logic from PDBFile, that would be a significant improvement.

**Comment by swails** [comment]
> But making this function more robust would be a good thing, and even if you just copy the guessing logic from PDBFile, that would be a significant improvement.

True.
