### ISSUE TITLE
git tag to parmed dev version?

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#472]
I just added this stuff to pytraj, my idea is to tell the git commit from version info.

What do you think about adding it to parmed?

https://github.com/Amber-MD/pytraj/blob/master/scripts/base_setup.py#L102-L182

demo:
`pytraj version =  0.1.2.dev12+7721e4c`

**Comment by swails** [comment]
+1, with a small variation.  I don't want it part of the `parmed.version` string.  Either a new attribute `parmed.git_revision` or `parmed.version.git_revision`.  Right now, `parmed.version` is ordered (you don't get that with git revisions), and tuple-based (behaves a bit like Python's `sys.version_info`).

The nice thing about attaching the git revision is that it's immune to accidentally forgetting to bump the version number (although I still have to look into versioneer and see if that can fit the bill).

**Comment by hainm** [comment]
> . I don't want it part of the parmed.version string.

agree. as long as we have something to inspect after installing parmed.

**Comment by hainm** [comment]
oh, unrelated FYI in case you don't know yet: if you move parmed to amber-md, `git clone https://github.com/ParmEd/ParmEd` is still legit.

Work for pytraj

```
$ git clone https://github.com/pytraj/pytraj
Cloning into 'pytraj'...
remote: Counting objects: 42534, done.
Receiving objects:  28% (11910/42534), 18.61 MiB | 18.51 MiB/s
```
