### ISSUE TITLE
Conversition of GROMOS to AMBER

### ISSUE THREAD

**Issue by adebayoadeniyi** [ParmEd/ParmEd#473]
Dear all,

Kindly help on how to make use of PARMED to convert GROMOS topology file to either GROMACS or AMBER topology file. I did a FORCEMATCH in CPMD which gave me a new topology file in GROMOS format and I need to convert it to either AMBER or GROMACS for molecular dynamics.

Thanks.

Kind regards,
Adebayo Adeniyi

**Comment by swails** [comment]
ParmEd does not read GROMOS topologies (I have never seen one before and have no experience at all with GROMOS).  The only GROMOS thing that ParmEd supports is the GROMOS force field through GROMACS topology files.

You will need to find another package that can convert GROMOS to GROMACS, then you can use ParmEd to convert GROMACS to AMBER (if AMBER supports the functional form of the force field).

**Comment by swails** [comment]
A potential package that reads GROMOS files in Python is ATB: https://atb.uq.edu.au/

I've never used it, though, so I'm not sure that it can do the conversions you need.

**Comment by swails** [comment]
I have no plans to add GROMOS support.  I have no familiarity with the package and know nobody that does (or at least I don't know that they do).  If someone wants to add support, I'm happy to help but until that seems likely I'm going to close this.
