### ISSUE TITLE
autopep8: specify some fixes

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#477]
We can specify which fix we want

`autopep8 -a --select=E701,W291,W293 ./parmed/*/*py -i`

E701 multiple statements on one line
W291 - Remove trailing whitespace.
W293 - Remove trailing whitespace on blank line.

**Comment by hainm** [comment]
and so on.

**Comment by swails** [comment]
I have vim set up to automatically delete trailing whitespace, so that fixes W293 and W291 :).

Anyway, I'm going to go ahead and close this.  I don't really feel like auto-formatting my code at this point...

**Comment by hainm** [comment]
:+1:
