### ISSUE TITLE
getting started with parmEd

### ISSUE THREAD

**Issue by mohammad0325** [ParmEd/ParmEd#483]
Hi,

I am new to parmEd and I want to use it in order to convert topology and coordinate files from amber to gromacs format. Now I don't know how to do it, actually actually I don’t know how to get started, which file I should download. How can I install it? Can you please help me?

Thank you, Mohammad.

**Comment by swails** [comment]
Welcome!

I should add this to the readme file so it appears right on the front page.  The first step is to download a copy of the source code.  You can either [download the latest release](https://github.com/ParmEd/ParmEd/releases) or you can clone the git repository from Github.  After you download the release, you need to unpack it (assuming you downloaded the `.tar.gz` version, use the command `tar zxf ParmEd-2.0.5.tar.gz` to unpack it).  This should create a ParmEd directory.

Change to that directory, then type the command

```
python setup.py install
```

Once you've done this, ParmEd should be installed.  Note, if you are using a system Python and get error messages regarding a lack of permissions to write the modules to the site-packages folder, you can add the `--user` option to install them to your home directory instead:

```
python setup.py install --user
```

And that's it.  Then it's installed.  Once you install ParmEd, you will need to write a very short script to do this Amber -> Gromacs conversion.  The following script will work:

```Python
import parmed as pmd
parm = pmd.load_file('your.prmtop', 'your.inpcrd')
parm.save('gromacs.top', format='gromacs')
parm.save('gromacs.gro')
```

Obviously change the file names to your files.  If you save that script in a file named `convert.py`, you can run it via `python convert.py`.  In a couple seconds, you should have your GROMACS files.

If you have other problems, let me know.  Hopefully in the near future file conversions will be quite a bit easier (i.e., doable via command-line).
