### ISSUE TITLE
Retrieving force term parameters with units attached?

### ISSUE THREAD

**Issue by jchodera** [ParmEd/ParmEd#485]
Is there a way to conveniently retrieve force parameters (e.g. `bond.type.k`, `bond.type,req`) with units automagically attached, rather than trying to guess based on what program the parameters were read from?

**Comment by swails** [comment]
There's never a need to guess.  They're always AKMA with time in ps (and if that's not true somewhere, it's a bug that needs to be fixed).  Programs that use the unit system OpenMM does (namely GROMACS and OpenMM) are automatically converted upon reading.

**Comment by jchodera** [comment]
Ah, OK!  Perhaps it's worth mentioning on [this page](http://parmed.github.io/ParmEd/html/dimensional_analysis.html) that internally `parmed` stores parameters in AKMA with time in ps throughout?  (Apologies if I missed this elsewhere in the docs.)

There's not an easy way to get back the parameters with units automagically attached, though?

**Comment by swails** [comment]
> Ah, OK! Perhaps it's worth mentioning on this page that internally parmed stores parameters in AKMA with time in ps throughout? (Apologies if I missed this elsewhere in the docs.)

That's probably the best place for it.

> There's not an easy way to get back the parameters with units automagically attached, though?

No.  Doing so would require some thought.

**Comment by jchodera** [comment]
> That's probably the best place for it.

Not the best, but maybe useful for a reminder in addition to also putting it in the best place.  :)
