### ISSUE TITLE
Incompatibilities between OpenMM Amber readers and ParmEd load_topology?

### ISSUE THREAD

**Issue by jchodera** [ParmEd/ParmEd#490]
We're having trouble with this piece of code that uses the OpenMM `app` Amber loader together with ParmEd's `load_topology()` function:
```python
from simtk.openmm import app
import parmed
prmtop = app.AmberPrmtopFile(prmtop_filename)
system = prmtop.createSystem(implicitSolvent=app.OBC1)
structure = parmed.openmm.load_topology(prmtop.topology, system)
```
This causes a series of warnings
```
/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/parmed/openmm/topsystem.py:429: OpenMMWarning: Detected incomplete exceptions. Not supported.
```
for essentially any GBSA `prmtop` file I use.

I tried, for example, the `prmtop` files [here](https://github.com/choderalab/openmmtools/tree/master/openmmtools/data/T4-lysozyme-L99A-implicit).

**Comment by swails** [comment]
Sorry, for some reason all of the Github emails were being sent to my spam folder and I only just noticed!

I will try this out tomorrow or Friday if I don't have time tomorrow.

**Comment by swails** [comment]
Actually I got to it tonight.  Problem was a 1-line fix.  Again, sorry for not responding earlier.  I've fixed my spam filter (I hope), so this won't happen again.

**Comment by jchodera** [comment]
No worries!  It also only took 1-2 lines for us to work around, with no
detrimental effects.

**Comment by swails** [comment]
As of 2.0.11, this workaround should no longer be necessary.  Sorry about that!
