### ISSUE TITLE
atom.radii or atom.radius

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#499]
which one is more correct in ParmEd?

**Comment by swails** [comment]
This is a trick question. radii is more correct. Radius will give you an AttributeError :).

**Comment by swails** [comment]
This is for the solvation radii that is stored in the RADII section of the Amber prmtop. I wanted the name to match more than the grammar.

**Comment by hainm** [comment]
does 'RADII' in Amber prmtop mean for a set of atom or just an English name people name? (no trick question).

**Comment by swails** [comment]
Radii is plural.

**Comment by hainm** [comment]
>  I wanted the name to match more than the grammar.

But I am really confused. What do you want to match here? `Radii is plural.`, so it indicate a set of atoms, not a single atom, right? btw, it's only minor thing (so I can understand better).

**Comment by swails** [comment]
It really should have been named solvation_radius. Probably a good change to make (and deprecate the radii name).

**Comment by hainm** [comment]
> It really should have been named solvation_radius. 

sounds good.
