### ISSUE TITLE
more python md package

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#51]
besides mdtraj. MDanalysis, there is one more package that's pretty nice (I think) https://code.google.com/p/pmx/

it's great if you could extend ParmEd to tleap's function in building FF + 3D structure (I know it's lots of work).

Let's discuss on March in further detail. Can't wait.

Hai

**Comment by swails** [comment]
> it's great if you could extend ParmEd to tleap's function in building FF + 3D structure (I know it's lots of work).

That's an eventual goal, actually.  I'd be happy to let ParmEd consume tleap and xleap, but it's a very long-term goal :).  I think at least now it's set up to at least make a legitimate run at such functionality.
