### ISSUE TITLE
load_file: OSError vs IOError

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#531]
just a minor point here. Should parmed use OSError or IOError?

- According to python doc
[IOError] (https://docs.python.org/2/library/exceptions.html#exceptions.IOError)
`Raised when an I/O operation (such as a print statement, the built-in open() function or a method of a file object) fails for an I/O-related reason, e.g., “file not found” or “disk full”.`

- parmed
```python
OSError: lysozyme_reference.pdb.pdb does not exist
```

**Comment by swails** [comment]
IOError for Py2 and FileNotFoundError for Py3.  Where is this exception being raised?

**Comment by hainm** [comment]
>  Where is this exception being raised?

```python
In [1]: pmd.load_file('non_existing_file.pdb')
---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
<ipython-input-1-b7d31ef61fea> in <module>()
----> 1 pmd.load_file('non_existing_file.pdb')

/home/haichit/amber_git/amber/lib/python3.5/site-packages/parmed/formats/registry.py in load_file(filename, *args, **kwargs)
    120             assert f
    121     elif not os.path.exists(filename):
--> 122         raise IOError('%s does not exist' % filename)
    123     elif not os.access(filename, os.R_OK):
    124         raise IOError('%s does not have read permissions set' % filename)

IOError: non_existing_file.pdb does not exist
```

> IOError for Py2 and FileNotFoundError for Py3. 
oops. PY2 vs PY3.

**Comment by swails** [comment]
This looks like it's raising an IOError to me...  Where did you see it raising an OSError?

**Comment by hainm** [comment]
weird py3 case

```python
--> 122         raise IOError('%s does not exist' % filename)
...
OSError: non_existing_file.pdb does not exist
```

**Comment by swails** [comment]
Because in Py3, they're the same:

```Python
In [4]: IOError is OSError
Out[4]: True
```

**Comment by hainm** [comment]
I see.
