### ISSUE TITLE
create .gro and .top from .pdb file with ParmEd

### ISSUE THREAD

**Issue by liyigerry** [ParmEd/ParmEd#551]
I want to use openmm to run simulation. But it failed to handle the incomplete pdb file. So I use gromacs to generate .gro and .top files. Can ParmEd directly create .gro and .top from .pdb file with ParmEd?

**Comment by swails** [comment]
No. Creating the top files involve assigning types from residue templates. You need to use gromacs to create the top file.

**Comment by swails** [comment]
Reading your question more closely, I think I'm misunderstanding what you are trying to do.

ParmEd can read the top and gro files directly if you already have those created.  However, if you are having trouble using OpenMM with a PDB file, you should open an issue there (or [ask a question on the OpenMM issue tracker](https://simtk.org/forums/viewforum.php?f=161)) with a detailed description of exactly what you tried and the error messages you received so we can help pinpoint what went wrong.

**Comment by liyigerry** [comment]
Ok, what I said is too complicated. But I have got the point that ParmEd can handle the .top and .gro files rather than create them. Thank your reply.
