### ISSUE TITLE
Potential bugs in tests

### ISSUE THREAD

**Issue by rafwiewiora** [ParmEd/ParmEd#554]
Was browsing through tests and this caught my eye:

https://github.com/ParmEd/ParmEd/blob/master/test/test_openmm_amber.py#L195-L196

```
 system = parm.createSystem()
 system2 = load_topology(parm.topology, system).createSystem()
 con1 = mm.Context(system, mm.VerletIntegrator(0.001), CPU)
 con2 = mm.Context(system, mm.VerletIntegrator(0.001), CPU)
```

`con2` should be using `system2` no? 

Same thing here:
https://github.com/ParmEd/ParmEd/blob/master/test/test_openmm_amber.py#L215-L216

Can't see any more right now. Am I right this is wrong?

**Comment by swails** [comment]
> con2 should be using system2 no?

Yes it should.

> Am I right this is wrong?

Yes you are.

**Comment by swails** [comment]
And that's why test-driven development says you need to write tests first and make sure they *fail* before writing the code.  Watching tests fail initially is very important (although I changed my practices some time after this code was written, IIRC).

**Comment by rafwiewiora** [comment]
Ah that's a new thing I've learned today, good to know!

**Comment by swails** [comment]
This is fixed by #556.  Test-driven development is tedious, but it really does lead to more reliable code.  I can't remember when I really shifted to ensuring tests failed before writing code, but it was somewhat recently...

Thanks for the report!

**Comment by hainm** [comment]
> you need to write tests first and make sure they fail before writing the code.

I try to follow this practice after reading yours and it's very helpful.

**Comment by swails** [comment]
> I try to follow this practice after reading yours and it's very helpful.

It's really remarkable how much that helps.  It's really difficult to actually write the tests first, but there are many good reasons to do so:

- You make sure your test is getting run and working
- You start writing "client" code before locking in an API, which helps alert you to possible deficiencies earlier
