### ISSUE TITLE
mol2 issue with GOLD: parmed.exceptions.Mol2Error: String conversion trouble: Residue already has atom named C2

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#565]
script
--------
```python
import parmed as pmd

# x = pmd.load_file('ligand_with_h.mol2', structure=True)
x = pmd.load_file('ligand_with_h.mol2', structure=False)
print(x)
```

error
-------
```python
Traceback (most recent call last):
  File "/u1/haichit/programs/parmed/parmed/formats/mol2.py", line 183, in parse
    restemp.add_atom(copy.copy(atom))
  File "/u1/haichit/programs/parmed/parmed/modeller/residue.py", line 119, in add_atom
    raise ValueError('Residue already has atom named %s' % atom.name)
ValueError: Residue already has atom named C2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "try_parmed.py", line 5, in <module>
    x = pmd.load_file('ligand_with_h.mol2', structure=False)
  File "/u1/haichit/programs/parmed/parmed/formats/registry.py", line 150, in load_file
    return cls.parse(filename, *args, **kwargs)
  File "/u1/haichit/programs/parmed/parmed/formats/mol2.py", line 329, in parse
    raise Mol2Error('String conversion trouble: %s' % e)
parmed.exceptions.Mol2Error: String conversion trouble: Residue already has atom named C2
```

file
----
https://github.com/hainm/amber_things/tree/master/things/OriginalGOLDValidationSet

**Comment by hainm** [comment]
(fine with cpptraj)

**Comment by hainm** [comment]
oops, never mind. this file has '***' in atom name. Not sure why this happen in this validation set
```bash
     42 ****        8.2160    1.4845   -7.0394 H         1 PSI1        0.0000 
     43 ****        7.2481    1.2185   -5.5695 H         1 PSI1        0.0000 
     44 ****        7.1129    2.7657   -6.4545 H         1 PSI1        0.0000 
     45 ****        6.2326    0.0260   -7.5620 H         1 PSI1        0.0000 
```

**Comment by swails** [comment]
The problem is not the `****` in the atom name, it's the fact that ParmEd tries to parse mol2 files as residue templates, meaning that every atom name in the template must be unique.  Once it encounters the same atom name twice, it throws an error.

It *might* do this for structures as well, i'm not sure.  If so, it might be worth easing up on that error message a little bit and letting it parse as a `Structure`.

**Comment by hainm** [comment]
ah yes, got same error if using `structure=True`

**Comment by swails** [comment]
I kinda cheated with the mol2 parser.  It creates both a `ResidueTemplate` *and* a `Structure` at the same time.  The argument just allows you to pick which one is returned :).  That's why I *suspected* that the error occurred in both cases, but I wasn't positive.
