### ISSUE TITLE
Allow mol2 parser to have multiple atoms with same name

### ISSUE THREAD

**Issue by swails** [ParmEd/ParmEd#566]
See #565 for a discussion.  This is only desired when using the `structure=True` option.

**Comment by hainm** [comment]
In case you're curious after adding this enhancement. 

You can try all mol2 file from: https://www.ccdc.cam.ac.uk/support-and-resources/downloads/#

(I chose `Original GOLD Validation Set`)

```python
from glob import glob
import parmed as pmd

mol2files = glob('*/*.mol2')

for mol2file in mol2files:
    try:
        pmd.load_file(mol2file, structure=True)
    except:
        print(mol2file)
```

with current code, the output of above script is something like

```bash
...
test1mdr/protein.mol2
test1mdr/ligand.mol2
test1frp/ranked_ligand_1.mol2
test1frp/ligand_reference.mol2
test1frp/protein.mol2
test1frp/ligand.mol2
test6abp/ranked_ligand_1.mol2
test6abp/ligand_reference.mol2
...
```
