### ISSUE TITLE
NBFIX 

### ISSUE THREAD

**Issue by ChayaSt** [ParmEd/ParmEd#572]
We need to add support for writing NBFIX to ffxml files. I am thinking of adding it with the ```<script> ``` section.

**Comment by jchodera** [comment]
What about adding a [`ForceGenerator`](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/forcefield.py#L4651-L4730) to OpenMM's `forcefield.py` instead?

**Comment by swails** [comment]
> What about adding a ForceGenerator to OpenMM's forcefield.py instead?

I suspect @peastman would've done that if that was the way to go.

I think we'll have to use `<script>`.  I just have to look into the best way to do that given the possibility that each XML file for each "part" of the FF will have to have its own `<script>` and each might define its own atom types and NBFIX rules and some may define NBFIX rules while others don't...  I'm really not sure how we're supposed to get this working outside the context of a "monolithic" XML file approach...

**Comment by peastman** [comment]
There's already a `CustomNonbondedGenerator`.  The hard part is how to combine multiple atom types defined in multiple files.  With `NonbondedForce`, it's fine with having definitions split between files, and it just combines all of them into a single force.  There's no reason `CustomNonbondedForce` couldn't do the same thing, but it would have to be more sophisticated about it.  You obviously should only combine forces if they have identical energy expressions and identical sets of parameters.  But I think that can be done.

**Comment by jchodera** [comment]
@peastman: What is the philosophy behind when to include a new
ForceGenerator?

For example, there is already a ForceGenerator for Urey-Bradley terms even
though these are just HarmonicBondForce terms. The processing in this
generator makes it *much* simpler to specify these terms in the ffxml file
than it otherwise would have been. It could have been handled through
making HarmonicBondForceGenerator more clever, but it was much more logical
to tackle things with a separate generator.

Is there a general philosophy here that can inform these choices?

**Comment by peastman** [comment]
Once upon a time, there was a class called `AmoebaUreyBradleyForce`.  That got eliminated years ago, but for backward compatibility we continued to support the XML tag, just implementing it with a `HarmonicBondForce` instead.

I wouldn't say there's anything that counts as a general philosophy.  These are handled on a case by case basis.  What are the advantages or disadvantages of adding a particular XML tag?

**Comment by jchodera** [comment]
Ha! Thanks for the storybook context. Was just wondering if there was some
guiding philosophy I missed.

I guess we should discuss the relative advantages of <script>, extended
CustomNonbondedForceGenerator, and NBFIXGenerator then?

**Comment by peastman** [comment]
Extending `CustomNonbondedForceGenerator` seems like a reasonable thing.  It would be consistent with `NonbondedForceGenerator`, and would be widely useful.  `NBFIXGenerator` seems more questionable.  NBFIX isn't really a force, it's a way of choosing parameters that's applicable to a variety of forces.

**Comment by ChayaSt** [comment]
There seems to be a consensus to go with extending ```CustomNonbondedForceGenerator```
Here is what I will do:
* extend ```CustomNonbondedForceGenerator``` to combine multiple atom types defined in multiple files. It will obviously only combine forces with identical energy expression and identical sets of parameters
* add a ```_write_nbfix``` to ```OpenMMParameterSet``` that will write nbfix with the ```<CustomNonbondedForce>``` tag.

**Comment by swails** [comment]
:+1:

**Comment by ChayaSt** [comment]
As per our discussion, extending ```CustomNonbondedForceGenerator``` is probably not the best way to go because the atom types needed to derive the type lookup tables might not be defined in the ffxml file. 

This is the other suggestion:
*  Have a ```NBFIXGenerator``` which will do something like the ```_omm_nbfix_force``` here https://github.com/ParmEd/ParmEd/blob/master/parmed/structure.py#L2479-L2587
* in the ffxml file, have a ```<NBFIXFoce>``` tag which will list the atom types and parameters the way CHARMM lists them here:
https://github.com/ChayaSt/FFconversion/blob/master/charmm/source_files/toppar/toppar_water_ions.str#L298-L323
The two atom types and the Emin and Rmin (with the proper unit conversion)

**Comment by swails** [comment]
cc #633 

I think the design has been pretty much established (a `LennardJonesForceGenerator`), and it is a great design IMO.  I'm going to go ahead and close this -- feel free to reopen if there's more to discuss here.
