### ISSUE TITLE
parmed-dev

### ISSUE THREAD

**Issue by jchodera** [ParmEd/ParmEd#574]
Just a heads-up that we need to start using this branch for continuous integration, so I am planning to make an `omnia/parmed-dev` package.

We can delete it once this is incorporated into an actual release.

**Comment by jchodera** [comment]
Built!
* conda recipe: https://github.com/omnia-md/conda-dev-recipes/tree/master/parmed-dev
* conda package: https://anaconda.org/omnia/parmed-dev/files

**Comment by swails** [comment]
There's actually an easier way to do this via `pip`.  Check it out:

```
pip install git+https://github.com/ParmEd/ParmEd.git@omm_params
```

This eliminates the need to do any of the conda packaging.  And since ParmEd is such a simple, almost-pure-Python package, pip is really all you need.  Upshot is you don't need to make an extra package on anaconda/binstar, it doesn't take up space, ..., etc.  Really not much downside :)

**Comment by jchodera** [comment]
Oh! I hadn't realized this.

Let me think about how to incorporate this into our devtools Travis framework. Unfortunately, the fact that conda and pip don't play nice together means this is not exactly straightforward when some dependencies (or dependencies of dependencies) are only available via one mechanism or the other.

**Comment by jchodera** [comment]
I think ParmEd only lists mininal dependencies in setup.py, so we could in principle install the other tools via conda?

**Comment by swails** [comment]
> I think ParmEd only lists mininal dependencies in setup.py, so we could in principle install the other tools via conda?

Exactly.  The only *hard* dependency ParmEd has is numpy (in that it will fail on import if you don't have it).  Other dependencies are optional and will only fail if you try to use functionality requiring it.

> Unfortunately, the fact that conda and pip don't play nice together

I've actually found quite the opposite.  Or, well, pip plays nice with conda, maybe not the other way around.  For instance:

```
swails@batman ~ $ which pip
/scratch2/miniconda/envs/py35/bin/pip
swails@batman ~ $ pip list
alabaster (0.7.6)
AmberLite (16.0)
AmberTools (16.0)
astroid (1.4.4)
Babel (2.1.1)
certifi (2015.9.6.2)
coverage (4.0)
cycler (0.9.0)
Cython (0.23.4)
decorator (4.0.6)
docutils (0.12)
fastcache (1.0.2)
ipykernel (4.2.2)
ipython (4.0.3)
ipython-genutils (0.1.0)
Jinja2 (2.8)
jsonschema (2.4.0)
jupyter-client (4.1.1)
jupyter-core (4.0.6)
lazy-object-proxy (1.2.1)
logilab-common (1.0.2)
MarkupSafe (0.23)
matplotlib (1.5.1)
mdtraj (1.6.0.dev1)
mistune (0.7.1)
MMPBSA.py (15.0)
mpi4py (1.2.2)
nbconvert (4.1.0)
nbformat (4.0.1)
netCDF4 (1.2.1)
nose (1.3.7)
nose-timer (0.5.0)
notebook (4.1.0)
numexpr (2.4.6)
... [snipped]
```

pip understands all the packages that conda installs.  And conda understands packages that pip installs, too:

```
swails@batman ~ $ conda list
# packages in environment at /scratch2/miniconda/envs/py35:
#
alabaster                 0.7.6                    py35_0  
amberlite                 16.0                      <pip>
ambertools                16.0                      <pip>
... [snip]
```

They don't interact with each other (i.e., conda won't use pip to satisfy dependencies, I don't think), but for CI testing, pip should work here just fine.
