### ISSUE TITLE
Does from_leaprc() support mol2 files?

### ISSUE THREAD

**Issue by jchodera** [ParmEd/ParmEd#592]
I tried to use the following `leaprc`:
```
naproxen = loadmol2 molecule-0000000000.gaff.mol2
loadamberparams molecule-0000000000.frcmod
aspirin = loadmol2 molecule-0000000001.gaff.mol2
loadamberparams molecule-0000000001.frcmod
imatinib = loadmol2 molecule-0000000002.gaff.mol2
loadamberparams molecule-0000000002.frcmod
bosutinib = loadmol2 molecule-0000000003.gaff.mol2
loadamberparams molecule-0000000003.frcmod
```
to generate an `ffxml` file via
```python
    leaprc = StringIO(leaprc)
    params = parmed.amber.AmberParameterSet.from_leaprc(leaprc)
    params = parmed.openmm.OpenMMParameterSet.from_parameterset(params)
    ffxml = StringIO()
    params.write(ffxml)
```
but ended up with just the `frcmod` parameters but no residue templates:
```
<ForceField>
 <Info>
  <DateGenerated>2016-02-04</DateGenerated>
 </Info>
 <AtomTypes>
 </AtomTypes>
 <Residues>
 </Residues>
 <PeriodicTorsionForce>
  <Proper type1="ca" type2="cp" type3="nb" type4="ca" periodicity1="2" phase1="3.14159265359" k1="20.0832"/>
  <Proper type1="cp" type2="cp" type3="nb" type4="ca" periodicity1="2" phase1="3.14159265359" k1="20.0832"/>
  <Proper type1="ca" type2="ca" type3="cg" type4="n1" periodicity1="2" phase1="3.14159265359" k1="0.0"/>
  <Improper type1="ca" type2="ca" type3="ca" type4="ha" periodicity1="2" phase1="3.14159265359" k1="4.6024"/>
  <Improper type1="ca" type2="ca" type3="ca" type4="ca" periodicity1="2" phase1="3.14159265359" k1="4.6024"/>
  <Improper type1="ca" type2="ca" type3="ca" type4="os" periodicity1="2" phase1="3.14159265359" k1="4.6024"/>
  <Improper type1="ca" type2="c" type3="ca" type4="ca" periodicity1="2" phase1="3.14159265359" k1="4.6024"/>
  <Improper type1="c" type2="ca" type3="o" type4="oh" periodicity1="2" phase1="3.14159265359" k1="4.6024"/>
  <Improper type1="c" type2="c3" type3="o" type4="os" periodicity1="2" phase1="3.14159265359" k1="4.6024"/>
  <Improper type1="ca" type2="ca" type3="cp" type4="ha" periodicity1="2" phase1="3.14159265359" k1="4.6024"/>
  <Improper type1="ca" type2="ca" type3="h4" type4="nb" periodicity1="2" phase1="3.14159265359" k1="4.6024"/>
  <Improper type1="ca" type2="cp" type3="h4" type4="nb" periodicity1="2" phase1="3.14159265359" k1="4.6024"/>
  <Improper type1="cp" type2="ca" type3="ca" type4="cp" periodicity1="2" phase1="3.14159265359" k1="4.6024"/>
  <Improper type1="ca" type2="ca" type3="ca" type4="n" periodicity1="2" phase1="3.14159265359" k1="4.6024"/>
  <Improper type1="ca" type2="ca" type3="ca" type4="nh" periodicity1="2" phase1="3.14159265359" k1="4.6024"/>
  <Improper type1="cp" type2="ca" type3="cp" type4="nb" periodicity1="2" phase1="3.14159265359" k1="4.6024"/>
  <Improper type1="ca" type2="nb" type3="nb" type4="nh" periodicity1="2" phase1="3.14159265359" k1="4.6024"/>
  <Improper type1="c" type2="ca" type3="n" type4="o" periodicity1="2" phase1="3.14159265359" k1="43.932"/>
  <Improper type1="nh" type2="ca" type3="ca" type4="hn" periodicity1="2" phase1="3.14159265359" k1="4.6024"/>
  <Improper type1="n" type2="c" type3="ca" type4="hn" periodicity1="2" phase1="3.14159265359" k1="4.6024"/>
  <Improper type1="ca" type2="ca" type3="ca" type4="cg" periodicity1="2" phase1="3.14159265359" k1="4.6024"/>
  <Improper type1="ca" type2="ca" type3="ca" type4="nb" periodicity1="2" phase1="3.14159265359" k1="4.6024"/>
 </PeriodicTorsionForce>
</ForceField>
```
I'm happy to take a stab at implementing what would be needed for molecules loaded by `loadmol2` to also appear as residue templates---just let me know what I would need to do.

**Comment by jchodera** [comment]
Ah, I see from [the documentation](https://github.com/ParmEd/ParmEd/blob/master/parmed/amber/parameters.py#L226-L243
) that `loadmol2` is not implemented:
```
    def from_leaprc(cls, fname):
        """ Load a parameter set from a leaprc file
        Parameters
        ----------
        fname : str or file-like
            Name of the file or open file-object from which a leaprc-style file
            will be read
        Notes
        -----
        This does not read all parts of a leaprc file -- only those pertinent to
        defining force field information. For instance, the following sections
        and commands are processed:
        - addAtomTypes
        - loadAmberParams
        - loadOFF
```
What would you think about us adding `loadmol2` to load these as residue definitions?  Is this something that would fit well, or something that would be incompatible with how `parmed` handles forcefields?

**Comment by jchodera** [comment]
Looks like the code to load a mol2 as a residue template already exists; we would just need to plug it into the leaprc reading part.

**Comment by rafwiewiora** [comment]
I think you could just do this to make it work already, no need to use a leaprc btw:
``` python
params = parmed.amber.AmberParameterSet('frcmod.1', 'frcmod.2', 'frcmod.3')
residues = OrderedDict()
residues['naproxen'] = parmed.load_file('naproxen.mol2')
(...)
params.residues.update(residues)
params = parmed.openmm.OpenMMParameterSet.from_parameterset(params)
params.write(ffxml)
```

Does this work?

**Comment by swails** [comment]
But if a leaprc file has a loadmol2 command in it (or loadmol3), we should parse that and do the right thing.

**Comment by jchodera** [comment]
> But if a leaprc file has a loadmol2 command in it (or loadmol3), we should parse that and do the right thing.

+1

Is this something I can help with?  If so, I'd just need a bit of direction about how you'd like it implemented.  But given the tools you already seem to have implemented, it looks like it might be trivial for you to add on your own.

**Comment by swails** [comment]
Yea, it should be trivial.

**Comment by rafwiewiora** [comment]
Ok, if you're doing that - I saw one of the leaprc's in Amber calling another leaprc as the first command with `source leaprc.x`, might be worth adding the source command support too at the same time?

**Comment by swails** [comment]
Probably, but then I have to implement a "join" :smiley:

**Comment by rafwiewiora** [comment]
Oh yeah, shoot, I didn't think about that! Yeah, not worth it then - it was some one old file.

**Comment by jchodera** [comment]
Should I take a stab at implementing the `loadmol2 filename.mol2` functionality in `from_leaprc()`?

**Comment by swails** [comment]
Sure, if you'd like to and have the time.  May not be a bad idea since the time I'll have to devote to ParmEd will decrease a bit in the near future and the more people that can hack on it the faster its development can continue :).

This will have to change how ParmEd processes leaprc files though.  Right now it loads everything into text and does a global find on `loadOFF` and `loadAmberParams` commands.  This makes sure that all OFF files are loaded in the order they were specified, and same for parameter files, but the relative order between them is lost.  This doesn't matter for parameters and libraries since they occupy different namespaces.  But if you introduce `loadMol2` support, the parser will have to walk through the leaprc line by line to make sure the correct overriding behavior is implemented.

It also shouldn't be difficult to implement a `join` on `ParameterSet`, so `source` support should be straightforward.

Let me know what you want to do.  I should definitely be able to get to `loadMol2` support sometime today if you don't want to tackle it.

**Comment by rafwiewiora** [comment]
Anyone working on this? I was wrong about the `source` support not being necessary - I need it for stuff like leaprc.parmbsc0_chiOL4_ezOL1 or leaprc.ff14SB + leaprc.modrna08. Can code this up if everyone else is busy?

**Comment by jchodera** [comment]
Take a stab at it!

**Comment by jchodera** [comment]
Did you have any luck on this @rafwiewiora?

**Comment by rafwiewiora** [comment]
Sorry, the dihedrals have kept me occupied... I think this afternoon I should be able to do this. (but those dihedrals do remain unpredictable)

**Comment by swails** [comment]
When this gets implemented we need to be careful about the following situation:

```
...
loadOFF something.lib
loadMol2 something_else.mol2
loadOFF something_further.lib
loadMol2 something_final.mol2
```

These have to be read in in-order.  Which means the leaprc text processing will have to move from re-matching the whole contents to processing line-by-line (which is why I haven't gotten to it yet).  I'll try to free up some time when I can to get to this if you're too busy to tackle it right away @rafwiewiora
