### ISSUE TITLE
parmed.load_file(file) goes into an infinite loop if file is empty 

### ISSUE THREAD

**Issue by rafwiewiora** [ParmEd/ParmEd#595]
Not sure if you'd call this a bug or more of a accept-the-consequences-of-your-script kind of thing, but doesn't cost anything to report:

I'm using temp files in my conversion script and it just so happened that tleap failed and exited without writing parameters to those files, so `parmed.load_file()` was called with empty files. Hence the infinite while loop:
```
^C---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-26-d77784cc0069> in <module>()
----> 1 parmed.load_file('a', 'b')

/Users/rafalpwiewiora/anaconda/lib/python2.7/site-packages/ParmEd-2.2.0-py2.7-macosx-10.5-x86_64.egg/parmed/formats/registry.pyc in load_file(filename, *args, **kwargs)
    128             continue
    129         try:
--> 130             if cls.id_format(filename):
    131                 break
    132         except UnicodeDecodeError:

/Users/rafalpwiewiora/anaconda/lib/python2.7/site-packages/ParmEd-2.2.0-py2.7-macosx-10.5-x86_64.egg/parmed/charmm/charmmcrds.pyc in id_format(filename)
     65             line = f.readline()
     66             while len(line.strip()) == 0:   # Skip whitespace, as a precaution
---> 67                 line = f.readline()
     68 
     69             intitle = True
```

**Comment by rafwiewiora** [comment]
Oh well the amount of red labels here tells me that was very much worth reporting!

**Comment by swails** [comment]
Yea, this is a bad bug.  It's also one that I routinely try to ensure doesn't happen.  Most of the `id_format` functions are explicitly tested against a blank file, but I must have missed this one.

I'll fix it.  Thanks for the very clear report that makes my life so easy! :smile:

This is also an unpredictable error.  The file format registry is stored in a dict, and `id_format` is tested on each class by iterating through the registry.  Which means that the order in which each format type is tested depends on the machine you're running on.  So a bug may or may not present itself when one of the `id_format` is buggy.

**Comment by swails** [comment]
At this point, I rely so heavily on `pmd.load_file` that I can't imagine it being unreliable (it's been surprisingly resilient in my hands so far, which is very encouraging).  #596 should future-proof against this happening again.  It does a loop over every registered file type and makes sure that a blank file returns `False` on `id_format`, which is the desired behavior.

Thanks for the report!

**Comment by rafwiewiora** [comment]
Sure thing, happy to help!
