### ISSUE TITLE
non-consecutive multi-term torsions not handled properly by leap

### ISSUE THREAD

**Issue by swails** [ParmEd/ParmEd#599]
Not sure what, if anything, should be done here.  Maybe have `AmberParameterSet` duplicate tleap's behavior?  But what *is* tleap's behavior?  Is it consistent and reliable?  Probably not...

The source of this discrepancy is reported in choderalab/openmm#4

**Comment by rafwiewiora** [comment]
I wonder - should `AmberParameterSet` reproduce tleap's behavior or the intention of the force field's authors? Clearly in this case the intention was different to what tleap does. 

But does reproducibility in science mean ParmEd should do the wrong thing too because AMBER does the wrong thing?

**Comment by swails** [comment]
> But does reproducibility in science mean ParmEd should do the wrong thing too because AMBER does the wrong thing?

Well if Amber is the reference implementation, we need to do what Amber does to claim to use the same FF.  But I don't know if Amber's behavior here *is* well-defined, so there's really nothing to do.

**Comment by hainm** [comment]
I agree with @swails

**Comment by swails** [comment]
I think the right thing to do is warn.  I'll implement that and close this.

**Comment by swails** [comment]
Done in #605
