### ISSUE TITLE
last residues or patches in stream files are not processed in CharmmParameterSet

### ISSUE THREAD

**Issue by ChayaSt** [ParmEd/ParmEd#600]
The last residues or patches in stream files are not added to the residue or patch dictionary using either ```CharmmParameterSet('*.str')``` or with ```param.read_stream_file``` . However, when I read it with the topology parser into an existing CharmParameterSet it does process it. 

After adding some debug statements, it seems like the ```read_stream_file```excludes the END from the section and that doesn't allow it to drop out of the while loop to assign the residues in the dictionary.

**Comment by ChayaSt** [comment]
I added these 3 lines to ```_charmmfile.CharmmStreamFile```
https://github.com/ChayaSt/ParmEd/blob/ommparams/parmed/charmm/_charmmfile.py#L156-L158. It seems to have solved the problem.

**Comment by swails** [comment]
Thanks!  You want to submit a PR with these changes?

**Comment by ChayaSt** [comment]
Will do.

**Comment by swails** [comment]
Fixed by #602
