### ISSUE TITLE
from_leaprc() doesn't handle filenames with spaces

### ISSUE THREAD

**Issue by jchodera** [ParmEd/ParmEd#603]
It looks like there is currently no way to get `from_leaprc()` to handle loading parameter files with spaces in them.  If the spaces are omitted, the filename is perceived as the first token; if they are surrounded in quotes, the filenames are not correctly identified.

**Comment by swails** [comment]
Ohhhhh... I understand what you mean now.  Yea, I can see why that would be true.  So something like this is incorrectly processed:

```
loadOFF "file with spaces.lib"
...
```

Yea, I can see why that would be the case.

**Comment by jchodera** [comment]
Thanks!

**Comment by swails** [comment]
Should be fixed by #615
