### ISSUE TITLE
deepcopy(Structure()) behavior and pickling methods

### ISSUE THREAD

**Issue by rafwiewiora** [ParmEd/ParmEd#618]
@ChayaSt noticed that, if you `copy.deepcopy` a `Structure` instance, `.createSystem()` on the copy fails because the `.unknown_functional` attribute does not exist: https://github.com/ParmEd/ParmEd/blob/master/parmed/structure.py#L1808

Of course I got obsessed over this and had to work out what was going on. My understanding here is that, as `Structure` doesn't have a `__deepcopy__` method, `copy.deepcopy(Structure())` will fall back to using the `__getstate__` and `__setstate__` pickling methods. And those happen to be missing the `unknown_functional` attribute, as well as the `space_group`. 

For the copying I guess you could just say - just use `copy.copy` because the `__copy__` method provides deep copying behavior. But for pickling this is definitely a bug it seems, you're getting a broken Structure after pickling-unpickling.

**Comment by rafwiewiora** [comment]
@ChayaSt you said `copy.deepcopy` used to work in the past - must have been before @swails added the pickling methods here https://github.com/ParmEd/ParmEd/commit/c3e312e123f7481d6ca1e2ab07411b5728004662 . 

(what does deepcopy fall back to when the pickling methods are unavailable too?)

**Comment by swails** [comment]
Thanks for the detailed report!  This should be trivial to fix.
