### ISSUE TITLE
OpenMMParameterSet writing - remove templates with missing atom types?

### ISSUE THREAD

**Issue by rafwiewiora** [ParmEd/ParmEd#627]
Before I've introduced the `write_unused` argument to remove those atom types, which are not being used in the templates existing in the ParameterSet. 

Now, the ions conversion has a somewhat reverse of this issue - `atomic_ions.lib` have a lot of stuff that does not get parameters from the appropriate frcmod, so I would like to remove those templates from the ParameterSet, which cannot be typified. 

I'm going to deal with this on my script level for now just be checking whether any `self.atom_types[atom.type]` returns KeyError and then removing that residue. But I wondered if it'd be useful to add this to ParmEd too? Perhaps we can now actually make it a pruning call that will do both of the jobs (remove types without templates & templates without types)?

**Comment by swails** [comment]
This should be doable at the ParmEd level. This functionality is being developed to serve this purpose (writing ffxml files for OpenMM), so it should do all the tasks that are necessary for that. 

Should we do this automatically in the write function, or maybe only when pruning unused types? Or should we add another argument to toggle that behavior?

I don't want to introduce a new flag where we will only ever (currently) use a single value. If we find ourselves in that situation, that should just become the behavior.

**Comment by rafwiewiora** [comment]
I agree about a new flag - that'll be too much at this point. But I also wouldn't make 'remove all templates without types' the only behavior possible - you might want to just convert a template into ffxml - for example for use with the ffxml-GAFF. I did a imatinib.lib --> imatinib.xml conversion that way for my GAFF testing - I guess you can do the same mol2 --> ffxml using ParmEd? So we need the writing functionality to take templates without atom types too. 

I'm thinking a small change here: https://github.com/ParmEd/ParmEd/blob/master/parmed/openmm/parameters.py#L165-L171

The if `self.atom_types` already gives us 'protection' for when you want to just convert a template, but I also don't want to kill the general 'whatever goes in - goes out' functionality, even personally I want to be able to use the write function without any cleaning within it for debugging / converting some more unusual stuff etc. - this will be useful for the future. But I am pretty sure that whenever I set `write_unused=False` I am doing a clean FF conversion - so how about we expand the meaning of `write_unused=False` to both a) delete unused atom types AND b) delete 'unused' templates? 

Then I would just, in addition to the warning if KeyError is raised on line 169, also do a removal of those templates there `if not write_unused`. Need to change how the typification is done for this though, would you rather:
* have `typeify_templates()` return a set of residues that raised a KeyError?
* change `typeify_templates()` to accept a single residue and do the loop over residues in the write function of OpenMMParameterSet rather than within `typeify_templates()`?

**Comment by rafwiewiora** [comment]
or another option:
* have `typeify_templates()` do the residue removal on `KeyError` - and it takes the `write_unused` flag as argument.

**Comment by swails** [comment]
> On Mar 2, 2016, at 11:54 AM, Rafal Wiewiora <notifications@github.com> wrote:
> 
> I agree about a new flag - that'll be too much at this point. But I also wouldn't make 'remove all templates without types' the only behavior possible - you might want to just convert a template into ffxml - for example for use with the ffxml-GAFF. I did a imatinib.lib --> imatinib.xml conversion that way for my GAFF testing - I guess you can do the same mol2 --> ffxml using ParmEd? So we need the writing functionality to take templates without atom types too.
> 
> I'm thinking a small change here: https://github.com/ParmEd/ParmEd/blob/master/parmed/openmm/parameters.py#L165-L171
> 
> The if self.atom_types already gives us 'protection' for when you want to just convert a template, but I also don't want to kill the general 'whatever goes in - goes out' functionality, even personally I want to be able to use the write function without any cleaning within it for debugging / converting some more unusual stuff etc. - this will be useful for the future. But I am pretty sure that whenever I set write_unused=False I am doing a clean FF conversion - so how about we expand the meaning of write_unused=False to both a) delete unused atom types AND b) delete 'unused' templates?
> 

+1 on this. 

> Then I would just, in addition to the warning if KeyError is raised on line 169, also do a removal of those templates there if not write_unused. Need to change how the typification is done for this though, would you rather:
> 
> have typeify_templates() return a set of residues that raised a KeyError?

Does typeify_templates already return anything? If no, this sounds fine. 
> change typeify_templates() to accept a single residue and do the loop over residues in the write function of OpenMMParameterSet rather than within typeify_templates()?

Could we instead do this in the writing routine? Loop over all atoms in a template and see if each has a type before writing it?

I'll have to look at it tonight.

**Comment by rafwiewiora** [comment]
> Could we instead do this in the writing routine? Loop over all atoms in a template and see if each has a type before writing it?

This sounds like the best idea to me - we don't change `typeify_templates` which is any ParameterSet general just to do this OpenMMParameterSet-specific thing. I will PR it like that, so you can check out tonight. Thanks!

**Comment by swails** [comment]
#628 seems the right way to go to me :)

**Comment by swails** [comment]
Fixed by #628
