### ISSUE TITLE
Transfer Amber topology and coordinate files to CHARMM or GROMACS formats

### ISSUE THREAD

**Issue by pengfeili1** [ParmEd/ParmEd#631]
Hi Jason,

I want to use ParmEd to transfer AMBER topology and coordinate files to CHARMM and GROMACS formats. Can you tell me how to do that? Thanks!

Warm regards,
Pengfei

**Comment by swails** [comment]
Hey, sorry!  This is quite easy:

```Python
import parmed as pmd

amber = pmd.load_file('prmtop', 'inpcrd')

# Save a GROMACS topology and GRO file
amber.save('gromacs.top')
amber.save('gromacs.gro')

# Save a CHARMM PSF and crd file
amber.save('charmm.psf')
amber.save('charmm.crd')
```

Doesn't get much easier :smiley:

**Comment by swails** [comment]
Here are the docs for `.save` -- it picks the default file type via filename extension:

```
save(self, fname, format=None, overwrite=False, **kwargs)
    Saves the current Structure in the requested file format. Supported
    formats can be specified explicitly or determined by file-name
    extension. The following formats are supported, with the recognized
    suffix and ``format`` keyword shown in parentheses:
    
        - PDB (.pdb, pdb)
        - PDBx/mmCIF (.cif, cif)
        - PQR (.pqr, pqr)
        - Amber topology file (.prmtop/.parm7, amber)
        - CHARMM PSF file (.psf, psf)
        - CHARMM coordinate file (.crd, charmmcrd)
        - Gromacs topology file (.top, gromacs)
        - Gromacs GRO file (.gro, gro)
        - Mol2 file (.mol2, mol2)
        - Mol3 file (.mol3, mol3)
        - Amber ASCII restart (.rst7/.inpcrd/.restrt, rst7)
        - Amber NetCDF restart (.ncrst, ncrst)
    
    Parameters
    ----------
    fname : str
        Name of the file to save. If ``format`` is ``None`` (see below), the
        file type will be determined based on the filename extension. If the
        type cannot be determined, a ValueError is raised.
    format : str, optional
        The case-insensitive keyword specifying what type of file ``fname``
        should be saved as. If ``None`` (default), the file type will be
        determined from filename extension of ``fname``
    overwrite : bool, optional
        If True, allow the target file to be overwritten. Otherwise, an
        IOError is raised if the file exists. Default is False
    kwargs : keyword-arguments
        Remaining arguments are passed on to the file writing routines that
        are called by this function
    
    Raises
    ------
    ValueError if either filename extension or ``format`` are not recognized
    TypeError if the structure cannot be converted to the desired format for
    whatever reason
    IOError if the file cannot be written either because it exists and
    ``overwrite`` is ``False``, the filesystem is read-only, or write
    permissions are not granted for the user
```

**Comment by pengfeili1** [comment]
Great! Thanks Jason! Are you familiar with LAMMPS? Can you also add the functionality to save LAMMPS format topology and coordinate files? The amber2lmp code (https://github.com/CFDEMproject/LAMMPS/tree/master/tools/amber2lmp) has not been updated for a long time and could not work properly for my case. Thank you!

**Comment by pengfeili1** [comment]
Forgot to tell you that my request is based on the thought that to make AmberTools and AMBER force field the "default" on the metal complex modeling: users could use MCPB.py and tleap generate the AMBER topology and coordinate files, while ParmEd could be used to transfer AMBER format to other formats such as CHARMM, GROMACS, LAMMPS, etc. if they want to use other program to perform the simulation.

**Comment by swails** [comment]
I don't know anything about LAMMPS, and am not really in a position to learn.  However, I do have plans on linking ParmEd with [InterMol](https://github.com/shirtsgroup/InterMol) to extend support to LAMMPS and Desmond.

For right now, you can use InterMol itself to convert from Amber to LAMMPS (it does this by converting Amber to GROMACS using ParmEd, then GROMACS to LAMMPS using InterMol).

This is something on the queue between me, @ctk3b, and @mrshirts -- they can give you more info on getting started from the InterMol side now.

**Comment by hainm** [comment]
@pengfeili1 may be you want to contribute LAMMPS Parser to ParmEd too (if you want to extend MCPB to broader users)? Writing parser is not difficult but requires extensive testing. @swails can be very helpful during code review.

**Comment by swails** [comment]
Writing a parser for many file formats is not difficult.  Writing one for a force field-bearing file format *is*.  Adding a GROMACS parser that worked correctly took significant contributions from at least 3 different developers -- the other two of whom were much more familiar with it than me.  Validation is by far the hardest part.  So *by far* the easiest way to add a LAMMPS parser to ParmEd is to tie InterMol and ParmEd together at the API levels :smiley:.  In fact, I think it's probably the only approach that has a reasonable chance of success on a realistic timescale.

**Comment by hainm** [comment]
I agree with all of your points (difficulty in validating, should combine with InterMol, ...). We really need to collaborate with LAMMPS user. :d

**Comment by ctk3b** [comment]
@pengfeili1 let me know if you try out the InterMol conversion and run into trouble!

I started tinkering around with a [validation suite](https://github.com/ctk3b/validate) a few weeks ago but haven't had time to fully see it through. Basically trying to clean up InterMol's testing infrastructure, take proper advantage of `pytest` and make it easy to add new unit tests. Right now it runs AMBER and GROMACS although I should probably be using the sander API and the AMBER unit tests aren't valid.

**Comment by rwmolt** [comment]
@swails May I ask what version of Gromacs output file is currently produced? i.e., 4.5 or 5.0?

**Comment by swails** [comment]
> @swails May I ask what version of Gromacs output file is currently produced? i.e., 4.5 or 5.0? In particular, I mean the parameter file.

What's the difference?  ParmEd's default behavior (which can be overridden) is to put the parameters in-line in the topology file (i.e., it does not use an include topology file to supply the parameters).

The difference between Gromacs 4.5 and 5.0 is not in the file formats as far as I'm aware, but rather in how GROMACS programs are invoked.  Separate programs in GROMACS 4.5 became subcommands of the `gmx` program in GROMACS 5.  But the file formats used should be the same.

The GROMACS topology files that ParmEd generates were validated on GROMACS 4 and GROMACS 5 when the functionality was being developed.

**Comment by rwmolt** [comment]
@swails I am using a software (http://rjdkmr.github.io/do_x3dna/usage.html) which demands I use parameter files from v4.5 or v4.6. The creator specified this in a post elsewhere (https://www.researchgate.net/post/what_is_the_procedure_to_run_do_x3dna_for_gromacs_5_trajectory_files#56e303de48954c039603005f)

**Comment by swails** [comment]
That post talks about TPR files.  Those are binary parameter/topology files generated by applying `gmx grompp` to the GROMACS topology/gro files that ParmEd generates.

So to be clear, ParmEd can't generate TPR files -- you need to create GROMACS top/gro files and use GROMACS itself to convert those to a TPR.

**Comment by rwmolt** [comment]
Thank you for the clarification; I've never run GROMACS before, and 
mistook that for the equivalent file top as prmtop. Obviously I need to 
learn GROMACS to complete my task. Thank you for your help.

**Comment by hainm** [comment]
also FYI: cpptraj has limited support for nucleic acid analysis,  you might try to find out if your need is in there first.

https://github.com/Amber-MD/cpptraj/tree/master/test/Test_NAstruct

**Comment by rwmolt** [comment]
@hainm Appreciate the thought. The challenge is that I have nucleic acids which are not recognized automatically. Daniel Roe offered some help that I may take him up on (he loosely outlined what would have to be coded to define units to be recognized in a helix).

**Comment by hainm** [comment]
ok. Can you open a new issue in cpptraj repo about that (so we can keep track what should be improved in future)? https://github.com/Amber-MD/cpptraj/issues
(I think I remembered your topic in amberlist now).

**Comment by swails** [comment]
I'm going to go ahead and close this -- the main question seems to have already been answered.

**Comment by fdwonder** [comment]
What about the charmm .prm files? Is there anyway to generate the parameter file along with the topology file in charmm format? Thanks.
