### ISSUE TITLE
Global atom type name change

### ISSUE THREAD

**Issue by rafwiewiora** [ParmEd/ParmEd#641]
So I need to change all names of atom types in `OpenMMParameterSet` for the ions - the XMLs that will be used for overloading cannot be using atom types with the same names as the XMLs they will be overloading, for example we'll have for tip3p: 
standard: `tip3p_standard-Fe2+`
HFE_multivalent: `tip3p_HFE_multivalent-Fe2+`
IOD_multivalent: `tip3p_IOD_multivalent-Fe2+`

Now is there a way to make these changes in one place and have the ParameterSet update itself in all the necessary places with the new names?

It doesn't look like it, so I'm just going with looping through everything - atom_types, atom.type for atoms in residues, bond_types etc. Perhaps there is a nicer way to do this that I'm missing?

**Comment by swails** [comment]
There's no simpler way of doing that that I'm aware of.  You'll need to do the brute-force renaming (since ParmEd stores parameter types using keys of type name or tuples of type names).

**Comment by rafwiewiora** [comment]
After I wrote the code for bonds, angles etc. I realized this is only for ions and all it needs to change is `atom_types` and `atom.type` for residues... Well, it works great anyway! Thanks!

**Comment by swails** [comment]
Don't forget to change the AtomType.name attribute for all of the objects in atom_types

**Comment by rafwiewiora** [comment]
Why is that necessary? That attribute is not used anywhere throughout the writing as far as I can see, so for this use case it doesn't look like it matters.

**Comment by swails** [comment]
It's used in some places -- particularly with CHARMM force fields that assign both an integer and name to each type.
