### ISSUE TITLE
Question on File Format

### ISSUE THREAD

**Issue by rwmolt** [ParmEd/ParmEd#642]
Hi...

I don't know if it is OK to pose questions on an alpha version of a software; I realize you are a busy man. I can use ParmEd pursuant to 

https://github.com/ParmEd/ParmEd/issues/631#issuecomment-195487248

to generate the topology files as recommended, but I encounter a difficulty for my purposes regarding solvent. I have inpcrd and .rst files which have the ENTIRE set of xyz coordinates (including solvent/ions of which I do not care). I have a revised parameter file prepared for NO solvent/ions. I would imagine that I can create a xyz file without breaking any rules to use in place of inpcrd/rst if I use one of my PDB files from my "dry" trajectory, just edit it to look like a inpcrd/rst file format. However, as I have no independent way of checking if the final result is correct (in terms a Gromacs file), I hoped to ask this question: would there be any problem in editing a "dryed" PDB file to inpcrd/rst format to use in ParmEd? Thank you.

Addendum: meaning I am concerned it is sensitive to the ORDER of coordinates of the topology file, which may not be preserved in a PDB.

**Comment by rwmolt** [comment]
I withdraw my question; I learned cpptraj can make a restart file for me from a trajectory, negating my difficulty.

**Comment by swails** [comment]
OK.  I'm going to go ahead and close this, then.  Just for completeness, order *does* matter.  Coordinates from a `Structure` are ordered, so if you put the coordinates from a PDB file on top of a GROMACS topology file (for instance), where the atom orders differ, then the coordinates will be wrong.
