### ISSUE TITLE
Error during conversion from gromacs topology to amber topology 

### ISSUE THREAD

**Issue by rahmanhpu** [ParmEd/ParmEd#647]
I am trying to convert gromacs topology file to amber topology file to used MMPBSA or MMGBSA module of Amber Tool.
 For this I used the following command 
**parmed -p topol.top  -O amb.parm7**
After running this command, I got the following error

GromacsWarning: angles funct != 1 or 5; unknown functional
GromacsWarning: angles funct != 1 or 5; unknown functional
GromacsWarning: angles funct != 1 or 5; unknown functional
GromacsWarning: angles funct != 1 or 5; unknown functional
GromacsWarning: angles funct != 1 or 5; unknown functional
GromacsWarning: angles funct != 1 or 5; unknown functional
GromacsWarning: angles funct != 1 or 5; unknown functional
GromacsWarning: angles funct != 1 or 5; unknown functional
GromacsWarning: angles funct != 1 or 5; unknown functional
GromacsWarning: angles funct != 1 or 5; unknown functional
GromacsWarning: angles funct != 1 or 5; unknown functional
GromacsWarning: angles funct != 1 or 5; unknown functional
GromacsWarning: angles funct != 1 or 5; unknown functional
GromacsWarning: angles funct != 1 or 5; unknown functional
GromacsWarning: angles funct != 1 or 5; unknown functional
GromacsWarning: angles funct != 1 or 5; unknown functional
GromacsWarning: angles funct != 1 or 5; unknown functional
GromacsWarning: angles funct != 1 or 5; unknown functional
GromacsWarning: angles funct != 1 or 5; unknown functional
GromacsWarning: angles funct != 1 or 5; unknown functional
GromacsWarning: angles funct != 1 or 5; unknown functional
GromacsWarning: angles funct != 1 or 5; unknown functional
GromacsWarning: angles funct != 1 or 5; unknown functional
GromacsWarning: angles funct != 1 or 5; unknown functional
GromacsWarning: angles funct != 1 or 5; unknown functional
GromacsWarning: angles funct != 1 or 5; unknown functional
GromacsWarning: angles funct != 1 or 5; unknown functional
GromacsWarning: angles funct != 1 or 5; unknown functional
GromacsWarning: angles funct != 1 or 5; unknown functional
Traceback (most recent call last):
  File "/home/rahman/anaconda3/bin/parmed", line 6, in <module>
    clapp()
  File "/home/rahman/anaconda3/lib/python3.5/site-packages/parmed/scripts.py", line 128, in clapp
    amber_prmtop.add_parm(parm)
  File "/home/rahman/anaconda3/lib/python3.5/site-packages/parmed/tools/parmlist.py", line 38, in add_parm
    parm = load_file(parm, structure=True)
  File "/home/rahman/anaconda3/lib/python3.5/site-packages/parmed/formats/registry.py", line 164, in load_file
    return cls(filename, *args, **kwargs)
  File "/home/rahman/anaconda3/lib/python3.5/site-packages/parmed/gromacs/gromacstop.py", line 233, in __init__
    self.read(fname, defines, parametrize)
  File "/home/rahman/anaconda3/lib/python3.5/site-packages/parmed/gromacs/gromacstop.py", line 436, in read
    self.parametrize()
  File "/home/rahman/anaconda3/lib/python3.5/site-packages/parmed/gromacs/gromacstop.py", line 940, in parametrize
    atom.atom_type = params.atom_types[atom.type]
KeyError: 'LP3'

**I was prepared this gromacs topology file using gromos53a6.ff force fields in GROMACS: gmx, VERSION 5.0.2.**

**Comment by davidlmobley** [comment]
You'll want to provide a copy of your topology file. However, I suspect
what this is telling you is that you're using the GROMOS force field which
is (???) relying on an angle parameter type which is not supported in
AMBER.

I'd also speculate that you'll run into other problems even if you get this
conversion to work. The GB/PB solvent models in AMBER, at least the last
time I looked, basically rely on AMBER atom typing to set the atomic radii
for the solvent model. I would expect the solvent model not to recognize
GROMOS atom typing. There may be ways to work around this, but it will
require some expertise. I'm thinking it might actually take LESS expertise
just to set up your own MM/GBSA in GROMACS.

On Tue, Mar 22, 2016 at 8:04 AM, rahmanhpu <notifications@github.com> wrote:

> I am trying to convert gromacs topology file to amber topology file to
> used MMPBSA or MMGBSA module of Amber Tool.
> For this I used the following command
> *parmed -p topol.top -O amb.parm7*
> After running this command, I got the following error
>
> GromacsWarning: angles funct != 1 or 5; unknown functional
> GromacsWarning: angles funct != 1 or 5; unknown functional
> GromacsWarning: angles funct != 1 or 5; unknown functional
> GromacsWarning: angles funct != 1 or 5; unknown functional
> GromacsWarning: angles funct != 1 or 5; unknown functional
> GromacsWarning: angles funct != 1 or 5; unknown functional
> GromacsWarning: angles funct != 1 or 5; unknown functional
> GromacsWarning: angles funct != 1 or 5; unknown functional
> GromacsWarning: angles funct != 1 or 5; unknown functional
> GromacsWarning: angles funct != 1 or 5; unknown functional
> GromacsWarning: angles funct != 1 or 5; unknown functional
> GromacsWarning: angles funct != 1 or 5; unknown functional
> GromacsWarning: angles funct != 1 or 5; unknown functional
> GromacsWarning: angles funct != 1 or 5; unknown functional
> GromacsWarning: angles funct != 1 or 5; unknown functional
> GromacsWarning: angles funct != 1 or 5; unknown functional
> GromacsWarning: angles funct != 1 or 5; unknown functional
> GromacsWarning: angles funct != 1 or 5; unknown functional
> GromacsWarning: angles funct != 1 or 5; unknown functional
> GromacsWarning: angles funct != 1 or 5; unknown functional
> GromacsWarning: angles funct != 1 or 5; unknown functional
> GromacsWarning: angles funct != 1 or 5; unknown functional
> GromacsWarning: angles funct != 1 or 5; unknown functional
> GromacsWarning: angles funct != 1 or 5; unknown functional
> GromacsWarning: angles funct != 1 or 5; unknown functional
> GromacsWarning: angles funct != 1 or 5; unknown functional
> GromacsWarning: angles funct != 1 or 5; unknown functional
> GromacsWarning: angles funct != 1 or 5; unknown functional
> GromacsWarning: angles funct != 1 or 5; unknown functional
> Traceback (most recent call last):
> File "/home/rahman/anaconda3/bin/parmed", line 6, in
> clapp()
> File
> "/home/rahman/anaconda3/lib/python3.5/site-packages/parmed/scripts.py",
> line 128, in clapp
> amber_prmtop.add_parm(parm)
> File
> "/home/rahman/anaconda3/lib/python3.5/site-packages/parmed/tools/parmlist.py",
> line 38, in add_parm
> parm = load_file(parm, structure=True)
> File
> "/home/rahman/anaconda3/lib/python3.5/site-packages/parmed/formats/registry.py",
> line 164, in load_file
> return cls(filename, *args, **kwargs)
> File
> "/home/rahman/anaconda3/lib/python3.5/site-packages/parmed/gromacs/gromacstop.py",
> line 233, in *init*
> self.read(fname, defines, parametrize)
> File
> "/home/rahman/anaconda3/lib/python3.5/site-packages/parmed/gromacs/gromacstop.py",
> line 436, in read
> self.parametrize()
> File
> "/home/rahman/anaconda3/lib/python3.5/site-packages/parmed/gromacs/gromacstop.py",
> line 940, in parametrize
> atom.atom_type = params.atom_types[atom.type]
> KeyError: 'LP3'
>
> *I was prepared this gromacs topology file using gromos53a6.ff force
> fields in GROMACS: gmx, VERSION 5.0.2.*
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ParmEd/ParmEd/issues/647>
>



-- 
David Mobley
Associate Professor
Department of Pharmaceutical Sciences
Department of Chemistry
3134B Natural Sciences I
University of California, Irvine
Irvine, CA 92697
dmobley@uci.edu
work (949) 824-6383
cell (949) 385-2436

**Comment by swails** [comment]
As @davidlmobley, AMBER does not support the functional forms for the bonded terms used in the GROMOS force fields.  So while your command-line usage of parmed is wrong (you need to start it with no arguments and use the `gromber` action to do such a conversion), it won't work regardless.

> The GB/PB solvent models in AMBER, at least the last
> time I looked, basically rely on AMBER atom typing to set the atomic radii
> for the solvent model.

Actually, it's now done by atomic number, so that's good :smiley:.

**Comment by swails** [comment]
There's nothing ParmEd can do to convert GROMOS FFs to Amber. Closing this.

**Comment by thepineapplepirate** [comment]
So this is actually happening to me with systems setup using CHARMM-GUI (protein-membrane), but prepped with AMBER FFs. I don't understand why it's giving this error, its an AMBER FF, with the same functionals. Has anybody else run into this issue?

**Comment by swails** [comment]
You should open a new issue and post your files there for help.
