### ISSUE TITLE
keep alternative conformations?

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#657]
Jason,

is there any option to keep alternative conformation when parsing pdb file? (related to phenix stuff).
I am too lazy to write my own, so if NO, can you point to where I can change the code.

**Comment by swails** [comment]
It automatically keeps them.

**Comment by swails** [comment]
Each `Atom` has an `other_locations` dict that pairs the altloc label (A, B, C, ... etc.) with another Atom instance containing the coordinates of the alternate conformer

**Comment by hainm** [comment]
lol. quick response. thx.

does parmed respect the atom order in pdb file?

**Comment by swails** [comment]
not sure what you mean.  The altlocs are stored in a dict, which are unordered (you could make the attribute an OrderedDict, but the altloc labels will be in alphabetical order, anyway, so it shouldn't matter)

**Comment by hainm** [comment]
phenix and amber has different way to interpret the atom order. It seems that LES parm7 has different order from pdb file (with alternative conformation). So when using sanderles to compute gradient, the gradient is ridiculously wrong for some atoms. I am working on mapping amber atom order to phenix one.

**Comment by hainm** [comment]
so my idea is: use parmed to read phenix's pdb file and read amber LES parm7 file. Then compare two parmed's structures to see how the atom orders are different.

**Comment by swails** [comment]
tleap does the atom reordering.  If you look at `addPDB`, it needs to do this same thing ([see here](https://github.com/ParmEd/ParmEd/blob/master/parmed/tools/actions.py#L3170-L3178)).  tleap keeps residues in the same order, but puts the atoms in the same order as that which appears in the residue template in the OFF file (not necessarily what appears in the original PDB file if they differ, which is frequently).

**Comment by swails** [comment]
Can this be closed?

**Comment by hainm** [comment]
Yeah
