### ISSUE TITLE
amber: make clean does not clean ParmEd

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#659]
after `make clean` AmberTools/src:

AmberTools/src/parmed (master) $ git ls-files --other

parmed/__pycache__/__init__.cpython-35.pyc
parmed/__pycache__/constants.cpython-35.pyc
parmed/__pycache__/exceptions.cpython-35.pyc
parmed/__pycache__/geometry.cpython-35.pyc
parmed/__pycache__/parameters.cpython-35.pyc
...

Probably ParmEd should add "clean" method (python setup.py clean). I will submit an PR for this.

**Comment by hainm** [comment]
fix: https://github.com/ParmEd/ParmEd/pull/660

**Comment by swails** [comment]
Fixed by #660
