### ISSUE TITLE
 ValueError: invalid literal for

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#663]
Hi,

so I am trying to use ParmEd to remove Hydrogen from pdb files generated by Rosetta (so I can use tleap to add H again and then build rst7 + parm7 files).

I got error like: (only failed 2/525 files)

```bash
    parmed/formats/pdb.py", line 368, in parse
        resid = int(resid)
    ValueError: invalid literal for int() with base 10: ''
```

Any idea how to fix it or why does is happens? :D thanks

https://github.com/hainm/amber_things/tree/master/things/rosetta_amber

```python
#!/usr/bin/env python

import parmed as pmd

pmd.load_file('./1dts_1dts1022_0001.pdb')
```

**Comment by hainm** [comment]
```bash
$ python -c 'import parmed as pmd; print(pmd.__version__)'
2.4.0
```

**Comment by rafwiewiora** [comment]
Well your PDB's are broken in those exact 2 lines:
https://github.com/hainm/amber_things/blob/master/things/rosetta_amber/1dts_1dts1022_0001.pdb#L1619 (I guess you get the error here? Missing residue number so you're doing `resid = int('')`)

https://github.com/hainm/amber_things/blob/master/things/rosetta_amber/1dts_1dts4403_0001.pdb#L1214

**Comment by hainm** [comment]
thanks. I will tell my labmate to have a look at those two. cheers. Hai

**Comment by hainm** [comment]
uhm, two those pdb files have missing residues.
