### ISSUE TITLE
read pdb with filtering/ignore

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#664]
idea from this issue: https://github.com/ParmEd/ParmEd/issues/663

What do you think about parsing pdb file with skipping specific atom in `mask`? 

Use case: I know some of my hydrogen coordinates are blank, so I just want ParmEd to skip it. 

```python
# load only heavy atoms.
pmd.load_file('my.pdb', mask='!@H=')
```

why? I just want to use ParmEd to read no-H atoms and then use tleap to build parm7.
Alternative way: using `sed` to delete :D

**Comment by swails** [comment]
This is equivalent to just doing

```Python
pmd.load_file('my.pdb')['!@H=']
```

only my approach is more extensible.  For instance, you just want Chain-A?

```Python
pmd.load_file('my.pdb')['A',:,:]
```

"There should be one-- and preferably only one --obvious way to do it." :)

**Comment by hainm** [comment]
> "There should be one-- and preferably only one --obvious way to do it." :)

sounds fair enough.

But to do `pmd.load_file('my.pdb')['!@H=']`, `pmd.load_file` needs to successful parse the pdb file.
Anyway, it seems complicated to let ParmEd handle missing data.

**Comment by swails** [comment]
> But to do pmd.load_file('my.pdb')['!@H='], pmd.load_file needs to successful parse the pdb file.

But in reality, so does your approach in general.  It just gives the impression that's not the case, and is only potentially a *little* more forgiving for bad PDB formats.

It needs to be able to find the atom name before determining whether or not to exclude it.  If it can't do that, then it'll fail, anyway (I think the PDB files you posted in #663 will still fail with your proposed addition, for instance (and for the same reason).  And I looked at your PDB files -- they're broken :).  I'd rather ParmEd choke on broken PDBs than silently handle them and skip over problems.

What you're really trying to do here is process the text before it hits the parser, which you can implement in a custom class if you wanted to:

```Python

class FilteredFile(object):

    ...
    def __iter__(self):
        for line in self._file_handle:
            if should_exclude(line): continue
            yield line

    def readline(self):
        line = self._file_handle.readline()
        while line and should_exclude(line):
            line = self._file_handle.readline()
        return line

    def readlines(self):
        return [l for l in self]

    def read(self):
        return ''.join(self.readlines())
```

Then just pass the `FilteredFile` instance to `pmd.formats.PDBFile.parse`.  This is the approach I take in many places in ParmEd -- for instance, the GROMACS files and CHARMM files.  It filters out comments and, for GROMACS, handles preprocessor directives naturally.

**Comment by hainm** [comment]
Cool. Thanks.

**Comment by swails** [comment]
Going to close this.
