### ISSUE TITLE
ValueError: AmberAsciiRestart mode must be 'r' or 'w'

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#671]
dummy try:

```python
pmd.load_file('new.rst7', 'new.parm7')
```

:D

**Comment by swails** [comment]
The error message says what it means.  `pmd.load_file` passes all arguments on to the corresponding constructor.  The docs for restart files say the second argument is `mode`, and that only `r` or `w` are accepted.

As a person, it's clear that the more appropriate error message would say "I was expecting a mode, but you gave me the file name of an Amber prmtop instead".  But that's not something you can code in a simple way.  I'm satisfied with the current behavior.
