### ISSUE TITLE
Have parmed print any loaded topologies when log is started.

### ISSUE THREAD

**Issue by drroe** [ParmEd/ParmEd#676]
Currently, any topologies loaded on the command line are not visible in the log. Could be useful so you know what file you were working with for a given set of commands, e.g.
```
# Log started on 04/11/2016 [mm/dd/yyyy] at 09:28:44
# Loaded topologies: input.parm7
addLJType @%ND
```
and so on.

**Comment by swails** [comment]
It would probably also be nice to have an echo of the command line that was used. 

Good suggestion. And one that will be quick and easy to implement and close :)

**Comment by swails** [comment]
I'll even add some self-gratifying labels here to make it even nicer when I close it in 15 minutes :smiley:

**Comment by drroe** [comment]
Nice! I think I'll do the same with cpptraj...

**Comment by drroe** [comment]
> I'll even add some self-gratifying labels here to make it even nicer when I close it in 15 minutes ￼

Ha - just saw this - I think the labels are entirely appropriate :+1:

**Comment by swails** [comment]
> Nice! I think I'll do the same with cpptraj...

About time a feature flows the other way :)

**Comment by drroe** [comment]
BTW, the original idea came from @cbergonzo, so we should thank her :-)

**Comment by swails** [comment]
Thanks @cbergonzo!
