### ISSUE TITLE
parsing mol2 to Structure is 3 times slower than parsing pdb

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#689]
I know ParmEd reads mol2 file to ResidueTemplate first. But it's quite slow if I (user) just want to read it to Structure. What do you think about writing different parsing route (to Structure)?.

for 4.8 K atoms, it takes ~8 seconds.

```python
In [10]: parm = pmd.load_file('./2pia_2pia1423_0001.pdb')

In [11]: parm.save("test.mol2", overwrite=True)

In [12]: %timeit pmd.load_file("./2pia_2pia1423_0001.pdb")
1 loop, best of 3: 2.41 s per loop

In [13]: %timeit pmd.load_file("test.mol2")
1 loop, best of 3: 7.53 s per loop

In [16]: %timeit pmd.load_file("test.mol2", structure=True)
1 loop, best of 3: 7.41 s per loop
```

File: https://github.com/ParmEd/ParmEd/issues/688

Of course, ParmEd does not need to be super fast. But still nice to be fast if don't need to take much effort to do so.

**Comment by swails** [comment]
It would be easier to just make PDB parsing slower :)

**Comment by swails** [comment]
This is not a common usage for mol2.

**Comment by swails** [comment]
The `ResidueTemplate` and `Structure` are constructed at the same time in the same loop.  Extracting those into separate loops would be possible, but tedious.  And I don't see a whole lot of benefit.  Especially when you can get a ~4-5x speedup by using pypy for performance-intensive tasks :).

**Comment by hainm** [comment]
One reason I do not really want to try pypy because it does not play nicely with Python ecosystem: no netcdf, no py3(>=4), no pandas, ... and you need to install everything, just like using another python version.

**Comment by swails** [comment]
It's developing that infrastructure (also, pypy supports a large part of the CPython C-API -- ParmEd's C++ Amber prmtop parser works in pypy, but it doesn't make it that much faster).  At the end of the day, Python will have a pretty slow upper limit on how fast it can do anything.  IMO, switching to pypy is a cleaner solution than peppering `@numba.jit` decorators everywhere -- the only place those are really good are for heavy number-crunching using pure Python (+numpy).  For parsing, there's no point.  The only way you get a faster parser (outside of an extra 10% here and there) is by rewriting the whole thing in C/C++/Cython... or swapping python for pypy.

If I want to mine the PDB for instance (which I've done a couple times), I write a ParmEd script that runs under pypy to mine the data and drop it into a CSV or something.  Then I read that in pandas with CPython.

Speaking of pytraj -- what's the use-case for making the mol2 file parsing faster for large structures here?  Why not just use pytraj's mol2 parser, which should be orders of magnitude faster?

**Comment by hainm** [comment]
> If I want to mine the PDB for instance (which I've done a couple times), I write a ParmEd script that runs under pypy to mine the data and drop it into a CSV or something. Then I read that in pandas with CPython.

sounds good to me.

> what's the use-case for making the mol2 file parsing faster for large structures here?

actually I don't work with large mol2 yet (and not find a useful case for it), but I am trying to read 15K mol2 files from phenix.

> Why not just use pytraj's mol2 parser, which should be orders of magnitude faster?

ah, I have not thought about this. For many mol2 files with different coordinates, I just feel more convenient to use ParmEd. For example
```python
parm = pmd.load_file('my.mol2', structure=True)
parm.atoms # having coordinate info and other stuff
```

```python
traj = pt.load('my.mol2')
traj.top.atoms # no coordinates info

# so I need to
traj[0].xyz[0]
```

But I think I am too lazy to switch back and forth between parmed and pytraj :D.

**Comment by hainm** [comment]
go ahead to close this issue if you don't have intention to speed up the parser.

**Comment by swails** [comment]
I might.  I'll look at it when I get time.

**Comment by swails** [comment]
Yea, too much work for not enough gain.
