### ISSUE TITLE
tutorial for amber website

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#690]
it's good to have an introductory tutorial.

**Comment by swails** [comment]
Where?  And about what?  ParmEd isn't like cpptraj and pytraj.  There's no such thing as "general purpose topology file editing" like there is for "general purpose trajectory analysis".  It's *part* of other tutorials, like "how do I run the CHARMM FF in Amber", or "how do I run the 12-6-4 L-J model", or "how do I run TI in pmemd".  Or more general conversions: "how do I run the XYZ force field in program ABC" -- that's not really something to put on the Amber tutorial page.

The target audience for the Amber tutorials is not the same as what a ParmEd tutorial would be aimed toward, so I doubt the Amber tutorial website would benefit from a dedicated ParmEd tutorial at all.

What's needed is for people to contribute how they use ParmEd to a repository of examples so others can see what it can be used for.

**Comment by hainm** [comment]
Okie I see.
