### ISSUE TITLE
wrong atomic number for Br, Cl, Fe, ...

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#697]
so I am trying to compare parmed (newest PR for atomic number) and pytraj/cpptraj with 15K ligands I am working on.

parmed predicts :
Br 5 ( vs 35 ).
Cl 6 (vs 17)
FE 9 (vs 26)

Still testing but give 1st report here. (title might be changed)

**Comment by swails** [comment]
Not sure what the state of this is, or if it's still relevant.

In any case, I'm not sure that it's worth doing much more on the atomic number prediction algos -- just use a format the specifies it :)
