### ISSUE TITLE
Temporary optional adjustment to .mol2 writer?

### ISSUE THREAD

**Issue by davidlmobley** [ParmEd/ParmEd#698]
Is there any chance you'd temporarily be willing to accept an adjustment to the `.mol2` writer which would manipulate the amount of whitespace used to delimit fields in the ATOMS section of `.mol2` files? We could submit a PR.

We've encountered an issue where the OpenEye tools can't process partial charges in `.mol2` files output by ParmEd because ParmEd increases the amount of whitespace separating fields. Apparently the OpenEye tools only process the first 80 characters on each line (even though there is no such limit in the file specifications that I can tell), so partial charges get truncated when roundtripping a `.mol2` file. 

I've submitted a bug report to OpenEye, but the timescale for releases is not super fast and our development will need to proceed anyway. The simplest work around would be to add an optional argument to the `.mol2` writer which would try to compress whitespace to hit an 80 character limit when possible (so the normal behavior would be as now and someone would only get this if they ask for it). Alternatively, we'll write some other tool which will postprocess ParmEd output `.mol2` files to reduce the whitespace. :( 

@camizanette , this is your issue.

Probably also relevant to @jchodera , given the extensive use of `.mol2` files and OpenEye tools in his group.

**Comment by swails** [comment]
Sure. What about adding a "compress_whitespace" argument to turn the nice formatting into a simple space-delimited line?

IIRC, the nice formatting was added by request from Kyle. Just put in the docstring what it's there for.

**Comment by davidlmobley** [comment]
Excellent, that would be perfect! I can generate some code for this if you want and submit a PR, though if you'd prefer to do it yourself I'm fine with that too.

**Comment by davidlmobley** [comment]
(It's slightly ironic that Kyle's request is what broke this, since he relied extensively on the same OpenEye `.mol2` reading and writing we rely on...)

**Comment by jchodera** [comment]
I think @kyleabeauchamp only ever used the ParmEd `mol2` writer to generate input for `antechamber`, which has its own set of weird behaviors.

**Comment by swails** [comment]
I'm mostly done with the PR, so I'll just go ahead and finish it up. It was really quite easy. 

The test case I wrote was to ensure the line lengths would be <80 chars, so this should hopefully be sufficient for your use cases.

**Comment by davidlmobley** [comment]
Perfect, thanks!


On Wed, Apr 27, 2016 at 5:22 PM, Jason Swails <notifications@github.com>
wrote:

> I'm mostly done with the PR, so I'll just go ahead and finish it up. It
> was really quite easy.
>
> The test case I wrote was to ensure the line lengths would be <80 chars,
> so this should hopefully be sufficient for your use cases.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ParmEd/ParmEd/issues/698#issuecomment-215271483>
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by swails** [comment]
OK, this is implemented by #699.  Let me know if this PR works, @camizanette.  I'm not sure how familiar you are with GitHub's workflow, but to try out this PR you can use the following commands in your ParmEd git repository:

```
git remote add swails https://github.com/swails/ParmEd.git
git fetch swails
git checkout -b mol2whitespace swails/mol2whitespace
```

That will create a new branch equivalent to this PR (since that's the branch I submitted this PR from).  Install that version of the code and give it a try.  Apologies if I'm rehashing what you already knew.

If you have any questions, feel free to ask.  If you report back that this works for you, I'll go ahead and merge #699.

**Comment by camizanette** [comment]
Thank you!

**Comment by camizanette** [comment]
@swails, I tested your code and it is working perfectly for our purpose. Could you merge it into master? Thanks!

**Comment by swails** [comment]
Sure thing.  Thanks!

**Comment by davidlmobley** [comment]
For the record, the OpenEye bug this bypassed is fixed in the October beta releases, so those affected by it don't necessarily need to use compress_whitespace anymore, or at least once the upgrade is made...
