### ISSUE TITLE
Maybe not a ParmEd problem, but my Travis is having trouble with ParmEd

### ISSUE THREAD

**Issue by davidlmobley** [ParmEd/ParmEd#703]
I'm still trying to figure out this whole travis-ci thing for my SolvationToolkit package (github.com/mobleylab/solvationtoolkit). Yesterday everything seemed to be behaving just fine on travis, but today I'm having an issue where it says it can't find `parmed-dev` in my channels, despite the fact that I haven't changed anything that could affect this (i.e. see https://travis-ci.org/MobleyLab/SolvationToolkit/jobs/127638824, which reports today's problem, as opposed to https://travis-ci.org/MobleyLab/SolvationToolkit/jobs/127380362, which reports how it was working yesterday)

The specific error is this:
```
Error:  Package missing in current linux-64 channels: 
  - parmed-dev
The command "conda build devtools/conda-recipe" exited with 1.
source activate _test
Error: could not find environment: _test
```

Does this mean perhaps there is currently a problem with `parmed-dev`, or am I doing something wrong somehow? (I haven't changed my travis configuration/conda recipes from yesterday except by removing `rdkit`, so I can't for the life of me figure out how I would have done anything that affected this).

**Comment by jchodera** [comment]
I know what went wrong.  It is due to the changes that came about from here https://github.com/omnia-md/conda-recipes/issues/488

Working on it.

**Comment by hainm** [comment]
@davidlmobley  since ParmEd is mostly Python, you can just use `pip` to install

```python
pip install git+https://github.com/ParmEd/ParmEd
```

**Comment by jchodera** [comment]
We are still debating about how to fix this, but I should have a
temporarily fix in soon.

**Comment by davidlmobley** [comment]
Great, thanks.

**Comment by swails** [comment]
Has this been fixed in conda-recipes yet?

**Comment by davidlmobley** [comment]
Yes, it's fixed. Thanks.
