### ISSUE TITLE
Support for dihedral terms with same periodicity and different phases?

### ISSUE THREAD

**Issue by KarlTDebiec** [ParmEd/ParmEd#707]
Hi all,

I am interested in using ParmEd to convert a Gromacs topology built using the CHARMM22\* force field to Amber parmtop format. Among other changes, CHARMM22\* replaces the non-Gly/Pro CMAP of CHARMM27 with the following torsions:

| Angle | Phase | k1 | k2 | k3 | k4 |
| --- | --- | --- | --- | --- | --- |
| C-Cα-N-C | 0.0 | −0.200 |  |  |  |
|  | 90.0 | −1.825 | 0.054 |  |  |
|  | 150.0 | −0.109 | 0.077 | −0.096 | −0.106 |
| N-C-Cα-N | 0.0 | 0.600 |  |  |  |
|  | 60.0 | −2.286 | −0.362 |  |  |
|  | 150.0 | 0.013 | 0.942 | 0.267 | −0.127 |

ParmEd's gromber command is able to convert the topology without error, but as it reads in the force field  it overrides the terms with phases of 0°, 60°, and 90° with the 150° terms, warning that:
`ParameterWarning: Overriding DihedralType in DihedralTypeList with same periodicity`

The resulting protein topology has the correct number of dihedral terms, but those with phases of 0°, 60°, and 90° are duplicates of the 150° terms, e.g.:

```
...
M   8  C (   C)  10  N ( NH1)  12 CA ( CT1)  22  C (   C) -0.1090 1.0000 150.0000
M   8  C (   C)  10  N ( NH1)  12 CA ( CT1)  22  C (   C) -0.1090 1.0000 150.0000
M   8  C (   C)  10  N ( NH1)  12 CA ( CT1)  22  C (   C)  0.0770 2.0000 150.0000
M   8  C (   C)  10  N ( NH1)  12 CA ( CT1)  22  C (   C) -0.1090 1.0000 150.0000
M   8  C (   C)  10  N ( NH1)  12 CA ( CT1)  22  C (   C)  0.0770 2.0000 150.0000
M   8  C (   C)  10  N ( NH1)  12 CA ( CT1)  22  C (   C) -0.0960 3.0000 150.0000
    8  C (   C)  10  N ( NH1)  12 CA ( CT1)  22  C (   C) -0.1060 4.0000 150.0000
...
M  10  N ( NH1)  12 CA ( CT1)  22  C (   C)  24  N ( NH1)  0.0130 1.0000 150.0000
M  10  N ( NH1)  12 CA ( CT1)  22  C (   C)  24  N ( NH1)  0.0130 1.0000 150.0000
M  10  N ( NH1)  12 CA ( CT1)  22  C (   C)  24  N ( NH1)  0.9420 2.0000 150.0000
M  10  N ( NH1)  12 CA ( CT1)  22  C (   C)  24  N ( NH1)  0.0130 1.0000 150.0000
M  10  N ( NH1)  12 CA ( CT1)  22  C (   C)  24  N ( NH1)  0.9420 2.0000 150.0000
M  10  N ( NH1)  12 CA ( CT1)  22  C (   C)  24  N ( NH1)  0.2670 3.0000 150.0000
   10  N ( NH1)  12 CA ( CT1)  22  C (   C)  24  N ( NH1) -0.1270 4.0000 150.0000
...
```

I only need to perform this conversion for a single system, and it is feasible for me to manually edit the parmtop to replace the duplicated 150° terms with the intended 0°, 60°, and 90° terms (unless these terms are unsupported by pmemd.cuda, which I don't think is the case). I just thought I should bring to the developers' attention that support for these types of dihedrals may be useful.

**Comment by swails** [comment]
ParmEd shouldn't duplicate the terms, it should simply ignore the ones that get overridden, I think.  I'll have to look into why this is happening, because it shouldn't.

That said, I've never seen torsion terms made up with Fourier terms with the same periodicity but different phase shifts.  Amber doesn't allow it at all.  If this is a necessary feature, though, then I'll likely have to think up some kind of solution to this...

**Comment by KarlTDebiec** [comment]
Yes, CHARMM22* is the only instance of these types of torsions that I am aware of, so I am not sure if it is worth your time to add in this functionality.

After using ParmEd to write out the parmtop, I manually replaced the duplicated 150° terms with the desired 0° and 90°/60° terms. For example, for Φ I changed:

    %FLAG DIHEDRAL_FORCE_CONSTANT
    %FORMAT(5E16.8)
     -1.09000000E-01 -1.09000000E-01  7.70000000E-02 -1.09000000E-01  7.70000000E-02
     -9.60000000E-02 -1.06000000E-01  2.00000000E-01  8.00000000E-01  3.10000000E+00
    ...

and

    %FLAG DIHEDRAL_PHASE
    %FORMAT(5E16.8)
      2.61799388E+00  2.61799388E+00  2.61799388E+00  2.61799388E+00  2.61799388E+00
      2.61799388E+00  2.61799388E+00  3.14159265E+00  0.00000000E+00  3.14159265E+00
    ...

to:

    %FLAG DIHEDRAL_FORCE_CONSTANT
    %FORMAT(5E16.8)
     -2.00000000E-01 -1.82500000E+00  5.40000000E-02 -1.09000000E-01  7.70000000E-02
     -9.60000000E-02 -1.06000000E-01  2.00000000E-01  8.00000000E-01  3.10000000E+00
    ...

and

    %FLAG DIHEDRAL_PHASE
    %FORMAT(5E16.8)
      0.00000000E+00  1.57079633E+00  1.57079633E+00  2.61799388E+00  2.61799388E+00
      2.61799388E+00  2.61799388E+00  3.14159265E+00  0.00000000E+00  3.14159265E+00
    ...

I don't _think_ this causes any issues with pmemd on its own, or at least it does not immediately crash.

Moving on to the next issue, **when using `gromber`, do I need to manually add in the water H-H bonds in order for pmemd to recognize and the water and apply SETTLE?** During equilibration I noticed that my angle energy was unexpectedly high:

          A V E R A G E S   O V E R      20 S T E P S

     NSTEP =     5000   TIME(PS) =      20.000  TEMP(K) =   292.57  PRESS =     0.0
     Etot   =   -284463.8269  EKtot   =     78013.4865  EPtot      =   -362477.3134
     BOND   =       531.2039  ANGLE   =     28965.5407  DIHED      =       224.9290
     UB     =       149.1759  IMP     =        89.7466  CMAP       =       -79.7357
     1-4 NB =       379.9181  1-4 EEL =      4186.5056  VDWAALS    =     39002.0816
     EELEC  =   -436101.8740  EHBOND  =         0.0000  RESTRAINT  =       175.1949
     EAMBER (non-restraint)  =   -362652.5083
     Ewald error estimate:   0.4331E-04
     ------------------------------------------------------------------------------

and found that the H-O-H angle was present in the topology, and the H-H bond was not:

    > printDetails :1000
    ATOM  RES RESNAME NAME TYPE At.# LJ Radius LJ Depth    Mass  Charge
    4822 1000     SOL   OW   OT    8    1.7682   0.1521 15.9994 -0.8340
    4823 1000     SOL  HW1   HT    1    0.2245   0.0460  1.0080  0.4170
    4824 1000     SOL  HW2   HT    1    0.2245   0.0460  1.0080  0.4170

    > printBonds :1000
            Atom 1          Atom 2   R eq Frc Cnst
    4822 OW (  OT) 4823 HW1 (  HT) 0.9572 450.0000
    4822 OW (  OT) 4824 HW2 (  HT) 0.9572 450.0000

    > printAngles :1000
             Atom 1         Atom 2          Atom 3 Frc Cnst Theta eq
    4823 HW1 (  HT) 4822 OW (  OT) 4824 HW2 (  HT)  55.0000 104.5200

I didn't think the presence of the H-O-H bond is a problem, as it is present in my `chamber`-converted CHARMM36 topologies, but I believe the H-H bond is necessary. I added the H-H bonds in using ParmEd:

    setBond :SOL@HW1 :SOL@HW2 553.0000 1.5136

and found the angle energy to be much lower:

          A V E R A G E S   O V E R      20 S T E P S

     NSTEP =     5000   TIME(PS) =      20.000  TEMP(K) =   291.49  PRESS =     0.0
     Etot   =   -306266.8751  EKtot   =     66869.1244  EPtot      =   -373135.9995
     BOND   =       528.7839  ANGLE   =      1105.2877  DIHED      =       225.6424
     UB     =       146.4239  IMP     =        86.4114  CMAP       =       -79.7880
     1-4 NB =       385.0374  1-4 EEL =      4182.3996  VDWAALS    =     36328.0976
     EELEC  =   -416222.9378  EHBOND  =         0.0000  RESTRAINT  =       178.6425
     EAMBER (non-restraint)  =   -373314.6420
     Ewald error estimate:   0.5693E-04
     ------------------------------------------------------------------------------

and the SHAKE CPU timing to increase accordingly, from:

    |  NonSetup CPU Time in Major Routines, Average for All Tasks:
    |
    |     Routine           Sec        %
    |     ------------------------------
    |     DataDistrib      53.66   18.01
    |     Nonbond         227.52   76.38
    |     Bond              0.02    0.01
    |     Angle             1.47    0.49
    |     Dihedral          0.39    0.13
    |     Shake             3.34    1.12
    |     RunMD            11.46    3.85
    |     Other             0.01    0.00
    |     ------------------------------
    |     Total           297.87

to:

    |  NonSetup CPU Time in Major Routines, Average for All Tasks:
    |
    |     Routine           Sec        %
    |     ------------------------------
    |     DataDistrib      56.31   18.01
    |     Nonbond         227.01   72.61
    |     Bond              0.02    0.01
    |     Angle             1.44    0.46
    |     Dihedral          0.39    0.12
    |     Shake            16.22    5.19
    |     RunMD            11.25    3.60
    |     Other             0.01    0.00
    |     ------------------------------
    |     Total           312.65

However, relative to my earlier equilibration of this system with a `leap`-built ff15ipq/spceb topology, the above angle and SHAKE timings appear to be much larger:

    |  NonSetup CPU Time in Major Routines, Average for All Tasks:
    |
    |     Routine           Sec        %
    |     ------------------------------
    |     DataDistrib      56.45   19.38
    |     Nonbond         221.19   75.94
    |     Bond              0.02    0.01
    |     Angle             0.12    0.04
    |     Dihedral          0.48    0.16
    |     Shake             1.69    0.58
    |     RunMD            11.34    3.89
    |     Other             0.01    0.00
    |     ------------------------------
    |     Total           291.29

Is it possible that pmemd is still doing the math for the water angles, and is there an easy way to remove the water angles using ParmEd? Also, do the force constants for the water bonds matter, if they are being constrained? It looks to me like different MD packages all use different values for the force constants, while the other parameters remain consistent (after unit conversion).

Also, my ultimate goal here is to use TIP4P-D, although I thought I should get TIP3P working before adding the extra complication of the virtual site. Are there any further issues I might run into there that come to mind?

**Comment by swails** [comment]
> Is it possible that pmemd is still doing the math for the water angles, and is there an easy way to remove the water angles using ParmEd?

I don't think there's an easy way to do this.  But I actually think you can get around this fairly easily.  By default, if no defines are given to the GROMACS parser, it supplies `FLEXIBLE` automatically.  This causes bonds and/or angles to get inserted for water molecules instead of defining constraints (this is because programs like CHARMM and AMBER define constraints by using the bond terms, whereas GROMACS doesn't).

If you *avoid* this define, then ParmEd should just do the right thing and convert the GROMACS SETTLE definition into what Amber will understand.  So try adding a dummy define to the `gromber` command:

```
gromber define DUMMY <rest of your gromber arguments>
```

This *should* prevent ParmEd from inserting any water angles at all.  I think what the timings you're seeing are pointing out is that adding the bond is making pmemd use SHAKE on waters when it *should* be using SETTLE (which it will do only for residues recognized as "water", so if the water residue and atom names do not match WATNAM and OWTNM/HWTNM1 etc. as described in the Amber manual, pmemd will do the wrong thing).  What's more is that pmemd.cuda doesn't support SHAKEing water molecules, since it assumes hydrogen has only one bond.  That water models define two bonds per hydrogen doesn't matter if you use SETTLE instead of SHAKE.  This is a frequent problem with chamber, and IIRC GROMACS uses "SOL" as the water name instead of the typical Amber convention of "WAT".

> Also, do the force constants for the water bonds matter, if they are being constrained?

Yes and no.  In principle, no.  In practice, you might run into problems getting SHAKE to converge if your force constants are too high.  However, if you use SETTLE (which is analytical), then it makes no difference.

**Comment by KarlTDebiec** [comment]
Thanks! Adding `define DUMMY` to my `gromber` command worked perfectly:

    |  NonSetup CPU Time in Major Routines, Average for All Tasks:
    |
    |     Routine           Sec        %
    |     ------------------------------
    |     DataDistrib      52.99   18.04
    |     Nonbond         227.29   77.40
    |     Bond              0.02    0.01
    |     Angle             0.12    0.04
    |     Dihedral          0.38    0.13
    |     Shake             1.64    0.56
    |     RunMD            11.22    3.82
    |     Other             0.01    0.00
    |     ------------------------------
    |     Total           293.66

I recall running into the WATNAM issue with `chamber`-converted systems earlier. For this system, since I needed to open up the parmtop to edit the torsions anyway, I just renamed the water to WAT, O, H1, and H2 manually.

Since it appeared that the CHARMM22\*/TIP3P system was converted correctly, I went ahead and converted my CHARMM22\*/TIP4P-D system the same way:

    |  NonSetup CPU Time in Major Routines, Average for All Tasks:
    |
    |     Routine           Sec        %
    |     ------------------------------
    |     DataDistrib      74.87   17.70
    |     Nonbond         329.95   78.01
    |     Bond              0.02    0.00
    |     Angle             0.12    0.03
    |     Dihedral          0.39    0.09
    |     Shake             1.82    0.43
    |     RunMD            15.78    3.73
    |     Other             0.01    0.00
    |     ------------------------------
    |     Total           422.96

All indications are that it is working correctly. Comparing my results from `pmemd.cuda` (12 ns thus far ) to a simulation of this system I had previously run on Anton (29 ns, using the CHARMM22* and TIP4P-D developers' implementation of their models), the system volume is within 0.25%, and the backbone Φ/Ψ sampling is consistent.

Thanks for your help with this.
