### ISSUE TITLE
pdb: wrong atom number in 2nd column

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#708]
seems that parmed counts the `TER` as an atom

cpptraj
----------
```python
ATOM   5287  H2  WAT  1702       4.179   1.963   5.991  1.00  0.00           H
TER    5288      WAT  1702
ATOM   5288  O   WAT  1703      10.065   8.044  33.232  1.00  0.00           O
ATOM   5289  H1  WAT  1703      10.159   8.414  34.110  1.00  0.00           H
ATOM   5290  H2  WAT  1703      10.683   8.540  32.695  1.00  0.00           H
TER    5291      WAT  1703
ATOM   5291  O   WAT  1704       0.523   8.479  18.051  1.00  0.00           O
ATOM   5292  H1  WAT  1704       0.131   9.024  17.368  1.00  0.00           H
ATOM   5293  H2  WAT  1704      -0.178   8.360  18.693  1.00  0.00           H
END
```

parmed
-----------
```python
HETATM 6976  H2  WAT  1702       4.179   1.963   5.991  1.00  0.00           H
TER    6977      WAT  1702
HETATM 6978  O   WAT  1703      10.065   8.044  33.232  1.00  0.00           O
HETATM 6979  H1  WAT  1703      10.159   8.414  34.110  1.00  0.00           H
HETATM 6980  H2  WAT  1703      10.683   8.540  32.695  1.00  0.00           H
TER    6981      WAT  1703
HETATM 6982  O   WAT  1704       0.523   8.479  18.051  1.00  0.00           O
HETATM 6983  H1  WAT  1704       0.131   9.024  17.368  1.00  0.00           H
HETATM 6984  H2  WAT  1704      -0.178   8.360  18.693  1.00  0.00           H
END
```

```python
$ python -c 'import parmed as pmd; print(pmd.__version__)'
2.5.1+22.geb6a465
```

**Comment by hainm** [comment]
script
--------


```python
$ cat save_pdb.sh
#!/bin/sh

cpptraj <<EOF
parm tz2.ortho.parm7
trajin tz2.ortho.nc 1 1
trajout tz2.cpptraj.pdb
EOF

tail tz2.cpptraj.pdb

python <<EOF
import parmed as pmd
pmd.load_file("tz2.cpptraj.pdb").save("tz2.parmed.pdb", overwrite=True)
EOF

tail tz2.parmed.pdb
```

**Comment by swails** [comment]
ParmEd does [what the PDB does](http://files.rcsb.org/view/1HRH.pdb), so I'm satisfied with the current behavior.  I actually [had to go out of my way](https://github.com/ParmEd/ParmEd/blob/master/parmed/formats/pdb.py#L850-L854) to make sure that `TER` records incremented the atom counter, so this is the behavior I want.

**Comment by hainm** [comment]
oh cool. I should ping @drroe here. Although cpptraj and ParmEd have different aim but it's nice to have agreement. @Dan: What do you think about adding it to cpptraj? Or may be cpptraj has it but I don't know (try to look at test folder for pdb writing).

**Comment by drroe** [comment]
> What do you think about adding it to cpptraj? Or may be cpptraj has it but I don't know (try to look at test folder for pdb writing).

Try the manual :-)

"teradvance: Increment record (atom) number for TER records (not done by default)." (29.8.5.1. options for pdb format)

@dacase specifically requested at one point that this be the default behavior for cpptraj. The reason is that if you don't increment the atom counter on TER cards it's easy to see how many actual atoms you have in the PDB.

**Comment by hainm** [comment]
Yeah, I agree about the actual atom number point, easy to tail. (That's why I opened this issue in ParmEd). Thanks all.
