### ISSUE TITLE
should update doc for pdb writing?

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#709]
`parm.save('test.pdb')` will write a bunch of models in a single pdb file if `parm.get_coordinates().shape[0] > 1`. 

May be adding this behaviour to doc? http://parmed.github.io/ParmEd/html/api/parmed/parmed.formats.pdb.html#parmed.formats.pdb.CIFFile.write

**Comment by swails** [comment]
Sounds good.
