### ISSUE TITLE
Additional validation for CHARMM conversion via TopoGromacs?

### ISSUE THREAD

**Issue by davidlmobley** [ParmEd/ParmEd#711]
The new VMD plugin TopoGromacs apparently handles CHARMM to GROMACS conversion. Perhaps this would provide a way to further validate the CHARMM conversion facilities? http://pubs.acs.org/doi/abs/10.1021/acs.jcim.6b00103

**Comment by swails** [comment]
CHARMM -> GROMACS is actually an easy conversion that ParmEd doesn't have problems with.  It's also been validated indirectly via OpenMM, Amber, and GROMACS.  OpenMM and Amber comparisons have been validated directly against CHARMM and shown to produce identical results (Amber gives results identical out to full double precision thanks to some tweaks to the standard prmtop format).  And OpenMM out to the precision model used in the calculation.

What is less-thoroughly validated is going to CHARMM.  Presumably that would be easier now that slowCHARMM is free to download and use, but I have no idea how to use it and no longer have time to learn that kind of stuff.  We got close with Alex's group, but there's simply less demand for converting to CHARMM among circles where ParmEd is known and used (mostly people are interested in converting from CHARMM to Amber, GROMACS, or OpenMM).

**Comment by davidlmobley** [comment]
Sounds good, thanks. So this can be closed. :)

DM


On Tue, May 24, 2016 at 7:19 AM, Jason Swails <notifications@github.com>
wrote:

> CHARMM -> GROMACS is actually an easy conversion that ParmEd doesn't have
> problems with. It's also been validated indirectly via OpenMM, Amber, and
> GROMACS. OpenMM and Amber comparisons have been validated directly against
> CHARMM and shown to produce identical results (Amber gives results
> identical out to full double precision thanks to some tweaks to the
> standard prmtop format). And OpenMM out to the precision model used in the
> calculation.
>
> What is less-thoroughly validated is going to CHARMM. Presumably that
> would be easier now that slowCHARMM is free to download and use, but I have
> no idea how to use it and no longer have time to learn that kind of stuff.
> We got close with Alex's group, but there's simply less demand for
> converting to CHARMM among circles where ParmEd is known and used (mostly
> people are interested in converting from CHARMM to Amber, GROMACS, or
> OpenMM).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ParmEd/ParmEd/issues/711#issuecomment-221285948>
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436
