### ISSUE TITLE
Issues in running CHARMM on ParmEd output

### ISSUE THREAD

**Issue by mrshirts** [ParmEd/ParmEd#715]
I'm having problems running CHARMM on my outputs from Parmet. The PSF files were generated by the command structure.save(charmm_output_psf, format='psf',overwrite=True), where charmm_output_psf is the filename saved to. I didn't see other options to use.

are generated with lines like:

         1 SYS      1        CLP      C1       C3LTU   -0.003799       12.0100

However, these seem to be throwing errors of the type:

    At line 246 of file /home/mish4610/software/charmm/source/io/psfres.src (unit = 90, file = 'CBC-G1/CBC-G1_converted.psf')
    Fortran runtime error: Bad value during integer read

Where that specific line 246 is:
              read(u,fmt01a,end=6) &
                   ii,lsegid,lresid,lres,atype(i),iac(i), &
                   cg(i),amass(i),imove(i),ech(i),eha(i)

Which seems to expect three more integers after the atomic mass. I thought about finding another read mode, but I can't seem to find any of them that expect amass(i) as the last argument.  Looking at PSFFile, there doesn't seem to be other ways to write the psffile atom records, that don't just end in the mass.

In contrast, I found a psf file with atom entries of the type 

         1 A        1        OAH      C1       CG2R61    0.00000       12.0110           0   0.00000     -0.301140E-02

Seemed to be read fine, with energies generated correctly. 

Any hints or ideas for getting energies out?  Perhaps there's some logic to the code I'm missing, and there's a flag that things would run correctly with?

Thanks!

**Comment by swails** [comment]
There are typically some flags (like EXT) on the first line of the PSF files.  What are the differences between the file that works and the one that doesn't?  Those flags might trigger different code paths.

I'm not sure if the failed integer read is coming from the atom type, or one of the "missing" fields.  Another thing to try is to copy the last 3 fields that are present in the working PSF to the end of the atom records in the one that ParmEd prints and see if that fixes it.

As an aside, do you have any insight into what imove, ech, and eha are?  I have a guess for imove (a flag that indicates whether an atom's position is constrained or not).

**Comment by mrshirts** [comment]
Apparently, if I change PSF CHEQ EXT to PSF CHEQ EXT XPLOR on the first line, then it reads the psf.  Thanks for the suggestion.  Do you think this should be a change that goes into the main code?

No idea what imove, ech, and eha are.  I've never used CHARMM before this week, and had to get some working example files from Frank Picard.

**Comment by swails** [comment]
OK, that makes sense.  Atom types are integers traditionally in CHARMM, but the "XPLOR" format uses atom type names (strings) instead.  So that XPLOR flag is telling CHARMM to read atom types as strings rather than integers (hence the failed integer read).

So I need to have ParmEd figure out whether its atom types are strings or integers and write XPLOR if it's the former.  In the meantime, go head and add XPLOR to the header manually.

**Comment by swails** [comment]
I can also ask Frank what imove, ech, and eha are (or Andrew Simonett would probably know, too).
