### ISSUE TITLE
Convert Topology Gromacs -> Amber - Ligand not defined

### ISSUE THREAD

**Issue by julimox** [ParmEd/ParmEd#720]
Hello,

I want to convert my gromacs topology to amber topology but somehow I don't manage to include my ligand.itp file. What am I doing wrong?

Thank you for your help and best regards,
Julian

PS: I tried several ways, one of them was this

``` python
import parmed as pmd 
mol = pmd.gromacs.GROMACS_TOPDIR = 'ligand.itp'
parm = pmd.load_file('protein_ligand.top', xyz='protein_ligand.pdb')
parm.save('protein_ligand_amber.top', format='amber')
parm.save('protein_ligand_amber.crd', format='rst7')
```

gives

parmed.exceptions.GromacsError: Structure contains MOL molecules, but no template defined

**Comment by swails** [comment]
Your second line is wrong.  `pmd.gromacs.GROMACS_TOPDIR` needs to be a *directory* where the topology files are located.  Instead, you set the variable "mol" and the GROMACS_TOPDIR to the string 'ligand.itp', which will certainly not do what you want.

In general, you should not have to change GROMACS_TOPDIR unless GROMACS is not in your PATH (then it should be set to something like GROMACS_BASEDIR/share/gromacs/top).  You need to make sure that `ligand.itp` is in a directory where the preprocessor can find it (either the current working directory or something referenced by GROMACS_TOPDIR).

Also, you need to make sure that you actually include the file in your GROMACS topology file.  That is, the following line should appear somewhere:

```
#include "ligand.itp"
```

If this doesn't occur, then ParmEd won't even know it should be including that file (and nor will GROMACS, for that matter).

**Comment by julimox** [comment]
Thank you for your answer! In the end my mistake was that in ligand.itp the ligand was indicated as "mol" and not "MOL". I want to convert my Gromacs files to Amber in order to use SPAM and since you are the developper of Spam I have a few quick questions:
- I have Spam from this [post](http://archive.ambermd.org/201401/0290.html) - is there any updated version that you could share?
- You mention that Spam is not working on Ambertools13 and needs Ambertools12 instead. A colleague of mine told me that he had it running using Ambertools15. Do you know whether it is also working with the latest version Ambertools16?
Thank you very much and best wishes,
Julian

**Comment by drroe** [comment]
> You mention that Spam is not working on Ambertools13 and needs Ambertools12 instead. A colleague of mine told me that he had it running using Ambertools15. Do you know whether it is also working with the latest version Ambertools16?

SPAM should be working in cpptraj as of AmberTools 14 and beyond (AmberTools 16 is currently the most up-to-date version). If this is not the case for you please open an issue on the cpptraj GitHub page so I can fix it. :-)

**Comment by swails** [comment]
I think this has been resolved?
