### ISSUE TITLE
GROMACS->Amber for dodecahedron

### ISSUE THREAD

**Issue by rolandschulz** [ParmEd/ParmEd#724]
I'm trying to convert a GROMACS topology with rhombic dodecahedron to Amber. The generated amber topology file has ifbox=2 which is incorrect. And Amber complains that the box doesn't have the 109 angle for truncated octahedral (which it should for ifbox=2).

**Comment by drroe** [comment]
Hmm - I'd be curious to see if the box settings become "fixed" after running through cpptraj. Something like:
```
parm MyParm.parm7
trajin MyCoords.rst7
trajout cpptraj.rst7
run
parmwrite out cpptraj.parm7
```

**Comment by swails** [comment]
What should ifbox be? 3?

There shouldn't be anything special about a truncated octahedron in terms of imaging that wouldn't work for any triclinic shape. So that error message in Amber is probably unnecessary.

**Comment by drroe** [comment]
> What should ifbox be? 3?

Yeah, that's the general triclinic. I think that the code for writing out a truncated octahedral cell doesn't work for every triclinic shape, so `ifbox` needs to be 3 if it's not trunc. oct.

**Comment by swails** [comment]
But the code inside sander and pmemd should be identical...

I'll fix this to output 3, though.
