### ISSUE TITLE
Converted name into CHARMM format apparently can't be read by CHARMM

### ISSUE THREAD

**Issue by mrshirts** [ParmEd/ParmEd#727]
One of the atom types created on the production if CHARMM files from an AMBER structure apparently has an illegal name.  The NA+ name in AMBER apparently leads to a CHARMM atom type NA+LTU (appearing in the .psf, .rtf, and .prm files), which is not recognized by CHARMM.  

I get the error: 

   PARRDR> WARNING: ATOM FOR NBOND NA+L DOESNT EXIST
   ****\*  WARNING  ****\* PARRDR no nonbond parameters for atom type:  15  NA+L
   NO nonbond interactions will be computed for this atom type.

Which I missed before, since the simulations seemed to run fine.

I have verified that if I simply change NA+LTU to NALTU (or to NALTUU, so the length remains constant), the it reads it just fine, so I think it may just be that '+' is an illegal character. 

Jason, this error should appear in the files I sent you earlier.

The only thing different is that I am now using the following input file (yes, the .crd file is actually called .par in the set I sent you -- I've now corrected it in the code for future runs, but left it the same here to be consistent).

   ! CHARMM Energy for CBC-G1.inp
   open read card unit 10 name "CBC-G1.rtf"
   read rtf card unit 10
   open read card unit 20 name "CBC-G1.prm"
   read para card unit 20
   read psf card name "CBC-G1.psf"
   read coor card name "CBC-G1.par"
   read coor card comp name "CBC-G1.par"
   crystal define cubic 40.25360320 40.25360320 40.25360320 90.00000000 90.00000000 90.00000000
   crystal build noper 0
   nbond inbfrq -1 imgfrq -1  -
   elec ewald pmew fftx 48 ffty 48 fftz 48 kappa 0.20822755 order 4 -
   vdw vatom lrc cutnb 15. cutim 15. ctofnb 15. ctonnb 15.
   energy
  stop

**Comment by swails** [comment]
#728 claims that this was fixed by that PR.  If I recall, I think it was.  If I'm mistaken, feel free to reopen.
