### ISSUE TITLE
Issue with the way parmed interprets the command line

### ISSUE THREAD

**Issue by mrshirts** [ParmEd/ParmEd#729]
ParmEd, when printing .top files (perhaps other files) prints the command line that the ParmEd file was called with in a comment. The converter I am using that calls Parmed include some options with strings that include newlines (since I'm passing in nonbonded parameters lines for files.  However, when printing to the .top file, it prints the newline literally (rather than \n), resulting in an uncommented line in the .top file that can't be interpreted. 

Any thoughts on a good way to resolve this?

**Comment by ctk3b** [comment]
Without testing, I THINK that modifying this [line](https://github.com/ParmEd/ParmEd/blob/master/parmed/gromacs/gromacstop.py#L1372) to print `r' '.join(sys.argv)` should do the trick.

**Comment by ctk3b** [comment]
Or perhaps using string escape: http://stackoverflow.com/a/15392758/2597468

**Comment by mrshirts** [comment]
OK, changing the line 1372 in parmed/gromacs/gromacstop.py

From:        

gmx.GROMACS_TOPDIR, ' '.join(sys.argv)))

To: 

gmx.GROMACS_TOPDIR, (' '.join(sys.argv)).encode('string_escape')))

Does indeed work.  The first fix does not seem to work (though I might have misread it).

**Comment by swails** [comment]
Glad this got figured out!

Any chance one of you could pr this?

**Comment by ctk3b** [comment]
#730 seems to do the trick.

**Comment by mrshirts** [comment]
Thanks Christoph!
