### ISSUE TITLE
add alternate atom label when writing to pdb file from LES parm7 + rst7?

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#733]
currently, with a given LES parm7 and rst7, I got 

```bash
...
ATOM     16  CE  LYS     1      -0.975   8.165  10.101  0.00  0.00           C  
ATOM     17  CE  LYS     1      -0.963   8.369  10.347  0.00  0.00           C  
ATOM     18  HE2 LYS     1      -0.780   9.159  10.504  0.00  0.00           H  
ATOM     19  HE2 LYS     1      -2.034   8.549  10.446  0.00  0.00           H  
ATOM     20  HE3 LYS     1      -0.339   8.047   9.224  0.00  0.00           H  
ATOM     21  HE3 LYS     1      -0.454   9.229  10.782  0.00  0.00           H  
ATOM     22  NZ  LYS     1      -2.393   8.077   9.689  0.00  0.00           N  
ATOM     23  NZ  LYS     1      -0.618   8.282   8.901  0.00  0.00           N  
```

do you want to add code to add 'A, B, ...' labels for alternative atoms?

```bash
ATOM     16  CE ALYS     1      -0.975   8.165  10.101  0.00  0.00           C
ATOM     17  CE BLYS     1      -0.963   8.369  10.347  0.00  0.00           C
ATOM     18  HE2ALYS     1      -0.780   9.159  10.504  0.00  0.00           H
ATOM     19  HE2BLYS     1      -2.034   8.549  10.446  0.00  0.00           H
ATOM     20  HE3ALYS     1      -0.339   8.047   9.224  0.00  0.00           H
ATOM     21  HE3BLYS     1      -0.454   9.229  10.782  0.00  0.00           H
ATOM     22  NZ ALYS     1      -2.393   8.077   9.689  0.00  0.00           N
ATOM     23  NZ BLYS     1      -0.618   8.282   8.901  0.00  0.00           N
```
related to cpptraj issue: https://github.com/Amber-MD/cpptraj/issues/388

**Comment by hainm** [comment]
I already have a working code, just want to ask if you would like to have it in ParmEd.

If yes, what's your favorite syntax?

```python
parm.write_pdb('new.pdb', label_alternates=True)
```
?

**Comment by swails** [comment]
I'd rather it just *write* the alternates.  How did you do this, by the way?  Because each `Atom` has an `other_atoms` dict that maps the label (e.g., 'B') with an `Atom` instance of its alternate location.

The PDB writer should automatically write them as alternate locations so long as the LES prmtop parser puts duplicated atoms in the `other_atoms` attributes of the atoms they were duplicated from instead of the main `parm.atoms` list.

**Comment by hainm** [comment]
>  How did you do this, by the way? Because each Atom has an other_atoms dict that maps the label (e.g., 'B') with an Atom instance of its alternate location.

something like
```python
if is_les(atom):
    atom.altloc = label
# where label is A, B, ...
```

> The PDB writer should automatically write them as alternate locations so long as the LES prmtop parser puts duplicated atoms in the other_atoms attributes of the atoms they were duplicated from instead of the main parm.atoms list.

So if you have two atoms

```bash
ATOM     22  NZ  LYS     1      -2.393   8.077   9.689  0.00  0.00           N  
ATOM     23  NZ  LYS     1      -0.618   8.282   8.901  0.00  0.00           N  
```

how do you decide put which atom in which atom? and do you need to delete atoms from `parm.atoms`?

**Comment by hainm** [comment]
below is the real code
```python
def get_atom_dict_for_amber_parm(parm, resids):
  """

  Parameters
  ----------
  parm : parmed's Structure, read from AMBER's prmtop
  resids: residue indices
  """
  atom_dict = defaultdict(list)

  for resid in resids:
    atom_dict[resid] = defaultdict(list)
    residue = parm.residues[resid]

    for atom in residue.atoms:
      atom_dict[resid][atom.name].append(atom)

  return atom_dict

def label_alternates(parm):
  """

  Parameters
  ----------
  parm : parmed's Structure
      parm should have duplicated atom name. This function will
      assign label A, B, ...

  Returns
  -------
  out : updated `parm`

  Examples
  --------
  >>> parm = label_alternates(parm)
  >>> parm.write_pdb("corrected_label.pdb", altlocs='all')
  """
  resids = range(len(parm.residues))
  atom_with_residue_dict = get_atom_dict_for_amber_parm(parm, resids=resids)

  possible_labels = list('ABCDEF')

  for _, adict in atom_with_residue_dict.items():
    for atom_name, atom_list in adict.items():
      if len(atom_list) > 1:
        # if there is alternate atom
        for atom, label in zip(atom_list, possible_labels):
          atom.altloc = label

  return parm
```

**Comment by swails** [comment]
> how do you decide put which atom in which atom? and do you need to delete atoms from `parm.atoms`?

It doesn't *really* matter, but whatever will be given the label `A` should be in the `parm.atoms` list, and whatever is given a label with another letter should be in the `other_atoms` of the atom it duplicates.

**Comment by swails** [comment]
And yes, you would need to delete those atoms from `parm.atoms` (or, preferably, not add them to `parm.atoms` in the first place :smiley:)

**Comment by hainm** [comment]
> And yes, you would need to delete those atoms from parm.atoms

yeah, this is what I don't want to do (because I am not sure if I need to do anything else like renumber the atom.idx, ...). I tried `atom.altloc = label` and that works. lol. Just want you to confirm that.

**Comment by swails** [comment]
That works.  Can you apply those labels inside the processing routine of AmberParm?

**Comment by hainm** [comment]
ok. I will make a PR and you can make comment there.

**Comment by hainm** [comment]
but wait, what if a pdb file has that duplicate atom name?

**Comment by swails** [comment]
> but wait, what if a pdb file has that duplicate atom name?

Example?

**Comment by hainm** [comment]
> Example?

from my top post. :D 

but nvm, I can add to AmberParm.

**Comment by swails** [comment]
I don't understand.  I thought that the duplicate names existed only because they weren't given altloc identifiers?  If they're given altloc identifiers, they're no longer "identical names" -- they're alternate locations for the same atom.  Am I missing something?

**Comment by hainm** [comment]
for example, if you convert LES parm7 and rst7 file by cpptraj to pdb file, the output pdb will have atoms having the same name.

**Comment by hainm** [comment]
that's why I opened an issue in `cpptraj` too: https://github.com/Amber-MD/cpptraj/issues/388

**Comment by hainm** [comment]
good for review now #735

**Comment by swails** [comment]
Done in #735
