### ISSUE TITLE
add action: copy coordinates?

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#739]
Given that I have a parm7 file and a phenix pdb from refinement. Sometimes the atom orders from that pdb is different from parm7. Do you think we should add an action to ParmEd so we can update parm7's coordinates to write a new pdb file with same atom order? (I already have the code).

**Comment by swails** [comment]
There is already an `addPDB` command that does most of this work.  This could probably be done inside the PDB writer pretty easily doing something like this:

```python
for residue in struct.residues:
    for atom in sorted(residue.atoms, key=lambda a: (a.number, a.idx)):
        ... write to the PDB
```

Where `atom.number` is set by the `addPDB` command by matching it to a PDB file.

**Comment by hainm** [comment]
What's about the syntax?

parm.write_pdb(filename, template=...) ?

Hai

**Comment by swails** [comment]
Have you checked that this is not already possible by setting `renumber = False`?

Look at [the code here](https://github.com/ParmEd/ParmEd/blob/master/parmed/formats/pdb.py#L787-L790) and you can see where the suggestion I made above has already been implemented for awhile...

**Comment by hainm** [comment]
Thanks. Sorry for my laziness since i am using phone now. Will look later. :d

**Comment by swails** [comment]
Any update on this?

**Comment by hainm** [comment]
Sorry, I have no progress on this.

**Comment by swails** [comment]
[This is already supported](https://github.com/ParmEd/ParmEd/blob/master/parmed/formats/pdb.py#L836) with the `renumber=False` option.

Closing this.
