### ISSUE TITLE
update doc for visualization

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#752]
note for myself.

**Comment by hainm** [comment]
example:

![viz_min](https://cloud.githubusercontent.com/assets/4451957/19615862/4d51522e-97d4-11e6-84f8-12b39e49af77.png)

**Comment by swails** [comment]
Did you ever do this?

**Comment by hainm** [comment]
low priority for me right now. Still fighting with amber build and phenix stuff. Please just leave it open.

**Comment by hainm** [comment]
done #792
