### ISSUE TITLE
parmed.version returns old version number in master branch

### ISSUE THREAD

**Issue by wesbarnett** [ParmEd/ParmEd#755]
This [project](https://github.com/MobleyLab/SolvationToolkit) requires at least ParmEd v. 2.5.10, so I've cloned ParmEd and run `python setup.py install`. When I print out `parmed.version` I get `version(major=2, minor=4, patchlevel=0)`. That's older than the latest release.

**Comment by swails** [comment]
Do you maybe have AmberTools installed with a `PYTHONPATH` that is causing that `parmed` to override the one you installed from GitHub?

**Comment by swails** [comment]
You can check this via the following:

```python
import parmed as pmd
print(pmd.version)
print(pmd.__file__)
```

Make sure the location of the file is where you expect it to be :wink:

**Comment by hainm** [comment]
Likely you are using parmed from amberhome like Jason said. I got this many times.

**Comment by wesbarnett** [comment]
Yes, `PYTHONPATH` was pointing to AmberTools. Thanks!
