### ISSUE TITLE
cut release

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#758]
Jason, 

can you make a release now? phenix will be released by the end of this month and need to use new ParmEd code for LES stuff. thanks.

**Comment by swails** [comment]
Sure.

**Comment by hainm** [comment]
Thanks. Just remind you about the tag name. :d

**Comment by swails** [comment]
I'll cut a release after #760 (and merge it back into Amber and update the amber-md fork).

Also, the tag name will be 2.6.0.  It's been awhile since the last release and you added some nice stuff.

**Comment by swails** [comment]
Done in https://github.com/ParmEd/ParmEd/releases/tag/2.6.0

**Comment by hainm** [comment]
thanks.

**Comment by swails** [comment]
Also now updated in the Amber git repo.

**Comment by hainm** [comment]
@swails can you update note about LES stuff (as a reference for phenix development)

https://github.com/ParmEd/ParmEd/releases/tag/2.6.0
