### ISSUE TITLE
add more examples?

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#766]
I think the best way for new users to learn is to read small example?

What do  you think about adding to 
https://github.com/ParmEd/ParmEd/tree/master/examples

Reading ParmEd's website or its code is ok but quite scary (code) or scattering (website) for beginner.

Or I just dump everything to: https://github.com/hainm/parmed-contrib

**Comment by swails** [comment]
Isn't this the same as #458 and #127?

**Comment by swails** [comment]
Although responding to the question, I'm all for adding examples, but I don't really have the time for that anymore.

Anyone that wants to add some are welcome, though.

**Comment by hainm** [comment]
oh boy. lol. I opened so many similar issues.

> I'm all for adding examples

I can add more. Just ask you first. lol. What's your opinion about folder's name?

**Comment by hainm** [comment]
btw, #458 is adding example to the doc.

**Comment by hainm** [comment]
For example, 

adding `TER`
```python
import parmed as pmd

parm = pmd.download_PDB('2igd')
asu_n_residues = len(parm.residues)

parm = parm * 4
for index in range(4):
    res_ter = parm.residues[asu_n_residues*(index+1) - 1]
    res_ter.ter = True
parm.save('test.pdb', overwrite=True)
```

(I used that script to build UnitCell for phenix).

**Comment by hainm** [comment]
seems like this issue won't be resolved by me. Sorry.
