### ISSUE TITLE
conda packages releases

### ISSUE THREAD

**Issue by jchodera** [ParmEd/ParmEd#768]
Can you guys help us make sure the conda package releases for `parmed` stay up to date? It looks like the latest conda release is [2.5.1](https://github.com/omnia-md/conda-recipes/blob/master/parmed/meta.yaml). I'm happy to help if you just let me know when we need to update.

**Comment by swails** [comment]
Sure, whenever I cut a release I will post an issue on omnia-md/conda-recipes.  Do you want me to do that now?

It would be very helpful if you could update the ParmEd recipe there.

**Comment by jchodera** [comment]
Works for me! 

For now, I'll build both 2.6.0 and 2.6.1

**Comment by swails** [comment]
Why not just 2.6.1?  It's only one commit ahead of 2.6.0 and fixes an irritating (but minor) bug

**Comment by jchodera** [comment]
Completeness? Shouldn't be a hassle to do both.

**Comment by hainm** [comment]
@swails pypi too: https://pypi.python.org/pypi/ParmEd/
