### ISSUE TITLE
RuntimeError: Cannot set cell lengths on old restart

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#778]
Hi

I got this error when trying to setting box for rst7 file
```python
In [9]: x = pmd.load_file('./1gdu_asu.rst7')
In [10]: x.box = x.box
```
trace
```bash
    390     def cell_lengths(self, stuff):
    391         if self._status == 'old':
--> 392             raise RuntimeError('Cannot set cell lengths on old restart')
    393         if not self._coords_written:
    394             raise RuntimeError('Coordinates must be written before box')
```

The I was trying to set `x._status='new'` but getting new error
```bash
RuntimeError: Coordinates must be written before box
```

Is this expected? If yes, then why is it?

**Comment by swails** [comment]
Sorry, I never responded here.  If you look at the setters for these attributes, they write the values to file when you set them.  Since the format of the Amber restart file is the following:

```
title
natom
x1 y1 z1 x2 y2 z2
...
[vx1 vy1 vz1 vx2 vy2 vz2
...]
[a b c alpha beta gamma]
```

You need to set the coordinates first, the velocities next (if you want to add velocities) and the unit cell last.  Not the best API choice, but one that I made early on.  I would recommend against using that class directly -- just work with Structure or AmberParm instead.

**Comment by swails** [comment]
So yes, this is expected.

**Comment by hainm** [comment]
The thing is  I do not use that class directly. I used load_file to read rst7 file and got that class.

So how can I make my example in my 1st post work?

**Comment by hainm** [comment]
So I assuming that there is structure=True option for that class (just like loading mol2 file)?

**Comment by hainm** [comment]
@swails: what's your thought here?

Adding `structure=True` is easy enough (I do have working code), just ask about API.

**Comment by swails** [comment]
The API on this file sucks, but I'm wary of changing it.

What ParmEd needs is a little bit of pytraj (without the added dependency).  It should have a "trajectory-like" class that is simply a container for phase space configurations (box, velocities, and coordinates) and have a `save` attribute that spits out any supported file types.

Then all of the trajectory parsers should create an instance of that class (or subclass) when parsing.

But that's a much bigger undertaking, and fairly low priority given that the aim is not to replace pytraj, and pytraj can already do this.

If you already have working code, though, feel free to raise a PR and I'll have a look.

**Comment by hainm** [comment]
> What ParmEd needs is a little bit of pytraj (without the added dependency). It should have a "trajectory-like" class that is simply a container for phase space configurations (box, velocities, and coordinates) and have a save attribute that spits out any supported file types.

yeah, this is what exactly I want for `parmed.Structure`.

useful for:
- easy to use it to build something
- close to pytraj, mdtraj... (which is easier to NOT learn new thing)
- ...

> If you already have working code, though, feel free to raise a PR and I'll have a look.

I have it here: #818

**Comment by hainm** [comment]
done in #818.
