### ISSUE TITLE
Updates to OpenMM Bond

### ISSUE THREAD

**Issue by jchodera** [ParmEd/ParmEd#779]
We're running into a new issue with [`perses`](https://travis-ci.org/choderalab/perses/jobs/175942379#L896-L911) that may be caused by https://github.com/pandegroup/openmm/pull/1668
```
======================================================================
ERROR: Abbreviated version of test_mutate_all for travis.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/perses/tests/test_geometry_engine.py", line 191, in test_mutate_quick
    new_positions, logp = geometry_engine.propose(pm_top_proposal, current_positions, beta)
  File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/perses/rjmc/geometry.py", line 116, in propose
    structure = parmed.openmm.load_topology(top_proposal.old_topology, top_proposal.old_system)
  File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/parmed/utils/decorators.py", line 31, in new_fcn
    return fcn(*args, **kwargs)
  File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/parmed/openmm/topsystem.py", line 92, in load_topology
    struct.bonds.append(Bond(atommap[a1], atommap[a2]))
KeyError: <Atom 1 (CH3) of chain 0 residue 0 (ACE)>
-------------------- >> begin captured logging << --------------------
```
It looks like the private API change in https://github.com/pandegroup/openmm/pull/1668 has broken the ParmEd release we're using (the latest conda version, 2.6.1).

Tagging @pgrinaway.

**Comment by swails** [comment]
If you roll back OpenMM before that PR was merged, does the test pass?

**Comment by jchodera** [comment]
According to our travis history, that test broke between yesterday (Thu Feb  5 15:09:33 UTC 2015) and today, which is when that merge occurred.

I'm not sure *how* it caused the code to break, though.

**Comment by swails** [comment]
It *shouldn't* have...

**Comment by jchodera** [comment]
Looks like the [parmed nightly builds are erroring](https://travis-ci.org/ParmEd/ParmEd) but for different reasons.

**Comment by jchodera** [comment]
Your travis tests [don't use OpenMM???](https://travis-ci.org/ParmEd/ParmEd/jobs/175725743#L1288-L1291)
```
Test error handling in load_topology ... SKIP: Cannot test without OpenMM
Test loading extra bonds not in Topology ... SKIP: Cannot test without OpenMM
Test Nonbonded exception handling with virtual sites ... SKIP: Cannot test without OpenMM
Tests assignment of 2-particle virtual site ... SKIP: Cannot test without OpenMM
```
Though I guess you probably wouldn't want to use the nightly `dev` label builds of `openmm` anyway...

**Comment by swails** [comment]
The way this piece of code works is that it takes every Atom in an OpenMM `Topology` and creates a ParmEd `Atom` with the same attributes (where applicable).  It then builds a dictionary where the `Topology` atoms are keys paired to the ParmEd `Atom` that was generated.

Then it loops through all of the bonds in the `Topology`, extracts the atoms in the bond (by unpacking the tuple, which still works), and then builds a ParmEd `Bond` from the two corresponding ParmEd `Atom` instances that correspond to the OpenMM `Atom` instances in the atommap dict pairing the two.

**Comment by jchodera** [comment]
So the only way it could fail is if the OpenMM atom wasn't in `openmm_topology.atoms()`? Hm...

**Comment by swails** [comment]
The map is built by iterating through all of the atoms in all of the residues in all of the chains and adding those to the map.

The KeyError you're getting is because *somehow* there is a reference to an `Atom` in one of the Topology's Bonds that is not in the atom list.  There is something very wrong there, and I don't think it has to do with the changes in the recent OpenMM PR.

**Comment by jchodera** [comment]
You might be right. Certainly suspicious timing, since the last merge to our codebase was 12 days ago, and that test has been passing every day since that merge until today (except for weird anaconda issues).

Will keep looking and reopen if needed.

**Comment by swails** [comment]
> Your travis tests don't use OpenMM???

I have a build matrix.  Some of the builds use OpenMM + pysander + Amber + pandas + scipy + netCDF4 + most other optional dependencies, some don't.

I want to make sure that ParmEd doesn't fall on its face if you don't have an optional dependency.

**Comment by jchodera** [comment]
Ah! Thanks for clarification.

**Comment by swails** [comment]
> Though I guess you probably wouldn't want to use the nightly dev label builds of openmm anyway...

I used to use the openmm-dev conda package, but those builds were so unreliable as to make my automated testing largely worthless.  So I dropped back to using the release conda package that I could rely on not getting frequently erased.

**Comment by jchodera** [comment]
> I used to use the openmm-dev conda package, but those builds were so unreliable as to make my automated testing largely worthless. So I dropped back to using the release conda package that I could rely on not getting frequently erased.

Stability has been better after anaconda cloud fixed some issues.

**Comment by swails** [comment]
Then it's probably fine to go back to openmm-dev.

Also, the ParmEd build failure is for a PR that hasn't been merged yet (the aim of that PR is to clean up the flood of warnings that get dumped to the logs).  master is not failing AFAIK.
