### ISSUE TITLE
Enable fancy indexing for `Structure`

### ISSUE THREAD

**Issue by swails** [ParmEd/ParmEd#78]
One thing that would be nice when manipulating structures is to make them indexable and slice-able.  Here are some ideas, all of which can be implemented side-by-side based on the argument type of the indexer:

- `struct[str]` -- Treat the string as an Amber selection mask
- `struct[int|slice|iter]` -- Select atoms. If it's an `int`, get a single atom. If it's a `slice`, get that slice of atoms.  If it's an iterable, make sure it's length `natom` and return the atoms whose indices evaluate to `True`.
- `struct[int|slice|iter, int|slice|iter]` -- First item in tuple is a residue selector.  Second item in tuple is an atom selector, whose semantics are identical to the last bullet.
- `struct[int|slice|iter, int|slice|iter, int|slice|iter]` -- First item in tuple is now a chain selector. Second item in tuple is a residue selector. Third item in the tuple is an atom selector.  Again, identical semantics as above.

A couple comments:

- Amber masks do not make sense in the context of the chain, residue, and atom slicing, so it is an independent mode.
- The duplication of the topology and parameter data means the slicing will be pretty slow, so that should be kept in mind.
- The idea is that the resulting selection will be a data copy (not much you can do to get around that within the current framework), but it will be a full description with force field and topology data (assuming it originally came with that), so you can immediately dispatch it to OpenMM or the sander API to carry out MM investigations.

If anyone else cares about this feature, input is welcome.

**Comment by hainm** [comment]
this will be great feature if you consider adding.

I've been playing with `chemistry` and sometimes just want to do `parm[index]`, 

in pytraj,

I can do (although I don't want to spend so much time on this fancy stuff because I prefer to use ParmEd for Topology processing)
    * parm['@CA'], parm[100], parm[list_of_indices], ...

I also would like ParmEd has `parm['@CA'].indices` returning indices of selected atoms and I will feed this to pytraj.

Hai

**Comment by swails** [comment]
Implemented by #110
