### ISSUE TITLE
[interactive mode] kicked if Ctrl-C when doing minimization

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#782]
e.g:

```bash
>>> minimize igb 8 maxcyc 1000000
```

then if I Ctrl-C, I would be kicked out of parmed terminal.

**Comment by swails** [comment]
That's always true.

**Comment by hainm** [comment]
do you mean it's expected? Just a bit annoying when I want to stop the minimization and need to retype all the commands again.

**Comment by swails** [comment]
you can always source the log :)

But yes, "ctrl-C" quits the application that is running.  Stopping the minimization and dropping back to the parmed interpreter is not necessarily straightforward.  It might leave the parm object in a weird state if it's being modified in-place (I'm not sure if that's what's happening or not).

**Comment by hainm** [comment]
thanks. Please leave this open in case I might want to work on this.

**Comment by swails** [comment]
There are a couple ways this could be done:

1. Spawn the minimization in a separate process (via `multiprocessing`), then register a new SIGINT handler (via `signal.signal`) that calls `terminate` on the spawned process (risks leaving stuff in a weird state)
1. Register a signal handler inside the `minimize` function that just returns from the function if SIGINT is caught *after* resetting the handler to quit

The second is probably more straightforward if it works.

**Comment by hainm** [comment]
> The second is probably more straightforward if it works.

sounds good to me. I actually tried with Python's threading for ParmEd but quite busy with other stuff so did not have time to review it. :D

**Comment by swails** [comment]
I do not think this is worth doing.  It could seriously mess up the sander internals if it aborts in the middle (since `Process.terminate` does not actually call destructors, even if a call is put inside a context manager).  It's all done in the same thread, so it doesn't really make sense that Ctrl-C *wouldn't* end the whole process (including the ParmEd interpreter).
