### ISSUE TITLE
Problems when writing and then reading a prmtop and crd from a Structure

### ISSUE THREAD

**Issue by davidlmobley** [ParmEd/ParmEd#784]
I'm attempting to convert an OpenMM system we created from our new SMIRFF forcefield format into AMBER format via ParmEd, and successfully am able to write a `prmtop` and `crd` with ParmEd, but when I load them again, I get this error:

```
/Users/dmobley/anaconda/lib/python2.7/site-packages/simtk/openmm/openmm.pyc in addException(self, particle1, particle2, chargeProd, sigma, epsilon, replace)
  14854             the index of the exception that was added
  14855         """
> 14856         return _openmm.NonbondedForce_addException(self, particle1, particle2, chargeProd, sigma, epsilon, replace)
  14857 
  14858 

Exception: NonbondedForce: There is already an exception for particles 2612 and 2615
```

I'm attaching the prmtop and crd in question which I'm trying to load. The issue can be reproduced by using:
`structure = parmed.amber.AmberParm( 'system.prmtop', 'system.crd')`

It seems possible there are actually two issues -- i.e. it's possible something is amiss in MY `System` which results in an incorrect prmtop and crd being written that then can't be read back in properly. However, it's probably a ParmEd bug that the system WRITES properly but fails on read.

If you'd like to see this in context, I have an IPython notebook in the `issue184` branch of `smarty` which is where I discovered the problem. I'm attempting to convert a simple mixture of cyclohexane and ethanol from being an OpenMM system into an AMBER prmtop and crd. Here's the IPython notebook: https://github.com/open-forcefield-group/smarty/blob/issue184/examples/testing/test_system_conversion/convert_to_amber.ipynb
and here's the branch (see `smarty/examples/testing/test_system_conversion` for input files): https://github.com/open-forcefield-group/smarty/tree/issue184

[Archive.zip](https://github.com/ParmEd/ParmEd/files/607403/Archive.zip)

**Comment by davidlmobley** [comment]
I'll update shortly -- I may be on to an explanation.

**Comment by davidlmobley** [comment]
Ah, OK. It turns out this is NOT a ParmEd issue but an OpenMM issue -- it seems I was using `app.AmberPrmtopFile('system.prmtop')` to re-load the prmtop and then create a system, and this fails; however, the ParmEd approach quoted above actually works fine. Marking as closed.

**Comment by swails** [comment]
This is what I've observed so far is happening:

1. You read in an OpenMM Topology and System and create a ParmEd `Structure` from those, then write it out to an Amber prmtop (and restart) file.
1. You read in that prmtop file and inpcrd file using OpenMM's `AmberPrmtopFile` reader to create the system.
1. Creating the `System` from the prmtop file fails because the same 1-4 exception is defined twice.

That would indicate to me that the 1-4 pair builder messed up somewhere.  It would be interesting to figure out why OpenMM thought the same 1-4 pair should have been included in two exceptions.  There is a bug *somewhere*, I'm just not sure where or why.

**Comment by davidlmobley** [comment]
Yes, @swails -- I agree with this assessment:

> That would indicate to me that the 1-4 pair builder messed up somewhere. It would be interesting to figure out why OpenMM thought the same 1-4 pair should have been included in two exceptions. There is a bug somewhere, I'm just not sure where or why.

I'm happy to try and track it down if you have any suggestions, otherwise I'll proceed with tracking down my more immediate issues (trying to make sure I get the same energies in OpenMM before and after visiting AMBER format in between) which might or might not lead me to resolve this same issue.

**Comment by swails** [comment]
OK, I think I might have narrowed down the problem.  GROMACS and ParmEd have different ways of tracking 1-4 exception parameters.  GROMACS does it through an explicit list, ParmEd encodes it into their bond, angle, and torsion lists.

What this means is that when ParmEd sees an exception that does not have a bond, angle, or dihedral explicitly defined in a GROMACS topology file, it adds a "dummy" one with a force constant of 0 specifically to get the exceptions to work out right.  It was tricky to get that part right.

However, it seems like it's getting confused somewhere, as the duplicate torsion terms that result in multiple 1-4 exceptions have one torsion with a force constant of 0.  So I think ParmEd feels the need to add exceptions where they shouldn't need to be added.  I would need to see the original Topology and System so I can debug what is happening.

**Comment by davidlmobley** [comment]
@swails - what's the easiest way to get you the original Topology and System? They are created in the IPython notebook I pointed you to, but I'm unsure if I can dump them out to some sort of archive file and send them? Would pickling work properly? (Sorry, I'm still a bit of an OpenMM newb).

**Comment by davidlmobley** [comment]
(Sorry, accidentally re-opened.)

**Comment by swails** [comment]
I don't know if pickling will work.  But you can send me the files necessary to create the topology from OpenMM (basically the files that I can run through your notebook to repro the exception)

**Comment by davidlmobley** [comment]
I don't think I can do that unless you have the OpenEye tools, as our `smarty` toolkit relies on these to generate the OpenMM system. Should I try pickling or is there something else I could dump to from within OpenMM?

(@jchodera, insights?)

**Comment by davidlmobley** [comment]
@swails - I've put serialized versions of the OpenMM systems in question here: https://github.com/open-forcefield-group/smarty/pull/187, see https://github.com/open-forcefield-group/smarty/pull/187#issuecomment-262417103

**Comment by davidlmobley** [comment]
As noted over on `smarty`, there are other issues I'm having with this "write out and then read back in" process, which is why @swails reopened this issue.
