### ISSUE TITLE
Writing out an OpenMM system to AMBER and reading back in results in a 1-4 scaling factor issue

### ISSUE THREAD

**Issue by davidlmobley** [ParmEd/ParmEd#790]
When writing out AMBER prmtop/crd files from an OpenMM system and reading them in again, I'm having two problems which seem likely to be related:
1. Writing my original system to AMBER prmtop/crd, reading it back in, and cross-checking energies before and after the write yields a missing factor of 0.83333 in the 1-4 Coulomb interactions.
2. Writing my system to serialized XML (to allow you to load it) before and after reading from AMBER format also yields different nonbonded energies 

This was discussed some in #784 and https://github.com/open-forcefield-group/smarty/pull/187 . I suspect the issue, at least in case #1, is inside ParmEd somewhere (https://github.com/open-forcefield-group/smarty/pull/187#issuecomment-262381974).  However, this is a slightly tricky problem for you to reproduce exactly as my test case begins with an OpenMM system parameterized from our SMIRFF format, which requires the OpenEye toolkits (though I note they are free for academics).

However, I think you can reproduce at least the second issue using this code to cross-compare energies, and the attached files: 
```python
from simtk.openmm.app import PDBFile
from simtk.openmm import XmlSerializer
from simtk.openmm.app import Topology
from simtk import openmm
# I might be missing a couple of imports here
smirff_system = XmlSerializer.deserialize(serialized_system_smirff)
amber_system = XmlSerializer.deserialize(serialized_system_amber)
pdbfile = PDBFile('cyclohexane_ethanol_0.4_0.6.pdb')

# Do an energy comparison
timestep = 1.0 * unit.femtoseconds
integrator0 = simtk.openmm.VerletIntegrator( timestep )
integrator1 = simtk.openmm.VerletIntegrator( timestep )
platform = simtk.openmm.Platform.getPlatformByName("Reference")
positions = pdbfile.positions
simulation0 = app.Simulation( pdbfile.topology, smirff_system, integrator0, platform = platform )
simulation0.context.setPositions(positions)
simulation1 = app.Simulation( parm.topology, amber_system, integrator1, platform = platform )
simulation1.context.setPositions(positions)
syscheck = system_checker.SystemChecker( simulation0, simulation1 )
groups0, groups1 = syscheck.check_energy_groups(skip_assert = False)
energy0, energy1 = syscheck.check_energies(skip_assert = False)
```

@swails - have you already verified that taking an OpenMM system from some other format (say, GROMACS), writing to AMBER format, and reading it back in results in the same energies before and after conversion? I routinely verify the reverse (AMBER -> GROMACS and reading back in) yields the same energies, but I have not done the reverse. If you're not checking it, I should probably start there as it might allow me to construct a more minimal example of the problem.

It's also possible that for debugging purposes, I could temporarily give you access to a group server where you can use our software license to reproduce the problem in item 1 above. Let me know.

Files for the example:
[cyclohexane_ethanol_0.4_0.6.pdb.zip](https://github.com/ParmEd/ParmEd/files/632690/cyclohexane_ethanol_0.4_0.6.pdb.zip)
[XML_systems.zip](https://github.com/ParmEd/ParmEd/files/632691/XML_systems.zip)

**Comment by davidlmobley** [comment]
Here's the code used in item 1, though as noted you can't use it unless you have the OpenEye tookits:  https://github.com/open-forcefield-group/smarty/pull/187#issuecomment-262381974

**Comment by swails** [comment]
GROMACS <-> Amber works in both directions for a large number of systems using both the Amber and CHARMM force fields.  I can also get Amber -> GROMACS -> Amber to work.

However, I'm not seeing the issue that you're seeing.  Based on the files you sent me before, I created two systems:

1. Using the system directly from `smarty_system.xml`
1. Using `swails.mol2` + `smarty_system.xml`, converting that to a prmtop, reading that back in, and calling `createSystem` on that object directly.

Both of these systems give me the same energy.  Here is my script:

```python
In [2]: import parmed as pmd
      : omm = pmd.openmm.load_topology(pmd.load_file('swails.mol2', structure=True).topology, pmd.load_file('smarty_system.xml'))
      : omm.save('test.parm7', overwrite=True)
      : omm.coordinates = pmd.load_file('swails.mol2', structure=True).coordinates
      : omm.save('test.rst7', overwrite=True)
      : parm = pmd.load_file('test.parm7', 'test.rst7')
      : omm.coordinates = parm.coordinates # Make sure coordinates are identical
      : 
      : 

In [3]: pmd.openmm.energy_decomposition_system(omm, pmd.load_file('smarty_system.xml')) # Use the OpenMM System directly
Out[3]: 
[('HarmonicBondForce', 42.56419725029097),
 ('HarmonicAngleForce', 109.54929865539138),
 ('PeriodicTorsionForce', 381.41869738246396),
 ('NonbondedForce', 12147.284220929932),
 ('CMMotionRemover', 0.0)]

In [4]: pmd.openmm.energy_decomposition_system(parm, parm.createSystem())
Out[4]: 
[('HarmonicBondForce', 42.564197250290974),
 ('HarmonicAngleForce', 109.54929866522606),
 ('PeriodicTorsionForce', 381.4186968652314),
 ('NonbondedForce', 12147.284217827897),
 ('CMMotionRemover', 0.0)]
```

The code to add 1-4 scaling factors based on explicit nonbonded exceptions was something we had to get working to enable GROMACS -> Amber conversions, so I'm reasonably confident that is being done correctly.

You can also check the prmtop file that gets generated and see that the SCEE section is filled with 1.2s (except for a few torsions that are assigned to dihedrals whose end-group interactions are excluded from the nonbonded sum -- those are left as 1).

Are you sure the problem is with the 1-4 electrostatic scaling factors?

**Comment by davidlmobley** [comment]
@swails - I'm looking into this now. But, you said you tried:
> 1. Using the system directly from smarty_system.xml
> 2. Using swails.mol2 + smarty_system.xml, converting that to a prmtop, reading that back in, and calling createSystem on that object directly.

Can you check using the system directly from `smarty_system.xml` versus using it from `amber_system.xml`? These should be the same system but on my computer they give different energies. They were obtained by (in the former case) taking my original OpenMM system and serializing to XML, and in the latter case, taken the original OpenMM system, writing to prmtop/crd with ParmEd, reading back in with ParmEd, THEN serializing to XML.

Here's how I got the `amber_systeml.xml` once I have my original OpenMM system, called `system`:
```python
structure = parmed.openmm.topsystem.load_topology( pdbfile.topology, system, pdbfile.positions)
structure.save('system.prmtop', overwrite=True)
structure.save('system.crd', format='rst7', overwrite=True)
parm = parmed.load_file('system.prmtop', 'system.crd')
ambersys = parm.createSystem(nonbondedMethod= app.NoCutoff, constraints = None, implicitSolvent = None)
from simtk.openmm import XmlSerializer
serialized_system_amber = XmlSerializer.serialize(ambersys)
outfile = open('amber_system.xml','w')
outfile.write(serialized_system_amber)
outfile.close()
```

Can you see whether those two result in different energies for you? In the meantime, I'll verify that your approach indeed results in the same energy for me.

**Comment by davidlmobley** [comment]
@swails - I verified that your example does yield identical energies for me. However, my example yields different energies if I add this code to yours:

```python
omm2 = pmd.openmm.load_topology(pmd.load_file('swails.mol2', structure=True).topology, pmd.load_file('amber_system.xml'))
omm2.coordinates = parm.coordinates
pmd.openmm.energy_decomposition_system(omm2, pmd.load_file('amber_system.xml'))
```
```
[('HarmonicBondForce', 42.56436386960996),
 ('HarmonicAngleForce', 109.54924584764584),
 ('PeriodicTorsionForce', 381.41867167565795),
 ('NonbondedForce', 13023.714183131233),
 ('CMMotionRemover', 0.0)]
```

Note substantial difference in NonbondedForce.

**Comment by davidlmobley** [comment]
UPDATE: I updated my comment above relating to 1-4 scaling; the 1-4 scaling factor issue now seems resolved, so this MAY entirely be an issue with serialization/deserialization in OpenMM now. I'll keep you posted, @swails

**Comment by davidlmobley** [comment]
Final update: I've re-generated the serialized XML files and now those yield identical energies as well. So, it seems I had some sort of problem generating my earlier files -- either a software version issue or a problem with intermediate files -- which I can no longer reproduce and everything is behaving properly now.

Sorry for all the false alarms. :( Thanks so much for your help, @swails .

**Comment by swails** [comment]
I purposely ignored the `amber_system.xml` file because I thought it was generated via the workflow:

OpenEye tools -> smarty -> OpenMM System -> ParmEd Structure -> AmberParm -> Amber XML

Since there was a problem that I fixed in the ParmEd Structure -> AmberParm conversion, that renders the Amber XML file incorrect, anyway.  Perhaps I misinterpreted what was happening?  But the main thing I wanted to be sure of is that you could go from OpenMM System XML to Amber topology file (and back via AmberParm's createSystem method) and get the same energy.

I *think* that route fully covers the conversion functionality you're trying to use, so I came to the conclusion that if that worked (which it did), then ParmEd did what you needed.
