### ISSUE TITLE
Cannot load topology from CPPTRAJ

### ISSUE THREAD

**Issue by drroe** [ParmEd/ParmEd#805]
(This will probably end up being an issue with the way CPPTRAJ is writing this particular topology, but I can't find anything wrong with it at first glance so I'm opening the issue here.)

I'm generating a topology (attached) 
[Closest2.withWater.parm7.zip](https://github.com/ParmEd/ParmEd/files/657630/Closest2.withWater.parm7.zip)

with CPPTRAJ that ends up being a little non-standard (for Amber) in that there is an ion in the middle of where the waters are. When I try to load this topology with parmed from the command line (several versions, including the latest) I get:
```
Traceback (most recent call last):
  File "/u/droe/.local/bin/parmed", line 11, in <module>
    load_entry_point('ParmEd==2.7.1', 'console_scripts', 'parmed')()
  File "/u/droe/.local/lib/python2.7/site-packages/ParmEd-2.7.1-py2.7-linux-x86_64.egg/parmed/scripts.py", line 128, in clapp
    amber_prmtop.add_parm(parm)
  File "/u/droe/.local/lib/python2.7/site-packages/ParmEd-2.7.1-py2.7-linux-x86_64.egg/parmed/tools/parmlist.py", line 43, in add_parm
    raise ParmError('Added parm must be Structure or a subclass')
parmed.tools.exceptions.ParmError: Added parm must be Structure or a subclass
```
From the parmed prompt, same thing:
```
> parm Closest2.withWater.parm7
Adding prmtop Closest2.withWater.parm7 to parm list. Closest2.withWater.parm7 is the active parm.
Action parm failed
	ParmError: Added parm must be Structure or a subclass
```
The topology can be loaded by CPPTRAJ and looks like this:
```
> parminfo
	Topology Closest2.withWater.parm7 contains 166 atoms.
		Title: Closest2Parm
		Original filename: Closest2.withWater.parm7
		18 residues.
		15 molecules.
		173 bonds (82 to H, 91 other).
		Box: Trunc. Oct.
		12 solvent molecules.
> resinfo
#Res  Name First  Last Natom #Orig  #Mol
    1 G5       1    32    32     1     1  
    2 A       33    65    33     2     1  
    3 C       66    96    31     3     1  
    4 C3      97   128    32     4     1  
    5 Na+    129   129     1     5     2  
    6 WAT    130   132     3     6     3  
    7 WAT    133   135     3     7     4  
    8 WAT    136   138     3     8     5  
    9 WAT    139   141     3     9     6  
   10 WAT    142   144     3    10     7  
   11 WAT    145   147     3    11     8  
   12 Na+    148   148     1    12     9  
   13 WAT    149   151     3    13    10  
   14 WAT    152   154     3    14    11  
   15 WAT    155   157     3    15    12  
   16 WAT    158   160     3    16    13  
   17 WAT    161   163     3    17    14  
   18 WAT    164   166     3    18    15  
```
Any ideas?

**Comment by swails** [comment]
The error message here is misleading because of how `parmed.load_file` works.  To load an Amber topology file, it basically has to check if it's one of 3 formats -- 'normal' Amber, chamber, or Amoeba Amber.  If it's not any of those, it just gives up and loads the raw data into a dictionary so it can be accessed.

However, that class (`AmberFormat`) does not derive from `Structure`, so the `parmed` program refuses to work with it.  So what this means is that something about that prmtop prevented it from being recognized as an Amber topology file.  The way to find out what is to load the prmtop directly into the `AmberParm` constructor and look at the resulting exception:

```python
>>> import parmed as pmd
>>> pmd.amber.AmberParm('Closest2.withWater.parm7')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch2/miniconda/envs/py35/lib/python3.5/site-packages/ParmEd-2.7.0-py3.5-linux-x86_64.egg/parmed/amber/_amberparm.py", line 182, in __init__
    self.initialize_topology(xyz, box)
  File "/scratch2/miniconda/envs/py35/lib/python3.5/site-packages/ParmEd-2.7.0-py3.5-linux-x86_64.egg/parmed/amber/_amberparm.py", line 213, in initialize_topology
    self.load_structure()
  File "/scratch2/miniconda/envs/py35/lib/python3.5/site-packages/ParmEd-2.7.0-py3.5-linux-x86_64.egg/parmed/amber/_amberparm.py", line 503, in load_structure
    self._check_section_lengths()
  File "/scratch2/miniconda/envs/py35/lib/python3.5/site-packages/ParmEd-2.7.0-py3.5-linux-x86_64.egg/parmed/amber/_amberparm.py", line 1271, in _check_section_lengths
    check_length('JOIN_ARRAY', natom)
  File "/scratch2/miniconda/envs/py35/lib/python3.5/site-packages/ParmEd-2.7.0-py3.5-linux-x86_64.egg/parmed/amber/_amberparm.py", line 1262, in check_length
    if len(self.parm_data[key]) != length:
KeyError: 'JOIN_ARRAY'
```

I believe that sander and pmemd read (and subsequently ignore) this array, but fails if it's not actually present in the topology file.  If you want a list of all of the FLAGs that ParmEd expects (and requires) Amber topology files to have, see [this part of the code](https://github.com/ParmEd/ParmEd/blob/master/parmed/amber/_amberparm.py#L1266-L1308). Anything that has a `False` there is not a required flag.  Anything else is.

**Comment by drroe** [comment]
I figured it was something like that. Any way to make the error message parmed kicks back for stuff like this a little more descriptive when loading from the command line or parmed prompt (for n00bs like me)? :-)

PS - How funny is it that there are these useless parts of the topology that sander/pmemd do not need (I think maybe ptraj too?) but fail if they aren't there anyway...

**Comment by drroe** [comment]
@swails Also, thanks for getting back to me so quickly!

**Comment by drroe** [comment]
OK, turns out I knew about this and consciously [disabled it for cpptraj](https://github.com/Amber-MD/cpptraj/blob/master/src/Parm_Amber.cpp#L1689-L1710). Guess I will reenable with a warning.

**Comment by swails** [comment]
Ah, the justification there makes sense.  The difference is one of mission -- ParmEd intends for you to use the prmtop files you create for simulation, whereas cpptraj, not always.

What were you trying to do that you needed to process a prmtop file that should not be used for simulation with ParmEd? I'd be interested to hear the use case.

**Comment by drroe** [comment]
I'm finding the closest ions to certain binding sites *and* retaining the closest waters around those ions. It's done via a combination of `closest` commands followed by `combinecrd` to get everything back together. `combinecrd` needs to be improved as well.

**Comment by swails** [comment]
I'm going to go ahead and close this.  #806 is the place-holder for the enhancement here.
