### ISSUE TITLE
Wrong number of REMARK entries for PSF? NAMD cannot read.

### ISSUE THREAD

**Issue by radakb** [ParmEd/ParmEd#807]
Loading and saving a PSF results in elimination of all REMARK entries (this is a feature, not a bug, yes?). However, the PSF written by ParmEd sets NTITLE as 1 and then an extra blanks line, which causes NAMD to crash with the following error:

Reason: FATAL ERROR: DIDN'T FIND "NATOM" IN PSF FILE

Presumably because the blank line is interpreted as white space, rather than a REMARK entry. Just manually adding a REMARK entry (and leaving NTITLE) unchanged) seems to solve the problem.

**Comment by swails** [comment]
This actually shouldn't happen, I don't think (it should retain title comments).

**Comment by radakb** [comment]
Yikes - I posted this a long time ago. 

For what it's worth, the problem appears to be use of save() (which has the behavior I reported) versus write_psf() (which has the behavior you say it should). Would I have known that if I were a more diligent reader of the documentation?

**Comment by swails** [comment]
Not sure -- `save()` is intended to be a general-purpose saver that is format-agnostic.  `write_psf` is for writing a PSF file from a PSF object.

Basically `save()` will cast to a PSF and then call `write_psf` (I think).  If the cast is lossy, then this could happen.

**Comment by radakb** [comment]
That indeed seems to be the case. I put a print statement inside PSFFile.write() while using save() and "struct.title" is indeed an empty string upon entering that function.

In any event, it's trivial to switch to write_psf() and that meets 100% of my usage needs.
