### ISSUE TITLE
better version for ParmEd in amber?

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#814]
```bash
In [4]: import parmed as pmd

In [5]: pmd
Out[5]: <module 'parmed' from '...amber_git/amber-phenix/lib/python2.7/site-packages/parmed/__init__.py'>

In [6]: pmd.__version__
Out[6]: '0+unknown'
```

If I went to the source folder
```bash
In [2]: pmd.__version__
Out[2]: '0+untagged.48704.g562d370.dirty'
```

**Comment by swails** [comment]
:).  I had been doing this by hand, but must have forgotten the last time.

This issue should disappear if we just make ParmEd a submodule.

**Comment by swails** [comment]
Done by hand, and this is a non-issue as a submodule.

**Comment by hainm** [comment]
@swails Can you reopen this issue. submodule does not help solving this. If we make the tarfile via mkrelease_at, there is no .git folder for ParmEd to check.

Just have a build today.
```bash
Installed /root/miniconda3/conda-bld/conda-recipe_1497199833710/work/lib/python2.7/site-packages/ParmEd-0+unknown-py2.7-linux-x86_64.egg
Processing dependencies for ParmEd==0+unknown
Finished processing dependencies for ParmEd==0+unknown
```

**Comment by swails** [comment]
Fix the mkrelease script to make a source distribution with setuptools.

**Comment by hainm** [comment]
I am very clear how to add that `sdist` to Amber tarfile and handle the folder name
(dist/ParmEd-2.7.3+165.g888e225.dirty.tar.gz)

I guess `mkrelease_at` can do
- `python setup.py sdist` to generate the `_version.py`; copy that file to ./parmed folder

**Comment by hainm** [comment]
here is a working code

```bash
(cd $AMBERHOME/AmberTools/src/parmed && 
 python setup.py sdist &&
 cd dist &&
 tar_parmed=`ls ParmEd*gz | sed "s/.tar.gz//g"` &&
 tar -xzf $tar_parmed.tar.gz $tar_parmed/parmed/_version.py &&
 cp $tar_parmed/parmed/_version.py ../parmed/ &&
 cd ../ && rm -rf ./dist
)
```

**Comment by hainm** [comment]
Ideally, we can update ParmEd's setup.py so that

```bash
python setup.py --write-version
```
