### ISSUE TITLE
Charmm to amber

### ISSUE THREAD

**Issue by paapu68** [ParmEd/ParmEd#816]
Dear All,

I try get from charm to amber. Is this possible with parmed or should one use chamber?

The parmed file so far:
```python
from __future__ import division, print_function
# ParmEd Imports
from parmed.charmm import CharmmPsfFile, CharmmCrdFile, CharmmParameterSet

print('Loading CHARMM files...')
param = CharmmParameterSet('plus27_24nov_MODIFIED.par',
                           'file top27_cox_5Jan_ALTERED.inp',
                           'top_all22_prot.inp')
psf = CharmmPsfFile('test_a.psf')
crd = CharmmCrdFile('test_a.crd')
```

I tried chamber but got issues with vdw:
```
# parmed -i charmm2amber.in
# Load the CHARMM files
chamber -top ../top27_cox_5Jan_ALTERED.inp -top ../top_all22_prot.inp -param ../plus27_24nov_MODIFIED.par -psf ../total.psf -crd ../total.crd
outpdb cox.pdb
parmout cox.prmtop cox.rst7
```

Output:
```
   NSTEP       ENERGY          RMS            GMAX         NAME    NUMBER
    573      -7.2894E+09     9.0730E+04     8.3885E+06     HD2      3746
 BOND    =   110454.4175  ANGLE   =     8230.8441  DIHED      =     4777.2773
 UB      =     1224.9982  IMP     =  3965634.9636  CMAP       =        0.0000
 VDWAALS = *************  EEL     =   -96605.0060  EGB        =   -15058.8345
 1-4 VDW = *************  1-4 EEL =    52677.0322  RESTRAINT  =        0.0000
```
So what would be the best option to proceed?
Terveisin, Markus

**Comment by swails** [comment]
I would suggest using the `chamber` action in the `parmed` program.  Note that it utilizes the only pathway to convert from CHARMM to Amber internally, so writing a Python script won't be able to "fix" the issues with the chamber conversion.

What is the output of ``parmed --version``?

**Comment by paapu68** [comment]
Thank's!
parmed --version parmed: Version 2.4.0

It was my mistake: some Charmm impropers were defined as 180deg which seems to be ok for Charmm, but not for Amber after the conversion.

So I just changed some charmm improper angles from 180 to 0 and 
chamber makes a perfect job.

Thank's for great programs and sorry for this question, it was my mistake, nothing wrong with chamber.

Terveisin, Markus

**Comment by swails** [comment]
Be careful changing parameters like that, since it can very easily change the whole force field. 

What you describe is a bug that was fixed recently, so if you update parmed to the latest version, it should work on the original files.
