### ISSUE TITLE
what does atom.xx, atom.xy, atom.xz mean?

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#817]
I know they are coordinates but why `xx`, `xy`, `xz`? Normally just `atom.x{y, z}` or `atom.coordinates` (tuple).

**Comment by swails** [comment]
x are for coordinates and v are for velocities. So xx, xy, and xx for coordinates. vex, vy, vz for velocities.

**Comment by hainm** [comment]
ah I see. thanks.
