### ISSUE TITLE
update water names from leap's solvents.lib?

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#829]
e.g: OPC, TP3, ...

what do you think?

**Comment by swails** [comment]
Why?  Those names should never make it into the Amber topology file.  Amber *needs* water names in the topology file to be named `WAT` for SETTLE to work.  What's the use case?

**Comment by hainm** [comment]
For some reasons `TP3` slipped into one of my pdb file. Will post here if I ever encounter again.

**Comment by swails** [comment]
OK, until then I'm going to close this.

**Comment by hainm** [comment]
Yeah
