### ISSUE TITLE
Is there a way to read a prep file into a ResidueTemplate?

### ISSUE THREAD

**Issue by dww100** [ParmEd/ParmEd#830]
I'm looking to generalise some old scripts building hybrid ligands from initial and final states contained in prep files. Is it possible to read these files in as input using ParmEd?

**Comment by swails** [comment]
No, but you can use tleap to convert them to a .lib or .mol2/mol3 file that ParmEd can then read.

There are really no plans to support the Amber prep file as it's a bit of work, and the goal is to get rid of the format.  (And there are straightforward workarounds for someone that has to work on old files).

I suggest using either the mol2 or mol3 file formats if you are automating a workflow.

**Comment by dww100** [comment]
Great - thanks
