### ISSUE TITLE
AttributeError after copying an AmberParm object

### ISSUE THREAD

**Issue by avirshup** [ParmEd/ParmEd#839]
Hi, I'm getting an AttributeError when trying to copy an `AmberParm` object created from a `prmtop` file. I get this behavior with version `2.5.1`, `2.7.3`, and with the current master branch (`ParmEd-2.7.3+31.gf5646cb`)

Here's the `prmtop` file I'm using: [prmtop.zip](https://github.com/ParmEd/ParmEd/files/789266/prmtop.zip)

**To reproduce**:
```python
import parmed
struc = parmed.load_file('prmtop')  # included above
struc = struc.copy(struc.__class__)  # it works if you remove this line
openmm_system = struc.createSystem()
```

It's raising this exception for me:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-f61ccb991e8d> in <module>()
      2 struc = parmed.load_file('/tmp/prmtop')  # included below
      3 struc = struc.copy(struc.__class__)
----> 4 openmm_system = struc_copy.createSystem()
<SNIP>
/usr/local/lib/python2.7/site-packages/parmed/amber/_amberparm.pyc in has_NBFIX(self)
    882             comb_sig = lambda sig1, sig2: sqrt(sig1 * sig2)
    883         fac = 2**(-1/6) * 2
--> 884         LJ_sigma = [x*fac for x in self.LJ_radius]
    885         pd = self.parm_data
    886         ntypes = self.parm_data['POINTERS'][NTYPES]

AttributeError: 'AmberParm' object has no attribute 'LJ_radius'
```

Trying to run `struc.recalculate_LJ()` produces this error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-11-16430b2c5ff1> in <module>()
----> 1 struc.recalculate_LJ()

/usr/local/lib/python2.7/site-packages/parmed/amber/_amberparm.pyc in recalculate_LJ(self)
    843             comb_sig = lambda sig1, sig2: sqrt(sig1 * sig2)
    844         pd = self.parm_data
--> 845         ntypes = self.pointers['NTYPES']
    846         fac = 2**(-1/6) * 2
    847         LJ_sigma = [x*fac for x in self.LJ_radius]

AttributeError: 'AmberParm' object has no attribute 'pointers'
```

Thanks - and please do let me know if I'm just doing something stupid :)

**Comment by swails** [comment]
I really should have made `Structure.copy` a private method ☹️ .  For copying you should use the `copy` module:

```python
import parmed
import copy
struc = parmed.load_file('prmtop')  # included above
struc = copy.copy(struc) # Use this approach for copying
openmm_system = struc.createSystem()
```

**Comment by hainm** [comment]
Does struct[:] work too?

**Comment by swails** [comment]
> Does struct[:] work too?

Yes, it should.

**Comment by hainm** [comment]
cool. save my typing.

**Comment by avirshup** [comment]
@swails - Perfect, that fixed it! For some reason, I had tried `struc.copy()`, and `copy.deepcopy(struc)`, but not just plain vanilla `copy.copy(struc)`.

**Comment by swails** [comment]
Did `copy.deepcopy` not work?  I would have expected that to work...

I had thought that if no `__deepcopy__` method was defined, it fell back to `__copy__` (which *is* defined).

**Comment by avirshup** [comment]
Yeah, surprisingly, deepcopy actually gave me the same behavior as `struc.copy(struc.__class__)`. (I think `__copy__` is allowed to return a shallow copy, which could be unpleasant if you were expecting a deepcopy.)

**Comment by swails** [comment]
hmm... well in this case `__copy__` really *is* a deep copy, so maybe I should implement a `__deepcopy__` that just invokes `__copy__`

**Comment by swails** [comment]
I'm going to close this, as it's resolved.
