### ISSUE TITLE
Adding two topologies give differentt Lennard Jones parameters

### ISSUE THREAD

**Issue by Steboss** [ParmEd/ParmEd#840]
Hi everyone,

I have a doubt about how Parmed deals with the Lennard Jones coefficients.
Basically, starting from a Na+ topology created with ```tleap```, I set the LJ sigma and epsilon to zero with parmed and save a new topology, with a new atom name and residue name ("du"). 
If I open this topology with parmed I can check effectively if sigma and epsilon are 0.0 : 

```
from parmed.amber import * 

#open the top and crd
base = AmberParm(TOP,CRD)

#select the atom I  set LJ to zero
base.residues[0].atoms[0].epsilon
0.0
base.residues[0].atoms[0].sigma
0.0
```

However, when I am inserting this zero LJ  atom in a new topology (for example a molecule "LIG" in a water box)- in this way:

```
#open the top and crd where we want to insert the zero LJ atom
base =AmberParm(top,crd)
#load the zero LJ atom top and crd
ion = AmberParm(iontop,ioncrd)
#take the zero LJ atom atom
add_atom = ion.residues[0].atoms[0]
#define the resname for this atom
resname="du"
#define the index for this atom
idx = idx
#add the atom 
base.add_atom(add_atom,resname,idx)
base.remake_parm()
base.write_parm("new.parm7")
base.write_rst7("new.rst7")
```
if I check "du" atom sigma and epsilon with parmed, by opening the new.parm7 and new.rst7, I have a non zero values both for sigma and for epsilon:

```
base.residues[2105].atoms[0].epsilon
0.10939999991572774

base.residues[2105].atoms[0].sigma
3.3996695084507405
```

Thus it is not clear to me why I have a non zero values for sigma and epsilon and where they come from
Where is my mistake?

I uploaded a zip with all the files:
-dummy.prmtop : the zero LJ atom prmtop (and zero charges as well) 
-dummy.rst7       : the zero LJ atom rst7
-original.top        : the Amber topology I would like to add the dummy atom
-original.crd        : restart coordiantes file 
-added.top         : the new topology once I have added the dummy ( in total I have 4 du in this top)
-added.crd         :  the coordinate file

Thanks very much

Stefano

[ParmedLJ.zip](https://github.com/ParmEd/ParmEd/files/793252/ParmedLJ.zip)

**Comment by swails** [comment]
> Thus it is not clear to me why I have a non zero values for sigma and epsilon and where they come from
> Where is my mistake?

The issue is subtle, but an `Atom` cannot "belong" to more than one `Structure`.  When it does, pointers can get crossed and you can get all kinds of weird and wonky behavior.

A better approach here would be to concatenate this extra atom as another `Structure` or to add an atom directly to the system.

For instance, try this script:

```python
#open the top and crd where we want to insert the zero LJ atom
base =AmberParm(top,crd)
#load the zero LJ atom top and crd
ion = AmberParm(iontop,ioncrd)
#take the zero LJ atom atom
dummy_atom_structure = ion[:1]
#define the resname for this atom
dummy_atom_structure.residues[0].name = 'du'
#add the atom 
base += dummy_atom_structure
base.remake_parm()
base.write_parm("new.parm7")
base.write_rst7("new.rst7")
```

See if that works for you.

**Comment by swails** [comment]
Actually it looks like this is hitting the bug #756...  Not sure if the above will work (but I *know* the approach of adding an atom the way you originally tried will cause problems).

**Comment by Steboss** [comment]
Thanks for your help @swails 
I have tried it but it does not work. Once I have the  new parameter file  "new.parm7" both epsilon and sigma of the dummy atom ("du") are different from 0.0 
Anyway, I was able to get what I want following your hint but without recreating the parm in parmed but using tleap :
```
#open the top and crd where we want to insert the zero LJ atom
base =AmberParm(top,crd)
#load the zero LJ atom top and crd
ion = AmberParm(iontop,ioncrd)
#take the zero LJ atom atom
dummy_atom_structure = ion[:1]
#define the resname for this atom
dummy_atom_structure.residues[0].name = 'du'
#add the atom 
base += dummy_atom_structure
#here I do not remake the parm or save it, instead I extract frcmod and off files
parmed.tools.writeFrcmod(base,"new.frcmod").execute()
#then extract off
parmed.tools.writeOFF(base,"new.off").execute()
#and create a mol2 file as a template for tleap
parmed.formats.Mol2File.write(base,"new.mol2")
```

After that I can load everyting in tleap and recreate a parameter file with the correct epsilon and sigma values for the dummy atom. 
There is a drawback: I have to use an additional script to "fix" the topology, in order to add the BOX informations (since I want to keep constant the number of water molecules )

**Comment by swails** [comment]
I think @jlmaccal's lab has done this in his MELD package.  The relevant code for adding a particle and setting its Lennard-Jones parameters is detailed [here](https://github.com/maccallumlab/meld/blob/master/meld/system/patchers.py#L137-L194).  The trick is to add an atom to the parm object *first*, then use `addLJType` to change its parameters.
