### ISSUE TITLE
hydrogen sulfide .prmtop and .inpcrd that wouldn't convert amber->charmm

### ISSUE THREAD

**Issue by mrshirts** [ParmEd/ParmEd#852]

**Comment by mrshirts** [comment]
When attempting to convert Amber parameters for H2S, I got an error that I didn't expect.

When calling:
        pmd.charmm.CharmmParameterSet.write(
            pmd.charmm.CharmmParameterSet.from_structure(amb_structure),
            top=charmm_output_rtf,
            par=charmm_output_prm)
  
I got the errors:

File "parmed/charmm/parameters.py", line 984, in write
    self._write_par_to(f)
  File "charmm/parameters.py", line 1023, in _write_par_to
    assert len(scee) == len(scnb) == 1, 'Mixed 1-4 scaling not supported'

Which I'm pretty sure is not mixed 1-4 scaling.  Looking at the .prmtop, I saw that   SCEE_SCALE_FACTOR and SCNB_SCALE_FACTOR were blank, which is probably what is causing the problems. . . . 

Files attached (with .txt appended so would be accepted).
[mobley_1929982.prmtop.txt](https://github.com/ParmEd/ParmEd/files/852996/mobley_1929982.prmtop.txt)
[mobley_1929982.inpcrd.txt](https://github.com/ParmEd/ParmEd/files/852997/mobley_1929982.inpcrd.txt)
[mobley_1929982.frcmod.txt](https://github.com/ParmEd/ParmEd/files/852998/mobley_1929982.frcmod.txt)

**Comment by swails** [comment]
Ugh, that should be <= 1, not == 1.

I'll fix this.  Thanks!

**Comment by swails** [comment]
And it also shouldn't be an `assert` :(

**Comment by swails** [comment]
Works for me with #853 -- thanks for the report!

**Comment by mrshirts** [comment]
Seems to have done the trick! Thanks!
