### ISSUE TITLE
Round-trip Amber-GROMACS-Amber does not always work

### ISSUE THREAD

**Issue by swails** [ParmEd/ParmEd#859]
See [the discussion here](https://github.com/ParmEd/ParmEd/pull/857#issuecomment-289968260)

**Comment by mrshirts** [comment]
So, it did work in 2.73 release and is broken now, so it's something that was changed in between.  Any thoughts before I dig in some more?

**Comment by swails** [comment]
A potential candidate for what broke things is #832 which is the first PR after 2.7.3 was cut.  Check out commit 6828756ddbd2582a039181b500e77b6809fe59a3 and see if it fails there.  If so, there was something that went wrong with the R-B --> proper dihedral conversion (which is continued in #845).

If it works after that change, next best candidate is #837

**Comment by swails** [comment]
I wonder if my latest fix to #845 solves this problem as well.  Can you try this again after that gets merged?

**Comment by mrshirts** [comment]
Downloading now seems to fix the problem.  I will run a larger test after look at a couple of other things and report back.

**Comment by mrshirts** [comment]
Seems to be working correctly with the latest master changes.

**Comment by swails** [comment]
Jackpot! I'll go ahead and close this then.
