### ISSUE TITLE
Improper ambiguity

### ISSUE THREAD

**Issue by ChayaSt** [ParmEd/ParmEd#866]
According to [this](https://github.com/ParmEd/ParmEd/blob/master/parmed/charmm/parameters.py#L553-L556) comment, the impropers are not always ordered with the central atom first so ParmEd just sorts the atom types and relies on the `psf` file to provide the order. 

In `psf`, it [checks for wildcards](https://github.com/ParmEd/ParmEd/blob/master/parmed/charmm/psf.py#L631-L642). However, there can be cases where this scheme leads to finding more than one improper that can match. 

For example, `GLU` has the [following](https://github.com/choderalab/openmm-forcefields/blob/master/charmm/toppar/top_all36_prot.rtf#L405) `IMPR`:
`IMPR CD CG OE2 OE1`
This corresponds to types: `'CC', 'CT2', 'OC', 'OC'`

Since some impropers have wildcards, and the types were sorted in ParmEd, there are 2 improper types this can match too:
`'CC', 'CT2', 'X', 'X'`
`CC', 'OC', 'X', 'X'`

The correct one is probably the second one, but since it breaks after the first match, it actually selects the first improper definition.

**Comment by jchodera** [comment]
@swails : Can you elaborate on when CHARMM seems to deviate from the requirement that the central atom is first? We think that the c36 parameter files require this.

**Comment by ChayaSt** [comment]
@jchodera, it seems like CHARMM deviates in the parameter definitions. 
The improper `C  CA  +N  O` is found in the [definitions](https://github.com/choderalab/openmm-forcefields/blob/master/charmm/toppar/par_all36_prot.prm#L2228) with `O` first. 
The fix for this can be:
if more than one definition matches:

- choose the one where the first two types match the first and last atom in the `IMPR` entry

**Comment by ChayaSt** [comment]
@swails, Currently, [these](https://github.com/choderalab/openmm-forcefields/blob/master/charmm/toppar/stream/prot/toppar_all36_prot_arg0.str#L417-L424) impropers are interpreted as periodic impropers in ParmEd. However, the parameters in the line above read `Kpsi   psi0` which suggest they're harmonic. Is there any reason for this?

**Comment by swails** [comment]
[here is the comment that explains why that distinction is made](https://github.com/ParmEd/ParmEd/blob/master/parmed/charmm/parameters.py#L542-L545)

**Comment by swails** [comment]
#865 made the comment that this is fixed. If not, feel free to reopen.
