### ISSUE TITLE
Selection masks containing the underscore symbol "_"

### ISSUE THREAD

**Issue by OleinikovasV** [ParmEd/ParmEd#869]
Drops an error whenever trying to select amber atom type containing "_", eg. scpe water oxygen atomtype "OW_s".

**Comment by swails** [comment]
I doubt this issue still exists.  There's an explicit test for masks with underscores that always passes before changes are merged in: https://github.com/ParmEd/ParmEd/blob/master/test/test_parmed_amber.py#L2027-L2034

What's more likely is that you are importing a very old version of ParmEd that still lives in your path.  The file paths in your error output indicate that the package was built with `distutils`.  However, ParmEd moved to `setuptools` quite awhile ago, so all of the pyc files should be inside an egg directory.

For instance, this is what I get on my machine:

```python
>>> import parmed as pmd
>>> pmd.__file__
'/scratch2/miniconda/envs/py35/lib/python3.5/site-packages/ParmEd-2.7.3+219.g3e92cd9c.dirty-py3.5-linux-x86_64.egg/parmed/__init__.py'
```

**Comment by OleinikovasV** [comment]
Thanks a lot! The issue was with using the omnia version of ParmEd, which is "2.7.3" but does not contain the most recent bug fixes.

**Comment by swails** [comment]
Sounds like I need to cut another release.
