### ISSUE TITLE
pytest style?

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#871]
what do you think about switching to pytest style?

```python
self.assertEqual(len(a), 2)
self.assertFalse(x)

assert len(a) == 2
assert not x
```

[unittest2pytest](https://github.com/pytest-dev/unittest2pytest) will do the conversion.

**Comment by swails** [comment]
Maybe if I was starting from scratch. Not worth the git history churn or effort to do it now. I have about 1000 tests and quite a few more assertions.

**Comment by hainm** [comment]
okie.
