### ISSUE TITLE
atom selection without slicing?

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#882]
Hi 
can you remind me if ParmEd has similar code like below?

```
atoms = parm.select(':1@H2R,H3R,H4R')
print([atom.bonds for atom in atoms]))
```

The `parm[...]` will delete the bond (of course)

related: https://github.com/Amber-MD/pytraj/issues/1385#issue-234840196

**Comment by swails** [comment]
Looking at the comment you linked to, the best thing to do would be to apply that selection on the view and then iterate through the atoms in that view and pull out the bond partners.  So something like this:

```python
from itertools import chain

parm = pmd.load_file('some_prmtop', 'some_inpcrd')
bonded_carbon_atoms = chain.from_iterable(
    [[bp for bp in a.bond_partners if bp.atomic_number == 6] for a in parm.view[':1@H2R,H3R,H4R']]
)
```

You could then get the index from all of those by `numbers = [a.idx for a in bonded_carbon_atoms]` and do whatever else you needed to.

**Comment by hainm** [comment]
cool. thanks.
