### ISSUE TITLE
Problems Recognising Chlorine Atoms in PSF files

### ISSUE THREAD

**Issue by leelasd** [ParmEd/ParmEd#897]
Hi,

I am trying to read a protein-ligand system PDB/PSF file with Parmed and It keeps failing with the following error message. I am attaching the PDB, PSF and par_oplsaa_aam.inp files. 

 Any suggestions on how to fix this are highly appreciated. 

[PL.zip](https://github.com/ParmEd/ParmEd/files/1308766/PL.zip)

```
Traceback (most recent call last):
  File "/Users/Sriram/anaconda3/lib/python3.5/site-packages/parmed/charmm/psf.py", line 527, in load_parameters
    atype = parmset.atom_types_str[atom.type]
KeyError: 'Cl83'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "MD_setup.py", line 41, in <module>
    switchDistance=9.0*u.angstroms,removeCMMotion=True,
  File "/Users/Sriram/anaconda3/lib/python3.5/site-packages/parmed/utils/decorators.py", line 31, in new_fcn
    return fcn(*args, **kwargs)
  File "/Users/Sriram/anaconda3/lib/python3.5/site-packages/parmed/charmm/psf.py", line 449, in createSystem
    if params is not None: self.load_parameters(params)
  File "/Users/Sriram/anaconda3/lib/python3.5/site-packages/parmed/charmm/psf.py", line 530, in load_parameters
    atom.type)
parmed.exceptions.ParameterError: Could not find atom type for Cl83
```

**Comment by swails** [comment]
The parameter set you are loading into your molecule does not contain any parameters for atom type `Cl83`.  If you look in your PSF file, you should see an atom with that type, but none of the prm or rtf files you loaded contain those atom type definitions.  Let me know if that's not the case (i.e., if there is a `Cl83` in any of your prm/rtf files).

However, what you need to do is find where this atom type is defined and load those parameter files into your `CharmmParameterSet` as well.

**Comment by leelasd** [comment]
Sorry for the late reply @swails 
I checked again. There are Cl83 types defined in atoms, bonds, angles, torsions and nonbonded terms. But it still gives an error saying it is not there. 
I did all the suggested things you mentioned, still this keeps happening. 
Can you please check and tell me if I am doing anything wrong ?

**Comment by swails** [comment]
I take that back, @KarlTDebiec made that change in 07ca1987b7a563146932edf742682940e73d99a8 -- I'll try and investigate to see why this was necessary.

**Comment by leelasd** [comment]
@swails  Thank you !! I will fix the missing angle. It's just weird that it happened. NAMD didn't complain or give any error. So I assumed everything is fine.

**Comment by swails** [comment]
Here's the PR where that discussion took place: #309 

I think we just have to take all atom type names to upper-case when looking for parameters in `load_parameters`.

**Comment by KarlTDebiec** [comment]
Interesting. Do I understand correctly that I got the top/par parsing to be case insensitive, but didn't think to do the psf parsing as well, leading to this issue?

**Comment by swails** [comment]
:smiley:
