### ISSUE TITLE
New release soon?

### ISSUE THREAD

**Issue by jchodera** [ParmEd/ParmEd#904]
Looks like it's been a while!
![image](https://user-images.githubusercontent.com/3656088/31040171-f2d292c2-a551-11e7-9b82-af0b44275c17.png)
Maybe we could cut a new release after getting the bugfixes in https://github.com/ParmEd/ParmEd/pull/895 wrapped up?

**Comment by swails** [comment]
Yes, I was planning one soon. Do you want to wait for #895?

**Comment by jchodera** [comment]
Yes please! Nearly done.

**Comment by swails** [comment]
Next release will be 3.0 -- #910 is a backwards-breaking change for the APIs in `parmed.tools` that is critical to getting that part to work with file paths containing spaces.

I'd like to merge all of the PRs that are currently open before I cut the new release.

**Comment by jchodera** [comment]
Phew---https://github.com/ParmEd/ParmEd/pull/895 should be ready to go, @swails.

**Comment by jchodera** [comment]
@swails : Any chance we could get a new release cut soon? We're getting close to the OpenMM 7.2 release, and it would be great to have a stable release out for reproducibility reasons.

**Comment by swails** [comment]
Just waiting on #926, which should be almost ready to go.  I'd also ideally like to get #915 fixed, too.  That might take too long, though.

**Comment by jchodera** [comment]
Update: Looks like #926 was closed in favor of #935. Does this look likely to be resolved soon?

**Comment by jchodera** [comment]
#935 was closed in favor of #936, which was merged!

@swails: Does that mean a release is imminent?

**Comment by jchodera** [comment]
@swails: Anything we can do to help with the release?

**Comment by swails** [comment]
Done. https://github.com/ParmEd/ParmEd/releases/tag/3.0.0

If you want to mine through the commit log and create a set of release notes, I'd be happy to add them.  It's too late to do that tonight, though.

**Comment by jchodera** [comment]
Thanks so much! Mind if we update the [`omnia` conda recipe](https://github.com/omnia-md/conda-recipes/tree/master/parmed) for you? @lnaden can help us with that.

The comparison with the previous release is so large that GitHub will only show me [the last 250 commits](https://github.com/ParmEd/ParmEd/compare/2.7.3...master), so I think it's going to take us a while to construct the release notes. Summarizing the PRs is probably the simplest route to making this work. How much detail is needed for each PR? Is the number and title sufficient?

**Comment by swails** [comment]
Yea, that’s more than enough.

**Comment by ctk3b** [comment]
This should help making the release notes: https://github.com/rmcgibbo/gh-util

**Comment by swails** [comment]
At least one new release has been cut since this issue.  Going ahead and closing this.

I'll be cutting a new release after AmberTools 19 is released next month.
