### ISSUE TITLE
Line continuation characters in CharmmFile and CharmmStreamFile

### ISSUE THREAD

**Issue by jchodera** [ParmEd/ParmEd#908]
CHARMM files seem to support `-` as an end-of-line continuation character.

Lines like [this](https://github.com/choderalab/openmm-forcefields/blob/master/charmm/toppar/stream/misc/toppar_ions_won.str#L498-L499) in are currently causing my conversions to OpenMM ffxml files to fail:
```
NONBONDED nbxmod  5 atom cdiel fshift vatom vdistance vfswitch -
cutnb 14.0 ctofnb 12.0 ctonnb 10.0 eps 1.0 e14fac 1.0 wmin 1.5
```
The cleanest way to handle this would be to update the various ways lines are read in [`parmed/charmm/_charmmfile.py`](https://github.com/ParmEd/ParmEd/blob/master/parmed/charmm/_charmmfile.py) to handle reading these extra lines and appending them correctly.

**Comment by jchodera** [comment]
@swails: I can implement this if you could give me some guidance as to the best way to do this in a general manner that won't break CHARMM reading more broadly.

**Comment by swails** [comment]
I started on it, but just need to modify `readline` to do the same (the `__iter__` generator of `CharmmFile` has already been modified).  It shouldn't be too much.

However, I was surprised that this problem popped up -- I've read those parameter files before and have never had problems. (Most prm files have the nonbonded keywords spread over multiple lines).

**Comment by jchodera** [comment]
I'm surprised this problem just cropped up as well. I believe the prm files had no issues but the *stream* files did have some issues. I'm not sure if this means that all the files were not being correctly processed before or if there's something odd with the order in which files are read in now.

**Comment by jchodera** [comment]
@swails : Is this something I can help with? Or are you trying to fix this in #910?

**Comment by jchodera** [comment]
If you need a test case to reproduce, let me know!

**Comment by jchodera** [comment]
FYI, I've just been running [this script](https://github.com/choderalab/openmm-forcefields/blob/charmm/charmm/convert_charmm.py) to convert the files specified in [`waters.yaml`](https://github.com/choderalab/openmm-forcefields/blob/charmm/charmm/files/waters.yaml) to encounter this failure.

**Comment by jchodera** [comment]
@swails : What do you want to do about this? Should I try to hack this in myself?

**Comment by swails** [comment]
I was wrapped up with #910 and the ridiculous number of changes needed to support file paths with spaces in them.  Apologies for not being on top of answering faster, but my already-limited time got more limited last week courtesy of a new baby (and our toddler isn't much help).

I made #914 on top of #910, but only the last commit is relevant to this issue.

**Comment by hainm** [comment]
>  new baby

wow, congrats.

**Comment by jchodera** [comment]
> new baby

Congratulations!!1!
