### ISSUE TITLE
dihedral func type 

### ISSUE THREAD

**Issue by qinghualiao** [ParmEd/ParmEd#920]
Hello,

Today I tried to converted the prmtop and inpcrd files of a small molecule into top and gro files in Gromacs format. Then I found that all the dihedral func types were set as 1, but the func type was re-assigned as 9 when all the parameters were passed to pdb2gmx. Actually, the function forms of 1 and 9 are the same, the only difference is func type 1 only take one set of parameters while func type 9 could take multiple sets of parameters. 

For example, the following parameters were obtained with parmed.
[ dihedrals ]
;    ai     aj     ak     al funct        
     11     13     15     17     1  0.00000  8.36800  1
     11     13     15     17     1  0.00000  8.36800  2
     11     13     15     17     1  0.00000  1.67360  3

The func type was set 1, and then I guess that only one parameter will be taken, but not all three for the dihedral. 1 should be corrected as 9, so that all three will be read.

Could you please also have a check? Thanks a lot! 

Best,
Qinghua

**Comment by swails** [comment]
If you set `inline=False`, then this should never happen.  My suspicion is that converting from an Amber topology file did not compress the torsion types to a Fourier series, but instead kept them as individual terms.  If the types are properly compressed (so that the Structure knows there are multiple terms in a particular type), then it properly assigns the "funct" value to 9.  Otherwise it sets it to 1.

**Comment by qinghualiao** [comment]
@swails Thanks a lot for the suggestion! What I did for the initial conversion is:
amber = pmd.load_file('mol.prmtop','mol.inpcrd')
#
amber.save('mol_gmx.top')
amber.save('mol_gmx.gro')

Then, I tried:
amber.save('mol_gmx.top', 'inline=false'), but it did not work.

Then I tried again:
amber.save('mol_gmx.top', 'parameters=false'), as inline is the default setting.
it worked, but the func type is still 1, and some dihedral parameters are missing.

Could you please be a little detailed how I should fix the problem? Thanks a lot! 

Best,
Qinghua

**Comment by swails** [comment]
The code

```python
amber.save('mol_gmx.top', 'inline=false')
```
is not doing what you think it's doing.  It passes the string `inline=false` as the second argument (to the `combine` argument).

Try this:

```python
amber = pmd.load_file('mol.prmtop','mol.inpcrd')
#
amber.save('mol_gmx.top', parameters='mol_gmx.top')
amber.save('mol_gmx.gro')
```

In the meantime, does GROMACS give incorrect energies when the funct value is 1 for these dihedrals?  If all of them get changed to 9, would that fix things?

**Comment by qinghualiao** [comment]
@swails Thanks a lot for the suggestion. I just tried, it partially solved the problem, manually edition is still needed. All the dihedral parameters were extract out correctly, putting together in one block. But in the topology file, there are still some parameters, which should be removed as the correct parameters are listed in the block mentioned above.  Here is the newly converted topology file, you may have a check. It is better than previous one.
[https://www.dropbox.com/s/aoljy8r871zio7i/dhap_new.top?dl=0](url)

I have not compare the potential energy yet, but I will do it later, and update here. Thanks! 

Best,
Qinghua

**Comment by swails** [comment]
> I have not compare the potential energy yet, but I will do it later, and update here. Thanks!

If the potential energies come out correct, then I'm not concerned about the distinction between 1 and 9.  As you pointed out, the functional forms are identical (this is also in one of the comments in the gromacstop.py source file).

The conversions *were* tested to ensure the energies and forces came out the same in both programs.  If that's no longer true, then this needs to be fixed.  But if it *is* still true, then I would say ParmEd is working correctly (one of multiple "correct" behaviors).

**Comment by qinghualiao** [comment]
@swails Thanks for the explanation. I did two simulations (10 ns) of the same small molecules in water, one is using the corrected topology (func 9), the other is using the topology file directly from parmed.
And I checked the dihedral energy, they are quite comparable to each other, then I agree with you that ParmEd is working correctly. Thanks a lot for the clearing!

All the best,
Qinghua

**Comment by swails** [comment]
Can you do a single-point energy calculation on the two structures and verify they're equivalent?

The energies can still be "comparable" if the topology with a funct of 1 is omitting some terms included by the topology where funct is 9.

**Comment by ggdhzdx** [comment]
I wrote a  function to compress or uncompress dihedral types
I don't know if Parmed have similar function. But I haven't found it in its manual
`    def adj_dihedral(pmd_struct,contract='auto'):
        '''contract or expand dihedral types
		pmd_struc is a parmed structure object
		contract="auto" will put multiple dihedral types to a DihedralTypeList
		contract="all" will put all  dihedral types to a DihedralTypeList
		contract="none" will remove all DihedralTypeList put all dihedral types as separated terms
		'''
		# firstly, generate a dict of dihedral and it parameters
        d2dtype = defaultdict(str)
        for d in pmd_struc.dihedrals:
            a1 = d.atom1.idx
            a2 = d.atom2.idx
            a3 = d.atom3.idx
            a4 = d.atom4.idx
            d_idx = (a1,a2,a3,a4)
            atoms = (d.atom1,d.atom2,d.atom3,d.atom4)
            if type(d.type) is pmd.DihedralType:
                typelist = [d.type]
            elif type(d.type) is pmd.DihedralTypeList:
                typelist = [t for t in d.type]
            if  d_idx not in d2dtype:
                d2dtype[d_idx] =  {'typelist':typelist,'atoms':atoms,'ignore_end':d.ignore_end,'improper':d.improper}
            else:
                d2dtype[d_idx]['typelist'] += typelist
				
		# secondly, regenerate  structure.dihedral and structure.dihedral_types based on d2dtype
        del pmd_struc.dihedrals[:]
        del pmd_struc.dihedral_types[:]
        pmd_struc.dihedral_types = pmd.TrackedList()
        pmd_struc.dihedrals = pmd.TrackedList()
        if contract == 'auto':
            for k,v in d2dtype.items():
                if len(v['typelist'])==1:
                    dtype = v['typelist'][0]
                    dtype.list = pmd_struc.dihedral_types
                    if dtype not in pmd_struc.dihedral_types:
                        pmd_struc.dihedral_types.append(dtype)
                    dihed = pmd.Dihedral(*v['atoms'],improper=v['improper'],ignore_end=v['ignore_end'],type=dtype)
                    pmd_struc.dihedrals.append(dihed)
                if len(v['typelist'])>1:
                    dtype = pmd.DihedralTypeList(v['typelist'], list=pmd_struc.dihedral_types)
                    if dtype not in pmd_struc.dihedral_types:
                        pmd_struc.dihedral_types.append(dtype)
                    dihed = pmd.Dihedral(*v['atoms'],improper=v['improper'],ignore_end=v['ignore_end'],type=dtype)
                    pmd_struc.dihedrals.append(dihed)

        if contract == 'all':
            for k,v in d2dtype.items():
                dtype = pmd.DihedralTypeList(v['typelist'],list=pmd_struc.dihedral_types)
                if dtype not in pmd_struc.dihedral_types:
                    pmd_struc.dihedral_types.append(dtype)
                dihed = pmd.Dihedral(*v['atoms'],improper=v['improper'],ignore_end=v['ignore_end'],type=dtype)
                pmd_struc.dihedrals.append(dihed)

        if contract == 'none':
            for k,v in d2dtype.items():
                for dtype in v['typelist']:
                    dtype.list = pmd_struc.dihedral_types
                    if dtype not in pmd_struc.dihedral_types:
                        pmd_struc.dihedral_types.append(dtype)
                    dihed = pmd.Dihedral(*v['atoms'], improper=v['improper'], ignore_end=v['ignore_end'], type=dtype)
                    pmd_struc.dihedrals.append(dihed)
        print(pmd_struc.dihedral_types)
        print(pmd_struc.dihedrals)`
