### ISSUE TITLE
Gromacs write box precision not affected by precision

### ISSUE THREAD

**Issue by mrshirts** [ParmEd/ParmEd#922]
When writing out a grofile using the write method in gromacsgro.py, the precision flag sets the precision of the coordinates, but does not affect the precision of the box.

The precision of initial energies is therefore limited by the box precision.

Right now, the box precision is always '%10.5f', regardless of set precision.

I suggest this either be made variable, or else the precision be increased several decimal places to avoid mismatches in the outputs. 

Also, I would suggest bumping up the default to at least 5.

I am preparing a PR with these, but wanted to save my thoughts.

**Comment by swails** [comment]
I’m good with anything permissible by the GROMACS format

**Comment by mrshirts** [comment]
OK, have something that mostly works, will need to verify a few things.

Though it doesn't look like it solves my basic issue, which is that AMBER -> GROMACS -> AMBER is giving energies that don't match between amber.  I'm still trying to track down why. I thought this might solve it (nonbondeds are the biggest) but not yet.

**Comment by mrshirts** [comment]
OK, posted a PR that fixed the output precision issue with the box vector.  However, I'm still not getting agreement in the nonbondeds when going from AMBER->GROMACS->AMBER, so still checking this.

**Comment by swails** [comment]
What force field?

**Comment by mrshirts** [comment]
GAFF + TIP3P.  Still investigating.

**Comment by mrshirts** [comment]
Updates on errors in AMBER->GROMACS->AMBER energies for a sample file:

* Dihedrals: 0.002 kcal  (relative errors 1.6 x 10-5)
* 1-4 Electrostatics: 0.0011 kcal/mol (relative error 3.7 x 10-7)
* NO errors within precision for other  LR electrostatics (despite LR electrostatics being 10x larger than 1-4 electrostatics) 
* VDWAALS: 0.06 kcal/mol, (relative errors 1.9 x 10-5)
* but no error in 1-4 VDWaals (A relative error of 1.9 x 10-5 should still in the last digit if present)

Will keep digging in files.   It seems that upon read/write/read, the order of the Na+ and Cl c-hanges ( goes from 1 CL 6 NA to 6 CL to 7 CL, 6 NA, but the bookkeeping appears to be done correctly (i.e. right atoms with right positions).  No other weird things in the coordinates. So now looking at the prmtop.

**Comment by mrshirts** [comment]
SCEE_SCALE_FACTOR upon conversion there and back ends up as differing by one part in 5 x 10-7 1.20000048E+00 vs 1.20000000E+00, likely due to rounding of 0.83333333, which likely explain issues in 1-4 electrostatics.  This could/should be fixed with more digits of precision in the output.

LENNARD_JONES_ACOEF and LENNARD_JONES_BCOEFF are all different in about the 5th decimal place (3.79876399E+05 vs. 3.79873471E+05), likely due to rounding.  This could/should be fixed with more digits of precision in the output.  

There's a LOT more dihedrals in the converted file, so I need to sort through this a bit more.

**Comment by mrshirts** [comment]
Re-addressed with fixes in #935

**Comment by swails** [comment]
This was fixed in #936
