### ISSUE TITLE
add more stuff to __str__ in AmberParm (and others too)

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#93]
Hi,

here is what I got when using AmberParm

    In [1]: from chemistry.amber import AmberParm 

    In [2]: parm = AmberParm("./Tc5b.top")

    In [3]: parm
    Out[3]: <chemistry.amber._amberparm.AmberParm at 0x2aaab7c15f60>

    In [4]: print (parm)
    ./Tc5b.top

it's really great if there will more info (n_atoms, n_mols, charges ...) for quickly have an idea about `parm`. 

Hai

**Comment by swails** [comment]
This would have to go in `__repr__` (which is really where this kind of information belongs).  The current `repr(parm)` is rather useless, and `str(parm)` returning the name of the topology file is used in several places inside ParmEd already.

Thanks for the idea!

**Comment by swails** [comment]
See #97

**Comment by swails** [comment]
Done in #97
