### ISSUE TITLE
Reading Tinker prm files

### ISSUE THREAD

**Issue by samarjeet** [ParmEd/ParmEd#934]
I can read in the xyzfile file but not the parameter prm file. I saw that AmoebaParameterSet wasn't exposed so I added that line in the tinker/_init_.py and with that I am able to at least read the prm file. However, only xyzfile object has createSystem method and I am unable to use it as I cannot find a way to pass in the parameter file object to it. 
Parmed examples directory doesn't have any tinker examples and so I am not able to get any references. Do you have any example scripts of its usage? Thanks !

**Comment by swails** [comment]
Parmed can’t do this, unfortunately
