### ISSUE TITLE
Converting Coarse-Grained CHARMM Model to Gromacs

### ISSUE THREAD

**Issue by reciprocal-space** [ParmEd/ParmEd#946]
Hi!

I have a CG model and I was wondering if it was possible to convert it from CHARMM to GROMACS - specifically I'd like to create a .gro file from the pdb/prm/cor files. Is this possible with ParmEd? If so, could you tell me how to do it?

Thanks,
Vivek

**Comment by swails** [comment]
I don't know what the functional form of the CG model is.  Most likely the answer is 'no'.  If it's the same functional form (or substantively similar) as the traditional CHARMM force field, then it's entirely possible the conversion is possible.

A python script like below would do the conversion:

```python
import parmed as pmd

struct = pmd.load_file('path/to/your/charmm.psf')
struct.load_parameters(
    pmd.charmm.CharmmParameterSet('file1.prm', 'file2.prm', 'file1.rtf', 'file2.rtf')
)
struct.save('gromacs.top')
```

If the conversion saves with no errors, you should very carefully check that GROMACS and CHARMM give the same energies and forces for the two sets of files.

**Comment by reciprocal-space** [comment]
Thanks a lot for pointing me in the right direction! The conversion saved with no errors, and under manual inspection the energies/forces between the two topology files seem to be the same, but I've been unable to replicate the [script from the documentation](https://parmed.github.io/ParmEd/html/readwrite.html) - the problem is Python can't seem to find OpenMM when  'system = gmx_top.createSystem()' is invoked, although it seems to find the OpenMM directory without any issues when I import the module.

I'm also having trouble creating the .gro file. Specifically when the .gro file is being written, there's an error as the array containing the xyz coordinates of the molecules is not populated. Unless I'm mistaken, this array should be populated from the .cor file, but I've hit a wall in attempting to associate the attributes of the coordinate file to the structure.

I'd really appreciate any guidance you could give me on these issues.

**Comment by swails** [comment]
If you have a CHARMM coordinate file, you may be able to try something like this:

```python
import parmed as pmd

struct = pmd.load_file('path/to/your/charmm.psf')
struct.load_parameters(
    pmd.charmm.CharmmParameterSet('file1.prm', 'file2.prm', 'file1.rtf', 'file2.rtf')
)
struct.coordinates = pmd.load_file('path/to/your/charmm.cor').coordinates
struct.save('gromacs.top')
struct.save('gromacs.gro')
```

**Comment by swails** [comment]
Note that the above will not set any kind of unit cell information -- you'll have to define the box dimensions somehow separately and set those attributes on the `struct.box` attribute. It's a 6-element array with the 3 lengths followed by the 3 angles in degrees.  For example:

```python
struct.box = [10, 10, 10, 90, 90, 90]
```
for a 10x10x10 Angstrom cubic cell.
