### ISSUE TITLE
Citation?

### ISSUE THREAD

**Issue by davidlmobley** [ParmEd/ParmEd#949]
Anything you'd like cited relating to ParmEd, @swails ? Default is to cite http://parmed.github.io/ParmEd but I'd love to have something more formal as well.

**Comment by swails** [comment]
I don't believe there are any citations for ParmEd.  @ctk3b and @mrshirts -- did we publish anything ParmEd-InterMol related?

**Comment by davidlmobley** [comment]
I have one JCAMD citation relating to SAMPL that has some details of both.

**Comment by ctk3b** [comment]
> JCAMD citation relating to SAMPL

That's probably the most appropriate citation
