### ISSUE TITLE
ParmEd is writing a `prmtop` that cannot be re-read by ParmEd

### ISSUE THREAD

**Issue by slochower** [ParmEd/ParmEd#952]
I'm encountering an issue where a `prmtop` written by ParmEd can't be re-read by ParmEd. This happens after combining and saving two structures, which can independently be written and re-read by ParmEd. In other words, I think ParmEd is not correctly writing a `prmtop` for this combined structure.

This [gist](https://gist.github.com/anonymous/b5963a98cf117c2e5dfb9131cd3274f8) demonstrates the issue. At the bottom of the gist, I have included the output of the `prmtop` files. I think the problem is in writing `%FLAG NONBONDED_PARM_INDEX` and it may be because the first structure (`dummy_atoms`) is simply three lead atoms with only mass terms, written using the below `frcmod`. It may also be because I'm using a force field with many more atom types than usual.

CC @davidlmobley 

<details><summary>Contents of `frcmod.dum`</summary><p>

```

Parameters for a "Lead-like" Dummy Atom
MASS
Pb     210.00

BOND

ANGLE

DIHE

IMPROPER

NONBON
Pb       0.000     0.0000000
```
</p></details>

**Comment by davidlmobley** [comment]
Can you provide a little context for me? How did you get to this/what's the big picture of what you're trying to do?

(And, for the record, have you provided enough that someone without OpenEye tools/`openforcefield` can reproduce the problem?)

**Comment by slochower** [comment]
> Can you provide a little context for me? How did you get to this/what's the big picture of what you're trying to do?

The context is setting up a host-guest calculation for attach-pull-release, which uses dummy atoms to setup distance, angle, and torsion restraints on the host and guest molecules relative to specific positions. The dummy atoms themselves are positionally restrained and they have no interactions with other atoms. (Figure 3 in this paper gives a good overview of the general setup: https://pubs.acs.org/doi/full/10.1021/acs.jctc.5b00405). The dummy atoms shouldn't be parameterized by `openforcefield` at all -- rather, I should be able to take a host and guest ParmEd structure with `openforcefield` parameters and merge that with a ParmEd structure for the dummy atoms determined from the linked `frcmod` file. This is the "mixed force field" approach of adding two ParmEd structures, parameterized separately, and writing out a combined `prmtop`. In this case, I don't think the combined `prmtop` has tabulated the nonbonded interactions correctly, and this could be an issue for other cases of combining separately parameterized ParmEd structures. Does that make sense?

> (And, for the record, have you provided enough that someone without OpenEye tools/openforcefield can reproduce the problem?)

Yes, this is downstream of `openforcefield` and OpenEye tools. It can be confirmed using the `prmtop` files at the end of the gist. Those `import`s at the top of the gist are unnecessary.

**Comment by slochower** [comment]
Actually, I think the issue is slightly more general than I first noticed. It's not _writing_ and _reading_ files that is a problem, it's the merge itself. I can take two structures that are valid (i.e., pass `checkValidity()`), but when combined, the merged structure is not valid. Here is a much simplified notebook: https://github.com/slochower/ParmEd-prmtop-read-write/blob/master/ParmEd-read-write.ipynb with files in the same repository.

**Comment by stefdoerr** [comment]
Indeed, I ran into the same issue today. But the problem (at least from my own tests) is not in the merge but in the write+read. Seems like the LJ parameters are written out wrong.

So I built protein, ligand and protein+ligand with tleap. Then I compare the energies of the protein+ligand tleap build with the parmed joined parameters of the protein and the ligand and they are the same. But if I write them out and read them back in they are different.

Here is the [gist](https://gist.github.com/stefdoerr/bd6489c93a5ba9644065b4c0f654f673) and here are the files if you want to test it yourself: 
[test.zip](https://github.com/ParmEd/ParmEd/files/2084849/test.zip)

```
Tleap built complex energies
{'angle': 791.98587181295272, 'bond': 663.06865317931431, 'dihedral': 3426.8169937776847, 'elec': -8273.6881807105729, 'improper': 80.069614788743536, 'vdw': -1957.1785553764721, 'total': -5268.9256025283503}
Parmed joined energies
{'angle': 791.98587181295272, 'bond': 663.06865317931431, 'dihedral': 3426.8169937776847, 'elec': -8273.6881807105729, 'improper': 80.069614788743536, 'vdw': -1957.1785553764721, 'total': -5268.9256025283503}
Parmed written+read joined energies
{'angle': 791.98587181295272, 'bond': 663.06865317931431, 'dihedral': 3426.8169937776847, 'elec': -8273.6881807105729, 'improper': 80.069614788743536, 'vdw': -1965.581910898665, 'total': -5277.3289580505425}
```

**Comment by stefdoerr** [comment]
I see, I think I found the problem. parmed when writing seems to join Lennard Jones parameters for atoms with the same name (?). As the ligand has hydrogens with H1,2,3,.. names it seems to copy their LJ parameters from the protein. 
So when you read it back in it has lost the custom ligand parameters.

```python
In [35]: x = np.array([x.rmin for x in prmjoinread.atoms])
    ...: y = np.array([x.rmin for x in prmjoin.atoms])
    ...: print('Differences in', np.where(x != y)[0])
    ...: print('Num atoms', len(x))
    ...: namesx = np.array([x.name for x in prmjoinread.atoms])
    ...: namesy = np.array([x.name for x in prmjoin.atoms])
    ...: print(namesx)
    ...: print(namesy)
    ...: 
    ...: 
Differences in [4811 4812 4813 4814 4815 4816 4817 4818 4819 4820 4821 4822 4823 4824 4825
 4826 4827 4828 4829 4830 4831 4832 4833 4834 4835 4836 4837 4838 4839 4840
 4841]
Num atoms 4842
['N' 'H1' 'H2' ..., 'H7' 'H8' 'H9']
['N' 'H1' 'H2' ..., 'H7' 'H8' 'H9']
```

**Comment by slochower** [comment]
Ah, interesting, good work. I haven't had a chance to look in detail, but your explanation seems plausible to me. This seems like it has the potential to cause some headaches. Unfortunately, I'm not sure where in the ParmEd code this problem arises, maybe we can find a not-so-painful fix.

**Comment by swails** [comment]
Looks like another manifestation of #756

**Comment by swails** [comment]
Can you try the fix in #989 and let me know if this fixes the problem?

**Comment by stefdoerr** [comment]
Yes indeed, that PR fixes it.

```
Parmed joined energies
{'angle': 791.98920874917758, 'bond': 603.40660145652214, 'dihedral': 3424.878048292715, 'elec': -8198.4110456946346, 'improper': 80.069614788743536, 'vdw': -1955.95906011695, 'total': -5254.0266325244265}
Parmed written+read joined energies
{'angle': 791.98920874917758, 'bond': 603.40660145652214, 'dihedral': 3424.878048292715, 'elec': -8198.4110456946346, 'improper': 80.069614788743536, 'vdw': -1955.95906011695, 'total': -5254.0266325244265}
```

**Comment by swails** [comment]
> Yes indeed, that PR fixes it.

Nice!  I get to close one of the longest-standing bugs in ParmEd :smiley:

> When do you plan to merge it?

As soon as I can get the Jenkins build working again (definitely today -- Travis build already succeeded).

Thanks for the quick verification!

**Comment by swails** [comment]
Nevermind, I'm going to merge it now.
