### ISSUE TITLE
The option constraints=HAngles is wrong in parmed.structure.createSystem 

### ISSUE THREAD

**Issue by nividic** [ParmEd/ParmEd#958]
Hi there,

I was trying to create an OpenMM system by using a Parmed structure object. I was selecting the following options:
```new_system = water_structure.createSystem(nonbondedMethod=NoCutoff, rigidWater=True, constraints=HAngles)```
The option HAngles should put angle constraints on all the angles of the form H-X-H and H-O-X (where X is an arbitrary atom) and on all bonds. Now, the problem are the lines
https://github.com/ParmEd/ParmEd/blob/641865e3cdda56cce10657a7afedcfce486cf24c/parmed/structure.py#L2140-L2156
In particular the line
https://github.com/ParmEd/ParmEd/blob/641865e3cdda56cce10657a7afedcfce486cf24c/parmed/structure.py#L2155
The bond lengths (l1 and l2) have already been multiplied by the conversion factor and the length between the the two hydrogens does not need to. This is causing to generate  wrong water  geometries. For example the water angle H-O-H was going from ~104 degrees to 9 degrees. 

@davidlmobley @jchodera

**Comment by davidlmobley** [comment]
You're going to do a PR to fix, right?

CC @slochower

**Comment by jchodera** [comment]
That would be good to fix! But we don't recommend using `HAangles` constraints because it can significantly disrupt conformational equilibria.

**Comment by nividic** [comment]
I'm going to work on a PR

**Comment by swails** [comment]
Fixed by #969
