### ISSUE TITLE
The rigidWater=True option in parmed.Structure.CreateSystem is not correctly working 

### ISSUE THREAD

**Issue by nividic** [ParmEd/ParmEd#959]
Hi there,

I was trying to create an OpenMM system by using a Parmed structure object. I was selecting the following options:

```new_system = water_structure.createSystem(nonbondedMethod=NoCutoff, rigidWater=True, constraints=None)```

If Parmed wants to mimic OpenMM, the option rigidWater=True should produce a rigid water i.e. bonds and angle constrained during MD runs. However, in the Parmed lines:
https://github.com/ParmEd/ParmEd/blob/641865e3cdda56cce10657a7afedcfce486cf24c/parmed/structure.py#L2127-L2135
the constraints are applied just between the two H-O bonds missing the extra constraints between the two H-H. This is causing the water to be not fully rigid as in the TIP3P water model. I have attached a simple script that you can use to check the problem.
[test_water.zip](https://github.com/ParmEd/ParmEd/files/1742382/test_water.zip)

 @davidlmobley @jchodera

**Comment by nividic** [comment]
I'm going to fix this in a PR request

**Comment by davidlmobley** [comment]
CC @slochower

**Comment by swails** [comment]
Fixed in #969
