### ISSUE TITLE
pdb parser has more problems than it should with atom numbers > 99999

### ISSUE THREAD

**Issue by dacase** [ParmEd/ParmEd#961]
The PDB standard doesn't really say what to do with more than 99999 atoms, and different programs
do different things.  ParmEd should be more forgiving on input.  This is especially true since the atom numbers in a PDB file can't be relied upon anyway: the official standard increments the atom count
when a TER card is written, but many, many other codes ignore this.

Example that prompted this: Phenix does a rather odd thing after 99999 atoms: it starts at A0000,
and continues in a base-36 system (using digits and capital letters.)  Since the first such extra
atom is "A00000", pdb.py in Parmed thinks it has found a hexadecimal number from VMD, and then
crashes a few lines later when it encounters "A000G".

My proposal: don't try to anticipate all possible extensions: if atnum = int(atnum) throws a ValueError exception, just set atom_overflow=True, and skip trying to be clever to see if this might be something VMD produced.

This idea has worked in things I've tried; there may be somewhere else where atnum needs to handled more carefully--perhaps in CONECT records, but I don't think one can trust CONECT records when there are more than 99999 atoms anyway....

If people think this is OK, I'll create a pull request.  Should that be sent here, or to Amber-md?

**Comment by dacase** [comment]
update: The Phenix way of handling atom numbers beyond 99999 (and residue numbers beyond
9999) is indeed a quasi-PDB standard:

      http://cci.lbl.gov/hybrid_36/

So, parmed should certainly give this format priority over something VMD might do.  We might
even consider using it on writing pdb files.....

**Comment by swails** [comment]
Can you put a copy of a PDB written like this somewhere so I can see it and add parsing support?

I don’t think it should be that hard to support these files side by side with what VMD writes.

**Comment by swails** [comment]
Oh, you have a PR to create -- I missed that.  I think here is the best place to raise it.

**Comment by dacase** [comment]
see snippet in attached pdb file.  Notes:  

a. this file doesn't have more than 9999 residues, but
the way "extra" residues are handled is the same: after 9999, go to A000, when continue with
base 36.

b. The web page above has sample python code to convert to/from base36 to base10.

[no_header.pdb.txt](https://github.com/ParmEd/ParmEd/files/1763261/no_header.pdb.txt)

**Comment by swails** [comment]
#1039 fixed this.  I downloaded the file and checked.
