### ISSUE TITLE
New parmed point release for openmm release

### ISSUE THREAD

**Issue by jchodera** [ParmEd/ParmEd#963]
@swails : @peastman would like to proceed with the official OpenMM 7.2 release, so I would really like to see #955 moved and a new point release cut so we can ensure the parameters distributed with 7.2 can be produced reproducibly by our users. Is there anything I can do to help move this along?

Thanks!

**Comment by swails** [comment]
Tests are running on #955 now (about 10-15 minutes left before they finish).  This was triggered by an update to the branch's PR (and GitHub's annoying new habit of forcing rebuilds of each PR following every update to the target branch irrespective of whether there are any conflicts or not).

After that's done, I'll update #957, merge that, and then I can cut a point-release if you want.

**Comment by jchodera** [comment]
Awesome! Thanks so much, and let me know if I can help in any way.

**Comment by jchodera** [comment]
Thanks again for merging the PRs!

What about a 3.0.1 bugfix release, since these PRs were mostly bugfixes to writing OpenMM ffxml files?

**Comment by swails** [comment]
3.0.3 has already been released.

Another release is worth cutting soon, I think.
