### ISSUE TITLE
Convert parameters files from CHARMM to AMBER

### ISSUE THREAD

**Issue by alexamist** [ParmEd/ParmEd#973]
Hi, I'm trying to convert CHARMM parameters files, so I can run a MD in AMBER. I try to use Chamber, and there is no problems with my files, but the converted files aren't been genereted:
![image](https://user-images.githubusercontent.com/37109603/37858548-da279520-2ee4-11e8-8aea-1f4238138406.png)
I'm learning now how to work at Amber/Antechamber/ParmEd, so, somebody can explain how can I get the files in amber format? (in details, cause I see some examples of executing parmed in python, and make me a little confuse) 

Thanks!

**Comment by swails** [comment]
You need to use the “outparm” command afterwards to actually write the prmtop. 

HTH,
Jason

--
Jason M. Swails
