### ISSUE TITLE
Why I got no results when I try to convert psf to Gromacs top file?

### ISSUE THREAD

**Issue by fanliqmul** [ParmEd/ParmEd#976]
I am new to Parmed. I want to convert psf file to top file of  Gromacs. I used following command:

import parmed as pmd
psf=pmd.load_file('AFM_noforcefiled.psf')
psf.save('gromacs.top')

But my linux system is stuck (mouse is locked and changed to cross-shape,no error messages are reported). And there is no output after 1 hour(I have about 10000 atoms). And I am able to run the tests in the test folder before I used above commands.  What is wrong?

**Comment by swails** [comment]
Can you send me the file so I can reproduce it?

It's probably hung somewhere.

**Comment by fanliqmul** [comment]
Fan Li has shared a OneDrive for Business file with you. To view it, click the link below.


<https://qmulprod-my.sharepoint.com/personal/exw941_qmul_ac_uk/Documents/Attachments/AFM_noforcefiled.psf>
[https://r1.res.office365.com/owa/prem/images/dc-generic_20.png]<https://qmulprod-my.sharepoint.com/personal/exw941_qmul_ac_uk/Documents/Attachments/AFM_noforcefiled.psf>

AFM_noforcefiled.psf<https://qmulprod-my.sharepoint.com/personal/exw941_qmul_ac_uk/Documents/Attachments/AFM_noforcefiled.psf>




The file is attached. Thanks for your time and help.


Fan Li

Ph.D student at Queen Mary University of London

________________________________

**Comment by fanliqmul** [comment]
To view AFM_noforcefiled.psf, sign in<https://qmulprod-my.sharepoint.com/personal/exw941_qmul_ac_uk/_layouts/15/acceptinvite.aspx?invitation=%7BAE42B898%2D9AB6%2D4AA8%2D9A3F%2D90B752925C71%7D&listId=bfbb952a%2De817%2D4595%2Db5b7%2D387016b7061e&itemId=912dfbfb%2D3caa%2D4b91%2D872c%2Dc69218dbf153> or create an account.

**Comment by swails** [comment]
I’m not a member of that sharepoint group and can’t get access to it without an admin granting that access. 

Can you put it somewhere public, like Dropbox, a GitHub gist, or just attach it as a comment here?

--
Jason M. Swails

**Comment by fanliqmul** [comment]
I created a public gist. You can find it here

https://gist.github.com/fanliqmul

**Comment by fanliqmul** [comment]
Hi 
I created a public gist. You can find it here. 
https://gist.github.com/fanliqmul

I also attached it here

[AFM_noforcefiled.zip](https://github.com/ParmEd/ParmEd/files/1899347/AFM_noforcefiled.zip)

**Comment by swails** [comment]
I know this is about a year old, but I looked through your files.  I'm not sure where you got this PSF file, but all of the residues are named either XXX or XXXX, which is really taxing the logic used to split systems into molecules (which GROMACS uses).

I've fixed the parsing issues so that this now "works", but it's still atypical.

I'm not sure if this is still useful for you or not.

**Comment by fanliqmul** [comment]
Hi Jason


It is useful.


Thanks for your time.


Kind regards


Fan Li

School of Engineering and Materials Science
Queen Mary University of London
London E1 4NS
United Kingdom


________________________________
