### ISSUE TITLE
installing parmed and running tests

### ISSUE THREAD

**Issue by hrg1000** [ParmEd/ParmEd#983]
Dear All,
I am trying to install ParmEd and am getting error messages when I run tests, I would be grateful for some advice.
Dr. Helen Eisenberg
Fritz Haber Center for Molecular Dynamics

I make sure I am in the same python environment as openmm
I have created a directory as sudo /opt/parmed and downloaded ParmEd-3.0.3.tar.gz there. 
I open ParmEd-3.0.3.tar.gz using tar -xvzf ParmEd-3.0.3.tar.gz.
I change to the new  ParmEd-3.0.3 directory. 
I type python setup.py install
It seems to install fine.
I go to tests directory and do nosetests . 
I get error messages:

```
ERROR: Failure: ImportError (No module named parmed)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 411, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/opt/parmed/ParmEd-3.0.3/test/test_parmedtools_parmlist.py", line 5, in <module>
    from parmed import Structure, load_file
ImportError: No module named parmed
```

**Comment by hainm** [comment]
Hi

Can you try following

1. Uninstall parmed
2. Either
- using pytest
- using development mode: pip install -e .

Hai

**Comment by hrg1000** [comment]
I'm sorry but I didn't completely understand what you wanted me to do in the second stage?
Do what using pytest?
Use "pip install -e parmed" ?
Thank you for your help,
Helen

**Comment by hrg1000** [comment]
Hi,
I uninstalled ParmEd
I opened ParmEd-3.0.3.tar.gz using tar -xvzf ParmEd-3.0.3.tar.gz.
I changed to the new ParmEd-3.0.3 directory.
I typed "pip install -e /opt/parmed/ParmEd-3.0.3"
It said that it was successfully installed.
I get the same error message when running the tests

**Comment by hainm** [comment]
> Do what using pytest?

replace "nosetests" by "pytest".

**Comment by hrg1000** [comment]
I tried replacing nosetests by pytest and got the same error

**Comment by swails** [comment]
It's impossible to tell what's going wrong here without more information.  Show us the output of the installation step:

```
python setup.py install
```

or

```
pip install -e /opt/parmed/ParmEd-3.0.3
```

Also, what is the result of `which python`?

What is the output of `python -c "import sys; print(sys.path)"`?

Something is happening where the test suite is not actually running against a Python into which ParmEd was installed.  Maybe that's because "pip" and "python" come from a different installation than either nosetests or pytest (although `pytest` is not an executable -- `py.test` is, so I'm not sure how you got "the same error" replacing nosetests with pytest).

**Comment by swails** [comment]
Also, when you do print output from the terminal, put it inside triple-bactick blocks so it gets formatted as "code" rather than markdown.  (I edited your original comment to do this).  It's really difficult to read terminal output when markdown converts a bunch of the characters to formatting.

**Comment by hrg1000** [comment]
Here are the answers to your questions:
'''which python''' gives '''/opt/conda/miniconda2/envs/openmm_env/bin/python'''
'''python --version''' gives '''Python 3.6.5 :: Anaconda, Inc.'''
'''python -c "import sys; print(sys.path)"''' gives
'''['', '/opt/conda/miniconda2/envs/openmm_env/lib/python36.zip', '/opt/conda/miniconda2/envs/openmm_env/lib/python3.6', '/opt/conda/miniconda2/envs/openmm_env/lib/python3.6/lib-dynload', '/usr/people/roib2/helen/.local/lib/python3.6/site-packages', '/opt/conda/miniconda2/envs/openmm_env/lib/python3.6/site-packages', '/opt/parmed/ParmEd-3.0.3', '/opt/conda/miniconda2/envs/openmm_env/lib/python3.6/site-packages/mbpol-1.0-py3.6-linux-x86_64.egg']
'''

The output (error message) of '''pytest .''' was (I'm only showing the end as it repeats itself for every test)
'''
========================  test_parmed_cif.py  ========================
unhandled exception occurred while testing test_parmed_cif
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/logilab/common/pytest.py", line 428, in testfile
    options=self.options, outstream=sys.stderr)
  File "/usr/lib/python2.7/dist-packages/logilab/common/pytest.py", line 764, in __init__
    testLoader=NonStrictTestLoader())
  File "/usr/lib/python2.7/unittest/main.py", line 77, in __init__
    self.module = __import__(module)
  File "test_parmed_cif.py", line 20, in <module>
    from utils import get_fn, get_saved_fn, diff_files, FileIOTestCase
  File "utils.py", line 12, in <module>
    from parmed import gromacs, openmm
ImportError: No module named parmed
===================  test_parmed_parameterset.py  ====================
unhandled exception occurred while testing test_parmed_parameterset
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/logilab/common/pytest.py", line 428, in testfile
    options=self.options, outstream=sys.stderr)
  File "/usr/lib/python2.7/dist-packages/logilab/common/pytest.py", line 764, in __init__
    testLoader=NonStrictTestLoader())
  File "/usr/lib/python2.7/unittest/main.py", line 77, in __init__
    self.module = __import__(module)
  File "test_parmed_parameterset.py", line 4, in <module>
    import parmed as pmd
ImportError: No module named parmed
*******************************************************************************
Ran 33 test cases in 0.00s (0.00s CPU), 33 errors
0 modules OK (33 failed)
failures: /opt/parmed/ParmEd-3.0.3/test/test_parmed_gromacs_cpp [1/1], /opt/parmed/ParmEd-3.0.3/test/test_parmedtools_actions [1/1], /opt/parmed/ParmEd-3.0.3/test/test_parmed_genopen [1/1], /opt/parmed/ParmEd-3.0.3/test/test_parmed_pandas [1/1], /opt/parmed/ParmEd-3.0.3/test/test_parmedtools_parmlist [1/1], /opt/parmed/ParmEd-3.0.3/test/test_openmm_charmm [1/1], /opt/parmed/ParmEd-3.0.3/test/test_parmed_serialization [1/1], /opt/parmed/ParmEd-3.0.3/test/test_openmm_gromacs [1/1], /opt/parmed/ParmEd-3.0.3/test/test_format_conversions [1/1], /opt/parmed/ParmEd-3.0.3/test/test_parmed_netcdf [1/1], /opt/parmed/ParmEd-3.0.3/test/test_openmm_reporters [1/1], /opt/parmed/ParmEd-3.0.3/test/test_parmed_gromacs [1/1], /opt/parmed/ParmEd-3.0.3/test/test_parmed_misc [1/1], /opt/parmed/ParmEd-3.0.3/test/test_parmed_modeller [1/1], /opt/parmed/ParmEd-3.0.3/test/test_parmed_amber [1/1], /opt/parmed/ParmEd-3.0.3/test/test_parmed_structure_slicing [1/1], /opt/parmed/ParmEd-3.0.3/test/test_openmm_amber_forces [1/1], /opt/parmed/ParmEd-3.0.3/test/test_parmed_residue [1/1], /opt/parmed/ParmEd-3.0.3/test/test_parmed_visualization [1/1], /opt/parmed/ParmEd-3.0.3/test/test_parmed_unit [1/1], /opt/parmed/ParmEd-3.0.3/test/test_openmm_amber [1/1], /opt/parmed/ParmEd-3.0.3/test/test_parmed_openmm [1/1], /opt/parmed/ParmEd-3.0.3/test/test_parmed_charmm [1/1], /opt/parmed/ParmEd-3.0.3/test/test_parmed_formats [1/1], /opt/parmed/ParmEd-3.0.3/test/test_parmed_tinker [1/1], /opt/parmed/ParmEd-3.0.3/test/test_parmed_structure [1/1], /opt/parmed/ParmEd-3.0.3/test/test_parmed_namd [1/1], /opt/parmed/ParmEd-3.0.3/test/test_parmed_topologyobjects [1/1], /opt/parmed/ParmEd-3.0.3/test/test_parmed_geometry [1/1], /opt/parmed/ParmEd-3.0.3/test/test_parmed_rdkit [1/1], /opt/parmed/ParmEd-3.0.3/test/test_parmed_rosetta [1/1], /opt/parmed/ParmEd-3.0.3/test/test_parmed_cif [1/1], /opt/parmed/ParmEd-3.0.3/test/test_parmed_parameterset [1/1]
'''

**Comment by hrg1000** [comment]
I installed parmed while in the openmm_env python environment.
It said it was installed successfully. 
I will try uninstalling and reinstalling to send you the output
To uninstall I ran '''python setup.py clean''' (I'm not sure if this was correct?)
When I run '''python setup.py install --record files.txt"
At the end it writes
'''
byte-compiling build/bdist.linux-x86_64/egg/parmed/residue.py to residue.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/parmed/modeller/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/parmed/modeller/standardtemplates.py to standardtemplates.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/parmed/modeller/residue.py to residue.cpython-36.pyc
creating stub loader for parmed/amber/_rdparm.cpython-36m-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/parmed/amber/_rdparm.py to _rdparm.cpython-36.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying ParmEd.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ParmEd.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ParmEd.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ParmEd.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ParmEd.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
parmed.amber.__pycache__._rdparm.cpython-36: module references __file__
parmed.modeller.__pycache__.standardtemplates.cpython-36: module references __file__
parmed.utils.__pycache__.six.cpython-36: module references __path__
creating dist
creating 'dist/ParmEd-3.0.3-py3.6-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing ParmEd-3.0.3-py3.6-linux-x86_64.egg
creating /opt/conda/miniconda2/envs/openmm_env/lib/python3.6/site-packages/ParmEd-3.0.3-py3.6-linux-x86_64.egg
Extracting ParmEd-3.0.3-py3.6-linux-x86_64.egg to /opt/conda/miniconda2/envs/openmm_env/lib/python3.6/site-packages
Removing ParmEd 3.0.3 from easy-install.pth file
Adding ParmEd 3.0.3 to easy-install.pth file
Installing parmed script to /opt/conda/miniconda2/envs/openmm_env/bin
Installing xparmed script to /opt/conda/miniconda2/envs/openmm_env/bin

Installed /opt/conda/miniconda2/envs/openmm_env/lib/python3.6/site-packages/ParmEd-3.0.3-py3.6-linux-x86_64.egg
Processing dependencies for ParmEd==3.0.3
Finished processing dependencies for ParmEd==3.0.3
writing list of installed files to 'files.txt'
'''
Do you want the whole output? (It is very long...)
Thank you for your help,
Helen

**Comment by hrg1000** [comment]
I am doing all of this as sudo

**Comment by swails** [comment]
> I am doing all of this as sudo in the openmm_env python environment,

My advice: don't use `sudo` for anything unless you know for absolute certain you need to.  It's an amazing tool, but it's definitely abused.  So rather than do everything as `sudo`, better to use `sudo` to change the ownership of the miniconda directory to a normal user.

Use the command:

```
sudo chown -R <your_username> /opt/conda/miniconda2
```

Weird things can happen to your environment within the context of the sudo command.  But I think I see what's happening.  Observe:

When you install ParmEd, it's going to `/opt/conda/miniconda2/envs/openmm_env/lib/python3.6/site-packages`.  This is what you expect.

But now look at the output of your `nosetests` command:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 411, in loadTestsFromName
```

Your nosetests is drawing from `/usr/local/bin`, not `/opt/conda/miniconda2/envs/openmm_env/bin` like it *should* be.  What I suspect has happened is that you installed nosetests using homebrew (or installed it directly from source?), which installed it against either the system Python or another one located inside `/usr/local/bin`.  What's important, though, is that this is not running against the Python environment you installed ParmEd into.

What's unclear to me is why this is happening.  There are two possibilities:

1. You *don't* have `nosetests` installed in your Miniconda installation (particularly the openmm_env environment)
1. `/usr/local/bin` is located first in your PATH ahead of the miniconda2 environment bin directory.

I strongly suspect it's the first (since `which python` returns the miniconda one).  You can confirm this by using the following command instead of `nosetests` in the installation step:

```
python -m nose .
```

Since you already said `which python` returns the miniconda2 Python, this will run `nosetests` from that environment... if it's installed.  That command is exactly the same as `nosetests`.  If you get a note about `nose` not being installed, then my prediction about the first scenario above is correct.

In that case the solution is simple:

```
conda install -n openmm_env nose
```

Then try again.

**Comment by hrg1000** [comment]
This helped, thank you!

**Comment by swails** [comment]
I take this to mean the problem is fixed.
