### ISSUE TITLE
Issue parsing AMBER off file

### ISSUE THREAD

**Issue by dww100** [ParmEd/ParmEd#993]
I encountered an issue when trying to load `$AMBERHOME/datt/leap/lib/phos_amino94.lib` from my AmberTools 17 install.
I get the error:

> RuntimeError: Expected atoms table not found

The issue appears to be trailing spaces in the residue name lines in the initial `!!index array str` section. As the lib file is from official sources it appears that the regex used to determine the section is too strict, or is this a design decision?

**Comment by swails** [comment]
Try the latest master branch -- I fixed up some of the regexes that were causing this problem.

Thanks for the report!
